### ISSUE TITLE
Bienvenido al foro! ᕦ( ͡° ͜ʖ ͡°)ᕤ

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#1]
En el [`README.md`](https://github.com/IIC2233-2015-2/syllabus/blob/master/README.md) están las instrucciones oficiales de uso.

Es de obligación de estos hacer lo más funcional posible este lugar. Ya sea detallando bien cada publicación y de usar un título lo más descriptivo posible. 

Toda publicación soporta la marcación **Markdown**. Por ejemplo, para escribir un código bien formateado se hace así:

![image](https://cloud.githubusercontent.com/assets/7570744/9183718/6151b170-3f87-11e5-87d7-14373d87fd76.png)

Y produce el siguiente output visual:

``` python
def hello_world():
    print('Hola mundo!')
```

Puedes encontrar más información de Markdown [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by vichoeq** [comment]
Venia a decir que esto es HERMOSO <3
