### ISSUE TITLE
Problema Github

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#10]
Estaba probando el tutorial del github y cuando llego a la parte de  "git push origin master" me pide usuario y contraseña y me tira 
![image](https://cloud.githubusercontent.com/assets/13748708/9291285/6e7f1d9e-43ae-11e5-9e88-9a767399d58c.png)

porque es?

**Comment by lopezjurip** [comment]
No tienes un repositorio en la nube. Esto es porque están intentando subir las cosas como si fueras el usuario `try-git` al repositorio `try-git`.
Te recomiendo hacer esto para que pruebes:
1. En Github, crea un repositorio. (arriba el signo `+` a la derecha). Digamos `mi-repo`.
2. Clona el repositorio a tu computador, sería algo como:
   1. `git clone https://github.com/fgvenegas/mi-repo.git`
   2. `cd mi-repo`
   3. `explorer .`
3. Pon algunos archivos o carpetas
4. `git add --all`
5. `git commit -m "commit inicial"``
6. `git push`.
7. Ahora deberían aparecer las cosas en Github.

**Comment by fgvenegas** [comment]
![image](https://cloud.githubusercontent.com/assets/13748708/9291730/9006b228-43c8-11e5-9cd6-997108465b49.png)

Hice todo al pie de la letra y ahora me sale eso

**Comment by lopezjurip** [comment]
http://lmgtfy.com/?q=perhaps+you+should+specify+a+branch+such+as+%27master%27

**Comment by vicentecastroa** [comment]
Cuando pongo git push para subir los archivos nuevos, me pide iniciar sesión y no me deja escribir en el campo de la contraseña, por lo que me tira error de autenticación. Hay alguna otra forma de iniciar sesión y que no la pida al momento de hacer git push?

![image](https://cloud.githubusercontent.com/assets/13738469/9321011/19c06206-4537-11e5-9c7d-64499714bb63.png)

**Comment by spiza** [comment]
Cuando haces eso PARECIESE que no se escribe la contraseña, pero en realidad si lo hace. Te recomiendo intentarlo asegurándote de escribir bien la contraseña

Enviado desde mi iPhone

**Comment by vicentecastroa** [comment]
Efectivamente! jajaj Gracias!
