### ISSUE TITLE
Resolver ecuacion Matricial

### ISSUE THREAD

**Issue by spiza** [IIC2233-2015-2/syllabus#100]
Chiquillos, necesito ayuda!

Llevo mucho rato buscando en internet, pero no consigo nada que me resulte.. Necesito encontrar alguna solucion -no trivial- a una ecuacion del tipo Ax=0

No se si alguien mas ha buscado esto, o si sabe como hacerlo.. Gracias!

PD: Les doy un ejemplo para que prueben:
[-1, 0.5, 1]
[1, -1, 0 ]
[0, 0.5, -1]

**Comment by trencoret** [comment]
@spiza hay unas librerias especiales de calculos matriciales, se podrán usar? Creo que es la linealg..

**Comment by lopezjurip** [comment]
Esperemos que @mbucchi conteste, pues él sabe bien las restricciones de ese tema.

**Comment by mbucchi** [comment]
@spiza, tienes permitido usar numpy para realizar la tarea. Con esto te debiese bastar y sobrar. Saludos!
