### ISSUE TITLE
Nombre Profesores repetidos

### ISSUE THREAD

**Issue by dpassi** [IIC2233-2015-2/syllabus#101]
Al momento de dar permisos a un alumno para que pueda tomar un ramo, la unica forma de saber que el profesor esta dandole permisos para SU ramo, es comprobar el nombre del profesor en el cursos.txt

Asumimos que no se repiten los nombres de los profesores en el archivo que ustedes vayan a probar?

**Comment by mbucchi** [comment]
Sí, puedes asumir eso.

**Comment by mbucchi** [comment]
No es necesario que asumas eso. Si sientes necesario agregar algún chequeo al sistema, adelante. Podrías preguntarle al profesor en qué curso desea otorgar el cupo especial, y ahí hacer los chequeos. Si existe algún choque de nombres (aunque dudo que ocurra), es lamentable... _--quién diría que un sistema como bummer tendría falencias?--_.
