### ISSUE TITLE
Orden de bacanosidad.

### ISSUE THREAD

**Issue by rrfoster** [IIC2233-2015-2/syllabus#103]
El orden de bacanosidad es unico o puede variar segun el codigo de cada persona?

**Comment by mbucchi** [comment]
Si el método que utilizaste para calcular la bacanosidad te entrega resultados que cumplen con el procedimiento planteado en la carpeta de bacanosidad (puntos entregados = puntos recibidos), entonces no debiese haber problema.

**PD:** Obviamente los puntos nunca van a calzar _exactamente_ debido a los redondeos, pero procura tener suficiente precisión para que el orden no se vea afectado por estos redondeos.
