### ISSUE TITLE
Duda import

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#106]
Se supone que para importar algo que esta en otra carpeta era 
from carpeta.modulo import Magia
pero marque una cosa en pycharm para poder hacer
from modulo import Magia 
sin necesidad de especificar la ruta, al revisarlo habra problemas con eso o necesito dejarlo para especificar la carpeta?

**Comment by lopezjurip** [comment]
Prueba si funciona al desactivarlo (no te puedo garantizar que todos los correctores usen PyCharm).
