### ISSUE TITLE
Problema con el syllabus

### ISSUE THREAD

**Issue by fergarciafaura** [IIC2233-2015-2/syllabus#107]
Abrí el main.pdf desde la carpeta del syllabus y subrayé cosas con el visor de textos, sin darme cuenta de lo que pasaría, y ahora cuando quiero hacer git pull me dice que tengo que hacer commit primero, pero si lo hago modificaré el syllabus, qué hago para no modificarlo y poder hacer git pull???.

**Comment by lopezjurip** [comment]
en la Consola/Terminal, anda a la carpeta del syllabus

``` sh
# Ejemplo, no sé cómo lo tengas en tu computador.
cd syllabus
```

Y ejecuta `git stash`. Ahora podrás hacer un `git pull` sin problemas :+1:

**Comment by fergarciafaura** [comment]
Gracias Pato :)
