### ISSUE TITLE
[IMPORTANTE] Sobre los FEEDBACKs de las Actividades

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#109]
# Sobre los FEEDBACK

Les estoy subiendo las correcciones que les hicieron los ayudantes a sus AC01 y AC02 (tomará un tiempo, son muchos). 

**Notarán que su _git_ en Github tendrá un commit que su _git_ local no tiene**. Cabe decirles que yo no corregí sus códigos (aunque el commit esté a mi nombre) y ante cualquier problema deben preguntar en el foro. Además recuerden que las instancias oficiales de recorrección son por el Siding. La @bcsaldias puede darles más información al respecto.
#### Probablemente tengan problemas al hacer `push` por un problema de `merge`.

La mejor manera de evitar estos problemas es que hayan ejecutado alguna vez este comando (que está en las [guías](https://github.com/IIC2233-2015-2/syllabus/wiki)):

``` sh
git config --global --bool pull.rebase true
```

Y la próxima vez que quieran hacer `git push`, antes hagan un `git pull`. Si no ejecutaste el comando de arriba tendrás que hacer `git push --rebase`.
#### Es un script

Estoy trabajando en una nueva versión del script para la [administración de repositorios según Github Students](https://education.github.com/guide) (para este ramos y para ojalá todos los ramos de computación). Si hay alguien interesado en saber sobre esto les dejo el repositorio del proyecto: 

**https://github.com/mrpatiwi/AyudanTS**

**Comment by Zepk** [comment]
Siguen subiendo los feedback de las actividades? Porque al menos yo no puedo encuentro los feedback de ninguna de las 2 actividades

**Comment by lopezjurip** [comment]
Probablemente los recibió tu compañero :/

**Comment by ralvarez94** [comment]
A mi tampoco me aparecen los commits y fui solo en ambas actividades

**Comment by Zepk** [comment]
Seria raro que lo recibiese mi compañero, porque la primera actividad la hice solo, y la segunda, solo se subio en mi repositorio o.O (al menos dentro del plazo)

**Comment by lopezjurip** [comment]
Escriban acá las personas que no recibieron el FEEDBACK y trabajaron solos en la AC01 y AC02

**Comment by orrios** [comment]
yop

**Comment by eduguerra-uc** [comment]
yo

**Comment by diflores** [comment]
Yo

**Comment by flobarrios** [comment]
Yo

**Comment by nateare** [comment]
yo (AC01)

**Comment by felipehv** [comment]
Yo !

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

2015-09-01 21:10 GMT-03:00 nateare notifications@github.com:

**Comment by fwzapata** [comment]
Yo

**Comment by andresespinosapc** [comment]
Yo. No tengo carpeta para la AC01, porque se entregaba por siding, no sé si importará.

**Comment by Arios16** [comment]
yo

**Comment by jgmontoya** [comment]
Yo no he recibido feedback y trabajé solo en la AC01 y con pareja en la AC02.

**Comment by benjavides** [comment]
Yo no he recibido feedback y trabajé solo en la AC01 y con pareja en la AC02 (pero yo subí el archivo)

**Comment by Mnfriedl** [comment]
Yo también trabajé solo en las actividades 01 y 02, y no tengo ninguno de los feedbacks.

**Comment by dpassi** [comment]
Yo tambien trabaje solo, aun sin feedbacks

**Comment by Zepk** [comment]
Bueno, publico denuevo, yo no tengo el feedack de la AC01, en la que trabaje solo, ni la de la AC02, en la que trabaje con pareja (pero yo subí el archivo)

**Comment by tamycova** [comment]
yo ac01 sola y ac02 en pareja

**Comment by raiperez** [comment]
yo ac01 solo y ac02 solo, sin feedbacks

**Comment by otro-felipe** [comment]
yo! ambas actividades las hice solo.

**Comment by SHGoldfarb** [comment]
yo, AC01

2015-09-02 18:30 GMT-03:00 MainScientist notifications@github.com:

> yo! ambas actividades las hice solo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IIC2233-2015-2/syllabus/issues/109#issuecomment-137250497
> .

## 

Samuel Goldfarb Hau
Estudiante de Ingeniería
Universidad Católica de Chile

**Comment by iqacevedo** [comment]
yo AC01 y AC02

**Comment by javierlopeza** [comment]
Yo la Ac01 y Ac02 las hice solo

**Comment by AlainLotissier** [comment]
yo tampoco

2015-09-03 21:36 GMT-04:00 javierlopeza notifications@github.com:

**Comment by vicentecastroa** [comment]
yo

**Comment by jpdattas** [comment]
yo

2015-09-04 16:52 GMT-03:00 vicentecastroa notifications@github.com:

**Comment by silvamatias** [comment]
yo trabaje solo en ac01 y ac02 y aun sin feedback, gracias!

**Comment by jnburgos** [comment]
Yo

**Comment by paxcema** [comment]
Yo!

**Comment by amroizman** [comment]
Yo, sola en la AC01 y con pareja en la AC02

**Comment by felipehv** [comment]
Aun nada

Felipe Haase Vargas
Estudiante de  Ingenieria
Pontificia Universidad Católica de Chile

**Comment by ralvarez94** [comment]
¿Qué va a pasar con esto? La recorrección de las AC01 y AC02 era hasta el jueves pasado según lo que avisaron...

**Comment by lopezjurip** [comment]
Creo que corregí el problema del script que hace la repartición. Están siendo subidos los `FEEDBACK.md` a las personas que no lo tenían (al menos del que subió la AC cuando eran de a dos).

La @bcsaldias publicará más información de las recorrecciones dado el problema que tuvimos. 

Recuerden que cuando quieran hacer `push`, antes deben hacer un commit con sus cambios, hacer un `git pull` y luego el `git push`.

**Comment by lopezjurip** [comment]
Están subidos los FEEDBACK de las AC03 y AC04

**Comment by benjavides** [comment]
Yo no tengo archivo de feedback en mi repositorio (Benjamín Benavides sección 1)
