### ISSUE TITLE
Creditos Maximos Pacmatico

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#110]
Cuantos son los creditos maximos que pueden tomarse en pacmatico?

**Comment by bamavrakis** [comment]
Hola!
No hay un máximo!! Solo se deben respetar las restricciones de topes correspondientes.
Saludos.

**Comment by Treisenegger** [comment]
Eso implica que uno le puede asignar cualquier cantidad de créditos a una persona o que los pueden pedir y después hay que botarles algunos?
