### ISSUE TITLE
algoritmo pacmático

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#111]
Hola tengo una duda de enunciado, este dice:

"luego de que todos los alumnos hayan seleccionado cursos y distribuido puntos, su programa debe ser capaz de dar los cursos a los alumnos de forma optima"

Van a evaluar el algoritmo como teoricamente? porque igual es complicado probarlo poblando el sistema con todos los alumnos y sus ramos ingresados

**Comment by mbucchi** [comment]
Hola!

Tenemos métodos mágicos para probar este tipo de cosas! (y muy buenos ayudantes) :smile: . 
Hablando más en serio, sí tenemos algunos métodos para probar esta funcionalidad, asumiendo que tu sistema permite una buena interacción por consola. No obstante, el algoritmo también se evalúa, como tu dices, "teóricamente". Nos preocupamos de que el código tenga sentido y que apunte en una dirección inteligente.
Esta es una de las razones por las cuales debes ser detallada en tu README. Sería muy útil que le expliques al ayudante la lógica detrás de tu algoritmo, así no lo tienes 2 días intentando entender tu código. Esto no solo facilita la corrección sino que incluso te puede favorecer en la evaluación de algunos puntos de la tarea.
Espero que esto aclare tus dudas. Saludos!
