### ISSUE TITLE
Problema leyendo los .txt

### ISSUE THREAD

**Issue by vnramirez** [IIC2233-2015-2/syllabus#112]
Hola! Hice un algoritmo para leer los archivos, y me andan bien hasta cierto punto. Llega un momento en el que ambos dejar de funcionar y me tira un error de 'str' object does not support item assignment.
En el caso de los cursos, me lee todo hasta el curso ICC2944, y para los nombres, los lee bien hasta el usuario espoerer. A alguien mas le pasa/le pasó?
Gracias!

**Comment by mbucchi** [comment]
Hola!
La verdad es que no observo nada especial con ese curso ni esa persona. El error implica que estás intentando asignar un valor suponiendo que un objeto es una lista pero es un string. Es el mismo error que arrojaría el siguiente código:

``` python
def func(lista):
    lista[0] = 'hola'

func('esto va a lanzar error')
```

Si te fijas, evidentemente no puedes asignar un valor al elemento número 0 del string `'esto va a lanzar error'`, pues los strings son inmutables. Lee tus métodos de parsing nuevamente e intenta observar en qué lugar podría estar pasando eso. Probablemente es un lugar en el que estás esperando una lista, pero te llega un string.

**PD**: Esto no está limitado a listas, pero el error debe ser algo similar.

Saludos!

**Comment by vnramirez** [comment]
Gracias!
