### ISSUE TITLE
Más de un profesor en el archivo cursos.txt

### ISSUE THREAD

**Issue by JoseRomeroi** [IIC2233-2015-2/syllabus#113]
Lei anteriormente que nuestra tarea debe leer de esta forma:

{
"property_1" : valor_1,
"property_2" : valor_2,
...
"property_n" : valor_n
} 

para el caso en el que hay más de un profesor, ¿Siempre estará escrito de esta forma?:

linea n: "profesor": [
linea n+1: profesor1
linea n+2: profesor2

no sé si me explique bien

**Comment by spiza** [comment]
Siempre que hay profesores están de esa forma... Me imagino que no es incorrecto pensar eso

Enviado desde mi iPhone
