### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by spiza** [IIC2233-2015-2/syllabus#115]
Hola!

No me queda muy claro que es lo que tiene que estar escrito en el archivo..

Cito:
"Debe adjuntar un archivo README.md donde comente sus alcances y el funcionamiento de su sistema
(i.e. manual de usuario) de forma concisa y clara."

Mi pregunta es: solo debo explicar como se usa el programa, o tengo que también describir en detalle como está hecho, y explicar cada una de sus partes? (Así como clases y métodos)

Saludos

**Comment by bcsaldias** [comment]
Hola !

La idea del README no es que expliques parte por parte tu código, si no
cómo testearlo (cómo probar que realmente funciona - cómo verificar que lo
que hiciste está bien o por qué está bien-> funciones importantes).

Además debes escribir tus supuestos que te hicieron hacer alguna parte de
una forma y no otra, explicar las partes que creas relevante (algoritmo de
bacanosidad?).

Puedes especificar qué cosas funcionan bien y cuáles más o menos. También
qué partes funcionan a la perfección o son genéricas, en general
comentarios de tu tarea.

Es una ayuda para el corrector para el momento de asignarte puntaje, un
buen readme hace que la evaluación sea más fácil, es como decir "hice esto
y esto, pero esto no".. etc. Ojalá no sea ultra largo porque son muchos
alumnos y el ayudante de todas formas verá todo tu código.

Saludos !
