### ISSUE TITLE
Ramos no existentes

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#116]
No sé si en todos los casos será así, pero los ramos que he visto que están en la lista de equivalentes son ramos que no existen y que sí aparecen como prerrequisito de otros ramos, de hecho hay listas de prerrequisitos que son solo ramos no existentes, por ejemplo "(ICH1102 y IIQ1002) o (ICH1102 y IIQ1002)". Qué hago en esos casos? Tengo que hacer una lista de equivalentes al revés para saber con qué ramo se podría convalidar?

**Comment by mbucchi** [comment]
_Los datos son obtenidos del Buscacursos directamente, cualquier reclamo por favor dirigirte a..._  :smile:

Mientras ellos no arreglen eso, existen varios pasos a seguir, los cuales quedan a tu criterio y deberás especificar en el README. Tiene bastante sentido hacer lo de las equivalencias, pero aún así, existen casos en que los ramos obsoletos solo tienen equivalencias con _otros_ ramos obsoletos. En esa situación existen varios soluciones. un par de ejemplos: decidir ignorar los requisitos o bien no dejar que alguien tome el ramo (lo cual en la realidad tiene poco sentido).

Intenta tomar una decisión que tendría sentido en un caso de la vida real y recuerda anotar estos alcances en el README.

Saludos.
