### ISSUE TITLE
Pacmatico tope evaluaciones/campus

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#117]
Pacmatico restringe el tope de evaluaciones y de campus?

**Comment by bamavrakis** [comment]
Hola!!
No, Pacmático no controla evaluaciones ni campus.
Saludos!

**Comment by javierlopeza** [comment]
¿¿¿??? 
El enunciado dice claramente que "a diferencia de Bummer, el Pacmatico no controla tope de horario"...

**Comment by bamavrakis** [comment]
Fallé, estaba pensando en Bummer, efectivamente Pacmático no controla tope de horario!!
Gracias por la corrección!
Saludos!

**Comment by otro-felipe** [comment]
Es decir que pacmatico **sí** controla evaluaciones y campus? o pacmatico no controla ningún tipo de tope?

me refiero a que uno puede pedir y apostar por sus ramos, pero a la hora de cerrar el proceso y entregarlos, no se controla ningún tope? asumimos que después habrá un período donde se regulen estos topes?

**Comment by robocop6** [comment]
Pacmático no controla ningún tipo de topes. Si quieres pensarlo más "realista", efectivamente después debiera haber algún periodo de reajuste, pero ustedes no se tienen que preocupar de esto.
