### ISSUE TITLE
Error usando librería numpy

### ISSUE THREAD

**Issue by Treisenegger** [IIC2233-2015-2/syllabus#118]
Estoy tratando de usar numpy para el problema de bacanosidad y cuando pruebo mi código para pocos datos funciona, pero cuando ingreso una cantidad grande arroja este error
![image](https://cloud.githubusercontent.com/assets/11668230/9668217/55dd07c0-524e-11e5-9f8b-7070735895be.png)
y he estado tratando de encontrar una solución, pero ni siquiera he encontrado la causa del problema. Qué podrá ser?

**Comment by mbucchi** [comment]
Uff jajaj, este problema es muy interesante. No te puedo decir específicamente qué es lo que lo está causando, pero te puedo explicar cuál es el problema.

Cuando tu ejecutas tu programa, varios de los datos se deben guardar en la memoria de tu computador, y estos se guardan en distintos lugares de la RAM. El tema, es que tu RAM tiene espacio limitado, y por lo mismo, siempre restringe algunas direcciones para uso del sistema operativo y de operaciones vitales para tu computador. Cuando algún programa intenta acceder a esos espacios de memoria, la CPU de tu computador toma el control de ese servicio y lo finaliza directamente (para evitar problemas graves con tu computador). Este es el error `0xC0000005`.

Ahora, _por qué rayos tu programa está intentando acceder direcciones de memoria privadas?_... Ese es otro tema:

Yo supongo que estás haciendo operaciones recursivas o bien muy complejas y estás guardando demasiados valores en distintas listas/arreglos/matrices/etc. Esto, en un principio tenderá a lanzar un error que probablemente hayas visto alguna vez: `StackOveflow`. Ahora, numpy es nuestro amigo e intenta no mostrarnos ese error, por lo cual varios de sus procesos simplemente ignoran ese error y siguen trabajando. El problema es que cuando se les acaba el espacio puede que intenten acceder a esos espacios restringidos de la memoria, ahí es cuando la CPU se enoja y simplemente corta la ejecución de tu programa.

Esto último es simplemente una tincada, pues no conozco exactamente el flujo de tu programa. Revisa tu código por si tienes muchas asignaciones innecesarias que puedes eliminar.

Espero que esta, _un poco complicada_, respuesta te haya servido.
Saludos!

**Comment by Treisenegger** [comment]
La verdad es que lo único que hace el código es armar una matriz en formato de listas, instanciar una matriz de numpy usando la anterior y luego ejecutar el comando numpy.linalg.eig sobre ella, por lo que no hay ninguna parte que pueda eliminar si quiero que el código funcione :(

**Comment by jgmontoya** [comment]
Me imagino que la matriz es demasiado grande como para calcular los valores/vectores propios :/

**Comment by Treisenegger** [comment]
Eso supuse también lo que me obligaría a reescribir toda esa parte del programa :\

**Comment by gebalassa** [comment]
@jgmontoya 

No entiendo qué tienen que ver los valores y vectores propios con solucionar el sistema de ecuaciones para sacar las bacanosidades. :-/

**Comment by jgmontoya** [comment]
@gebalassa 

Te dejo un link que te puede servir para entenderlo: https://es.wikipedia.org/wiki/Vector_propio_y_valor_propio
Saludos!

**Comment by fgvenegas** [comment]
El metodo de valores y vectores propios para esta matriz enorme creo que no era muy recomendado debido a la cantidad de tiempo y memoria que gasta

**Comment by gebalassa** [comment]
intenta con **linalg.solve** en vez de linalg.eig
