### ISSUE TITLE
Duda acerca de versión de Python

### ISSUE THREAD

**Issue by rrhurtado** [IIC2233-2015-2/syllabus#120]
Dice en el enunciado que es requisito trabajar con python 3.4. Hasta ahora había asumido que era equivalente a usar python 3.4.3, pero no está de más preguntar: habrá algún problema al corregir mi tarea? 

Saludos!

**Comment by aaossa** [comment]
Hola, **no deberían haber problemas** con esa versión. De hecho, es la última versión estable (en cuanto a que es la más "avanzada") que Python "promociona" en su página web, por lo que todo bien con `Python 3.4.3`. :snake: 

**Un poco mas de datalle:** [**Aquí**](https://www.python.org/downloads/) puedes encontrar todas las versiones publicadas de Python. Como verás, la última versión estable que se publicó es `Python 2.7.10`, que estabiliza Python 2 _en su forma final_. Pero la versión actual, Python 3, está avanzada hasta `Python 3.4.3`. (A pesar de que ya están desarrollando Python 3.5 y preparando los cambios para 3.6).

**Resumen:** Durante el transcurso del semestre nos mantendremos en esta versión. Así que si tienes `Python 3.4.3` estás listo :grin:

**Comment by lopezjurip** [comment]
Nunca está de más aprender:

# Versionamiento Semántico

http://semver.org/lang/es/
