### ISSUE TITLE
Subir Tarea

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#121]
Solo para confirmar, hay que subir en nuestro repo en la carpeta tareas en T01 todos los archivos .py que hayamos creado mas el README y por el siding subir solo el diagrama?

**Comment by lopezjurip** [comment]
Sip, asegúrense de declarar en el `README.md` si hay que ejecutar algún comando `pip` para instalar algo o algo así. 

Sí, el diagrama al Siding. `git` está hecho para trabajar con archivos de texto/código livianos. Si suben una imagen pesada se entorpece su uso.
