### ISSUE TITLE
T02

### ISSUE THREAD

**Issue by ouhenio** [IIC2233-2015-2/syllabus#123]
Buenas. ¿Se va a subir en algún texto tipo para saber mas o menos cómo es el sistema a hackear o hay que inferirlo?

**Comment by mbucchi** [comment]
A qué te refieres con un texto tipo? todos los datos necesarios son generados por la librería `systema.pyc`. Espero estar respondiendo tu pregunta, de no ser así, por favor aclárame. 
Saludos!

**Comment by ouhenio** [comment]
Perfect, ya entendí. Gracias!!
