### ISSUE TITLE
¿Puedo modificar el README.md?

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#124]
Resulta que en el README.md de la Tarea 1 di algunas instrucciones mal y no estaba muy completo por falta de tiempo, y no quiero que el corrector se complique al revisar. ¿Será posible hacer algo al respecto?

**Comment by bamavrakis** [comment]
Hola!
Sube tu nueva versión del README a tu repositorio, los correctores lo revisarán desde ahí.
Saludos!
