### ISSUE TITLE
Duda Enunciado T02

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#125]
1. Con respecto a que no se pueden utilizar estructuras de datos como las que vienen por defecto: Puedo utilizar clases para definir estructuras que simulen exactamente el comportamiento de estas? O debo evitar por completo los conceptos de "listas", "diccionarios", etc.
2. No entiendo en que podría consistir la interacción con el usuario. No basta hacer un programa que corra y genere los archivos de texto pedidos?

**Comment by fdoflorenzano** [comment]
Hola! 
1. Esa es precisamente la idea de la restricción. Que aprendan a desarrollar sus propias estructuras en distintas complejidades. Si la clase Mi_lista, ningun problema.
2. Puede ser así, queda libre. Tal vez quieres que se genere solo uno de los archivos cuando lo corres para ir probando o algo así. Pero puede ser como tu dices también.
Saludos!

**Comment by fgvenegas** [comment]
Que cosas estan restringidas aparte de listas y diccionarios ? len , for y ese tipo de cisas las podemos usar?

**Comment by gafigueroa** [comment]
Puedes usar len y for, pero para usarlas debes definirlas tu en tus clases lista o diccionario (o la estructura que hagas), te recomiendo revisar la materia de Overriding de operadores (Capitulo 3 de OOP del material de clases).

Acá tienes además la [documentación](https://docs.python.org/2/reference/datamodel.html) de python en donde están descritas las distintas funciones que puedes implementar

**Comment by javierlopeza** [comment]
@gafigueroa Con respecto al mismo tema, todavía no entiendo cómo hacer una estructura que haga lo mismo que una lista pero sin usar nada de nada de listas. ¿Puedo por ejemplo hacer esto?:

``` python
class MiLista:
    def __init__(self, lista):
        self.lista = lista

    def __getitem__(self, i):
         return self.lista[i]


mi_lista = MiLista([1,2,3,4,5,6])
print(mi_lista[3])    # 4
```

¿En este caso se considera que estoy usando listas?

**Comment by lopezjurip** [comment]
https://en.wikipedia.org/wiki/Linked_list

**Comment by gafigueroa** [comment]
No :(
Debes programar la lista desde cero, ahí estas usando las listas de python.
Para que tengas una idea, una lista simple es una estructura de datos que esta compuesta por nodos, la lista sabe cual es su primer nodo, a la vez, cada nodo sabe cual es el nodo siguiente, y el valor que esta guardando.

El siguiente es un ejemplo de una lista:
![linked_list](https://cloud.githubusercontent.com/assets/11564999/9803173/66efdc38-57f6-11e5-9fa9-32ab4a0ebd86.png)

**Comment by javierlopeza** [comment]
@gafigueroa gracias!
