### ISSUE TITLE
Duda sobre las conexiones alternantes y antiguas.

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#126]
Hola! Tengo la siguiente duda respecto de las conexiones. Supongamos que estoy por primera vez en un puerto P, del cual avanzo por una conexión C hacia un puerto Q (C es un número int de conexión, el que se ingresa como parámetro en hacer_conexión(int)), pero desconozco el tipo de conexión que sea C (normal, aleatoria o antigua). Supongamos también que eventualmente regreso a P luego de n llamados de la función hacer_conexión(), y que el llamado n+1 es también por la conexión C (C es el mismo número de antes). Si esta me lleva al mismo nodo que antes, es decir, a Q, ¿inmediatamente asumo que esa conexión C de P es normal? (es decir, no es aleatoria ni es de las antiguas, sino que siempre dirige a Q). Mi pregunta es porque, si fuera alternante y tuviera como posibilidad mandar al puerto Q o al puerto R, por ejemplo, y al llamarla otra vez me mandase a R, descarto inmediatamente que es simple, por razones obvias. Pero, si tuviera la "mala suerte" que la llamara 100 veces, por ejemplo, y siempre me mandara a P, ¿qué me garantiza que la vez número 101 no me mandará a R? Lo mismo, pero más en general, me pasaría para una conexión antigua, que según entiendo, maneja un conjunto de n posibilidades. Si fuera aleatorio, pero tuviera como restricción que no salga la misma que salió la vez anterior al llamar a la misma conexión C del puerto P, descartaría que es simple o normal. Más aún, si la que saliera fuese distinta a las dos de los últimos dos llamados, las cuales a su vez fueran distintas (por ejemplo, salieron ya Q y R y ahora sale S), podría descartar no sólo normalidad, sino alternabilidad entre dos.  ¿Cómo funciona en realidad? Muchas gracias de antemano y por favor preguntar si no fui suficientemente claro. Saludos!

**Comment by gafigueroa** [comment]
Holas, de las conexiones que funcionan de manera rara hay dos, las alternantes y las aleatorias.

Si la conexión es alternante, tiene solo dos posibles puertos a los que puede llegar, entre los que se turna. Siguiendo como tu lo escribiste, si estás en el puerto P, y haces la conexión C, y esta es alternante, esto quiere decir, que si la primera vez que haces esa conexión te lleva a Q, la segunda vez que la hagas te llevará a R, la tercera a Q, la cuarta a R, así sucesivamente.

Mientras que si es aleatoria, esta tiene un conjunto de nodos (pueden ser más que 2) a los que puede ir, y cada vez que hagas la conexión, te llevará de manera aleatoria a un nodo de este conjunto, por lo que teóricamente, si, podría ocurrir que 100 veces te mande a la misma conexión, y a la vez 101 te mande a otra.

Espero te haya aclarado como funciona.

**Comment by jgmontoya** [comment]
Hola!

¿Podemos suponer que, en una conexión aleatoria, la probabilidad de llegar a cualquier nodo (del conjunto de nodos a los que puede ir) es la misma?

Es decir, si desde el nodo A puedo llegar a los nodos B, C y D, ¿puedo suponer que la probabilidad de llegar a cualquiera de estos tres en específico es 1/3?, ¿o bien puede ocurrir que alguno de los nodos sea más probable?, por ejemplo que llegar al nodo B tenga una probabilidad de 1/2 mientras que llegar a los nodos C y D tenga una probabilidad de 1/4 para cada uno.

Saludos!

**Comment by AlfonsoIgnacioV** [comment]
Sí, me quedó claro :) gracias de nuevo!! :)

**Comment by alopez7** [comment]
La probabilidad de que una conexión aleatoria es igual pata todos los objetivos. Ojo que cuando el robot pasa por una conexión alternada también cambia la dirección.

**Comment by javierlopeza** [comment]
Varias dudas de las conexiones.
**1.** Si estoy en un puerto X, ¿dicho puerto solo tiene conexiones de 1 tipo con otro(s) puerto(s)? (solo aleatorias, o solo alternante, o solo normales) ¿O puede existir un puerto que tenga algunas conexiones alternantes y otras normales por ejemplo?
**2.** Si estoy en un puerto X el cual tiene una conexión alternante con otros dos puertos. Luego uso el metodo _posibles_conexiones()_, ¿me debería retornar 1 o 2? La misma pregunta para las conexiones aleatorias, ¿me debería retornar 1 o el numero total de posibles puertos a los que aleatoriamente se puede conectar?.
Gracias!

**Comment by gafigueroa** [comment]
1. Un puerto puede tener distintos tipos de conexiones con otros puertos, puede existir uno que tenga conexiones normales, alternantes y aleatorias al mismo tiempo.
2. Tanto las conexiones alternantes como las conexiones aleatorias cuentan como una conexión, por lo tanto, si el puerto tiene una sola conexión, da lo mismo si esta es normal, aleatoria o alternante, retornará 1.

**Comment by javierlopeza** [comment]
@gafigueroa perfecto, gracias. Y siguiendo con lo que se dijo más arriba, ¿cuantas veces puedo suponer que es determinante para decidir si una conexion C del puerto P es normal, alternante o aleatoria? O sea, si hago 100 veces esa conexión desde P y cada vez que la hice me llevó al mismo puerto Q, ¿puedo determinar que esa conexión es normal? Sino, ¿cual seria el criterio para determinar el tipo de conexion? Ya que como señalaste arriba, podría pasarnos que 100 veces nos lleve al mismo puerto y la 101 nos lleve a otra. 
En ese mismo sentido, podría pasar que al hacer miles y miles de hacer_conexion() algunas conexiones aleatorias nunca nos lleven a ciertos puertos, por lo que no podriamos determinar bien esa parte de la red.

**Comment by gafigueroa** [comment]
Ahi entraría un tema de probabilidades, pero como dato, si es aleatoria, y puede llevar a dos puertos, y pasas 6 veces, la probabilidad de que te envié las 6 a un mismo lugar es de 0,03125. Y si pasas 100 veces, bueno http://www.wolframalpha.com/input/?i=2*%281%2F2%29%5E100 , un numero muy muy chico.
Si quieres que lo decisivo sea según con cuantas veces pasas, ahí puedes jugar en wolframalpha con el exponente y ver la probabilidad.

**Comment by javierlopeza** [comment]
Perfecto! Gracias @gafigueroa 
**1**. ¿Entonces es cosa de que dejemos explicado en el Readme que hago suposiciones validas basadas en probabilidades?
**2.** Y la ultima cosa en relación a las conexiones: si llego a un puerto P que tiene una conexión C del tipo aleatoria (de la cual me puedo dar cuenta que claramente lo es por los diferentes puertos a los que me ha llevado), ¿cómo puedo saber que ya he pasado por todos los puertos posibles a los que aleatoriamente me podría llevar esa conexión? ¿igualmente con probabilidades? Algo así como por ejemplo: si ya he pasado 50 veces por esa conexión y me ha llevado sólo a 7 puertos diferentes, ¿podría asumir por probabilidades que esa conexión aleatoria elige entre dichos 7 puertos y ninguno más? ¿O debería usar métodos que _no_ se basen en probabilidades?

**Comment by fgvenegas** [comment]
Cuando se habla de las conexiones que tiene un nodo es equivalente a los caminos que tiene este? y lo otro, si un me sale que tiene 3 caminos, puede incluir el camino del que vengo?

**Comment by fdoflorenzano** [comment]
@javierlopeza Todas las suposiciones en el readme siempre! Y claro, es una suposición válida pensarlo en términos de probabilidades. Pero tal vez no sea la única.
@fgvenegas Cada puerto tiene conexiones por la cual uno puede ingresar, o caminos que te llevaran a algún lado, pero siempre son que te llevan de ese puerto a otro. Entre las conexiones de un puerto puede haber uno que te lleve a un puerto justo anterior al de que vienes, pero esa conexión en sí es distinta a la usada para llegar al nodo original. Piénsalo domo flechas unidireccionales, 2 puertos pueden apuntarse entre ellos pero son flechas distintas entre sí. 
Espero se entienda y ayude! Saludos

**Comment by javierlopeza** [comment]
@fdoflorenzano gracias por la aclaración. Me surgió otra duda respecto a lo que respondiste de las conexiones. Cuando estoy en un puerto y pregunto _posibles_conexiones()_: ¿Me retorna, por así decirlo, la cantidad de flechas que **salen**? ¿O la cantidad de flechas que **entran**? ¿O ambas?

**Comment by fdoflorenzano** [comment]
@javierlopeza que salen!

**Comment by javierlopeza** [comment]
@fdoflorenzano gracias!

**Comment by javierlopeza** [comment]
Otra pregunta más que me surgió. Para el caso de las conexiones aleatorias, si paso por esa conexion varias veces me puedo dar cuenta que es aleatoria, pero: ¿cómo puedo saber que ya me ha enviado a todos los puertos entre los que aleatoriamente me puede mandar?. Por ejemplo la conexion C me puede mandar a 100 puertos diferentes (no se puede saber que son 100) y luego de pasar 150 veces por esa conexión descubro que me ha mandado ha 70 puertos diferentes ya que algunas veces repitio los puertos a los que me envió. Va a sonar repetitivo pero: por ejemplo si pase 150 veces por la conexion y ya me envió mas de 10 veces a cada puerto, ¿puedo asumir probabilisticamente que no me enviará otro puerto que no me haya mandado antes? Me complica el tema de la incertidumbre que existe en la red.

**Comment by djpassi** [comment]
@javierlopeza A tu ultima duda:
Si preguntas a tu nodo, posibles_conexiones() y te dice que hay N conexiones, luego de haber iterado hartas veces te das cuenta que has podido llegar a N-2 nodos desde el nodo que estabamos hablando, entonces quiere decir claramente que te faltan 2 nodos por recorrer.

**Comment by javierlopeza** [comment]
Pero @gafigueroa dijo más arriba que una conexión aleatoria vale por 1 conexión, no por la cantidad de posibles puertos a los que me puede enviar, ¿o me equivoco?.  Lo que entiendo yo es que si estoy en el puerto P, que tiene **1 conexion**, la cual es aleatoria, esta me podría llevar a **M puertos diferentes**.

**Comment by djpassi** [comment]
No, tu al preguntar posibles_conexiones(), te da el numero de conexiones posibles.
Lo que cambia y es aleatorio o alternante es que al momento de hacer_conexion() si tu al aplicar  hacer_conexion(0) te llevaba a la lista A y luego cuando volviste al nodo, hiciste  hacer_conexion(0) te puede llevar al nodo B.

Creo estar en lo correcto, si no, que alguien me corrija.

**Comment by gafigueroa** [comment]
@javierlopeza Es como dije anteriormente, retorna la cantidad de conexiones, no la cantidad de puertos a los que puede llegar, te puede decir que tiene 1 conexión, que esta sea aleatoria y que te lleve a M puertos diferentes.

**Comment by gafigueroa** [comment]
Con respecto a tu otra duda, puedes decir en tu readme que asumes que luego de haber pasado X veces por cada puerto, ya sabes todos los posibles puertos a los que puede llegar tu conexión aleatoria.

**Comment by javierlopeza** [comment]
@gafigueroa perfecto, ahí me quedo más claro. Gracias!
