### ISSUE TITLE
sistema.pyc

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#127]
No entendi como trabajar con este archivo, lo puse en una carpeta y trate de importarlo pero no paso nada, no lo reconocia, eso :cry:

**Comment by gafigueroa** [comment]
Hola, como lo estas intentando de importar?
La forma correcta de importarlo es que estén en una misma carpeta y escribir
`import sistema`

Si lo estas escribiendo así, que error te está dando?

**Comment by AlfonsoIgnacioV** [comment]
Hola, a mí también me pasó lo mismo, pero lo que hay que usar es el mismo archivo que resulta de hacer pull. No intentes copiarlo porque yo lo hice y me salía un error de bad magic number. Ojalá sirva, saludos :)

**Comment by gafigueroa** [comment]
El bad magic number también les puede aparecer si corren su programa con python2.7 en vez de python3

**Comment by fgvenegas** [comment]
D; voy a intentar lo que dice Alfonso porque lo copiaba en una carpeta X i ponia import sistema y no pasaba nada, pycharm nisiqueira lo reconocia en la carpeta donde estaba

**Comment by fergarciafaura** [comment]
Pucha yo no puedo hacerlo de ninguna forma. Ayuda !!

**Comment by Pochoclo** [comment]
Bajé el archivo lo deje en la carpeta que estoy usando y al tratar de importar no me lo reconoce D: estoy trabajando con pycharm

**Comment by aaossa** [comment]
Podrían probar esto y me dicen si funciona?

``` python
import imp

sistema = imp.load_compiled("sistema", r"sistema.pyc")
```

**Comment by fgvenegas** [comment]
al final lo importe y me salia `import sistema` pero el "sistema" como si no lo reconociera, pero al usar algunas de las funciones del PDF funcionan igual

**Comment by Pochoclo** [comment]
Si, ahora vi que no lo reconoce pero igual se pueden usar las funciones.

**Comment by famunoz16** [comment]
a mi tampoco me reconoce el import sistema /:!! y no me deja usar las funciones

**Comment by ghost** [comment]
Guille sigo teniendo problemas con eso:

`Traceback (most recent call last):
  File "/Users/Federico/Desktop/fekunze-repo/Tareas/T02/main.py", line 1, in <module>
    import sistema
ImportError: bad magic number in 'sistema': b'\xee\x0c\r\n'`

**Comment by ghost** [comment]
Resuelto 

El archivo sistema.pyc está hecho en Python 3.4, por lo que para leerlo hay que tener la misma versión de python como interprete. Para cambiarlo, hay que ir a Pycharm > Proyect: <usuario-repo> > Proyect Interpreter y ahí cambiar la versión de Python. 

También pueden ver la versión de Python con el comando `sys.version` importando previamente la librería `sys`

**Comment by spiza** [comment]
@aaossa , funciona lo que dijiste, pero tal y como dicen mis compañeros, no funciona bien, pues al hacer sistema. algo, no reconoce las funciones que puede tener sistema, y por lo tanto complica mucho la programación

**Comment by aaossa** [comment]
Que raro @spiza , a mi me funciona bien. No sé que podría estar provocando el comportamiento distinto. 

![st3](https://cloud.githubusercontent.com/assets/10425834/9832897/b9dcd8f4-595b-11e5-9319-8ce1109e3f55.PNG)

¿Estás haciendo otra cosa o llamando otra función? Quizás también me equivoqué y no es a lo que se refieren

**EDIT:** Cuando hago `import sistema` no me reconoce el módulo, pero si hago lo que muestro en la siguiente imagen (antes de llamar a la función escribo `import sistema`) ahí si me reconoce el módulo, aunque parece no ser necesario para llamar a la función (como se ve en la primera imagen)

![st3](https://cloud.githubusercontent.com/assets/10425834/9832922/8a3b0fac-595c-11e5-906c-929528b89025.PNG)

**Comment by spiza** [comment]
A mi el imp me aparece tachado! Quizás pueda ser eso!

**Comment by aaossa** [comment]
@spiza ¿Funciona si usas `imp.load_module`?

**Comment by spiza** [comment]
Nopes, si uso load module me tira error
