### ISSUE TITLE
Pregunta sobre la estructura de la red y el robot

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#128]
Hola! Mi pregunta es si dada la red sobre la cual trabajamos, a partir de todo puerto se puede acceder siempre a todo puerto. Es decir, si para todo puerto de la red existe siempre un camino que lo lleva a todo otro puerto. Mi pregunta es porque eventualmente la red tiene tal estructura, que una vez llegado a cierto puerto P ya no existe ninguna posibilidad de volver a un puerto Q. 
    En caso de que no fuera así, o sea, que pudiera quedar por lo menos un puerto aislado, ¿el robot encuentra siempre al usuario en tiempo finito, o eventualmente puede que nunca lo encuentre? Muchas gracias!
Saludos

**Comment by fdoflorenzano** [comment]
Hola! La construcción de la red garantiza que se puede llegar a todo puerto desde cualquier otro. Nunca quedaras atrapado en uno. En cuanto al robot, no se detalla su movimiento a propósito. La idea es escapar de el, por que puede detener tu exploración de la red. Espero te haya respondido!
