### ISSUE TITLE
Atrapado por el robot

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#129]
¿Si el robot me pilla husmeando en la red de bummer, cambia la red por completo? ¿Que comienza con un nuevo paquete significa que se hace reset please try again?

**Comment by mbucchi** [comment]
Nop, simplemente te manda al nodo inicial. Que comiences con un nuevo paquete implica que estás mandando un nuevo request desde tu computador, por eso comienzas nuevamente desde el puerto inicial. Saludos!

**Comment by jgmontoya** [comment]
¿Qué pasa si el robot me atrapa en el nodo inicial?

**Comment by mbucchi** [comment]
@jgmontoya, sigue la misma lógica. Un paquete nuevo se envía desde tu computador, es decir partes desde el puerto inicial.

**Comment by jgmontoya** [comment]
Entonces si eso sucede el robot me campeará por siempre en el puerto inicial? :(

**Comment by mbucchi** [comment]
@jgmontoya, no debiese haber problemas ya que las conexiones son por turno. En este caso, solo te causaría problemas si es que al decidir hacer una conexión desde el nodo inicial, tanto tú como el robot eligen el mismo camino. En aquel caso, sí te devolvería al puerto inicial una segunda vez. No obstante, como podrás ver, esta vez el robot no se encuentra en el puerto inicial y podrás moverte libremente. Espero haberte aclarado un poco la situación

**Comment by jgmontoya** [comment]
Entiendo, gracias!
