### ISSUE TITLE
Se quedó este gorrito en la sala de la ayudantía.

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#13]
Se quedó esto: :snowflake: :womans_hat: 

![image](https://cloud.githubusercontent.com/assets/7570744/9317741/01a5b694-4514-11e5-84aa-4bc4b5f7e970.png)

Lo dejaré en el CAi en las cosas perdidas :)

**Comment by gebalassa** [comment]
El código me parece bien.
Falta la clase _"Persona"_ y la subclase _"Dueño del Gorro"_, pues de por sí el gorro es demasiado abstracto para cualquier fin práctico.
