### ISSUE TITLE
Lo que está permitido

### ISSUE THREAD

**Issue by ivanwolf** [IIC2233-2015-2/syllabus#130]
Hola, si o me equivoco, para la tarea 2, no podemos usar listas, dict y esas cosas.
La idea es que cree mi propia estructura,  mi pregunta es si es que puedo heredar algunos métodos de la clase `dict` , por ejemplo. i.e., puedo crear mi clase de esta forma:
`class MyDict(dict):`
o la tengo que hacer de la nada, eso.
Saludos.

**Comment by gafigueroa** [comment]
No, la idea es que tu hagas la estructura desde cero, al heredar list o dict como que seguirías usando las estructuras de python solo que le cambiarías los nombres
Ejemplo, si creo la clase 

``` python
class Diccionario(dict):

    def nothing():
        pass

diccionario = Diccionario()

diccionario["ejemplo"] = 1
print(diccionario["ejemplo"])
```

Esto funcionaria y te imprimiría 1, tendrías el diccionario armado sin realmente haber programado, la idea es que tu hagas el código que ocurre al momento de ejecutar `diccionario["ejemplo"]`, que entiendas que esta pasando dentro de la estructura.

**Comment by fgvenegas** [comment]
y se pueden usar lambda functions, map y reduce?

**Comment by fwzapata** [comment]
Esa es la idea de la tarea... usar las cosas de programacion funcional....

**Mensaje de un ayudante (@aaossa):** Esto es correcto :+1: (me dio lata enviar spam por esto)
