### ISSUE TITLE
¿Se puede usar el módulo collections.abc de la librería estándar?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#133]

**Comment by fdoflorenzano** [comment]
Perdón la demora! Se pueden usar en el contexto de asegurarse que contengan los métodos que quieres que tus estructuras. Pero recuerda que la idea es que se implementen cada una por ti sin la ayuda de estructuras nativas. Espero esto haya ayudado, saludos.
