### ISSUE TITLE
preguntar_puerto_actual()

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#134]
El método "preguntar_puerto_actual()" que sale en la primera plana del enunciado (donde dice "su segunda componente se explica en la siguiente seccion") es el mismo método de la parte dificultades "pregunta_nodo_actual()" ?? (el segundo no existe con ese nombre parece)

**Comment by gafigueroa** [comment]
Si, es el mismo, fue un error de tipeo en el enunciado, el método correcto es preguntar_puerto_actual()

**Comment by tamycova** [comment]
Gracias!
