### ISSUE TITLE
¿Se puede usar raise?

### ISSUE THREAD

**Issue by SHGoldfarb** [IIC2233-2015-2/syllabus#136]
Lo usaria para indicar el fin del  **getitem** de mi clase, con IndexError

**Comment by fdoflorenzano** [comment]
Perdón por la demora! Como es manejo de excepciones, no hay restricción. Mejor aún si manejas excepciones de tus propias estructuras! Saludos

**Comment by SHGoldfarb** [comment]
Ok, Gracias!
