### ISSUE TITLE
Cantidad de puertos

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2015-2/syllabus#138]
Uno puede asumir que el puerto inicial es el 0, y el puerto final siempre será el numero más grande de la red? O puede ocurrir que el puerto final sea, por ejemplo, 35 y la cantidad de puertos de la red sean 50

**Comment by fdoflorenzano** [comment]
No se puede asumir. Es como el caso que dices. Pero el puerto inicial siempre es cero. Saludos!
