### ISSUE TITLE
Restricciones listas

### ISSUE THREAD

**Issue by rrhurtado** [IIC2233-2015-2/syllabus#139]
Tengo entendido que no se pueden usar listas, y uno debería crear su propia clase Mi_Lista. Mi duda es si al usar una función 'zip' por ejemplo, también tengo prohibido hacer el casteo a list, ¿debería hacer un casteo a Mi_Lista para ocuparlo, o está permitido usar [ ] de vez en cuando?

**Comment by rodolfopalma** [comment]
Hola,

Tu_Lista debería ser capaz de castear un iterable (como el que retorna la función `zip`) sin necesidad de usar `list`.

**Comment by rrhurtado** [comment]
Buena gracias !
