### ISSUE TITLE
problemas con pushear repositorio

### ISSUE THREAD

**Issue by fjsalinas** [IIC2233-2015-2/syllabus#140]
El martes pasado no pude entregar la actividad porque tengo problemas con el repositorio, al poner git add . me aparece este error
![problema repo](https://cloud.githubusercontent.com/assets/8507323/9778571/26e19cbe-5740-11e5-8657-cee611728b67.png)

**Comment by lopezjurip** [comment]
http://lmgtfy.com/?q=windows+index.lock+file+exists

Otra opción es respaldar los cambios a mano y clonar el repositorio de nuevo.

**Comment by jpdattas** [comment]
Hola, para la actividad de oidia tuve problemas para pushear. Me di cuenta de esto tarde eso si, como 11:20. Hice lo que habían dicho en una ayudantía de poner "git pull --rebase" y se me borró lo que tenía (estaba apurado y no pensé en respaldarlo antes de esto). Hay alguna forma de recuperar lo perdido (quizás alguna herramienta de pycharm)? No creo que pueda contar para la corrección (o si?) pero serviría saberlo. 

![image](https://cloud.githubusercontent.com/assets/13739046/9791259/80d96650-57b0-11e5-977f-b26b85ee6a09.png)

Y ahora no puedo hacer pull ni push

edit: ya recupere los archivos viendo los commits anteriores. Y ya los subí también. hay alguna forma de que me cuente para la actividad (quizás viendo la hora del commit que subi, siesque se puede)

**Comment by lopezjurip** [comment]
@jpdattas revisé tu commit y sí, estás dentro de los que entregaron :+1: 

Puedes verlo tu mismo acá:
https://github.com/IIC2233-2015-2/jpdattas-repo/commit/ba2dd3d6f6f00d9b84a10462e3954bd8dedc472a.patch

**Comment by jpdattas** [comment]
ok, gracias!
