### ISSUE TITLE
__new__ y __init__

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#141]
El siguiente código:

```
class Meta(type):
    def __new__(cls, name, bases, attr):
        print(1)
        name = "A_class_named_" + name
        return super().__new__(cls, name, bases, attr)

    def __init__(cls, name, bases, attr):
        print(2)
        print('¡I am still called ' + name + ' in init!')
        return super().__init__(name, bases, attr)

class A(metaclass = Meta):
    pass

print("Now I'm", A.__name__)
```

Imprime:

```
1
2
¡I am still called A in init!
Now I'm A_class_named_A
```

¿Por qué al momento de llamar a **init**, name seguía igual?

**Comment by robocop6** [comment]
Hola! @jecastro1 resolvió esto en la sección 2, pero para que quede claro para todos, respondo por acá. Lo que pasa es lo siguiente:

Cuando se crea la clase `A`, al haberse declarado una metaclase para `A`, se ejecutarán los métodos `__new__` e `__init__` (en ese orden). Los argumentos que reciben son:

 Para `__new__`:
- `cls` es la propia metaclase `Meta` (que es quien va a modificar la clase a ser creada).
- `name` es el nombre de la clase a ser creada
- `bases` son las clases de las cuales hereda la clase a ser creada
- `attr` es el diccionario de atributos (y métodos)

Para `__init__`:
- `cls` **NO ES** la metaclase `Meta`, sino la clase que retornó `__new__`, la que acaba de ser creada. Esta clase, en tu ejemplo, es la que tiene modificado el atributo name.
- `name` es el nombre de la clase a ser creada, **pero es el mismo nombre que recibió anteriormente el new**
- `bases` son las clases de la cual hereda la clase a ser creada, **pero es el mismo valor que recibió anteriormente el new**
- `attr` es el diccionario de atributos (y métodos). Este sí viene modificado, con las actualizaciones que se le hicieron en el `__new__`. Es decir, este sí es el nuevo diccionario de atributos de la clase que ha sido creada.

Así, por ejemplo, si ejecutas el siguiente código en vez del anterior:

``` Python
# Clase que sera subclaseada
class B: pass

class Meta(type):
    def __new__(cls, name, bases, attr):
        print(1)
        print(cls)
        name = "A_class_named_" + name
        bases = (B,)  # la estoy obligando a heredar de B
        attr['nuevo'] = 1
        return super().__new__(cls, name, bases, attr)

    def __init__(cls, name, bases, attr):
        print(2)
        print(cls)
        #name es el mismo que recibio __new__
        #bases tambien: es (), pero cls si hereda de B
        #attr fue modificado, pues tiene la key "nuevo"
        print('name: ', name)
        print('bases: ', bases)
        print('attr: ', attr)
        print('You think I am called ' + name + ' in init but my name is ' + cls.__name__)
        return super().__init__(name, bases, attr)

# Clase a ser creada con Meta
class A(metaclass=Meta): pass

#Esto muestra que A si hereda de B
print(A.__mro__)
```

El output en consola es:

```
1
<class '__main__.Meta'>
2
<class '__main__.A'>
name:  A
bases:  ()
attr:  {'__module__': '__main__', 'nuevo': 1, '__qualname__': 'A'}
You think I am called A in init but my name is A_class_named_A
(<class '__main__.A'>, <class '__main__.B'>, <class 'object'>)
```

Espero que haya quedado claro! Si quieres saber un poco más, la razón por la cual el `attr` que recibe el `__init__` viene modificado es que las funciones reciben a los diccionarios por referencia, pero si redefines una variable entera o tupla dentro de la función, esta no se modifica afuera. Esto queda claro con el siguiente código:

``` Python
def fdic(dic):
        dic['robot'] = 'robocop6'

def fint(num):
        #hacer cosas
        num += 1
        #hacer otras cosas

d = {}
fdic(d)
print(d)  #esto imprime {'robot': 'robocop6'}

i = 1
fint(i)
print(i)   #esto imprime 1
```

Entonces, cuando `__new__` recibe a `name`, `bases`, `attr`, y adentro redefine las variables `name`, `bases`, estas modificaciones solo existen en el scope de `__new__` y por lo tanto, `__init__` las recibe sin las modificaciones. Pero al modificar `attr` se modificó el objeto diccionario, y este mismo objeto fue el que se envió a `__init__` posteriormente, por lo cual el `attr` que recibe `__init__` sí incluye los cambios.

Saludos!

**Comment by cpieringer** [comment]
Muy buena pregunta y excelente explicación :smile:
