### ISSUE TITLE
Recorreccion AC03

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#142]
Hola, en día de la actividad 03 no dije presente en la lista, pero hablé inmediatamente con el profesor sobre el tema, la actividad la realicé en pareja y me aparece un 1.0 en el siding y no me aparece el feedback en mi repo, existe la posibilidad de que me suban el feedback o mando la recorrecion sin saber que dice el feedback por el siding?

**Comment by bcsaldias** [comment]
@mrpatiwi ve lo de los feedbacks

Manda a recorregir de cualquier manera.

Saludos !

**Comment by lopezjurip** [comment]
De dejé tu feedback en las Issues de tu repositorio privado.
https://github.com/IIC2233-2015-2/oatorresuc-repo/issues/1

Manda a recorregir y menciona lo que acabas de poner acá.
