### ISSUE TITLE
Lo que se puede ocupar

### ISSUE THREAD

**Issue by vclaro1** [IIC2233-2015-2/syllabus#143]
Hola, tenia unas dudas de que se puede ocupar. Sale que no se puede utilizar los for, listas, diccionarios, etc...  pero se puede usar string y while? 

Saludos

**Comment by gafigueroa** [comment]
Holas, si se puede usar for, solo que para poder utilizarlo la estructura de datos que crees debe ademas ser iterable.
Y si se pueden utilizar string y while.

**Comment by AntoniaMendoza** [comment]
y usar los diccionarios de las instancias de una clase? para ver si hay un atributo en la instancia? (Entiéndase algo como if "nombre" in instancia.**dict**)

**Comment by robocop6** [comment]
Python es lo suficientemente ordenado como para que no debas acceder directamente al `__dict__` de un objeto en este caso. Puedes usar los built-ins `getattr`/`hasattr`.

Saludos!
