### ISSUE TITLE
Notebook sala B23

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#144]
Nadie vio un notebook sony vaio en esta sala? estaba con una funda saxoline naranja :( por favro es el unico que tengo para hacer la tarea :(

**Comment by lopezjurip** [comment]
Ouh :( 
¿Preguntaste en los grupos de Facebook de Ingeniería?

**Comment by otro-felipe** [comment]
Si ya pregunté, estoy a la espera a que un alma caritativa se apiade de mi. Solo lo pude haber sacado para progra avanzada, en ningun otro momento lo saque de mi mochila :(

**Comment by aaossa** [comment]
Lo cierro porque ya lo encontraste :grin: :clap: :clap: #QueNoNosRobenLosNotebook
