### ISSUE TITLE
Qué retorna hacer_conexion()

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#145]
Una duda rápida al momento de generar la red de conexiones:

Cuando se llama hacer_conexion(), el "dato" que retorna es el nuevo puerto?

Gracias! :smile:

**Comment by gafigueroa** [comment]
Cuando se hace hacer_conexion(int) no retorna ningún dato (tal como dice el enunciado -> None), para saber en que puerto estas tendrías que preguntarlo.
