### ISSUE TITLE
Uso de *args

### ISSUE THREAD

**Issue by iqacevedo** [IIC2233-2015-2/syllabus#146]
Hola, 
Para la tarea 2 esta permitido usar *args ?. O se considera como usar listas?

**Comment by gafigueroa** [comment]
Si quieres usarlo, no hay problema, pero siempre y cuando no almacenes directamente la información del args, por ejemplo, `self.data = args`esta prohibido, porque args es una tupla, y recuerda que está prohibido el uso de tuplas, por lo tanto estarías yendo en contra de las restricciones del enunciado.
Pero si esta permitido si usas cada valor del args por separado, por ejemplo `for arg in args:`, y luego trabajas directamente con cada arg.

**Comment by iqacevedo** [comment]
Me quedo super claro, muchas gracias :)

**Comment by tamycova** [comment]
podria usar arg[0] por ejemplo?

**Comment by gafigueroa** [comment]
Si, lo importante es que no almacenes directamente args
