### ISSUE TITLE
Creacion de listas

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#147]
Me puedo basar en la ListaEnlazada que sale en el html Arboles para crear mi lista? o tiene que ser de una manera completamente nueva?

**Comment by fdoflorenzano** [comment]
Esa es la implementación clásica de una lista y eres libre de elegir. Según el contexto del problema, algunas implementaciones pueden ser más ventajosas (en términos de eficiencia), te recomiendo aprovechar esto para todas tus estructuras pero puedes usar la que quieras mientras la hagas tu ;)
