### ISSUE TITLE
Duda identificacion de conexiones

### ISSUE THREAD

**Issue by selira** [IIC2233-2015-2/syllabus#148]
en el enunciado en hacer_conexion(int), dice que "Los caminos estan enumerados
desde el 0 hasta cantidad de conexiones - 1". ¿Esta enumeración permite hacer una identificación de de las conexiones que hay desde un puerto? Me refiero a que si, por ejemplo, en un momento estoy en el puerto 5 y hago hacer_conexion(2), y mas adelante estoy de nuevo en el puerto 5 y hago hacer_conexion(2) nuevamente, se pasa a través de la misma conexión? Además, la cantidad de conexiones desde un puerto no varía en el tiempo, o sí?

**Comment by fdoflorenzano** [comment]
Las conexiones son fijas, no te preocupes. Si vuelves a un nodo, las conexiones son las mismas que la primera vez que ingresaste. Espero ayude!

**Comment by selira** [comment]
ok gracias!
