### ISSUE TITLE
Uso de listas por comprensión

### ISSUE THREAD

**Issue by rrhurtado** [IIC2233-2015-2/syllabus#151]
Cuando realizo la siguiente operación [ i.valor for i in MiLista_instancia ] logra reconocer a MiLista_instancia como lista. Mi duda es si es posible usarlo haciendo una conversión a MiLista al final o debería convertir el generador que entrega (i.valor for i in MiLista_instancia)

**Comment by robocop6** [comment]
Recuerda que uno de los objetivos de la tarea es programación funcional. Puedes revisar la AC07 en la cual se pedía hacer ciertas cosas sin usar comprensión de listas. Debieras poder conseguir el generador `(i.valor for i in MiLista_instancia)` sin usar comprensión, y luego puedes iterar sobre él.

Ahora bien, sobre si tienes que convertir el generador a un objeto clase MiLista, primero preocúpate si de verdad necesitas guardar esa información o solo debes iterar una vez. Si quieres guardarla, invoco a @gafigueroa para que responda si en este caso puedes valerte de las listas de Python.

**Comment by gafigueroa** [comment]
Como dijo @robocop6 , la idea es que uses programación funcional, en cambio si usas list comprehension, aunque luego hagas una conversión de esta lista, estarías utilizando listas y no es la idea de la tarea.

Pero para suerte tuya, la programación funcional tiene funciones que te pueden ayudar, por ejemplo si lo que tu quieres es obtener todos los valores de MiLista_instancia, puedes mapear estos valores 

``` python
map((lambda i: i.valor ), MiLista_instancia)
```

Pero recuerda que esta función te retorna un objeto de tipo map, que luego debes poder ser capaz de instanciar en tu lista.

**Comment by rrhurtado** [comment]
Buena, muchas gracias, ya pude instanciar en mi lista usando el iterable de map.
