### ISSUE TITLE
Problema osx el capitan y git

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#152]
actualice a la GM de el capitan y ahora al hacer git desde el terminal me dice esto:

➜  T02  git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by lopezjurip** [comment]
Instalaste las developer tools? Una manera es bajando y ejecutando XCode. Había otra manera a través de la terminal. 

Desconozco el estado actual de El Capitan.

**Comment by yackpott** [comment]
funciono!
