### ISSUE TITLE
Posibles conexiones nodo

### ISSUE THREAD

**Issue by sebamenabar** [IIC2233-2015-2/syllabus#153]
Hola, leyendo las preguntas anteriores hay varias cosas que todavía no me quedan claro.
Si estoy en un nodo A y pregunto la cantidad de conexiones y me dice por ejemplo 3.
Si la conexion 0 es normal y me lleva al nodo B, si vuelvo al nodo A y hago nuevamente la conexion 0 me lleva unicamente al nodo B?? Y así, la conexion numero "n" siempre será la misma para un nodo? O puede ser que la próxima vez que pase por el nodo A la conexion que me lleve a B ya no es la 0 sino la 1?
Lo otro, por lo que entendi podria ocurrir que de las 3 conexiones del nodo A, la 1 puede ser alternante y la 2 aleatoria?
Para el camino a bummer, considero todas las conexiones como normales? En el caso de que haya una aleatoria elijo la conexion entre nodos que mas me convenga? Lo mismo para las rutas de doble sentido y ciclos?
Y para la nueva red? Todo nodo debe tener una conexion con la red principal que va del puerto 0 a Bummer o solamente todo nodo de poder hacer una conexion aunque quede aislada de la red principal?

**Comment by alopez7** [comment]
1. Si una conexión es normal y pasas dos veces por ella, siempre te va a llevar al mismo nodo de destino.
2. Un mismo nodo puede tener los tres tipos de conexiones (incluso repetidos) y en cualquier orden.

**Comment by alopez7** [comment]
1. Puedes considerar conexiones random para la ruta más corta, pero hay que especificarlo en el readme
2. Todas los nodos de las redes tienen que ser conexos. No puede pasar que hayan nodos a los que no puedes acceder
