### ISSUE TITLE
Pregunta conexiones entre dos nodos

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#154]
Puede un nodo tener más de una conexión que lleve a otro nodo?

Por ejemplo, supongamos que A tiene 3 conexiones, una normal, una alternante y una aleatoria. Digamos que la conexión normal lleva al nodo B, ¿Puede ocurrir que la alternante lleve también al nodo B (y, obviamente a un tercer nodo C) y/o que B se encuentre dentro de los nodos a los cuales se puede llegar por medio de la conexión aleatoria?

**Comment by alopez7** [comment]
Si, incluso puede ser que todas las conexiones del nodo A te lleven al B. También puede pasar que una conexión te lleve al mismo nodo de origen.
