### ISSUE TITLE
len

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#155]
Hola, que es mas eficiente?
- tener un atributo que vaya guardando la longitud de la lista (+= 1 cada vez que agregue un elemento)
- definir una funcion len que recorra la lista contando los elementos

En términos de memoria/tiempo

Gracias

**Comment by fdoflorenzano** [comment]
Hola! El atributo por lo general. Piensa que al agregar un elemento solo es un paso extra cada vez pero calcular longitud en una lista muy grande demora el tamaño de la lista. Y obtener el atributo es directo.

**Comment by lopezjurip** [comment]
Yo suelo preferir que se calculen las cosas en vez de estar guardando valores redundantes (y que uno después tiene que andar preocupado de mantenerlos actualizados). 

Sin embargo, si estás buscando eficiencia (en _tiempo_), es mejor guardar el valor de la longitud que usa super poco espacio en memoria.

**Comment by tamycova** [comment]
Thanks!
