### ISSUE TITLE
Conexiones aleatorias y alternantes

### ISSUE THREAD

**Issue by ralvarez94** [IIC2233-2015-2/syllabus#156]
Se puede asumir que las conexiones aleatorias tienen como posible destino 3 o más nodos? Pregunto esto porque de lo contrario, no se podría distinguir entre una conexión alternante (que necesariamente es entre un par de nodos) y una conexión aleatoria que conecte al nodo con 2 posibles nodos.

**Comment by alopez7** [comment]
Se puede asumir que tienen como destino un grupo de nodos definido, pero no se puede asumir que son más de 3

**Comment by robocop6** [comment]
Sí puedes reconocer una conexión alternante de una aleatoria con 2 nodos de llegada, porque las conexiones alternantes **siempre cambian a la otra opción**. Es decir, si una conexión es alternante con nodo de origen A y nodos de destino B, C, y la última vez te mandó a B, entonces la próxima vez que vayas por esa conexión te enviará a C, la subsiguiente nuevamente a B y así sucesivamente.

Por otra parte, si la conexión fuese aleatoria, cada vez que uses la conexión, no sabes a qué nodo te enviará: B o C.

**Comment by ralvarez94** [comment]
Perfecto, con lo último me quedó clara la diferencia entre los alternantes y los aleatorios.  Gracias!
