### ISSUE TITLE
"desconectarme"  del nodo

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#157]
Es posible hacer una conexion, revisar el nodo, y devolverme inmediatamente al nodo del que venia? o es algo que tengo que descubrir yo? es que sinceramente no se me ocurre

**Comment by fgvenegas** [comment]
y lo otro, que pasa si quiero una recursion y python colpasa porque llega al limite de recursiones?

**Comment by alopez7** [comment]
Las conexiones no son bidireccionales, por lo que lo más probable es que volver al nodo anterior no sea fácil. 
Si tienes una recursión que colapsa puede ser porque no es muy eficiente o porque se queda atrapado en algo infinito.

**Comment by fgvenegas** [comment]
pero entonces es posible volver al nodo, sin la necesidad de que el robot me mande al principio?

**Comment by alopez7** [comment]
Si

**Comment by fgvenegas** [comment]
Cuanto deberia demorarse un codigo "eficiente" en encontrar el puerto de banner?

**Comment by cdonoso** [comment]
El mío lleva 5 minutos más o menos jajajaja pero no es eficiente, lo estoy arreglando para mejorarlo jajajaja

**Comment by fgvenegas** [comment]
Otra duda que me surgió, la red es "circular"? Es decir que todos los puertos están conectados con todos o hay puertos que al hacer conexión con ellos no pueda ir a ninguna parte ?

**Comment by mbucchi** [comment]
@fgvenegas, la red es fuertemente conexa. Esto quiere decir que desde todo nodo puedes llegar a todos los otros nodos. Saludos!
