### ISSUE TITLE
Uso de diccionarios Tarea 2

### ISSUE THREAD

**Issue by fdoflorenzano** [IIC2233-2015-2/syllabus#160]
Se ha preguntado mucho si la implementación de diccionarios es necesaria para la tarea 2. La implementación de estos es muy variada y más compleja que las estructuras convencionales como listas, arboles, etc... Y se escapan del alcance del curso. Es por esto que NO se tomará como necesario que los implementen en la corrección. Pero sigue la regla, si desean usarlos, DEBEN implementarlos ustedes mismos, pero se advierte su complejidad. Saludos y suerte!

**Comment by mbucchi** [comment]
Si lo encuentran muy necesario, existe una forma de simularlos mediante una modificación a las listas ligadas. Estos diccionarios serán mucho más ineficientes, sin embargo harán bien su pega. 
Saludos!
