### ISSUE TITLE
Capacidad de datos 

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#162]
Hola.
En la parte de capacidad de datos, la capacidad del puerto indica la cantidad de puertos que puede estar conectado antes de _caerse_ la conexión y devolver la información?
Por ej, si el puerto 0 tiene una capacidad de 8, significa que a la conexión del noveno puerto se cae y no retorna nada  (asumiendo que los puertos en el camino tienen capacidad mayor a 8)? Y en caso de ser así, existirá siempre al menos un camino que retorne la ruta desde el puerto 0 al final o puede ser que no haya camino posible?

**Comment by santiagocruzb** [comment]
#Tarea2

**Comment by mbucchi** [comment]
La capacidad de una conexión indica qué tan grande es el **paquete** de datos que puede pasar. Es decir cuantos datos aguanta simultáneamente. Si una conexión tiene capacidad 8, podrán pasar infinitos paquetes con peso menor o igual a 8. Lo único que causaría un problema con la conexión sería si llegara un paquete de datos con peso 9 o más. Esto implica que _siempre_ habrá caminos para llegar al puerto final, el punto es que distintos caminos podrían tener un límite más grande en el porte de los paquetes de datos.
Espero que esto te aclare el panorama. Saludos!

**Comment by tamycova** [comment]
Entonces, seria esta la solucion del problema? (ineficientemente hablando)
 Encontrar todos los caminos que llevan a bummer y la capacidad de cada camino seria la de su puerto con la capacidad mas pequeña, buscamos el camino cuya capacidad mas pequeña sea la mayor

**Comment by mbucchi** [comment]
Exacto @tamycova.

**Comment by tamycova** [comment]
Gracias @mbucchi !!
