### ISSUE TITLE
Memoria y Tiempo

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#163]
Al recorrer la red tenia pensado ir guardando los datos de las conexiones y puertos pero me di cuenta que si lo hago se hace muy lento el programa por la cantidad inmensa de conexiones que existen... ¿alguna recomendación al respecto? Porque si no guardo los datos de las conexiones después no tengo como analizar si eran Alternantes, Random o Normales...

**Comment by fdoflorenzano** [comment]
Recuerda que la idea de la primera parte es entregar las especificaciones de la red en su totalidad. Los puertos con sus id's y las conexiones entre puertos, por lo que es natural que haya que guardar la información de alguna forma. Intenta hacer el almacenamiento eficiente e inteligente, que no guarde más de una vez y repita el mínimo de veces el acceso a cada puerto. Saludos y suerte!
