### ISSUE TITLE
Errores de tipeo en pdf (funcion puerto_robot)

### ISSUE THREAD

**Issue by AntoniaMendoza** [IIC2233-2015-2/syllabus#164]
Hola, la función "pregunta_puerto_robot" no existe en sistema. Se llama "preguntar_puerto_robot", o al menos así es en mi caso. Me dijeron que, al parecer, hay otros errores de tipeo. Aviso para que editen el pdf. Saludos.

**Comment by lopezjurip** [comment]
Lo estamos viendo ahora mismo los ayudantes y pronto subiremos el enunciado corregido, gracias! :smile:

**Comment by fdoflorenzano** [comment]
Efectivamente. Los errores son: 
pregunta_puerto_robot() debería ser preguntar_puerto_robot()
no existe pregunta_nodo_actual, hacia referencia al metodo: preguntar_puerto_actual().

Eso es lo único que hemos detectado en cuanto a métodos. Gracias por avisar y estamos atentos a otros. Intentaremos subir una nueva versión lo antes posible.
