### ISSUE TITLE
arboles con mas de un padre

### ISSUE THREAD

**Issue by fjsalinas** [IIC2233-2015-2/syllabus#165]
hola! existe la opcion de arboles, que un elemento pueda tener mas de un padre.
Muchas Gracias

**Comment by aaossa** [comment]
Creo que eso sería mas parecido a un grafo:

![Arboles](http://www.stoimen.com/blog/wp-content/uploads/2012/08/1.-Graph-Tree.png)

Puedes hacer que tu estructura tenga la forma que quieras :grin: Aprovecha de usar tu creatividad y ver qué resuelve mejor tu problema. Si en tu caso necesitas que un elemento de tu árbol tenga más de un padre, entonces se llama grafo.

**PD:** Estoy asumiendo que esto es una pregunta, aunque no se si etiquetarla como materia o como parte de la tarea.
