### ISSUE TITLE
¿Está permitido usar tuplas para que una función retorne más de un valor?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#166]
Por ejemplo:

``` python
def f(a,b):
    return a+b, a-b  # Esto es una tupla

x = 10
y = 5
i, j = f(x,y)  # Ahora i tiene el valor 15 y j tiene el valor 5
```

**Comment by lopezjurip** [comment]
Yo diría que sí, es parte de las gracias de las funciones en python.

Esperemos la confirmación de un ayudante de tareas :+1:

**Comment by fdoflorenzano** [comment]
Sí, pero recuerda no utilizarlas de la forma de estructura de almacenamiento. Contestaron una duda parecida en la issue #146 . Saludos!
