### ISSUE TITLE
Numero del Paquete ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#168]
Puedo asumir que despues de varias pruebas si el puerto mas grande fue el 1000, existen puertos numerados solo entre 0 al 1000, es decir que haya mil puertos numerados 0,1,2,3.. 999? no se si se entiende

**Comment by fdoflorenzano** [comment]
Los ejemplos muestran que sí, así se arman los ids de los puertos. Ahora, por enunciado solo se identifican como ids y no se puede asumir para cualquier caso, como posibles pruebas que podríamos realizar en la corrección.
