### ISSUE TITLE
Conexiones alternantes

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#169]
Hola, resulta que por razones místicas sé cuales son las conexiones aleatorias y al compararlas con las que encuentra mi programa resulta que son bastante menos de las que en realidad deberían ser. Me puse a revisar y resulta que al entrar a una conexión que es supuestamente alternante me lleva hacia los siguientes puntos:

`[703, 703, 703, 703, 246, 703, 246, 703, 246, 246, 246, 703, 246, 703]`

yo no veo nada de alternante en esa secuencia, 
¿Están funcionando bien las conexiones alternantes?

**Comment by gafigueroa** [comment]
Hola, si el robot pasa por la conexión alternante, también se cambia la dirección de la conexión, puede ser que por eso cuando tu pasas no se vea tan alternante.

**Comment by otro-felipe** [comment]
Tenia la intuición de que él estaba detrás de todo esto. Muchas gracias!

**Comment by alopez7** [comment]
Las conexiones aleatorias no necesariamente tienen como destino muchos nodos, podría también ser una aleatoria con dos nodos de objetivo

**Comment by otro-felipe** [comment]
El problema es que se de buena fuente que no es aleatoria, solo no estaba considerando el movimiento del robot y la hacia parecer aleatoria. Gracias de todas formas

**Comment by AntoniaMendoza** [comment]
Hola, tengo la misma duda. A mi me dieron que eran todas aleatorias bajo el supuesto de que si paso por el robot ocurriría algo asi: 1,3,1,3,"r",3,1.
Está bien esa secuencia o debiese ser 1,3,1,3,"r",1,3 ?

**Comment by alopez7** [comment]
Supongo que te refieres a que el robot pasó por ese lugar. En ese caso, si la el nodo es alternado y el robot pasó, esa debería ser la secuencia correcta
