### ISSUE TITLE
Intermediate Python - Mini-libro opensource

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#17]
Este repositorio se hizo popular hace poco. Les puede servir como material complementario al que subimos aquí para esta primera parte del curso.

https://github.com/IntermediatePython/intermediatePython

**Comment by aaossa** [comment]
:heart_eyes: Un muy buen recurso :clap: :clap:

**Nota**: Al parecer parte del código está escrito en Python 2.7 (la versión final por ahora es Python2, ya que Python3 aun esta en desarrollo), lo que a grandes rasgos causas diferencias en que:
- Ahora `print` es una función
- Algunas importaciones de módulos cambian (esto en los módulos que vienen con Python)
