### ISSUE TITLE
Se pueden usar iteradores (generadores)?

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#173]
Hola. Hay algun problema en crear un iterador por comprension? Algo asi como

iterador = (str(num) for num in iterador_con_numeros if num % 2 == 0)

Pregunto porque tiene cierto "parecido" con utilizacion de lista?
Pretendo acceder a sus valores con next(iterador)

**Comment by alopez7** [comment]
No hay problema con que uses generadores (no confundir con listas por comprensión)
