### ISSUE TITLE
Conexiones alternantes y aleatorias

### ISSUE THREAD

**Issue by mathias-katscher** [IIC2233-2015-2/syllabus#174]
En la parte de reconocer la red, es necesario encontrar todas las conexiones alternantes y aleatorias o basta con recorrer todos los caminos una sola vez?

**Comment by alopez7** [comment]
Reconocer las conexiones alternadas y aleatorias es un extra (bonus). Digamos que pasaste por la conexión 1 del puerto 150 y es una conexión aleatoria que te lleva al 300, al 500, y al 600. Si te llevó al 300 y pusiste que es una conexión del 150 al 300, entonces está bien. Si reconoces que es aleatoria, entonces será bonus.

**Comment by mbucchi** [comment]
EDIT: No es necesario que reconozcan absolutamente todas las aleatorias/alternantes. Lo importante es que sepan distinguir si es que son normales o no. Sí confundes una aleatoria con una alternante, no habrá problemas.

**Comment by orrios** [comment]
y si por esas casualidades de la vida ponemos que es aleatoria y era alternante o vice-versa, hay descuento o el bonus solo suma ? :eyes:  

EDIT: porque al final no tendra efecto nocivo en los resultados

**Comment by mathias-katscher** [comment]
@alopez7 @mbucchi gracias por la aclaracion

**Comment by AntoniaMendoza** [comment]
Hola, una duda, las alternantes debieran ir siempre cambiando nodo no? así como 1,2,1,2,1,2,1,2,1,2? Yo asumí que era así, y resulta que me dieron que todas eran aleatorias (de la lista de 4000 conexiones, ninguna era alternante definida como tal) jajaja porque de las 300 veces que pasaba por cada conexión, muchas veces ocurría que mandaba al mismo nodo que el anterior. (algo como 1,1,2,1,2,1,2,2,1).. y para mi eso es aleatorio :/ (el robot si fue considerado para efectos de algoritmo jaja)

**Comment by aaossa** [comment]
@AntoniaMendoza Podría ser lo de #169 ?

**Comment by alopez7** [comment]
Recuerda que el robot también puede pasar por una ruta alternada y cambiar la dirección.
