### ISSUE TITLE
Parte III: El Hackeo

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#176]
En esta parte se nos pide arreglar la red eliminando los ciclos, ¿debemos eliminar todo ciclo o solo los triangulares y cuadrados encontrados antes? En el caso de tener que eliminar todo ciclo, ¿una ruta doble sentido se considera como un ciclo? ¿y una conexión bidireccional?  Gracias.

**Comment by alopez7** [comment]
La idea es elimina la mayor cantidad de ciclos posibles de manera de que se pueda llegar a todo nodo desde cualquier origen, pero tratando de minimizar la cantidad de conexiones eliminadas. En otras palabras, tienes que eliminar los ciclos que sobran (pueden tener cualquier tamaño)

**Comment by javierlopeza** [comment]
Pero por ejemplo si hay un puerto con 1 posible conexion, la cual es parte de un ciclo. Si yo elimino ese ciclo ese puerto queda incomunicado... ¿En ese caso no le hago nada a ese ciclo y lo dejo tal cual? ¿Los puertos originales se tienen que mantener?

**Comment by alopez7** [comment]
Todos los puertos tienen que estar conectados, por lo que ese ciclo no se tiene que eliminar

**Comment by javierlopeza** [comment]
Perfecto, gracias!

**Comment by javierlopeza** [comment]
Solo para aclarar, ¿se deben eliminar todos los ciclos, pero teniendo el cuidado de no dejar puertos incomunicados y manteniendo la condición de que desde cualquier nodo se pueda llegar a otro nodo?

**Comment by alopez7** [comment]
Si

**Comment by javierlopeza** [comment]
Pero para mantener la condición de que se pueda llegar de cualquier nodo a otro nodo hay muchos ciclos que se deben mantener intactos?

**Comment by alopez7** [comment]
Si, solo tienes que eliminar los ciclos que sobran. Esto de puede hacer de varias maneras, así que tienes que tratar de hacerlo eliminando la menor cantidad de conexiones.

**Comment by mathias-katscher** [comment]
@alopez7 me confundiste un poco con esa ultima aclaracion porque me parece un poco contradictorio. Si se tiene que eliminar la menor cantidad de conexiones entonces como se definiria un ciclo que sobra? Segun lo veo yo, deberia ser eliminar la mayor cantidad de conexiones sin desconectar nodos, o estamos hablando de lo mismo?

**Comment by alopez7** [comment]
Ignora lo que dije, me enredé solo. Tienes razón

**Comment by javierlopeza** [comment]
Perdón pero no me queda claro todavía. ¿Se debe mantener o no que de todo puerto se llegue a todo puerto? ¿O solamente importa que siempre se pueda llegar a Bummer?

**Comment by alopez7** [comment]
Debes mantener la condición fuertemente conexa de los nodos. Esto significa que debes poder llegar a cualquier nodo A a cualquier nodo B.
