### ISSUE TITLE
Retorno 4.2 Tarea 2

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#178]
El enunciado de la tarea en la parte 4.2 dice que "se deben especificar todos los puertos y conexiones encontradas", pero más arriba, al explicar la red, el enunciado dice: "Lo ideal es lograr que los paquetes de datos que envías lleguen al servidor final". Mi duda es: ¿Tengo que, de alguna forma, recorrer toda la red y luego detallar todos los puertos y conexiones de ella?, ¿O debo intentar llegar al puerto final y luego detallar todos los puertos y conexiones encontradas en el camino? De antemano gracias =)

**Comment by alopez7** [comment]
La parte 4.2 tiene como objetivo que recorran toda la red y sus conexiones y que retornen la lista completa de conexiones y nodos. Además de eso, se les pide hacer unas consultas de caminos a bummer, etc..., pero hay que partir recorriendo la red completa y a partir de eso se contestan las consultas.
