### ISSUE TITLE
Problema con guia actualizada

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#18]
Hola. Nunca logré instalar correctamente las librerías, así que intenté ahora siguiendo la nueva guía actualizada para windows, y cuando comienzan los pip installs me topé con el siguiente error: Justo en el paso anterior había que ingresar 

'''  [Environment]::SetEnvironmentVariable("Path", "$env:Path;C:\tools\python\Scripts\", "User")   '''

y no obtuve ninguna respuesta cuando lo hice (quizás por eso no funciona después).

![image](https://cloud.githubusercontent.com/assets/13739960/9345872/7aa43a14-45e3-11e5-88b1-7e7abd79514c.png)

**Comment by felix91gr** [comment]
Hola!

Dónde te quedaste en la guía anterior? Quizás la instalación de antes está
interfiriendo con la de ahora.

Saludos!

**Comment by aaossa** [comment]
Disculpa, ¿qué comando ingresaste antes del error? Gracias :+1:

**Comment by lopezjurip** [comment]
Prueba reiniciando la terminal e intenta el comando `pip` o `pip3`. Si no arroja error, estás bien :)
Puede que @felix91gr tenga razón

**Comment by aaossa** [comment]
Una pregunta, si corres Python y ejecutas el siguiente código:

``` python
import platform

print(platform.python_implementation())
```

¿Cuál es el output?

**Comment by raiperez** [comment]
@felix91gr He intentado instalar las librerias de tantas maneras distintas que eso es probablemente lo que pasa >.<

@aaossa  antes del error ejecuté pip install --upgrade simpy. 
Si corro ese código en python obtengo:  "CPython"

@mrpatiwi Cuando utilizo pip obtengo el error:

![image](https://cloud.githubusercontent.com/assets/13739960/9346777/042cf482-45ef-11e5-9872-d7497270ddab.png)

Aunque al parecer pip 3 funciona.

**Comment by aaossa** [comment]
Puedes ejecutar esto?

``` python
import sys

print(sys.version)
```

**Comment by raiperez** [comment]
3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]

**Comment by aaossa** [comment]
Ya mira, esto encontré que podría ser, pero no lo he probado porque al menos yo no he tenido ese problema. Encontré una pregunta en **StackOverflow** con tu mismo error. Python utiliza una expresión regular (o _RegEx_ por si quieres ver un poco de esto mas adelante) en el módulo [platform.py](https://github.com/python/cpython/blob/master/Lib/platform.py) (en la variable `_sys_version_parser`) para obtener información de tu sistema. El problema es que esa expresión no espera el caracter `|`, que se ve en la información del primer error. Basado en [**esta respuesta aceptada en StackOverflow**](http://stackoverflow.com/a/19105436/3281097), podrías ejecutar lo siguiente, en Python nuevamente:

``` python
import sys
# Si te fijas es lo mismo que sale en el error de la foto que nos mostraste
# Exceptuando lo que esta encerrado por el caracter '|'
sys.version = "3.4.3 (default, Mat  6 2015, 12:06:10) [MSPC v.1600 64 bit (AMD64)]" 
# Te sugiero revisar bien que sea el mismo 
platform.python_implementation()
```

y volver a probar. Si no lo soluciona, mejor vuelve a guardar en la variable el valor que acabas de decir que te salio.

**Comment by raiperez** [comment]
Me tiró error de que no pudo parsear, pero intenté nuevamente con pip3 install y logré instalar las librerías!! :+1: Ya no me arroja error al importar PyQt4. Muchas Gracias!!

Ahora cuando intento configurar sublime y instalar Anaconda con package control, recibo el error:

ERROR:root:Your operating system denied the spawn of C:\tools\python3\python.exe process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
error: Anaconda can not spawn a new process with your current configured python interpreter (C:\tools\python3\python.exe), make sure your interpreter is a valid binary and is in your PATH or use an absolute route to it, for example: C:\Python27\python.exe

**Comment by lopezjurip** [comment]
Opción 1:
El error lo dice todo, tienes que revisar si Python está instalado en esas rutas. Revisa eso y busca en internet cómo modificar tu variable de entorno `PATH`.

Opción 2:
No uses Sublime.

**Comment by raiperez** [comment]
Ahí logré solucionar todo! Muchas gracias!!

**Comment by felix91gr** [comment]
Al final cómo lo hiciste? Modificaste el PATH? :)

**Comment by raiperez** [comment]
Sii! El problema era que en mi computador la carpeta python34 se encontraba directamente dentro del disco C, no dentro de una carpeta tools. :+1:
