### ISSUE TITLE
Pauta Evaluación

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#183]
En el caso de que nuestra forma de recorrer la red (encontrar todo puerto y conexión) sea poco eficiente y lenta, pero las demás partes de la tarea funcionan a la perfección con una red ya cargada... ¿Hay algo así como error de arrastre o se evalúan las partes por separado? Pregunto para saber a qué dedicarle más tiempo (y porque no hay pauta de evaluación de la tarea todavía :grin:).

**Comment by alopez7** [comment]
En general se evalúan las partes por separado, por lo que una cosa no debería afectar a la otra. Pero evidentemente es mejor que hagas más eficiente la función para que todo funcione bien.
