### ISSUE TITLE
Eficiencia y conocimiento de la red.

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#184]
1) ¿Dentro de qué rango de tiempo debe tardarse mi programa en reconocer la red para que se considere 'eficiente'?

2) ¿Es necesario encontrar absolutamente todos los nodos y conexiones?

**Comment by alopez7** [comment]
No hay un tiempo específico para determinar si es eficiente o no el programa. Se determina que un programa es eficiente por el modo en que se hace, ya que podría haber un programa muy eficiente pero que se demora mucho por la dificultad del problema.
Si es necesario encontrar todos los nodos y conexiones normales. Si no determinas todas las conexiones random y alternadas, no importa, mientras encuentres la conexión.

**Comment by jgmontoya** [comment]
Pero entonces dada una conexión aleatoria, ¿debo (hasta algún nivel de probabilidad) lograr identificar todos los nodos a los que llega? 

Pienso que es así porque entonces nada ma garantizaría que si hay algún nodo que se me pase de esa conexión que estoy siendo capaz de llegar al nodo por algún otro lado. Es decir, quizás un nodo solo tiene una conexión aleatoria como forma de llegar a él...

**Comment by Arios16** [comment]
No es necesario determinar todos los nodos a los que te podria dirigir una
conexion alternante o aleatoria? Osea, si yo paso solo una vez por una
aleatoria con 3 destinos, y la registro como si tuviera un solo destino,
eso esta bien?

El 14 de septiembre de 2015, 23:12, alopez7 notifications@github.com
escribió:

> No hay un tiempo específico para determinar si es eficiente o no el
> programa. Se determina que un programa es eficiente por el modo en que se
> hace, ya que podría haber un programa muy eficiente pero que se demora
> mucho por la dificultad del problema.
> Si es necesario encontrar todos los nodos y conexiones normales. Si no
> determinas todas las conexiones random y alternadas, no importa, mientras
> encuentres la conexión.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IIC2233-2015-2/syllabus/issues/184#issuecomment-140255828
> .

## 

Andres Rios.

**Comment by alopez7** [comment]
Se puede llegar a todos los nodos si utilizar conexiones random  o aleatorias, por lo que ese problema no es posible. 
Si en el txt dice que la conexión 1 del nodo 3 va al nodo 5, pero en realidad es uno de los posibles destinos, entonces está bien. Si descubres las conexiones random y las alternadas mejor.

**Comment by jgmontoya** [comment]
Es decir que la red es fuertemente conexa aun considerando sólamente las conexiones normales?

**Comment by alopez7** [comment]
Si
