### ISSUE TITLE
4.2

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#185]
En la parte de retornar las conexiones, si yo descubro que 0 tiene 3 conexiones, una normal con 220, una alternate con 1 y 15 y una aleatoria con 1123, 14,55 como deberia ir eso en mi .txt?

**Comment by alopez7** [comment]
CONEXION 0 220
CONEXION 0 1 ALT
CONEXION 0 15 ALT
CONEXION 0 1123 RAND
CONEXION 0 14 RAND
CONEXION 0 55 RAND

**Comment by fgvenegas** [comment]
Gracias :smile:

**Comment by raiperez** [comment]
@alopez7 Es estrictamente necesario entregar las conexiones con ese formato?
Seria incorrecto entregarlos de la siguiente manera?

Puerto ID138
Conexion 0 de puerto 138. Hacia [748, 319, 117], RAND
Conexion 1 de puerto 138. Hacia [782], 
Conexion 2 de puerto 138. Hacia [981], 
Conexion 3 de puerto 138. Hacia [589],

**Comment by alopez7** [comment]
Tiene que ser en el formato dado por el enunciado, de otra manera podría haber descuento.

**Comment by raiperez** [comment]
Perfecto, gracias!

**Comment by santiagocruzb** [comment]
pero @alopez7, si paso 100 veces por el puerto 0 y varias veces elige el camino random, tengo que anotar todas las direcciones? y por lo mismo, entre mas veces pase por el camino random, es más posible encontrar un camino más corto al puerto final?

**Comment by alopez7** [comment]
Podría ser que encuentres un camino más corto a través del random, o de un camino alternado, pero no es necesario considerar este tipo de caminos en la consulta del camino más corto. Si lo quieres considerar tienes que especificarlo en el readme

**Comment by raiperez** [comment]
@alopez7 y deben estar ordenados los puertos de manera creciente? 
PUERTO 1
CONEXION 0 220
CONEXION 0 1 ALT
CONEXION 0 15 ALT
CONEXION 0 1123 RAND
CONEXION 0 14 RAND
CONEXION 0 55 RAND
PUERTO 2
.
.
.

**Comment by alopez7** [comment]
No es necesario
