### ISSUE TITLE
pycharm licenses

### ISSUE THREAD

**Issue by fjsalinas** [IIC2233-2015-2/syllabus#187]
hola, se me acabaron los dias de pycharm, y no se como obtener un licencia. Como puedo hacerlo??

Muchas Gracias

**Comment by cpieringer** [comment]
PyCharm Community Edition es free y open-source. No necesitas licencia.

https://www.jetbrains.com/pycharm/download/download_thanks.jsp?edition=comm&os=win&options=undefined

**Comment by jgmontoya** [comment]
Con el mail UC puedes pedir una licencia profesional: https://www.jetbrains.com/student/
