### ISSUE TITLE
Sobre las conexiones entre puertos

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#188]
Hola! ¿Puede pasar que una conexión que parte en un puerto llegue al mismo puerto, o incluso que eso pase más de una vez en cada puerto (es decir que hayan varias conexiones del puerto haciendo lo mismo)? Gracias de antemano.
Saludos

**Comment by rrhurtado** [comment]
Tengo la misma duda, hay veces en que me aparece que de 3 conexiones por ejemplo que tiene un puerto X, todas llevan al mismo puerto Y (al asumirlas normales y hacer_conexion() solo una vez para 0, 1 y 2)

**Comment by alopez7** [comment]
Si es posible
