### ISSUE TITLE
5.3 rutamaxima

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#189]
si paso por un alternante o aleatorio tengo que crear una ruta alternativas verdad, pero que pasa si paso por 10 alternantes por ejemplo, tendria que crear una ruta alternativa por cada una? y ademas que pasa si por una ruta alternativa paso por otro alternante, tendria que crear una ruta alternativa de la alternativa?

**Comment by alopez7** [comment]
No es necesario incluir rutas alternantes o randoms a las rutas de las consultas. Si lo haces, especifícalo en el readme y explica porqué lo hiciste de esa manera. 
ME CONFUNDÍ, LEER LO QUE DICE MÁS ABAJO.

**Comment by yackpott** [comment]
osea con solo poner la rutamaxima sin poner una ruta alternativa en caso de pasar por una conexion alternante, ya tengo todo el puntaje?

**Comment by alopez7** [comment]
Si explicas que lo hiciste así, deberías tener todo el puntaje

**Comment by ironcadiz** [comment]
Pero en el enunciado dice: 
"La consulta anterior puede considerar puertos alternantes y aleatorios. De ser así usted ademas debe detallar las rutas alternativas a seguir en en el caso de que al conectar aquellos puertos uno termine fuera de la ruta planteada. Separe la ruta principal de las alternativas con una linea con guion."

Osea estaría mal el enunciado y no me tengo que preocupar de eso??

**Comment by alopez7** [comment]
Perdón, olvidé esa parte del enunciado. Digamos que la ruta máxima pasa por un puerto con una conexión alternada o random. En este caso debes considerar todas las rutas posibles a las que te podría dirigir.  Si pasas por varias rutas con caminos random o alternados, la cantidad de rutas aumentará y tienes que considerar todas las posibles rutas que se originen.

**Comment by SHGoldfarb** [comment]
Pero si mal no recuerdo, antes habian dicho que identificar los puertos random o alternantes no es obligatorio. Entonces podria decir que me conviene no identificarlos para ahorrarme el trabajo de hacer las rutas alternativas?

**Comment by fdoflorenzano** [comment]
Si quieres hacer el trabajo mínimo.
