### ISSUE TITLE
Error al instalar PyQt4 en Mac OS X

### ISSUE THREAD

**Issue by panchopp** [IIC2233-2015-2/syllabus#19]
![captura de pantalla 2015-08-18 a las 23 26 50](https://cloud.githubusercontent.com/assets/13740634/9347650/e64d3080-4602-11e5-83cd-f0278d33e9f5.png)
Me arroja ese error. Por alguna razón, aunque le pongo la parte de que lo instale con python 3, igual al probarlo en python 3 no funciona, pero en python 2 si.

**Comment by lopezjurip** [comment]
Prueba `brew info pyqt`, debería salirte algo parecido a lo que tengo yo:
![image](https://cloud.githubusercontent.com/assets/7570744/9355799/92ceb8d4-4652-11e5-9e7a-fb0f58c2f523.png)

Quizás no se _linkeó_, prueba `brew link pyqt`.

Ejecuta `brew doctor` y revisa si te salen problemas relacionados con python.

**Comment by panchopp** [comment]
esta todo igual:
![captura de pantalla 2015-08-19 a las 9 29 58](https://cloud.githubusercontent.com/assets/13740634/9356145/07f5111a-4655-11e5-9348-d56325a1ff8f.png)

**Comment by ralvarez94** [comment]
Hola, seguí los pasos de la guía actualizada y Python sigue sin reconocer PyQt4.  Intenté instalándolo de nuevo y no pasa nada.  Los pantallazos que pusieron antes en este issue representan exactamente lo que aparece en mi computador.  Ayuda!

**Comment by eduguerra-uc** [comment]
+1 tengo el mismo problema

**Comment by lopezjurip** [comment]
1. Qué Sistema operativo usan
2. Cómo instalaron Python ¿de internet o con un administrador de paquetes?.
   1. Hagan `which python3 && which python` y pongan aquí qué les muestra.

Es difícil ayudar si no tenemos pistas.
Y por favor, lean los mensajes que les dice la terminal y búsquenlos en internet.

**Comment by eduguerra-uc** [comment]
1. OSX Yosemite 10.10.3
2. Lo tenía instalado de internet desde antes, pero borré esa versión y después lo instalé con brew (brew install python3)

```
which python3 && which python

/usr/local/bin/python3
/usr/bin/python
```

Gracias!

**Comment by eduguerra-uc** [comment]
El error actual que tengo al correr `brew install pyqt --with-python3` es:

```
Traceback (most recent call last):
  File "configure.py", line 27, in <module>
    import sipconfig
ImportError: No module named 'sipconfig'
```

Lo otro es que al hacer `brew install python3`se instaló python 3.5

**Comment by lopezjurip** [comment]
En #7 , aquí: https://github.com/IIC2233-2015-2/syllabus/issues/7#issuecomment-148919406

**Comment by eduguerra-uc** [comment]
```
$ brew uninstall pyqt4

Error: No such keg: /usr/local/Cellar/pyqt4

$ brew uninstall python3

Uninstalling /usr/local/Cellar/python3/3.5.0... (7612 files, 122M)

$ curl -o /usr/local/Library/Formula/python34.rb https://raw.githubusercontent.com/Homebrew/homebrew/7d8b04c417d16f320680c58d0eb335cafd881849/Library/Formula/python3.rb

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15772  100 15772    0     0  11049      0  0:00:01  0:00:01 --:--:-- 11052

$ brew install --debug python34.rb

/usr/local/Library/brew.rb (Formulary::FromPathLoader): loading /Users/Eduardo/python34.rb
Error: No available formula for python34 
==> Searching formulae...
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/python34.rb
python34
==> Searching taps...

$  python3 --version

-bash: python3: command not found

```

**Comment by mrpatiwi** [comment]
seguiste toodas las instrucciones?
En particular esta:
```sh
$ curl -o /usr/local/Library/Formula/python34.rb https://raw.githubusercontent.com/Homebrew/homebrew/7d8b04c417d16f320680c58d0eb335cafd881849/Library/Formula/python3.rb

```

**Comment by eduguerra** [comment]
Si, arriba puse el output

**Comment by eduguerra-uc** [comment]
Hay alguna forma de borrar todo lo que había de Python en el computador y volver a empezar desde 0?

**Comment by ralvarez94** [comment]
Yo tambien tengo OS X El Capitan.  Hice lo que habían puesto en el issue referenciado (eliminé el python bajado desde internet) pero cuando ejecuto brew install --debug python34.rb, me tira el siguiente, error:
<img width="883" alt="screen shot 2015-10-19 at 1 32 45 pm" src="https://cloud.githubusercontent.com/assets/8507322/10583983/4721829c-7666-11e5-99ab-427cbf7c945e.png">
¿Qué puede estar pasando?

**Comment by lopezjurip** [comment]
@ralvarez94, es porque el archivo `python34.rb` está en otra parte. Haz lo siguiente:

``` sh
$ curl -o /Users/Raimundo/python34.rb https://raw.githubusercontent.com/Homebrew/homebrew/7d8b04c417d16f320680c58d0eb335cafd881849/Library/Formula/python3.rb
```

**Comment by lopezjurip** [comment]
Olviden todo, solo tienen que actualizar las fórmulas de Homebrew:

``` sh
$ brew update
$ brew upgrade
$ brew install python3  # si lo habian borrado
$ brew install pyqt
```

**Comment by ralvarez94** [comment]
Me sigue sin reconocer PyQt4, lo descarga sin problemas pero no lo puedo abrir desde python.  (Y de hecho, ahora tampoco me deja descargar matplotlib).

**Comment by flobarrios** [comment]
hola !! si te sirve yo tengo el capitán y esto fue lo único que me resulto:

http://www.noktec.be/python/how-to-install-pyqt4-on-osx
