### ISSUE TITLE
Formato Rutas Doble Sentido

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#191]
En el enunciado dice que si tengo las rutas A<-->B y B<-->C solo debo poner A<-->B<-->C en el txt. ¿Pero que pasa si tengo las rutas A<-->B , B<-->C , B<-->D? ¿Escribo  A<-->B<-->C y A<-->B<-->D, o  A<-->B<-->C y B<-->D, o como?

**Comment by alopez7** [comment]
Escribes A<-->B<-->C y A<-->B<-->D, ya que son rutas distintas

**Comment by Arios16** [comment]
Ok, gracias!
