### ISSUE TITLE
Tarea2: Pregunta sobre los ciclos

### ISSUE THREAD

**Issue by SHGoldfarb** [IIC2233-2015-2/syllabus#192]
Hola, en la tarea 2 puede ocurrir que si un puerto tiene una conexion a si mismo entonces al buscar los ciclos triples encontrare A->A->A, o tambien A->A->B. De manera similar, en los ciclos cuadrados encuentro conexiones dobles y sucede A->B->A->B.

Que pasa si los incluyo en mi ciclos.txt? o hay que omitirlos?

**Comment by alopez7** [comment]
Debes omitir estos casos

**Comment by SHGoldfarb** [comment]
ok, gracias!
