### ISSUE TITLE
Problema raise StopIteration

### ISSUE THREAD

**Issue by spiza** [IIC2233-2015-2/syllabus#193]
Hola! Resulta que para poder recorrer mi lista Utilizo esto, y cada cierto tiempo (Cuando recorro la red muchísimas veces) me arroja un error, y me dice que salí del loop por culpa del raise.. y la verdad no puedo entender por que rayos pasa eso (he printeado antes de entrar al raise, y no hay dramas, muchas veces aplico el raise StopIteration, pero solo algunas veces el programa caga)

Porfavor help!

**Comment by alopez7** [comment]
Ese problema se puede deber a muchas cosas, te recomiendo ir a la ayudantía o a las salas de ayuda que se hacen en la semana.

**Comment by spiza** [comment]
Perfect, feliz iría, pero no hay ayudantía ni sala de ayudas hasta después de la entrega..

Enviado desde mi iPhone
