### ISSUE TITLE
Borrar ciclos

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#194]
¿Al borrar los ciclos debemos considerar todos los ciclos de cualquier largo que puedan haber? De tener que considerar todos los ciclos, ¿podemos usar algoritmos conocidos para encontrar todos los ciclos?. De no poder usarlos, ¿influirá mucho la eficiencia del método para encontrarlos?

**Comment by fdoflorenzano** [comment]
Hola! Perdón la demora, y si se refiere a cualquier ciclo. Puedes referenciar a algún algortimo, no esperamos que reinventes la rueda. De todas formas depende de tu modelación si el algoritmo que utilizas es eficiente, incluso podrías alterarlo por el contexto del problema. Readme! Saludos
