### ISSUE TITLE
Duda sobre el robot y posibles_conexiones()

### ISSUE THREAD

**Issue by ouhenio** [IIC2233-2015-2/syllabus#195]
¿Si el robot llega a encontrarme, el sistema entero se resetea? Es decir, ¿toda la red de servidores cambia su estructura?

Sobre posibles_conexiones: si, por ejemplo, en el servidor X posibles_conexiones me entrega 4, la próxima vez que pase por X posibles_conexiones seguirá siendo 4 o este valor varía?

**Comment by otro-felipe** [comment]
Para tu primera pregunta: #129, la segunda yo en base a mi experiencia propia hasta ahora te diría que ese valor no varía.

**Comment by alopez7** [comment]
Si el robot te encuentra, solo vuelves al inicio. El mapa sigue igual

La cantidad de conexiones de un servidor seguirá siendo la misma para siempre, y la conexión número n del servidor X seguirá siendo la misma (No se desordenan las conexiones de un mismo servidor)

**Comment by ouhenio** [comment]
Gracias :)
