### ISSUE TITLE
Como volver al estado normal de git

### ISSUE THREAD

**Issue by ouhenio** [IIC2233-2015-2/syllabus#197]
Estaba buscando una version antigua de mi programa  por lo que use git log y git checkout para llegar a dicho commit. Mi problema es que ahora no se como volver a lo que sería el presente de mi git :(

**Comment by lopezjurip** [comment]
Espero que hayas guardado los cambios antes de volver a una version vieja. 

¿Qué comandos usaste?

Debería ser como

``` sh
git checkout master
```

Asumiendo que estabas trabajando en la _branch_ `master` (la branch por defecto).

**Comment by ouhenio** [comment]
Gracias! Si, menos mal lo guardé.
