### ISSUE TITLE
5.3. Capacidad de Datos - DUDA

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#198]
En el enunciado indican que si la conexión tomada en cada viaje de puerto a puerto llega a ser de tipo aleatoria o alternante, tendremos que agregar al documento de texto las rutas alternativas en caso de que no hayamos llegado al puerto que esperábamos llegar. ¿La nueva ruta debe ser desde el punto en el que quedamos después de tomar la conexión engañosa?

**Comment by fdoflorenzano** [comment]
Claro. Te deja en un puerto fuera del camino y a partir de ahí avanzar.

**Comment by btkramm** [comment]
Pero digamos que hago:

1 -> 2 -> 3 -conexión aleatoria> 4

y dicha conexión aleatoria que esperaba me dejase en 4, me deja en 88. El output tiene que ser:

1 2
2 3
3 4
SEPARACIÓN
3 88

o

1 2
2 3
3 4
SEPARACIÓN
1 2
2 3
3 88

¿?
