### ISSUE TITLE
Pregunta sobre If, and, or

### ISSUE THREAD

**Issue by SHGoldfarb** [IIC2233-2015-2/syllabus#199]
Si yo tengo en mi programa lo siguiente:

```
f1 = funcion que demora bastante en retornar
f2 = otra funcion que demora bastante
if f1() and f2():
    Mas codigo...
```

Python evalua ambas funciones o basta que f1() retorne False para que no entre al If? Seria mas eficiente, en terminos de tiempo, poner

```
If f1():
    If f2():
        ....
```

?

Lo mismo para el 

```
If f1() or f2():
```

Basta que la primera retorne True?

**Comment by felipehv** [comment]
Si

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

**Comment by rjherrera** [comment]
En ambos casos evita hacer trabajo extra y evalua de derecha a izquierda, terminando lo antes posible, así que sería igual de eficiente (y más ordenado), aquí se ve más claro:

![and-or-python](https://cloud.githubusercontent.com/assets/11674283/9955584/7df54f94-5dc8-11e5-9824-93bdf606e3d6.png)

**Comment by SHGoldfarb** [comment]
Ok gracias!
