### ISSUE TITLE
Problema al instalar/usar git con chocolatey siguiendo la guía del set up

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2015-2/syllabus#2]
Siguiendo las instrucciones de la guía de set up, me aparece un problema con git, luego de instalarlo(si es que se instala bien) al usar powershell:
Adjunto una imagen con el problema.

![git](https://cloud.githubusercontent.com/assets/13739046/9213998/fe6f083a-406e-11e5-9304-50d9675ab481.jpg)

después de cerrar y abrir nuevamente powershell, nada cambia

**Comment by lopezjurip** [comment]
Prueba reiniciando la Powershell (recuerda el modo administrador)

**Comment by jpdattas** [comment]
sigue pasando lo mismo

**Comment by lopezjurip** [comment]
Prueba: 
`choco install git.install -yfd`

> Fuente: https://stackoverflow.com/questions/25129232/chocolatey-git-installs-but-is-not-on-the-path

**Comment by mrpatiwi** [comment]
También puedes probar con:
```sh
choco install poshgit -y
```

**Comment by jpdattas** [comment]
ahi si funciono, muchas gracias! cual era el problema?

**Comment by jpdattas** [comment]
funcionó con 

`choco install git.install -yfd`

**Comment by lopezjurip** [comment]
Una cosa es instalar un programa. Eso hacemos siempre, pero para usarlo así tal y como viene deberíamos escribir a cada rato:

``` sh
echo "Estoy inventando"
C:\Archivos y Programas\git1.5\git.exe config --global etc etc
```

Lo que se hace es añadirlo a la **variable de entorno** `PATH` para poder usarlo simplemente como `git`. Actualmente el paquete de `git` de Chocolatey no está funcionando bien :cry:

**Comment by jpdattas** [comment]
ok, muchas gracias!
