### ISSUE TITLE
Error al instalar Atom en Windows

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2015-2/syllabus#20]
Estoy siguiendo los pasos de la guia para la instalacion, ya instale atom pero la terminal no reconoce los comandos atom y apm (ya la reinicie) por lo que no puedo continuar con la guia.

**Comment by lopezjurip** [comment]
Qué sistema operativo?
Puedes usar otra IDE de todas formas: Sublime o PyCharm

Trata ejecutando al menos una vez Atom, y en algún menú creo que sale la opción `Install Shell commands`. Igual puedes instalar los paquetes de Atom por medio del mismo programa sin usar el `apm install...`

**Comment by caackermann** [comment]
Mi sistema operativo es Windows 10. Me gusta mas Atom por su simplicidad, de todas maneras ya tengo Pycharm.. Buscando en internet encontre que esa opcion solo existe para OSX, pero que los de Windows no deberian tener problema porque chocolatey deberia agregar los comandos, lo cual no paso. De todas maneras, ya instale todos los paquetes desde atom.

**Comment by ChristianCarruego** [comment]
Perdón que me meta, a mi me ha pasado algo similar y no se como solucionarlo.
He instalado el atom, y no me permite descargar los paquetes, paso a mostar el error: **Searching for "nombre del paquete" failed.Show output... no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable. El sistema no puede encontrar la ruta especificada**. Y no se como cambiar dicha ruta Muchas gracias de antemano. Saludos

**Comment by lopezjurip** [comment]
Revisa cómo cambiar las 'variables de entorno'

**Comment by baaz3050** [comment]
Que se necesita poner en las variables de entorno, he intentado dar solución a este problema, intente cambiar de versión, tratar de instalar paquetes de manera manual pero sigo sin tener solución, si me puedes apoyar con lo que se necesita colocar en las variables de entorno te lo agradecería mucho amigo :D
