### ISSUE TITLE
Recolectada T02

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#200]
Para que estén tranquilos, aquí está la lista de las personas que entregaron la T02.

Vamos a cerrar las [issues relacionadas con la tarea](https://github.com/IIC2233-2015-2/syllabus/issues?utf8=%E2%9C%93&q=label%3A%22Tarea+2%22) para mantener lo más limpio posible el syllabus.

Que tengan un buen dieciocho :)

```
Agrios1636
AlainLotissier
AlfonsoIgnacioV
AntoniaMendoza
ChrisAMS
Fernando17
GabrielGarib
GutoAR
KatherineGuerrero
MainScientist
ManuelBeckerT
Mnfriedl
Nebula2028
Niotac
PaulaSanzana
PipeQ
Pochoclo
Rodancoci
RodrigoBocazG
Sitoro
Togose
Treisenegger
Vanana
Vince-Valence
Yackpott
Zepk
ajgutierrezr
amroizman
andresespinosapc
andresfdezc
augustoas
benjavides
btkramm
cdonoso
cfvilla
clagos4
cotehidalgov
crabarca
crxzadytho22
ctalvarez
diegostrobl
diflores
djnoguera
djpassi
dndelavega
eduguerra
eiherrera
estebanmino
fagomez2
fcgfaura
fekunze
felipehv
fgvenegas
fimuniz
fjsalinas
flmartinez
flobarrios
fomorales
fvr1
fwzapata
gdburky
ggfresard
glbello
haroldmuller
icrocco
icussen
ignaciourzuaf
iqacevedo
ironcadiz
ivanwolf15
jatrincado
javierlopeza
jecastro2
jelsaca
jfcampos1
jgmontoya
jlires
jnburgos
jnrosenbluth
jpdattas
jpjofre94
kmreyes
mafillol
malvo1
marizurita
mathias-katscher
mdelaf
menavarrete
nateare
navasquez
orrios
pahaeussler
panchopp
pcerdam
raalliende
raiperez
ralvarez94
rjherrera
rrfoster
rrhurtado
rtacuna
santiagocruzb
sebamenabar
sebawarrior
selira
shgoldfarb
silvamatias
spiza
tamycova
thomasfmunozs
tommyefr
tomvillage
twallacech95
vicentemartintarud
vjfuenzalida
vjmoreno

# Total: 116
```

**Comment by AntoniaMendoza** [comment]
¿Se puede aún editar el readme?

**Comment by lopezjurip** [comment]
Haría que consultarlo con los @IIC2233-2015-2/ayudantes-tareos, al fin y al cabo ellos corrigen las tareas.

¿@mbucchi, @bamavrakis?

**Comment by caackermann** [comment]
Yo entregue la tarea dentro del plazo establecido y no aparesco en la
lista. Esta en mi repositorio y se puede ver la fecha en que fue entregada.

**Comment by lopezjurip** [comment]
@caackermann según veo en tu repo, no seguiste la convención de tener tu solución de la tarea en `Tareas/T02`.

**Comment by jtagle2** [comment]
@mrpatiwi, yo tambien la entregué, pero se me olvidó nombrar la carpeta como T02 (no me había fijado en eso, me pasó lo mismo en la tarea 1 parece D: ). Es posible mandar la tarea todavia? La subí en el plazo

**Comment by lopezjurip** [comment]
@jtagle2 se está conversando, no se preocupen, será revisada pero quizás bajo alguna penalización

**Comment by paxcema** [comment]
Al final, ¿se puede editar el README o no?
