### ISSUE TITLE
classmethod

### ISSUE THREAD

**Issue by sebawarrior** [IIC2233-2015-2/syllabus#201]
Hola, una pregunta, es posible que una clase herede de un objeto? es que buscando información en la página de python, específicamente en la función classmethod(function), aparece como ejemplo una clase que hereda de un objeto, y luego al decorar con classmethod una función, ésta recibe como primer argumento cls en vez de self ¿Por qué ocurre esto?
Muchas gracias y que pasen todos un feliz 18 junto a sus familias y/o amigos!

**Comment by lopezjurip** [comment]
Creo que estás confundiendo algunas cosas.
Un objeto (algo concreto) es una instancia de una clase (algo abstracto). No es posible heredar de objetos (al menos en Python y en la OOP en general). 

Cuando declaramos un método común y corriente es un **método de instancia**. Por esta razón estos métodos se aplican sobre `self`, que es la instancia. 

``` python
class Clase:
    def metodo(self, arg):
        pass

c = Clase()
c.metodo("argumento")
```

El `@classmethod` sirve para declarar un **método de clase**. Este aplica sobre la clase, que es el primer argumento `cls`.

``` python
class Clase
    @classmethod
    def metodo2(cls, arg):
        pass

Clase.metodo2("argumento")
```

El `@staticmethod` sirve para declarar un **método estático**. Este aplica sobre la clase, sin embargo esta no pasa como parámetro.

``` python
class Clase:
   @staticmethod
    def metodo3(arg):
        pass

Clase.metodo3("argumento")
```

La diferencia del `classmethod` vs `staticmethod` es que el método de clase pasa a sus subclases. En cambio el estático es solo de esa clase y no para sus decendientes.

No todos los lenguajes hacen diferencia entre estos dos últimos. En mi opinión es una feature que da claridad y permite mucha flexibilidad.

**Comment by sebawarrior** [comment]
Ahhh perfecto muchas gracias!! bacán la explicación!! pero una última duda, entonces para qué sirve en la práctica darle un método a la clase si al fin y al cabo esta la debo instanciar para ejecutar métodos, osea, en resumen, porqué darle métodos a las clases también si lo que voy a instanciar son los objetos... muchas gracias!

**Comment by lopezjurip** [comment]
No tienes que instanciar objetos para usar métodos estáticos o de clase. 

Por ejemplo en algunos lenguajes para elevar un número cierta potencia se usa la clase Math con su método estático `pow(a ,b)`.

Entonces puedes hacer esto:

``` js
// Ejemplo en Javascript
var resultado = Math.pow(2, 3)
// resultado es 8
```

No tendría sentido hacer:

``` js
// Ejemplo sin sentido en Javascript
var math = new Math()
var resultado = math.pow(2, 3)
```

Un ejemplo práctico:

``` python
from enum import Enum


class Tamano(Enum):  # Una enumeracion es simplemente ponerle nombre a numeros
    normal = 1
    familiar = 2
    xl = 3


class Pizza:
    def __init__(self, precio, tamano, ingredientes):
        self.precio = precio
        self.tamano = tamano
        self.ingredientes = ingredientes

    @classmethod
    def napolitana(cls, tamano):
        precio_napolitana = 8990 * tamano
        ingredientes = ['Queso', 'Oregano', 'Tomate']
        # Instanciamos 'cls' que es la clase Pizza
        return cls(precio_napolitana, tamano, ingredientes)


if __name__ == '__main__':
    # Puedo crear pizzas 'a mano':
    hawaiana = Pizza(9990, Tamano.normal, ['Tomate', 'Jamon', 'Pina'])

    # Creamos una pizza con nuestro metodo de clase
    napolitana = Pizza.napolitana(Tamano.familiar)

```

**Comment by sebawarrior** [comment]
okaa muchas gracias!!
