### ISSUE TITLE
¿Contenidos I1?

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#202]

**Comment by lopezjurip** [comment]
Agregados en #203

**Comment by javierlopeza** [comment]
Gracias! ¿Es necesario aprenderse los nombres de los metodos como `__lt__` , `__add__` , etc?

**Comment by lopezjurip** [comment]
No es esencial en la evaluación, pero si te lo sabes es mejor.

Puedes inventar métodos si no te acuerdas de los nombres, siempre y cuando digas a qué te referías.
Por ejemplo:

``` python
def __menor__(self, otro):  # Método inventado: para usar el operador '<'
    # ...
```

**Comment by javierlopeza** [comment]
Buena buena gracias!
