### ISSUE TITLE
I1 2015-1 

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#205]
Tengo la I1 del semestre pasado con solución, la puedo subir a algún lado o la subirán ustedes ? Para poder estudiar

**Comment by lopezjurip** [comment]
Se supone que todos deben saber que pueden acceder al syllabus del semestre pasado.
https://github.com/IIC2233-2015-1/syllabus/tree/master/Pautas%20Interrogaciones

Ahí tienen las Ies del semestre pasado. :+1: 
No hay más hacia atrás porque antes el curso se hacía en C# de manera muy distinta y no creo que les sirvan mucho esas Ies.

Gracias de todas formas por la motivación :ok_hand:
