### ISSUE TITLE
Destrucción, reparación y resistencia de vehículos

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#206]
Tengo las siguientes dudas:
- Se dice que para destruir un vehículo hay que atacar todas sus partes. 
  - ¿Es el ataque "Kamikaze IXXI" es una excepción de esto?
- Se dice que para destruir un vehículo se debe lograr un daño mayor o igual a la resistencia de este.
  - ¿La resistencia dada es la resistencia total del vehículo o su resistencia por casilla?
    - Por ejemplo, el barco pequeño tiene una resistencia de 30 y ocupa un área de 3x1, ¿Puedo destruirlo si le hago 20 puntos de daño a una casilla y luego 5 a cada una de las restantes, o bien cada casilla tiene una resistencia independiente de 10 (o de 30)?
- ¿Hay algún requerimiento de cercanía con respecto al puerto para reparar algún vehículo? ¿o puede el puerto usar su 'ataque' (Kit de ingenieros) con cualquier unidad propia, independiente de donde se encuentre en el mapa?

**Comment by bamavrakis** [comment]
Hola!
Para destruir un vehículo se debe lograr un daño mayor o igual a la resistencia total del vehículo, es decir, no hay resistencia por casillas. Tomando el barco pequeño que mencionas, debes aplicar 30 de daño total, y éste puede ser distribuido de cualquier forma (todo el daño en una pieza, o repartido entre todas, etc). Por otro lado, el Kamikaze IXXI destruye completamente el vehículo objetivo. Por último, con respecto al puerto, no hay ningún requerimiento de cercanía para utilizar su habilidad.
Espero haber aclarado tus dudas, Saludos!

**Comment by jgmontoya** [comment]
Entiendo, entonces simplemente ignoramos esto del enunciado?

>  Para destruir cualquier vehículo enemigo, se deben atacar todas sus partes. Por ejemplo, para hundir una lancha, se debe atacar cada una de sus 2 coordenadas (2 x 1).

**Comment by tamycova** [comment]
si @jgmontoya  a mi tampoco me quedo claro, existen dos formas de destruir un vehiculo?
forma 1 -> atacar cada coordenada (sin importar magnitud de daño)
forma 2 -> que la suma de las magnitudes de ataque supere su resistencia (pudiendo estar distribuidos en cualquier coordenada)

**Comment by bamavrakis** [comment]
Ignoren esa parte del enunciado, se subirá una versión corregida (esa parte se coló de una versión anterior no final).
Saludos!

**Comment by jgmontoya** [comment]
Entendido, cierro!
