### ISSUE TITLE
contenido tarea 3

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#207]
en la tarea nos piden cosas que no hemos visto aún (manejo de errores, testing), vamos a ver esa materia estas semanas o tenemos que buscar nosotros el material?

**Comment by aaossa** [comment]
En el [README.md](https://github.com/IIC2233-2015-2/syllabus/blob/master/README.md) principal se pueden ver los contenidos del curso y después de metaclases y clases abstractas viene esa materia, por lo que después de la interrogación deberían empezar a ver esta materia. 

Se verá todo lo que necesiten para esta tarea en el curso :+1:

**Comment by tamycova** [comment]
Gracias! se me fue revisar el readme ;D
