### ISSUE TITLE
Respecto a la actividad 10

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#208]
Dicha actividad no logré hacerla principalmente por una duda que hasta el día de hoy no logro solucionar.

Cuando en la metaclase debemos añadir nuevos atributos a la instancia de la clase y necesitamos que además los valores de estos atributos sean properties ¿Como lo hago?

``` python
class RestrictedAccess(type):
    def __new__(mcs, cls_name, cls_base, cls_dict):
        def new_init(self, *args):
            for attr in zip(cls_dict['attributes'], args):
                self.__dict__[attr[0]] = attr[1]
        cls_dict['__init__'] = new_init
        return super().__new__(mcs, cls_name, cls_base, cls_dict)
```

En el anterior código, yo nada más estoy haciendo que attr[0] sea attr[1]. Yo necesito algo como attr[0] = property(_get_attr), pero no sé en qué scope definir a "_get_attr". Estoy casi seguro que es dentro del loop for, pero aún no lo consigo :/

**Comment by lopezjurip** [comment]
Algo así?

``` python
... = property(lambda s: getattr(s, '__attribute'))
```

**Comment by btkramm** [comment]
Es que... ahgghgh. No lo comprendo. No puedo llegar y hacer attr[0] = property(getter) porque ni siquiera le he dado como el valor inicial que iba a tener attr[0] :/ Como que el getter siempre daría None si nunca pasé por el proceso de settear el atributo antes de hacerlo property.

**Comment by lopezjurip** [comment]
Dame un momento, llamaré a mis amigos expertos en metaclases.

**Comment by btkramm** [comment]
Creo que es pertinente que quien desee ayudarme lea la actividad 10. Tal vez quede clara mi duda.

**Comment by otro-felipe** [comment]
Si te fijas bien las properties son declaradas como si fueran estáticas. La manera en que yo lo hice fue "declarar" la property en el init de la metaclase:

``` python
def getter(self):
    return self.__solo_lectura

class SoloLectura(type):
    def __init__(cls, nombre, base_clases,diccionario):
        setattr(cls, "solo_lectura", property(getter))
```

**Comment by btkramm** [comment]
Sigo sin comprender :/

**Comment by ivaniadg** [comment]
Hola! 
Lo que pasa es que debes separar las acciones. Primero debes crear la property para cada uno de los atributos que va a tener la **clase**. Luego debes asignarle un valor a los atributos del **objeto** en el nuevo `__init__`. 
Dentro del `__new__` de la metaclase debes definir las properties

``` python
class RestrictedAccess(type):
    def __new__(mcs, cls_name, cls_base, cls_dict):
        for attr in attributes:
            clsdict[attr] = _getter('__' + attr) # el __ es solo para que se entienda por humanos que es un atributo privado
        def new_init(self, *args):
            pass #Todavía no hacemos nada aquí
        cls_dict['__init__'] = new_init
        return super().__new__(mcs, cls_name, cls_base, cls_dic
```

El método `_getter` va definido afuera. Este va a entregar una property tal y como escribió Pato. Se debe definir afuera porque si pones directamente ese código dentro del `__new__` ocurren cosas extrañas. Puedes ver [este link](http://stackoverflow.com/questions/27629944/python-metaclass-adding-properties) para más información. 

``` python
def _getter(attr):
    return  property(lambda s: getattr(s, attr)) #s se refiere a la clase que va a llamar a esta property. 
```

Ahora que ya existen las properties, hacemos los setter dentro del `__init__` que va a tener la **clase** "metaclaseada"

``` python
class RestrictedAccess(type):
    def __new__(mcs, cls_name, cls_base, cls_dict):
        for attr in attributes:
            clsdict[attr] = _getter('__' + attr)
            # el __ es solo para que se entienda 
            # por humanos que es un atributo privado
        def new_init(self, *args):
            for attr in zip(cls_dict['attributes'], args): 
                setattr(self, '__' + attr[0], attr[1]) 
        cls_dict['__init__'] = new_init
        return super().__new__(mcs, cls_name, cls_base, cls_dic

def _getter(attr):
    return  property(lambda s: getattr(s, attr)) #s se refiere a la clase que va a llamar a esta property. 
```

Igual esto no cumple con todas las restricciones de la actividad. En esta se especificaba que `attributes` debía desaparecer. 
(Hint: puedes usar pop())

**Comment by btkramm** [comment]
Pero si creo las properties antes, cómo voy a hacer setattr sin un setter ¿?

**Comment by Arios16** [comment]
El getter de una property es basicamente un metodo que no recibe parametros y se llama sin parentesis. En este caso uno define el getter para que retorne el atributo con nombre __attr, pero uno todavia puede acceder o setear el atributo __attr manualmente.

``` python
clsdict[attr] = _getter('__' + attr)
```

Lo que esto hace es asignar en el diccionario de la clase una property, con attr como key.
Asi, si yo tengo un objeto obj y yo llamo obj.attr, estoy llamando al getter de la property, que me va a retornar el atributo __attr del objeto (asi se definio a la property).

Alternativamente, si yo tengo un objeto y llamo a obj.__attr, estoy accediendo directamente al atributo.

Así, yo puedo escribir obj.__attr=5, y luego al llamar a obj.attr llamo al getter de la property, que luego accede al attributo __attr del objeto y retorna 5.
La gracia de la actividad era que si intento hacer obj.attr=5, da error porque la property no tiene un setter.

> Pero si creo las properties antes, cómo voy a hacer setattr sin un setter ¿?

Por lo que dije antes, no necesitas un setter de la property para setear el atributo, simplemente seteas manualmente el atributo al que luego va a acceder el getter. Este atributo se podria llamar como quieras, simplemente tienes que asegurarte que el getter acceda a este atributo. Se elige el nombre __attr porque esto normalmente lo haria privado, aunque en la practica en este caso el name mangling no funciona por otras razones.

Da lo mismo si creas las properties antes o despues, son cosas independientes. Lo unico que importa es que al _llamar_ a la property el atributo ya este definido.

**Comment by btkramm** [comment]
Okkkkkkkk ya entendí. Lo que me causaba problemas era que no estaba utilizando el '__' para "referirme a una variable distinta". Pensé que cuando lo explicaron así estaban usando un name mangling por formalidad, pero ya entiendo que no era tan solo eso.

SAJDASKD ahora me doy cuenta que mi duda era muy básica. Cuando uno crea una property respecto a un atributo de la clase, digamos, self._len, uno decora la función "len", y no "_len", la cual buscará al valor "self._len". No sé si me explico. El punto es que acá me fue mucho más difícil verlo.

Muchas gracias :DDDD

**Comment by btkramm** [comment]
SAJDASKD ahora me doy cuenta que mi duda era muy básica. Cuando uno crea una property respecto a un atributo de la clase, digamos, self._len, uno decora la función "len", y no "_len". No sé si me explico. El punto es que acá me fue mucho más difícil verlo.
