### ISSUE TITLE
Tablero y radar

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#210]
Hola, tengo dos dudas del enunciado:
1) El tablero dice que es de nxnx2 y que los mapas para cada usuario son distintos y deben estar separados. No me queda claro como funciona la asignacion del mapa:
- n va a ser un random para cada usuario? 
- un usuario va a tener mas espacio maritimo que el otro? 
- "deben estar separados" se refiere a que cada usuario solo pueda ver su tablero? (evidente, pero puedo hacer un tablero auxiliar para los jugadores con lo que se sabe del otro jugador, como en algunas versiones de battleship?)
- La interaccion por consola es libre? osea puedo decidir que se printee o no el estado actual del tablero etc?

2) En la seccion 6 se habla de un radar mistico que creo que no se menciona antes, cuales son los detalles especificados por el radar?

Gracias!!

**Comment by javierlopeza** [comment]
También para el `Misil de crucero BGM-109 Tomahawk` dice que _este ataque daña 5 puntos a la resistencia de toda una fila oponente (a lo largo de un eje, usted elige cuál)_, pero en la tabla resumen dice que el área atacada por este misil es de `1 X 15`. ¿Entonces el tablero lo hacemos de 15 X 15? ¿Cuál es el área de ataque correcta? Hay como una contradicción ahí creo yo.

**Comment by plorrego** [comment]
1. - El tablero tiene las mismas dimensiones para ambos jugadores. Puede quedar fija para todas las partidas, o se puede definir cada vez antes de comenzar. Eso queda a tu criterio, déjalo especificado el el README.
   - Ambos jugadores tienen el mismo espacio maritimo para una misma partida.
   - Ese tablero auxiliar vendría siendo el radar. A diferencia de battleship en este juego se pueden mover los barcos, asi que piensa bien las diferencias que esto podría implicar.
   - Cada jugador debe poder ver su propio tablero en su turno. Cuando se juega contra el computador solo debes ver tu propio tablero.
2. Los detalles quedan a tu criterio, claramente solo puede contener la informacion que tu contrincante te dio segun las reglas. Ojo que puede ir variando a traves de los turnos con los movimientos de los barcos.

**Comment by tamycova** [comment]
Gracias!
