### ISSUE TITLE
¿Cuánto sabe el oponente?

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#211]
Tengo esta duda. ¿De qué cosas se entera el oponente y de que cosas no?. Tengo claro que yo, cuando destruyo un barco enemigo me lo notifican. ¿Pero sé si mi enemigo realizó un ataque (fallido, obviamente) o se movió? ¿O eso es un misterio?

**Comment by plorrego** [comment]
Eso queda a tu criterio. Decide qué sería mejor para el desarrollo del juego y especifícalo en el README.
