### ISSUE TITLE
Posición y movimiento de vehículos

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#212]
Un vehículo se puede posicionar horizontal y verticalmente?
Si es así, una vez puesto (por ejemplo) verticalmente, al moverlo puede cambiar a posición horizontal? O se mantendrá con la misma orientación durante toda la partida?

**Comment by jgmontoya** [comment]
Aprovecho para preguntar si los vehículos se pueden mover en cualquier dirección o si tienen restricciones.

**Comment by eiurrutia** [comment]
1) La posición (horizontal o verticalmente) de cada vehículo se determina en el principio de la partida y luego no recomiendo girarlos. Sin embargo, queda a criterio de ustedes si es que consideran mejor girarlo para la dinámica del juego. Solo recuerden especificarlo en el Readme. 

2) La única restricción sería la cantidad de espacios por turnos, los bordes del mapa y que no se tope con otro barco.

**Comment by tamycova** [comment]
si estan orientados horizontalmente por ejemplo en coordenadas A1 - A2 - A3, puedo moverlo a B1 -B2 -B3? o solo a A2 - A3 - A4?

**Comment by plorrego** [comment]
Para ambos lados. saludos

**Comment by icrocco** [comment]
Para moverlos puedo indicar una dirección de desplazamiento o debe ser una coordenada de destino? De ser lo último, desde dónde se mediría el límite de movs.? Dado que las piezas no son de 1x1.

Gracias!
