### ISSUE TITLE
¿Salas I1?

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#213]
¡Saludos!

No sé si estoy mirando en el lugar equivocado, pero todavía no veo publicadas las salas de la I1, a una hora de la prueba.

¿Alguna idea?

Gracias :D

**Comment by aaossa** [comment]
Se publicaron en SIDING:

**Sección 1:**

```
B24
Desde: ABARCA   QUIROGA CRISTÓBAL ANDRÉS
Hasta: LIRES    PADIN   JULIAN

B23
Desde: MARTÍNEZ JARAMILLO       FRANCISCA VALENTINA
Hasta: ZAPATA   LLANQUILEO      FERNANDO WLADIMIR
```

**Sección 2:**

```
B25
Desde: ACKERMANN        GUZMAN  CHRISTIAN ANDRES
Hasta: NOGUERA  EGUIGUREN       DIEGO JOSÉ

B23
Desde: PÉREZ    MODOLO  RAIMUNDO ANDRÉS
Hasta: ZURITA   SOLER   MARIANA
```

**Comment by gebalassa** [comment]
Gracias! Es que como en el calendario del **README.md** aparece un guión bajo donde deberían ir las salas supuse que las colocarían aquí también.
