### ISSUE TITLE
Ataques

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#215]
En 3.1 se dice que _cada vehículo cuenta con un arsenal de armas específico, por lo que si un vehículo se destruye, se dejará de contar con dichos ataques_. Pero para el caso del `GBU-43/B Massive Ordnance Air Blast Paralizer` no se menciona en ninguna parte el vehículo que posee dicho ataque. ¿Todo vehículo lo posee?

Otra cosa, para el `Misil de crucero BGM-109 Tomahawk` en la parte 4.2 dice que daña 5 a la resistencia de la fila atacada y en la parte 4.3.3 dice que daña 3 a la resistencia de la fila atacada. ¿Cual tomamos? Sé que es muy detalle pero es por si quizás en la corrección afecta (?).

**Comment by ivanwolf** [comment]
Comento para saber

**Comment by jgmontoya** [comment]
Comento agregando un par de dudas respecto a los ataques:

Cuando se explican los ataques sale que:

> Misil UGM-133 Trident II: Todos los vehículos cuentan con este tipo de ataque.

Sin embargo cuando se explican los vehículos marítimos, dice que:

> Lancha: (...) sólo sirve para distraer a su enemigo, no permite realizar ningún
> ataque.

¿En este caso se aplica la regla de la lancha?

En el caso de los vehículos aéreos, ¿tienen también el ataque Misil UGM-133 Trident II?

**Comment by eiurrutia** [comment]
- Para el caso del GBU-43/B Massive Ordnance Air Blast Paralizer puedes asumir que lo tienen todos los barcos (se cuenta durante toda la partida con él). 
- Para el Misil de crucero BGM-109 Tomahawk, hubo en error de enunciado. Considerenlo como que daña 5.
- Para el caso de Misil UGM-133 Trident II, el juego termina cuando a un juegador se le destruyen todos sus barcos a excepción de la lancha (por lo difícil que sería atacarla ya que podría escapar cada turno) y de los aviones (nunca se les puede atacar, sólo paralizar en el caso del explorador). Por ende sí puedes considerar que lo contiene, lo importante es contar con el ataque durante toda la partida.

**Comment by tamycova** [comment]
Preunta, el misil Trident es solo para los barcos??? porque sino no servivira de nada el ataque Napalm que tambien ataca 5 pero solo cada 8 turnos

**Comment by otro-felipe** [comment]
Tamy el misil napalm ataca 5, y al turno siguiente pega 5 de nuevo (en total pega 10) es como si hubieras dejado en llamas el barco enemigo atacado por un turno (?

**Comment by fgvenegas** [comment]
no se si respondieron  esto en otro lado, pero sale que el area de daño del Tomahawk es de 1x15 pero se supone que ataca una fila entera, con cual me quedo?

**Comment by tamycova** [comment]
@fgvenegas  si lo respondieron! quedate con la fila entera , y @MainScientist  jaja siii cache despues #shiponfire
