### ISSUE TITLE
Corrección Actividad 6

### ISSUE THREAD

**Issue by marizurita** [IIC2233-2015-2/syllabus#216]
¡Hola!

¿Hasta cuándo se puede mandar a re-corregir la actividad 6? Tengo la nota pero no el feedback.

**Comment by lopezjurip** [comment]
Revisé en nuestro repositorio privado de ayudantes y no encuentro. Probablemente le quedó a tu compañero

**Comment by marizurita** [comment]
En esa actividad fui sola... ¿Qué pudo haber pasado?

**Comment by lopezjurip** [comment]
Quizás la persona que la revisó la borró/olvidó. Revisaré en un momento más.

**Comment by oatorresuc** [comment]
Tengo el mismo problema y yo tambien fui solo

2015-09-22 12:02 GMT-03:00 marizurita notifications@github.com:

**Comment by jgmontoya** [comment]
Yo tampoco tengo el feedback, solo la nota en el siding. Igual mandé a recorregir porque estoy seguro de que ha habido algún tipo de error (tengo un 1 y mi actividad no está tan mala :( (lo juro))

**Comment by PaulaSanzana** [comment]
Yo tampoco tengo el feedback y también fui sola

**Comment by jecastro1** [comment]
Los que tienen 1.0, no tienen feedback y creen que merecen más nota manden a recorregir tal y como les dijo Belén por mail.

El formulario está en el SIDING.
