### ISSUE TITLE
5. Estadísticas

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#217]
Algunas dudas de las estadísticas que se piden entregar al final de la partida:
- El punto 2, _porcentaje de ataques exitosos por barco y avión_, ¿se refiere al porcentaje de ataques exitosos por **cada** barco y **cada** avión de la flota del jugador? ¿o al porcentaje de ataques exitosos **por mar y aire**?
- El punto 3, _daño por barco_, ¿se refiere al daño **recibido** por cada barco de la flota del jugador?
- El punto 9, _ataque más eficiente_, ¿se refiere al ataque en que la razón de (daño causado)/(veces usado) es mayor?

**Comment by plorrego** [comment]
Punto 2: porcentaje de ataques exitosos por cada barco y cada avión.
Punto 3: daño recibido por cada barco.
Punto 9: ataque que tenga la mayor razón (daño causado)/(veces usado).

**Comment by javierlopeza** [comment]
Gracias!
