### ISSUE TITLE
Problemas con 'import numpy'

### ISSUE THREAD

**Issue by nabodorbuco** [IIC2233-2015-2/syllabus#22]
Hola a todos, estaba revisando el documento de Polimorfismo y al replicar los códigos que ahí aparecen, me encuentro con que el comando: 

``` python
import numpy as np
```

me arroja el siguiente error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/nabodorbuco/Documentos/PyCharm/pycharm-community-4.5.3/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: No module named 'numpy'
```

Y a pesar de haber indagado en internet, no puedo darle solución al problema. Desde ya muchas gracias si alguien sabe como solucionar esto.

**Comment by aaossa** [comment]
Si importas `numpy` desde Python (the real, IDLE) funciona?

**Comment by felipehv** [comment]
No hay que instalar numpy antes?
Intenta con pip install numpy en el cmd

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

2015-08-19 22:55 GMT-03:00 Antonio Ossa notifications@github.com:

**Comment by flobarrios** [comment]
Tienes que istalar la libreria, en mac prueba con el comando (desde el terminal): pip3 instal numpy. En
windows no me se el comando. Saludos!

**Comment by oatorresuc** [comment]
A mi me pasó lo mismo y probé desde python y aparece esto

```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32
bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\numpy\__init__.py", line 170, in
<module>
    from . import add_newdocs
  File "C:\Python34\lib\site-packages\numpy\add_newdocs.py", line 13, in
<module>
    from numpy.lib import add_newdoc
  File "C:\Python34\lib\site-packages\numpy\lib\__init__.py", line 8, in
<module>
    from .type_check import *
  File "C:\Python34\lib\site-packages\numpy\lib\type_check.py", line 11, in
<module>
    import numpy.core.numeric as _nx
  File "C:\Python34\lib\site-packages\numpy\core\__init__.py", line 6, in
<module>
    from . import multiarray
ImportError: DLL load failed: %1 no es una aplicación Win32 válida.
>>>
```

2015-08-19 22:55 GMT-03:00 Antonio Ossa notifications@github.com:

**Comment by aaossa** [comment]
@oatorresuc Prueba instalando la versión de `numpy` correspondiente desde [**aquí**](http://www.lfd.uci.edu/~gohlke/pythonlibs/). Ya te agrego las instrucciones (en **EDIT**).

@nabodorbuco, como dijeron @felipehv y @flobarrios tienes que instalar numpy usando el comando en pip correspondiente. Debería ser algo como: `pip install numpy`.

**EDIT:** Descarga la versión correspondiente a tu versión de Python y de Windows y luego abres una ventana de comandos en la carpeta donde se encuentre tu descarga. Una vez en la ventana de comandos escribes `pip install <nombre_del_paquete_version_blablabla>.whl` y se debería instalar sin problemas. Si sigues con problemas avisanos :grin:

**Comment by nabodorbuco** [comment]
Hice lo siguiente, puse en el cmd

```
sudo apt-get install python-pip
```

```
pip install numpy
```

y después reinicié pycharm... pero me sigue tirando el mismo error

**Comment by flobarrios** [comment]
ojo que si en pycharm estas usando python 3 tienes que usar pip3 en el terimal para instalar numpy, o si no, se instalara en la versión de python 2 que tengas (por lo que tengo entendido :) )

**Comment by felipehv** [comment]
si, en el caso de mac/linux, necesitas especificar que es pip3 para python 3 y pip para python 2.7

**Comment by flobarrios** [comment]
prueba esto:

```
sudo apt-get install python3-pip
```

```
pip3 install numpy
```

**Comment by nabodorbuco** [comment]
Probe:

```
sudo apt-get install python3-pip
```

y

```
sudo apt-get install python-pip3
```

y aun así me dice que "No se ha podido localizar el paquete (nombre del paquete)"... (Seré yo Señor?... u.u)

**Comment by eavildosola** [comment]
@nabodorbuco si estas usando pycharm tienes que ver que Project Interpreter estas ocupando y preocuparte que tengas instalado _numpy_ ahí

**Comment by oatorresuc** [comment]
Escribi pip3 install numpy sale esto

PS C:\WINDOWS\system32> pip3 install numpy
Requirement already satisfied (use --upgrade to upgrade): numpy in
c:\python34\lib\site-packages

ingreso a esa carpeta pero no se como actualizarlo

2015-08-19 23:12 GMT-03:00 Eduardo Vildosola notifications@github.com:

**Comment by eavildosola** [comment]
@oatorresuc para actualizarlo tienes que escribir en la consola el comando

> pip3 install --upgrade numpy

**Comment by oatorresuc** [comment]
justo encontré esa solución en google pero el problema persiste

2015-08-19 23:18 GMT-03:00 Eduardo Vildosola notifications@github.com:

**Comment by aaossa** [comment]
Y si usas `pip3 install numpy --upgrade`? Es algo mínimo pero bueno, es pip...

**Comment by oatorresuc** [comment]
Dice que ya actualizado pero aun no funciona import numpy as np

**Comment by gebalassa** [comment]
Tampoco soy capaz de hacer que:

pip3 install --upgrade numpy

funcione. Se descargó y todo pero luego de terminar la descarga se generó
el siguiente texto:

```
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in ['C:\\Python34\\lib',
```

'C:\
', 'C:\Python34\libs']
      NOT AVAILABLE

```
atlas_blas_info:
  libraries f77blas,cblas,atlas not found in ['C:\\Python34\\lib',
```

'C:\', '
C:\Python34\libs']
      NOT AVAILABLE

```
blas_info:
  libraries blas not found in ['C:\\Python34\\lib', 'C:\\',
```

'C:\Python34\l
ibs']
      NOT AVAILABLE

```
blas_src_info:
  NOT AVAILABLE

  NOT AVAILABLE

non-existing path in 'numpy\\lib': 'benchmarks'
lapack_opt_info:
openblas_lapack_info:
  libraries openblas not found in ['C:\\Python34\\lib', 'C:\\',
```

'C:\Python3
4\libs']
      NOT AVAILABLE

```
lapack_mkl_info:
mkl_info:
  libraries mkl,vml,guide not found in ['C:\\Python34\\lib', 'C:\\',
```

'C:\Py
thon34\libs']
      NOT AVAILABLE

```
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas,tatlas not found in C:\Python34\lib
  libraries lapack_atlas not found in C:\Python34\lib
  libraries tatlas,tatlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries tatlas,tatlas not found in C:\Python34\libs
  libraries lapack_atlas not found in C:\Python34\libs
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries satlas,satlas not found in C:\Python34\lib
  libraries lapack_atlas not found in C:\Python34\lib
  libraries satlas,satlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries satlas,satlas not found in C:\Python34\libs
  libraries lapack_atlas not found in C:\Python34\libs
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in C:\Python34\lib
  libraries lapack_atlas not found in C:\Python34\lib
  libraries ptf77blas,ptcblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries ptf77blas,ptcblas,atlas not found in C:\Python34\libs
  libraries lapack_atlas not found in C:\Python34\libs
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries f77blas,cblas,atlas not found in C:\Python34\lib
  libraries lapack_atlas not found in C:\Python34\lib
  libraries f77blas,cblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\
  libraries f77blas,cblas,atlas not found in C:\Python34\libs
  libraries lapack_atlas not found in C:\Python34\libs
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

lapack_info:
  libraries lapack not found in ['C:\\Python34\\lib', 'C:\\',
```

'C:\Python34\
\libs']
      NOT AVAILABLE

```
lapack_src_info:
  NOT AVAILABLE

  NOT AVAILABLE

running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands
```

--compiler
options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands
--fcompiler
 options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build\src.win32-3.4
    creating build\src.win32-3.4\numpy
    creating build\src.win32-3.4\numpy\distutils
    building library "npymath" sources
    No module named 'numpy.distutils.msvccompiler' in numpy.distutils;
trying fr
om distutils
    Running from numpy source directory.

C:\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb5f6\numpy\numpy\distutils
\system_info.py:1603: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.**doc**)

C:\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb5f6\numpy\numpy\distutils
\system_info.py:1612: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      warnings.warn(BlasNotFoundError.**doc**)

C:\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb5f6\numpy\numpy\distutils
\system_info.py:1615: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      warnings.warn(BlasSrcNotFoundError.**doc**)

C:\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb5f6\numpy\numpy\distutils
\system_info.py:1505: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.**doc**)

C:\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb5f6\numpy\numpy\distutils
\system_info.py:1516: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.**doc**)

C:\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb5f6\numpy\numpy\distutils
\system_info.py:1519: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.**doc**)
    C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown
distribution opt
ion: 'define_macros'
      warnings.warn(msg)
    error: Microsoft Visual C++ 10.0 is required (Unable to find
vcvarsall.bat).

```
----------------------------------------
Command "C:\Python34\python.exe -c "import setuptools,
```

tokenize;**file**='C:
\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb5f6\numpy\setup.py';exe
c(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n',
'\n')
, **file**, 'exec'))" install --record
C:\Users\Gabriel\AppData\Local\Temp\pip-9
vpisca_-record\install-record.txt --single-version-externally-managed
--compile"
 failed with error code 1 in
C:\Users\Gabriel\AppData\Local\Temp\pip-build-bf2kb
5f6\numpy
C:\Users\Gabriel>

Porfa, si alguien cacha como finalizar la instalación sería ideal :-/ El
paquete al final no se instaló pues Python sigue sin poder encontrarlo.

**Comment by aaossa** [comment]
@gebalassa Sigue el instructivo que puse más arriba: Prueba instalando la versión de `numpy` correspondiente desde [**aquí**](http://www.lfd.uci.edu/~gohlke/pythonlibs/).

Descarga la versión correspondiente a tu versión de Python y de Windows y luego abres una ventana de comandos **en la carpeta donde se encuentre tu descarga**. Una vez en la ventana de comandos escribes `pip install <nombre_del_paquete_version_blablabla>.whl` y se debería instalar sin problemas. Si sigues con problemas avisanos :grin:

**Comment by aaossa** [comment]
Si alguno de ustedes sigue con este problema puede reabrir esta issue. Además, el lunes después de la ayudantía o después de alguna cátedra podemos revisarlo.

**Comment by gebalassa** [comment]
![error](https://cloud.githubusercontent.com/assets/11603889/9564600/540da792-4e7a-11e5-8afc-4c98e10e5094.png)

Abrí el CMD en el escritorio (donde tengo el archivo) y me sale esto :-(

Tengo Windows 32-bit por lo que debería funcionar.

**Comment by lopezjurip** [comment]
¿No te funcionó el de la [Wiki](https://github.com/IIC2233-2015-2/syllabus/wiki/Windows#python-3x)?

``` sh
pip install -i https://pypi.binstar.org/carlkl/simple numpy
```

Una opción es instalarlo directamente con `pip install -U numpy` pero en Windows necesitarás instalar antes un compilador de `C`.

**Comment by gebalassa** [comment]
¿Si uso el primer comando no se me va a instalar el numpy para Python 2.x?

Lo otro: Cuando intenté usar `pip install -U numpy` hace un tiempo mencionaba a Microsoft Visual C++. ¿Será eso lo que necesito como compilador? ¿Cuál me recomiendas?

**Comment by lopezjurip** [comment]
Entonces prueba con `pip3`, todo esto depende de cómo hayas hecho el setup.

``` python
pip3 install -i https://pypi.binstar.org/carlkl/simple numpy
```

**Comment by rodolfopalma** [comment]
Quizás el error de plataforma tiene que ver con la versión de Python que se usó al compilar el paquete que descargaste (me parece que el archivo que tienes es para Python 2.6). Trata de bajar alguno de [esta página](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) que calce con la versión de Python que tienes instalada (si tienes Python 3.3, tiene que ser el archivo que se llama `numpy‑1.9.2+mkl‑cp33‑none‑win32.whl`; si tienes Python 3.4, `numpy‑1.9.2+mkl‑cp34‑none‑win32.whl`).

**Comment by gebalassa** [comment]
@rpalmaotero Puede ser. Probaré ahora.

EDIT: Tenías razón :P Funcíonó. Muchas gracias por todo. 

En un detalle aparte, resulta que tengo instalado el Redistributable de Microsoft Visual C++ 2010 y aún así me aparece como requerimiento para instalar "numpy" con Pip directamente. En un link mencionaban que eso no era un compilador y lo que de verdad se necesita es Microsoft Visual Studio C++ Express 2010, lo que me parece extraño pues según tengo entendido eso es una IDE, y no debería ser necesaria de forma entera para compilar :-/

**Comment by oatorresuc** [comment]
Intente todo lo que sale ahí y me tira este error:

Osvaldo Torres Mds@PC-OSVI ~/Downloads
$ pip3 install numpy-1.10.0b1+mkl-cp34-none-win32.whl
Processing c:\users\osvaldo torres mds\downloads\numpy-1.10.0b1+mkl-cp34-none-win32.whl
Installing collected packages: numpy
  Found existing installation: numpy 1.9.2
    Uninstalling numpy-1.9.2:
      Successfully uninstalled numpy-1.9.2
  Rolling back uninstall of numpy
[31mException:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 311, in run
    root=options.root_path,
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 646, in install
    **kwargs
  File "C:\Python34\lib\site-packages\pip\req\req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Python34\lib\site-packages\pip\req\req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "C:\Python34\lib\site-packages\pip\wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Python34\lib\site-packages\pip\wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "C:\Python34\lib\site-packages\pip\utils__init__.py", line 71, in ensure_dir
    os.makedirs(path)
  File "C:\Python34\lib\os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Acceso denegado: 'C:\Python34\Lib\site-packages\numpy\core'[0m

**Comment by oatorresuc** [comment]
Y de la nada intentandolo, funcionó.
Gracias

**Comment by jon998** [comment]
Si usan pycharm esta es la solucion...
https://www.youtube.com/watch?v=dxwB8KBLMcs
