### ISSUE TITLE
Lo más correcto

### ISSUE THREAD

**Issue by benjavides** [IIC2233-2015-2/syllabus#221]
Hay varias situaciones en que no sé qué es "más correcto" hacer. El problema de fondo es que no entiendo **qué se busca con el código**, que sea: **¿Corto? ¿Muy entendible? ¿Reutilizable? ¿Modular?**
1. Si tengo el objeto Cara, qué es mejor:
   
   _(Suponiendo que tiene sentido tener una clase para cada oreja y no hay más rasgos faciales en `Cara`)_
   a)   
   
   ``` python
   class Cara:
       self.oreja_iz = Orejaiz()
       self.oreja_der= Orejader()
   ```
   
   b)   
   
   ``` python
   class Cara:
       self.orejas = {"izquierda": OrejaIz(), "derecha": Orejader()}
   ```
2. En general, si hay un objeto que puede ser de dos tipos, que no tienen ninguna diferencia más que el tipo. conviene crear una crear una clase Objeto con una variable que especifique el tipo o hacer dos clases que hereden de Objeto.
   a)   
   
   ``` python
   class Objeto:
       self.tipo = "string"
   ```
   
   b)   
   
   ``` python
   class Objeto:
       pass
   class Tipo1(Objeto):
       pass
   class Tipo2(Objeto):
       pass
   ```
3. Lo ideal es que los objetos se comuniquen llamando a un metodo del otro y que este internamente se preocupe de hacer cosas? (Intentar acceder lo menos posible "a la fuerza" al otro objeto).
   a)   
   
   ``` python
   class Barco:
       self.salud = 10
       def atacar(self, oponente):
           oponente.salud -=1
   ```
   
   b)   
   
   ``` python
   class Barco:
       self.salud = 10
       def atacar(self, oponente):
           oponente.recibir_ataque()
       def recibir_ataque():
           self.salud -=1
   ```

**Comment by lopezjurip** [comment]
Tus preguntas/problemas son áreas de estudio dentro de la **Ingeniería de Software**, hay _papers_ y gente que investiga el tema de cómo escribir buen código, más allá de qué tan óptimo sea. 

Mi opinión sobre lo que preguntas:

**1.** Es más simple la forma **a)**, sin embargo es más extensible la forma **b)** (si una persona llegara a tener más orejas...).

Pero voto por la **a)** porque esta no depende de _llaves_ (_keys_). Usar _strings_ para llaves puede ser propenso a errores de tipeo que una IDE no va a reconocer. En lenguajes más estructurados no se usan _strings_ así como así, sino que se definen **strings constantes**, _**symbols**_ o **enumeraciones**. 

**2.** Por ejemplo, si estás programando una máquina dispensadora de bebidas sería innecesario declarar que Pepsi hereda de bebida. Porque todas las bebidas **se comportan igual, solo cambian en un atributo que es la marca**. Ahora, otro tipo de bebestible (:beer:) que sí puede tener un comportamiento distinto le convendría tener su propia clase.

**3.** https://en.wikipedia.org/wiki/Cohesion_(computer_science)

Si declaras el método `recibir_ataque` tu clase es más _cohesiva_, hace lo que tiene que hacer y depende solo de ella, no de externos. Además es más reusable porque te aseguras que siempre el daño se reciba de cierta manera. Si es que el valor del daño después llegue a cambiar, solo tendrás que modificar ese `1` que pusiste ahí y no en todos los otros lugares donde recibe daño. 

Que bueno que te estés preocupando de esos detalles :smile:

**Comment by benjavides** [comment]
Muchas gracias por toda la explicación!
