### ISSUE TITLE
Posición vehículos aéreos

### ISSUE THREAD

**Issue by benjavides** [IIC2233-2015-2/syllabus#223]
En que afecta la posición de los vehículos aéreos?

Al principio del enunciado dice "...cuidando de colocar vehículos aéreos en el sector aéreo" luego no se especifica el espacio que estos ocupan ni su resistencia y por último se dice que estos "no reciben ataques habituales".

Están de alguna forma limitados los ataques aéreos por la posición del avión?

**Comment by plorrego** [comment]
Respondi esto en el punto 2 del issue #228
