### ISSUE TITLE
¿Deberíamos actualizarnos a python 3.5?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#224]
Parece ser que la versión 3.5 ya es release estable, ¿debiésemos actualizarnos a esa versión o seguiremos trabajando con la 3.4?

**Comment by lopezjurip** [comment]
Yo estoy usando 3.5 desde que salió jeje. 
Puedes instalarla pero asegúrate de no usar las funcionalidades nuevas porque no te puedo asegurar que el ayudante que te corrija tenga esa versión.

**Comment by jgmontoya** [comment]
Mmm, dale... entonces mejor no me arriesgo :dizzy_face:
