### ISSUE TITLE
Testear funciones que solicitan input

### ISSUE THREAD

**Issue by ivanwolf** [IIC2233-2015-2/syllabus#225]
Hola, para testear mis funciones estoy usando la librería `unitest` de `python` (espero que no tengamos que crear nuestros propios test...) y tengo la siguiente duda. 
Digamos que quiero testear esta función:

``` python
def ingrese_el _valor_dos():
    return = int(input('ingrese un valor entero'))
```

Luego en mi test aparecerá algo así como

``` python
class TestFuncion(TestCase):
    def test_funcion(self):
        self.assertTrue(ingrese_el_valor_dos() == 2)
```

O algo por el estilo, no se si alguien me podría ayudar o dar una idea de como testear este tipo de funciones. De ante mano, gracias.
PD: la funcion que de verdad quiero testear se llama a si misma hasta que el usuario ingresa un valor entero.

Saludos!

**Comment by lopezjurip** [comment]
Ese test está mal enfocado.
Un mejor test sería: _"dado un input del usuario"_:
- Si es el número esperado _2_, debe pasar tal cosa.
  - Lo prueba pasandole el _2_ a mi función y espero que haya tal cosa.
- Si es un número no esperado, pasar tal cosa.
  - Le paso un _3_ a mi función y espero que haya tal cosa.
- Si no es un número, avisar con error o tirar excepción.
  - Le pasó un "hello world\* ...
- Si es vácio, se espera que el programa termine su ejecución.
  - Le paso ` ` ...

Todos esos valores de ejemplo **uno los escribe en el código** (se _hardcodean_), la idea es que los test sean automáticos.

**Comment by ivanwolf** [comment]
Entiendo, gracias!

**Comment by gebalassa** [comment]
@mrpatiwi Hola!

¿Cómo hardcodeas valores para testearlos en una función que utiliza "input()"?

En este caso, ¿Cómo haces un test que entregue un input 2, o 3, o "banana", o nada, a la función mencionada, sin que el usuario deba escribirlo por si mismo?

**Comment by lopezjurip** [comment]
lo hardcodeas :ok_hand: 

``` python
input_usuario = "banana"
assert funcion(input_usuario) ...
```

**Comment by gebalassa** [comment]
Pero eso no funcionaría con la función de arriba sin modificarla. Si yo hiciese una función más complicada que utiliza varios inputs, como _hardcodeo_ sin modificar la función?
