### ISSUE TITLE
Utilidad de las Exceptions 

### ISSUE THREAD

**Issue by spiza** [IIC2233-2015-2/syllabus#227]
Hola!

Tengo una duda.. Al final del material de clases numero 2 de excepciones, se habla de las diferencias entre usar ifs y usar excepciones, pero a mi me nace una duda importante.. 

Si la excepción corta todo el programa, entonces no entiendo porque es taaaaan útil en comparación a los ifs.. Pensando en la tarea, si yo le pido a un usuario que ingrese una coordenada de ataque, y esta coordenada de ataque no existe, probablemente (y esté pensada así la tarea) mi programa tire una excepción.. pero que pasa si estamos en la mitad de un juego super reñido, y uno de los jugadores tira una excepción?? Sería harto más agradable que el programa me advierta que no se puede hacer eso, antes que cerrarse! 

Saludos

**Comment by jgmontoya** [comment]
La idea, según entiendo, es que tires la excepción pero que la agarres dentro de un bloque **try_/_except** cosa de que el programa siga funcionando con normalidad teniendo en cuenta que se generó esa excepción.

Quizás sirve para guiar un poco al usuario cuando se equivoque y ponerle un mensaje de qué está haciendo mal sin que se caiga el programa.

**Comment by spiza** [comment]
Sí, puede ser.. es que no me quedó claro en el material de clases que cuando se usaban los bloques try/except no se paraba el programa.

**Comment by jgmontoya** [comment]
Está en "Manejo de Excepciones", en el segundo html entre "Generando Excepciones Personalizadas" y "Creando Excepciones Personalizadas" como en la mitad :expressionless:

**Comment by lopezjurip** [comment]
muchos contenidos del curso no están enfocados para _el usuario de sus programas_, sino para **el usuario de sus códigos**, o sea, otro programador. 

Las excepciones pueden ser usadas por ejemplo:
- Cuando no tienes control de la operación
  Por ejemplo bajar un archivo de internet. Puede que no tengas internet o se corte durante el proceso. La única manera de avisarle al programador que está usando ese método `bajar_archivo(url)` es tirando una excepción y que el la _agarre_ (`catch`) y controle qué pasa en ese caso (volver a intentar, hacer un respaldo de lo que se alcanzó a bajar, etc) o no la controle y le tire el problema a un código de más alto nivel (al que esté usando su código). 
- Cuando el resultado de una operación no puede ser representado.
  Por ejemplo al intentar dividir por cero: no tiene sentido retornar 0 ó -1 ó infinito porque ninguno es correcto. Lo mismo al intentar invertir matrices no invertibles, no puedes retornar una matrix vacía o None. En estos casos tienes que tirar una excepción matemática. 

Ahora cuando sí puedes controlar los casos especiales, es más limpio usar `if`.

Es mejor que un programa se caiga ante un error identificable y poder arreglarlo al tiro versus que el programa siga funcionando con datos incorrectos y que pasen piola: https://en.wikipedia.org/wiki/Garbage_in,_garbage_out
