### ISSUE TITLE
Varias preguntas Tarea 03

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#228]
Hola! Tengo varias preguntas que me han surgido al intentar avanzar en la Tarea. 
1. Al comenzar el juego, cada jugador coloca sus barcos y aviones en el tablero, pero, ¿Coloca una y solo una pieza de cada una en su tablero? ¿Esas piezas son siempre las mismas o de alguna forma hay que permitir al usuario que cree más vehículos o que instancie dos vehículos iguales (por ejemplo dos kamikazes)?
2. ¿Los aviones pueden moverse? ¿Considero que se mueven igual que un barco o se mueven más rápido (que sería lo más lógico) ¿De qué les serviría si no reciben daño (además de al explorador)?
3. ¿Cuánto daña el misil Tomahawk? En la descripción dice 5 por casilla pero en la tabla resumen sale que daña 3. Además, ¿su alcance es ilimitado en una fila o solo alcanza 15 (tabla resumen)? ¿Sus direciones son horizontal y vertical, o también debe considerarse la diagonal?
4. Sobre los vehículos, ¿Sus direciones son horizontal y vertical, o también debe considerarse la diagonal?
De antemano gracias por la ayuda =)

**Comment by plorrego** [comment]
1. Respecto a esas dudas, lo que no esté explícito en el enunciado queda a tu criterio. El el README debes justificar qué decidiste y por qué.
2. Es verdad, solo el avion explorador puede ser atacado. Pueden moverse pero no tendría mucho sentido estrategico perder un turno en moverlos, a excepción del explorador.
3. Daña 5 por casilla. Ataca toda una fila, osea 1xn. 
4. Solo horizontal y vertical.

**Comment by gebalassa** [comment]
Entonces no debería haber problema con darle movimiento al avión caza, no?

**Comment by andresespinosapc** [comment]
@gebalassa yo creo que si se deberian poder mover los aviones. Que pasa si quieres mover el explorador a una posicion ocupada por otro avion?  :scream:

**Comment by plorrego** [comment]
Buena observación @andresespinosapc . Si se pueden mover
