### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by selira** [IIC2233-2015-2/syllabus#23]
Dejo esto por acá para los que decían que las posiciones deben ser clases:
http://stackoverflow.com/questions/14027417/what-does-pylints-too-few-public-methods-message-mean
Sé que a veces es mejor usar clases, pero creo que igual debieran ser flexibles en la corrección de actividades en ese sentido.
Saludos!

**Comment by lopezjurip** [comment]
Siempre un problema tiene más de una solución :smile: 

La pauta para la correción de la AC01 es bastante flexible con respecto a las _coordenadas_ por existir muchas formas de hacerlo :+1: 

Sin embargo, era obligación declarar las clases `Cielo`, `Field`, `Estrella` y `Observacion` (o con nombres similares)

**Comment by selira** [comment]
Ahhh ok. Pensé que iban a ser mas estrictos para corregir.
Gracias por responder!

**Comment by bcsaldias** [comment]
Hola,

Las posiciones tenían nombres concretos y no podrían ser considerados como una tupla. Debían ser atributos de los objetos. En los feedback o correcciones dirá eso, en la ayudantía se vio. Cualquier otro caso pueden apelar a recorrección, pero la idea no es crear clase por todo.

Si yo digo que algo tiene un atributo RA, entonces se lo dejo como atributo (self.RA), no invento una tupla self.coordenadas = (RA), independiente que es una coordenada, porque cuando yo quiera conocer el valor de RA diré: mi_objeto.RA y no mi_objeto.coordenadas[0]  ¿cómo saber que era la 0 y no la 1? -  mi_objeto.coordenadas.RA es más apelable aunque tal vez no era necesaria la clase coordenadas, ya que se explicita el nombre del atributo por lo mismo.

Cuando se suban las notas se exlicará cómo se corrigió.

Aun así existen muchas formas de modelar el problema, pero en algo básico como eso deben coincidir.

Saludos !
