### ISSUE TITLE
Lancha

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#231]
¿Cómo va a distraer al oponente la ancha si tiene 1 punto de resistencia? ¿Si le llegásemos a dar con cualquier ataque se destruiría, o estoy entendiendo mal el concepto de resistencia?

**Comment by plorrego** [comment]
Puede distraer si la encuentra el avión explorador y la confunde con un barco. Pero tienes razón, si pudiera resistir al menos un ataque podría distraer mas. Si quieres cámbialo y lo pones en el README.

**Comment by otro-felipe** [comment]
Ahí le voy a hacer un rework jejejeje muchas gracias.
