### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by fergarciafaura** [IIC2233-2015-2/syllabus#232]
Hola, cuando hago git pull, me tira este error:

remote: Counting objects: 47, done.
remote: Compressing objects: 100% (32/32), done.
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed

qué puedo hacer?

**Comment by lopezjurip** [comment]
¿al hacer `git push` o `git pull`?
¿Buscáste en internet? Al parecer no eres la única que ha tenido ese error
