### ISSUE TITLE
Sobre el efecto del ataque GBU-43/B Massive Ordnance Air Blast Paralizer

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#233]
Hola! Mi pregunta es cuál es el área que afecta este ataque, ya que en una parte se señala que ataca dos casillas juntas y que paraliza al Avión Explorador del enemigo solamente si ambas coordenadas afectadas son sobre éste. Sin embargo, en la sección 4.4.3 (tabla) aparece que el área atacada es solamente de 1 x 1. ¿Es un error de la tabla?
Si fuera de dos casillas, aprovecho de preguntar también cómo se hace en este caso, ya que el usuario podría o elegir una sola coordenada para que el ataque surta efecto y que la otra sea elegida de manera aleatoria por el programa, o que tenga la posibilidad de elegir ambas (y que el programa no permita que la segunda coordenada se elija a menos que sea consecutiva a la primera).
Muchas gracias de antemano
Saludos! :)

**Comment by eiurrutia** [comment]
Hola!
- Sí, corresponde a un error de enunciado en la tabla. El paralizador actúa sobre 2 x 1
- Al explorar con dicho avión, dado que este ocupa un área de 3x3, se revela dicha área para el jugador que utiliza el avión. Sin embargo, al explorar, con cierta probabilidad (en el enunciado sale 50% pero puede variar acorde a como estimen conveniente) el avión explorador revelará una de esas nueve casillas (del espacio 3x3 explorado) y se le notificará al contrincante que se le exploró en dicha casilla. Luego el contrincante puede hacer uso de esta información y lanzar un ataque paralizador, el cual sólo surge efecto si ambas casillas (2x1) quedan contenidas dentro del área del avión explorador del otro jugador (espacio de 3x3).

Saludos!

**Comment by andresespinosapc** [comment]
@eiurrutia en el enunciado sale que el Avión Explorador ocupa un área de 2x2. Esto es un poco raro, porque no sé hacia dónde es el área que se explora, no queda centrado el avión en un área de 3x3 que es la que se quiere explorar.

**Comment by fagomez2** [comment]
Hola!! No entiendo el funcionamiento del explorador: El avión según la tabla es de 2x2, pero explora una zona de 3x3. ¿"Explorar" es un movimiento del explorador (se mueve a un lugar y luego notifica la zona de 3x3 a donde se movió) o es un ataque (seleccionas cualquier lugar para explorar y notificas la existencia de un barco en esa zona)? Además, en el enunciado dice que tras el ataque hay una posibilidad de revelar una de las coordenadas del avión explorador, pero "eiurrutia" acaba de decir que la probabilidad es sobre revelar una de las coordenadas exploradas. ¿Cómo funciona entonces?

**Comment by eiurrutia** [comment]
Hola! Bueno, nuevamente hubo error de enunciado en la tabla. El tamaño del avión es de 3x3 (su tamaño es igual a lo que explora). La posición que el avión explorador toma es el área explorada en cada turno, es así como se revelará una coordenada del área explorada o del avión explorador (serán lo mismo). Si en un turno cualquiera no se explora, entonces su posición será su última área explorada. Es decir, el avión explorador actúa como "ataque y movimiento del vehículo" al mismo tiempo y puede moverse todas las casillas que se desee.

**Comment by fgvenegas** [comment]
Quienes tienen el ataque paralizador? porque creo que no especificia si lo tienen algun barco o avion
