### ISSUE TITLE
Sobre lambda y PEP8

### ISSUE THREAD

**Issue by ouhenio** [IIC2233-2015-2/syllabus#234]
Tengo instalado el modulo de anaconda en sublime text por lo que me avisa si cometo una falta en pep8. 

Cuando asigno lambda a una variable, como por ejemplo f = lambda.... me dice que es un error, que use def para definir una función. El problema es que de esta manera se puede escribir muy facilmente algunas funciones recursivas sin tener que gastar líneas o apretar teclas demás.

¿Le hago caso al pep8 por el bien de la sintaxis (que en este caso me parece exagerado porque es sólo una línea, se entiende completamente) o me viro por la eficiencia?

Agrego ejemplo, sacar máximo común divisor, para que vean la diferencia:

```
def mcd(a,b):
    if b==0:
        return a
    return mcd(b, a%b)
```

vs

```
f = lambda a, b: a if b == 0 else f(b, a % b)
```

**Comment by lopezjurip** [comment]
Claro, a PEP8 no le gusta eso. Ver: http://docs.quantifiedcode.com/python-code-patterns/correctness/assigning_a_lambda_to_a_variable.html

Si te gusta el estilo _one-liner_ (como a mi jaja), te recomiendo:

``` python
def f(a, b): return a if b == 0 else f(b, a % b)
```

Los `lambda` están pensados para ser usados de manera [_anónima_](https://en.wikipedia.org/wiki/Anonymous_function) dentro de funciones.

**Comment by ouhenio** [comment]
Perfect, gracias!

**Comment by tamycova** [comment]
A mi también me tira un error cuando uso los otros argumentos de la función print, por ejemplo:

print("hola", end = "") o print("hola", file = f)

por qué?

**Comment by rodolfopalma** [comment]
Tira error por los espacios que tienes alrededor del `=`. Las formas correctas (según PEP8) serían `print("hola", end="")` y `print("hola", file=f)`, respectivamente.

**Comment by tamycova** [comment]
print("\n Sorteo realizado exitosamente. ", end="") - Eso tambien me tira error!

**Comment by lopezjurip** [comment]
No le veo problema alguno de formato:
![image](https://cloud.githubusercontent.com/assets/7570744/10123155/c29289d2-6507-11e5-855d-ebd0d64645e0.png)

**Comment by lopezjurip** [comment]
quizás PyCharm te reclame que `"Sorteo realizado exitosamente"` no está en su diccionario de palabras en inglés.

**Comment by tamycova** [comment]
Es sublime! (con anaconda) , filo jaja 
![screenshot from 2015-09-27 17 28 24](https://cloud.githubusercontent.com/assets/11545206/10125053/3e49ec2a-653d-11e5-8f39-d63e84dd373f.png)

**Comment by felipehv** [comment]
muerte a pep8 ! :D

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

2015-09-27 17:29 GMT-03:00 tamycova notifications@github.com:
