### ISSUE TITLE
¿Diferencia entre el enunciado T03 y main.pdf?

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#235]
Uno pesa más que el otro y sin embargo parecen ser iguales. ¿Cuál debemos usar?

**Comment by lopezjurip** [comment]
Por transparencia, te dejo el `git diff` de las versiones que se subieron:
![image](https://cloud.githubusercontent.com/assets/7570744/10080667/5f3fe010-62c7-11e5-8f05-aec7e08300f0.png)

**Comment by lopezjurip** [comment]
Claramente debes usar el último que se subió al syllabus

**Comment by gebalassa** [comment]
Ok pero por qué no se borró el anterior?

**Comment by lopezjurip** [comment]
Es una actualización, ¿para qué dejar el viejo?
