### ISSUE TITLE
Misil de crucero BGM-109 Tomahawk

### ISSUE THREAD

**Issue by crxzadytho22** [IIC2233-2015-2/syllabus#237]
En el enunciado se especifica esto :

_Este ataque dan ̃a 5 puntos a la resistencia de toda una fila oponente (a lo largo de un eje, usted elige cual)._

pero en la tabla sale que daña 3, a quien le creo ? saludos !

**Comment by AlfonsoIgnacioV** [comment]
Hola! La tabla está errónea (lo preguntaron en otra parte), así que daña 5
Saludos :)

**Comment by aaossa** [comment]
Efectivamente, eso se respodió en #215:

> Para el Misil de crucero BGM-109 Tomahawk, hubo en error de enunciado. Considerenlo como que daña 5.
