### ISSUE TITLE
Duda con la asignacion de daño y destruccion

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#238]
Hola, me quedo una duda con como se maneja la asignacion de daño. El enunciado dice que para destruir un barco, tengo que haberlo golpeado en todas sus casillas. Entonces, si tengo un barco  pequeño de 3x1 y le tiro un misil UGM133 a una de sus casillas ¿Como se asignaria el daño?

No se al final si debo considerar que cada casilla del barco pequeño tiene 30hp (con lo que solo se destruiria el barco si uso 6 misiles UGM133 en cada una de sus casillas), o si la resistencia es unica para el barco pequeño (pero en este caso, al atacar a una casilla 6 veces lo dejaría con resistencia cero, y aun asi no se destruiria porque faltaria atacar a las otras 2). 

Saludos!

**Comment by plorrego** [comment]
Hola, el enunciado fue modificado un par de días después de que se publico. Baja la ultima versión, creo que ahí queda aclarada esa duda. Te adelanto que solo se considera la resistencia del vehículo.

**Comment by AntoniaMendoza** [comment]
Otra duda, una vez que se destruye un vehículo, se "hunde" o quedaría su cadáver estático en su última posición?

**Comment by fgvenegas** [comment]
asumo que eso queda a libertad de cada uno (?) y como los barcos se mueven seria mejor que se hundiera para dejar el espacio libre

**Comment by AntoniaMendoza** [comment]
pero se puede usar como estrategia pal otro lado también

**Comment by silvamatias** [comment]
tengo la misma pregunta @AntoniaMendoza
