### ISSUE TITLE
Numero de piezas 

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#240]
Hola!

Al iniciar el juego cada jugador tiene una pieza de cada tipo? o queda a nuestro criterio? (que hayan por ejemplo 3x barcos pequeños, 2x lanchas, etc) o los jugadores pueden elegir como quieren jugar?

**Comment by eiurrutia** [comment]
Hola!
Queda a tu criterio el número de piezas por tipo. Lo importante es que ambos jugadores tengan la misma cantidad de piezas por tipo al momento de inciar la partida.
Saludos!

**Comment by tamycova** [comment]
Gracias!
