### ISSUE TITLE
Feedbacks T01 pendientes

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#241]
Hubo un problema con los siguientes repositorios que recibieron un feedback vacío de su T01:

```
Fernando17
icrocco
eduguerra
ignaciourzuaf
pcerdam
mdelaf
jgmontoya
jlires
Vince-Valence
jecastro2
cfvilla
```

Se los subiré mañana a sus repositorios a penas reciba los feedbacks completos de los ayudantes.
Disculpen.

**Comment by juancarlostorres** [comment]
Patricio,

Tengo una consulta, en la nota de la tarea me aparece un 1, no estaba tan
bien hecha y la entregue un par de horas atrasadas, pero pensé que no era
tanto como para un 1, para ver en que me había equivocado quise revisar el
feedback pero tampoco esta en mi respositorio, y no estoy en la lista de
alumnos pendientes, que puede ser?

Gracias desde ya.

Atte.,

Juan Carlos Torres

El 24 de septiembre de 2015, 21:48, Patricio López Juri <
notifications@github.com> escribió:

> Hubo un problema con los siguientes repositorios que recibieron un
> feedback vacío de su T01:
> 
> Fernando17
> icrocco
> eduguerra
> ignaciourzuaf
> pcerdam
> mdelaf
> jgmontoya
> jlires
> Vince-Valence
> jecastro2
> cfvilla
> 
> Se los subiré mañana a sus repositorios a penas reciba los feedbacks
> completos de los ayudantes.
> Disculpen.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IIC2233-2015-2/syllabus/issues/241.

## 

Juan Carlos Torres Piérola
Estudiante Ingeniería Civil
Pontificia Universidad Católica de Chile

**Comment by lopezjurip** [comment]
Según veo la mandaste fuera de plazo (puedes ver tu último commit de tu T01 [aquí](https://github.com/IIC2233-2015-2/juancarlostorres-repo/commit/e875d5bee779c4066ff6ede085728c305a5dbe9d.patch)). 

Pasa que hay un _deadline_ y se baja de los repositorios lo que haya a esa hora y se les manda a los ayudantes correctores. 

Manda a recorregir por el Siding.

**Comment by juancarlostorres** [comment]
Si, la mande un par de horas tardes. Entonces la tarea no esta corregida?

Por siding solo pido recorrecion o ademas la debo reenviar a alguna
dirección?

Gracias desde ya Patricio.

Juan Carlos

El 24 de septiembre de 2015, 22:19, Patricio López Juri <
notifications@github.com> escribió:

> Según veo la mandaste fuera de plazo (puedes ver tu último commit de tu
> T01 aquí
> https://github.com/IIC2233-2015-2/juancarlostorres-repo/commit/e875d5bee779c4066ff6ede085728c305a5dbe9d.patch).
> 
> Pasa que hay un _deadline_ y se baja de los repositorios lo que haya a
> esa hora y se les manda a los ayudantes correctores.
> 
> Manda a recorregir por el Siding.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IIC2233-2015-2/syllabus/issues/241#issuecomment-143096603
> .

## 

Juan Carlos Torres Piérola
Estudiante Ingeniería Civil
Pontificia Universidad Católica de Chile

**Comment by lopezjurip** [comment]
Solo di que se entregó fuera de plazo, puedes adjuntar el `SHA` de un commit en específico para que se revise ese (totalmente opcional).
![image](https://cloud.githubusercontent.com/assets/7570744/10091081/1da96036-630d-11e5-9ebf-bf1629c55252.png)

Ahí los ayudantes correctores aplicarán los criterios y descuentos pertinentes.

**Comment by felipehv** [comment]
Yo tambien tengo feedback vacio!

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

**Comment by lopezjurip** [comment]
@felipehv lo comuniqué con el ayudante que te corrigió para que te lo suba a tu repositorio lo antes posible.

**Comment by felipehv** [comment]
Gracias!

Felipe Haase Vargas
Estudiante de  Ingenieria
Pontificia Universidad Católica de Chile

**Comment by spiza** [comment]
A mi tampoco me subieron feedback!

Help!

**Comment by ralvarez94** [comment]
Yo tambien tengo un feedback vacio.

**Comment by lopezjurip** [comment]
Recibí los feedbacks pendientes y fueron subidos a los siguientes repositorios:

```
amroizman
andresfdezc
cfvilla
crxzadytho22
dndelavega
eduguerra
felipehv
Fernando17
icrocco
ignaciourzuaf
ivanwolf15
jecastro2
jgmontoya
jlires
jpjofre94
mdelaf
Niotac
Patoulloa
pcerdam
Pochoclo
ralvarez94
selira
silvamatias
spiza
vclaro1
Vince-Valence  # Pendiente
Zepk
```

Para estas personas le hagan `pull`.

Disculpen, pero parece que algunos ayudantes no saben hacer `git push` a nuestro repositorio privado jaja.

**Comment by jecastro2** [comment]
¿Puede ser que el feedback subido no sea el correcto? pregunto esto porque menciona cosas que no están en mi programa, también, dice que mi programa no se puede iniciar, pero si se inicia. Ademas la nota que aparece no es la misma que la del siding

**Comment by gebalassa** [comment]
Tampoco tengo feedback.
