### ISSUE TITLE
AC08

### ISSUE THREAD

**Issue by felipehv** [IIC2233-2015-2/syllabus#243]
Tengo una duda, la actividad 08 no tenia nota maxima 9  y que cada punto era un punto de la nota?

**Comment by jpjschele** [comment]
Si, las notas van a ser corregidas en la planilla
Y la nota es la suma de los puntajes en sus feedback mas 1 (r1+r2+1)

**Comment by jgmontoya** [comment]
¿Mandamos a recorregir en el siding o esperamos?

**Comment by felipehv** [comment]
Gracias!

Felipe Haase Vargas
Estudiante de  Ingenieria
Pontificia Universidad Católica de Chile

**Comment by jpjschele** [comment]
Tienen que esperar
