### ISSUE TITLE
Dudas puerto y lancha tarea 03

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#244]
Tengo un par de dudas con el puerto:
1. ¿Puede atacar? En el enunciado se dice que el puerto es un vehículo y que todos los vehículos tienen un ataque en común (a excepción de la lancha), pero igual pregunto porque no me queda tan claro.
2. Si no pudiera atacar, ¿Puedo establecer como condición de derrota que te quede solo el puerto y/o la lancha? Digo porque si no pudiera atacar, no hay manera de que ganes solo con el puerto, por lo que el juego perdería el sentido. 
3. ¿Puedo considerar el kit de ingenieros como: añadir 1 de vida, en vez de: reducir en 1 el daño? Para mí la diferencia estaría en que el puerto permitiría aumentar la vida de un vehículo por sobre su máximo inicial, lo que abre nuevas estrategias.
4. ¿Está bien que la lancha solo tenga 1 punto de vida? Según mi punto de vista la gracia de la lancha es salir arrancando después de recibir el primer ataque y hacer que tu oponente pierda el tiempo atacando cerca de donde estaba inicialmente la lancha, pero esa función no la puede cumplir si es destruida al primer golpe. Bajo esa lógica, para que la lancha sea útil debería tener al menos 10 de vida
Saludos y gracias por resolver las dudas anteriores.

**Comment by eiurrutia** [comment]
Hola!
1. Si, considéralo como vehículo y como que si puede atacar, así contarás con el ataque Misil UGM-133 Trident II toda la partida.
2. Hundir el puerto debe ser condición de derrota.
3. No, no puedes aumentar la vida de un vehículo sobre su máximo.
4. Es razonable lo que planteas. Puedes aplicar ese tipo de cambios si estimas conveniente, sólo recuerda especificarlo en el Readme.
Saludos!

**Comment by fgvenegas** [comment]
Aprovecho de preguntar, al final el Trident II lo tienen todos los barcos menos la lancha, y todos menos la lancha pueden atacar? sorry si parece muy reiterativo pero el enunciado esta raro igual :c

**Comment by iacopogarizio** [comment]
Hola @fgvenegas,
sí es tal como lo planteas, todos los barcos tienen el ataque Trident II, excepto la lancha, porque esta simplemente no puede atacar. La idea de la lancha es "distraer" al oponente. ¡Saludos!

**Comment by fgvenegas** [comment]
gracias!
