### ISSUE TITLE
Libreria Curses

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#245]
instale la libreria curses pero cuando intente probar un codigo de internet para ver si funcionaba me tiro  "Redirection is not supported", a un amigo tambien

**Comment by aaossa** [comment]
Si es el `curses` que creo que es,  ¿lo corriste desde consola o algún editor? Lo único que encontré sobre ese error es que podría ser que no lo llamas desde alguna terminal

Relevante: https://docs.python.org/3.4/howto/curses.html

**Comment by fgvenegas** [comment]
Lo corri desde pycharm con varios codigos y no funciono :c

**Comment by aaossa** [comment]
Eso es lo que te digo, ejecuta el archivo de Python **desde consola**, no desde el editor. Logré simular tu error en Sublime Text y luego lo "arreglé". Digo "arreglé" porque no hay un error, solo no ejecutas el script desde donde corresponde:

**Sublime Text 3**
![curses en ST3](https://cloud.githubusercontent.com/assets/10425834/10119389/37bfeab2-646b-11e5-8488-657358aa1afc.png)

**cmd**
![curses en cmd](https://cloud.githubusercontent.com/assets/10425834/10119431/de7c2b18-646b-11e5-8205-a4193bbce832.PNG)

Para ejecutar un codigo desde consola solo tienes que escribir:

```
python miscript.py
```

Según como hayas instalado python puede que no sea necesario escribir `python`.
