### ISSUE TITLE
Duda sobre el mapa y el tablero

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#247]
Hola! Mi duda es la siguiente: se dice en el enunciado que hay un tablero (que incluye aire y mar), pero lo que yo no entiendo es si este tablero es único o hay uno para cada jugador. En el primer caso, el tablero tendría a ambas flotas y por lo tanto, eventualmente podrían chocar y esto quizá podría dar cierta información con respecto a la posición de un contrincante si es que hay un movimiento prohibido. ¿O, eventualmente pueden estar en el mismo espacio sin dar información de este tipo (que se encuentran en el mismo lugar)?
Mientras que en el segundo caso no existiría esta posibilidad dado que al estar en "mares separados" y aires también "separados", no podrían chocar.  
Muchas gracias
Saludos :)

**Comment by crabarca** [comment]
La parte 3.1 del enunciado dice que ambos jugadores tienen tableros separados, ambos jugadores tendrian un sector de mar y sector tierra
Saludos
