### ISSUE TITLE
No me "pesca" la importacion

### ISSUE THREAD

**Issue by spiza** [IIC2233-2015-2/syllabus#248]
Hola! Tengo un problema, y la verdad no tengo idea de cómo resolverlo.

Cuando importo un módulo a otro módulo ( from modulo import *), no me funciona!

Explico lo que pasa. Tengo en un módulo todas las clases de un tipo. En otro modulo, importo el modulo (así como lo hice arriba), y cuando quiero instanciar alguna clase, PyCharm no me genera el autorelleno y además me subraya el nombre del modulo en rojo. 

Cuando ejecuto el código, me funciona todo bien, pero es bastante tedioso para completar todos los nombres.

Y lo otro, es que cuando hago "from .modulo import *", me funciona el autorelleno, pero me falla al ejecutar  :P 

Help!

**Comment by lopezjurip** [comment]
En qué archivo en particular? para echarle una mirada en tu repositorio

**Comment by spiza** [comment]
El archivo vehículos, con el archivo ataques

**Comment by lopezjurip** [comment]
Cloné tu repositorio y puedo hacer los imports sin ningún problema. 
Al parecer PyCharm revisa los módulos considerando la raíz donde abriste el programa.

Si abres PyCharm en tu carpeta `T03` desaparece el problema.

![image](https://cloud.githubusercontent.com/assets/7570744/10120493/021bb810-6492-11e5-8769-34f4d43c076c.png)

También probé en Atom y ese no presente esta problema.

PD: Tu código está muy mal formateado, no estás siguiendo PEP8. Te recomiendo:

![image](https://cloud.githubusercontent.com/assets/7570744/10120495/49d5d6d6-6492-11e5-8395-af0ea653d306.png)

**Comment by spiza** [comment]
Muchas gracias señor patiwi!!!
Me funcionó tal cual lo dijiste tú!

PD: En algún minuto pensé que tenía que dejar dos líneas en blanco entre que definía la clase, y el primer método.. Gracias!!

**Comment by andresespinosapc** [comment]
Hola, yo sé como hacer arreglarlo sin tener que abrir Pycharm desde esa carpeta. En Pycharm haces click derecho en la carpeta en la que están los módulos que quieres importar y pones Mark Directory As -> Sources Root. Ahí te debería captar bien y autorrellenar.
