### ISSUE TITLE
Duda Atom

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2015-2/syllabus#25]
Tengo una duda: acabo de instalar Atom y todo parece funcionar bien, excepto que cuando trato de ocupar el comando input, no se puede escribir, aparece como un reloj de arena pero no sigue ejecutando el codigo.

**Comment by lopezjurip** [comment]
Ni Atom ni Sublime aceptan inputs de usuario. Puedes ejecutar tu script `.py` desde la consola/terminal y ahí si funciona. 

O simplemente _hardcodeas_ los valores en el script y así evitas pedir inputs del usuario.

**Comment by caackermann** [comment]
Y esto deberia ser un problema a lo largo del curso? Como para no ocupar Atom? O no se ocupan tanto los inputs de usuario?

**Comment by lopezjurip** [comment]
Casi nunca pedimos inputs del usuario, así que no hay problema :+1:

**Comment by bcsaldias** [comment]
Recomiendo usar PyCharm para que desarrolles las competencias de debuggeo..
Podrás estar un cojo en esto si no lo usas, y es uno de los objetivos del
programa. Aun así es tu decisión !

Saludos !
Belén

2015-08-20 13:47 GMT-04:00 Patricio López Juri notifications@github.com:
