### ISSUE TITLE
Archivo recorrección T01

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#251]
En el Siding se pide adjuntar un archivo que permita explicar mis motivos, pero no creo que tenga que subir nada especial para hacerlo. Al tratar de enviar la solicitud me pide subir un archivo. Intenté subir un .txt vacío pero sale un mensaje diciendo que el archivo no fue recibido, y luego en cuestionarios no aparece como que ya lo envié.

**Comment by bcsaldias** [comment]
Hola !

Umm... que raro, intenta adjuntarlo de nuevo :) Creo que Siding no da la opción de dejar campos en blanco :'( .

Saludos !
Belén
