### ISSUE TITLE
tablero

### ISSUE THREAD

**Issue by sebawarrior** [IIC2233-2015-2/syllabus#253]
Hola, con respecto a la tarea 3, el mapa dice que debe ser de nxnx2, pero antes de comenzar debo pedirle al usuario que ingrese ese "n", cierto?

**Comment by sebawarrior** [comment]
Y cada tipo de vehículo de estar sólo una vez en el mapa?, o puede repetirse a gusto del usuario?

**Comment by tamycova** [comment]
#210 #240 @sebawarrior

**Comment by sebawarrior** [comment]
Gracias Tami!!! te pasasteee
