### ISSUE TITLE
ataque Misil de crucero BGM-109 Tomahawk

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#254]
Este ataque daña 5 a la resistencia de cada objetivo encontrado, pero si mi ataque es a la fila L y mi oponente tiene un barco pequeño en esa fila donde su resistencia dado el transcurso del juego es menor o igual a 15, yo atacaria cada una de las casillas de ese barco, por lo cual se hundiria dado que perdio su vida entonces este ataque si mostraria las coordenadas del barco que hundio y el tipo de barco?

**Comment by fgvenegas** [comment]
me cuelgo para preguntar si el Tomahawk golpea en 3 partes a un barco, el hace 15 o sigue siendo solo 5?

**Comment by icrocco** [comment]
Repito pregunta de @fgvenegas

**Comment by eiurrutia** [comment]
Queda a criterio de ustedes la efectividad del ataque. Puede afectar como si se le diera a una sola casilla del barco (para que el ataque no sea tan potente) o bien a todas las que el ataque abarque. Si se debe notificar el hundimiento del barco enemigo pero también queda a criterio de ustedes revelar a que tipo de barco corresponde específicamente.
