### ISSUE TITLE
Metodo o funcion? PEP8

### ISSUE THREAD

**Issue by SHGoldfarb** [IIC2233-2015-2/syllabus#256]
Tengo una duda, tengo una clase que tiene un método en el cual nunca usa _self_, es decir, podria escribirse como funcion (fuera de la clase). Pero es una funcion que solo le sirve a esa clase, y yo se que nunca la voy a utilizar para otra cosa fuera de los metodos de dicha clase. Entonces, la dejo como método o la escribo como funcion? (pep8 me tira "method could be a function")

**Comment by lopezjurip** [comment]
## Métodos de clase o estáticos.

Un método de clase, como su nombre lo dice, es **de la clase** nombrada como `cls`. Los métodos típicos que uno hace con `self` son **métodos de instancia**, dependen de la instancia llamada `self`.

Por otra parte, uno puede declarar métodos estáticos que están en una clase, pero no dependen de esta. Quizás esto estés buscando.

Ejemplo:

``` python
class Math:
    @staticmethod
    def raiz_cubica(numero):
        return numero ^ 1/3
```

y lo usamos como:

``` python
resultado = Math.raiz_cubica(9)
# Notar que no instanciamos Math
```

**Comment by SHGoldfarb** [comment]
Si! Me referia a lo que pusiste en el ejemplo :) Mi pregunta es: ¿Que tan correcto es declarar esos metodos dentro de la clase, considerando que son estaticos, versus declararlos fuera como una funcion? Teniendo en cuenta que ese metodo/funcion solo es llamado por instancias de la clase, y nunca por algo externo.

**Comment by lopezjurip** [comment]
En el mismo ejemplo, si los declaras dentro basta con importar `from math import Math` para usarlo externamente (si lo llegases a necesitar).

Si lo declaras afuera, sería `from math import Math, raiz_cuadrada` y sería dos cosas completamente aparte.

Ahora, **es un tema de modelación**. Tienes que preguntarte si de verdad tiene relación con la clase o es algo ajeno y utilitario.

**Comment by SHGoldfarb** [comment]
Ok, gracias!
