### ISSUE TITLE
Duda excepciones

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#258]
No tengo claro cuando tengo que trabajar los manejos de excepciones, es necesario usarlos en los inputs para que el usuario entregue lo que se pide, en ocasiones como al mover los barcos y evitar con eso que se salga de los bordes?. Necesito tirar errores? lo que implicaria que el programa se caiga.  
De antemano gracias

**Comment by plorrego** [comment]
La idea de las exepciones es evitar cualquier situacion que haga que el juego se caiga o no funcione correctamente. Con esto puedes tirar errores que expliquen que es lo que esta fallando pero sin que el programa se caiga, o decirle al programa que hacer en caso de cierto error especifico.
