### ISSUE TITLE
Actividades propias

### ISSUE THREAD

**Issue by spiza** [IIC2233-2015-2/syllabus#26]
Hola, quería saber si podemos subir nosotros mismos la resolución de las actividades al foro. Lo digo porque por ejemplo yo ahora hice la actividad 3, y creo que quizás a alguien le pueda interesar ver mi código, así como quizás yo quiera en un futuro ver código.

Saludos :+1:

**Comment by micostabal** [comment]
Buena idea, de repente no se alcanzan a hacer enteras en clases, por lo que sería bueno para corregirlas y comparar.

**Comment by bcsaldias** [comment]
Estimados,

No están autorizados ni para subir código de sus tareas ni código de sus
AC's.

Cualquier pregunta/propuesta podrían enviármela al correo, así no olvidaría
estudiarla.

Cualquier posibilidad que se abra se las informaré,
Saludos !

2015-08-23 21:55 GMT-04:00 Martín Ignacio Costabal Castillo <
notifications@github.com>:
