### ISSUE TITLE
Duda Atom

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#260]
Ayer descargue Atom para probarlo como IDE y me surgieron algunas dudas de su funcionamientos (actualmente uso pycharm) así que invoco a @mrpatiwi que si no me equivoco lo utiliza 
- Me corrige Pep8? 
- Respecto a las importaciones, yo tengo por ejemplo una carpeta Clases, dentro de ella tengo la carpeta Autos (que tiene un archivo autos.py) y la carpeta Trenes (que tiene un archivo trenes.py) cuando en pycharm creaba un project, para importar los datos de trenes.py hacía

`from Clases.Trenes.trenes import *`

Pero cuando abrí esos archivos en Atom no me resultaba importarlos
Tendrá que ver eso con que es un proyecto de pycharm ? (Mi T01 y T02 las importaciones las hacía así sin problemas) 
- Si comencé mi tarea en pycharm, la termino en pycharm o puedo cambiarme a Atom sin que pase nada ?  (En referencia a lo anterior de las importaciones)  
- Se puede aumentar el máximo de 79 caracteres por línea D:?

De ante mano muchas gracias :B

**Comment by fgvenegas** [comment]
por cierto cuando abro atom ahora me sale esto :( 

![image](https://cloud.githubusercontent.com/assets/13748708/10164993/af64e3a6-66b4-11e5-9c61-46e50c474616.png)

He navegado hasta el averno buscando info y no lo he podido solucionar

**Comment by lopezjurip** [comment]
pip install -U pylint

**Comment by lopezjurip** [comment]
- Para que te corrija PEP8, necesitas instalar [atom-beautify](https://atom.io/packages/atom-beautify).
  - Necesitas además instalar `autopep8` por medio de `pip`.
- Un proyecto debe ser agnóstico de la IDE que uses. Si no funciona en uno, puede que estés haciendo algo mal.
- Si puedes aumentar el largo de la lineas. Tienes que ir a las configuración de `language-python` (paquete que viene por defecto).

**Comment by fgvenegas** [comment]
Yap, revisare lo segundo que dijiste, pero lo de pylint no se soluciono, he visto en foros que empiezan a modificar archivos de atom y ahi ya me perdi :c  
Gracias por lo demas!

**Comment by fgvenegas** [comment]
P*ta bida 

![image](https://cloud.githubusercontent.com/assets/13748708/10167760/d4aa1e1c-66c1-11e5-9ac1-6fac612e58be.png)

**Comment by lopezjurip** [comment]
dice que `pylint` no está en tu path, trata de reiniciar tu terminal y Atom. Si no funciona, reinicia el PC. Windows no suele comportarse bien con el `$PATH`.

**Comment by fgvenegas** [comment]
nada :c bueno no importa si te pillo algun dia te pregunto, gracias!

**Comment by fgvenegas** [comment]
Despues de mucho tiempo logre hacer funcioanrlo :+1: pero como ejecuto codigos que funcionan con inputs? siempre desde la consola? porq al correrlos en atom solo queda esperando..

**Comment by aaossa** [comment]
Algunos editores como Sublime Text y Atom no soportan input de usuario

**Comment by fgvenegas** [comment]
Entonces solo me queda llorar ?

**Comment by lopezjurip** [comment]
_La terminal es mi copiloto_

Los ☠`h4ckers_` la usamos para todo :+1:
