### ISSUE TITLE
Duda orientación de las piezas

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#261]
¿Es necesario dar la posibilidad al usuario de rotar las piezas a la hora de ponerlas? Ya que no lo explicita el enunciado, pensé que podría estar bien si no daba esta posibilidad (y ponerlo en el README que las piezas tienen un tamaño y orientacion predefinida). ¿O es necesario que mi programa implemente la rotación al principio? Muchas gracias.

**Comment by dpassi** [comment]
Buena!
Tengo entendido que la 'orientacion' que nos dieron es cualquiera.
Hay piezas que dice son de 3x1 y otras que dicen son de 2x3.
Al final estos numeros son solo areas y no dicen para donde esta orientado el vehiculo, por eso es necesario preguntar al jugador como posicionar la pieza...

**Comment by plorrego** [comment]
Tal como dice diego, las dimensiones entregadas representan tamaño y no orientacion. Al comenzar el juego se debe definir la orientacion pero desde ese momento queda fija hasta el final del juego.
