### ISSUE TITLE
Fecha de entrega Tarea 3

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#262]
A fecha 30/09 a las 13:20 PM bajé un enunciado "actualizado" de la Tarea 3 en donde se aclaran algunos aspectos (doy las gracias por ello), pero en este enunciado no se actualizó la fecha de entrega de la Tarea, de manera que se sigue viendo para el domingo 04 de Octubre - 23:59 PM. 
¿Asumo que se les olvidó cambiarlo y que la fecha de entrega es el míercoles 7 de octubre- 23:59 PM, tal y como se indicó por correo? Disculpen si la duda es un poco tonta, pero prefiero prevenir =)

**Comment by lopezjurip** [comment]
Miércoles 7 de octubre a las 23:59 hrs, está en el Siding. Lo voy a poner en el calendario del syllabus :+1: 

Relacionado con #249
