### ISSUE TITLE
¿Mañana hay AC?

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#263]
No sale nada calendarizado para mañana y tampoco hay nuevo material de clases en la carpeta. ¿De nuevo testing?

**Comment by robocop6** [comment]
Hola! La Actividad de mañana, como tú dices, es de testing. Esta vez se enfocará en **Pytest**, por lo que deben instalarlo para poder probar sus códigos.

Puedes hacer
`pip install -U pytest`
en la terminal.

Saludos!
