### ISSUE TITLE
Problema al intentar instalar PyTest

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#268]
Hola! Tengo el siguiente problema cuando intento instalarlo a través de la consola escribiendo
pip install -U pytest
me aparece un error de que no puede importar un tal **main**. ¿A qué se debe esto? (Me gustaría especificar más sobre este error pero se vería horrible). ¿Qué puedo hacer en este caso? 
Muchas gracias de antemano
Saludos!

**Comment by lopezjurip** [comment]
¿Windows, OSX o Linux?

**Comment by yackpott** [comment]
si es mac intenta con pip3, a mi me funciono
pip3 install -U pytest

**Comment by AlfonsoIgnacioV** [comment]
es Windows (lo intenté también con pip3 y me tira el mismo error :( )
Gracias

**Comment by lopezjurip** [comment]
Muéstranos el error

**Comment by AlfonsoIgnacioV** [comment]
Ojalá se vea bien, es esto:
<?php
    Traceback (most recent call last): 
        File: "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main
            "__main__", mod_spec)
        File: "C:\Python34\lib\runpy.py", line 86, in _run_code
            exec(code, run_globals)
        File: "C:\Python34\Scripts\pip.exe__main__.py", line 5, in <module>
    Import Error: cannot import module 'main'
?>
