### ISSUE TITLE
Duda tablero aereo

### ISSUE THREAD

**Issue by silvamatias** [IIC2233-2015-2/syllabus#270]
Mi duda es que si los aviones solo atacan y no reciben daño entonces para que sirve este tablero..a lo que voy es porque el jugador posiciona sus aviones en ese tablero si no importa donde estos se encuentren?

**Comment by plorrego** [comment]
El area que revela el avion explorador esta directamente relacionada con su posicion. La posicion de los otros aviones es relevante porque no puede coincidir con la del explorador (si no chocarían).
