### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#272]
El radar tiene que se una especie de mapa que se muestre donde se ha atacado ? o puede ser una lista por ejemple de "Se ataco en x,y y paso tal cosa"

**Comment by gebalassa** [comment]
Siguiendo el enunciado, pues cualquiera de los dos.

Lo importante es que puedas (por alguna razón que me cuesta entender) volver a un punto en el pasado y ver los ataques **sólo** hasta ese punto. Supongo que la única finalidad de esto es probarnos en estructuras de datos o algo así.
