### ISSUE TITLE
¿Es posible testear cualquier función?

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#273]
Para la tarea 3, o más generalmente para cualquier caso en el que deba testear funciones, quiero saber cuáles son las funciones que debo testear. Me imagino que debo probar la mayor cantidad de mi código posible (por no decir todo), pero tengo dudas con dos casos específicos. 
Por una parte, tengo "funciones de validación" (f1), que piden un input al usuario, aplican otra función (f2) y retornan el valor solo si este es válido, en caso contrario, imprime un error y vuelve a pedir el valor. Para este caso, ¿Debo testear ambas funciones? ¿Solo f2? ¿Hay una forma de testear f1 sin ingresar las entradas manualmente?
El segundo caso que tengo es para funciones que solo imprimen algo, sin retornar un valor en especial. ¿Puedo comprobar que se hizo correctamente la impresión sin tener que hacerlo yo mismo de forma visual? ¿Puedo hacer eso de forma "interna" (sin que se imprima en la consola al ejecutar el test)?
De antemano gracias por resolver las dudas.

**Comment by lopezjurip** [comment]
Deberías testear solo la `f2`. La `f1` no tendría mucho sentido y sería complicarse demás.

Sobre lo segundo que preguntas. Suelen hacerse:
1. Que la función retorne un `Error`. Para testearla solo habría que revisar si lo retornado es `None` o no. Esto se suele hacer bastante en el lenguaje  [`Golang`](https://blog.golang.org/error-handling-and-go)
   
   ``` python
   err = funcion1()
   assert err is None  # o sea, no retorna error.
   ```
2. Otra opción es que retorne un `bool` (`True` o `False`).
3. Otra opción es que la función arroje una `Exception` si algo sale mal. Entonces la testeas revisando si tira la excepción o no. En algunos lenguajes más estructurados incluso se declara en la firma del método qué excepción tiran.

``` java
/* Ejemplo en Java */
public void writeList() throws IOException, IndexOutOfBoundsException {
    // ...
}
```

**Comment by fagomez2** [comment]
Gracias por la respuesta!! Todo claro ahora =)

**Comment by fgvenegas** [comment]
Que pasa si tengo una funcion f(0) que trabja con el valor que recibe de f(1)(mediante un input que hace f(1)), para testearlo y poder entregarle un valor fijo con el que trabaje, como dandole un input fijo por asi decirlo, no se si se entiende
