### ISSUE TITLE
[off-topic] Ruby

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#275]
Hola aprovechando los conocimientos de los mayores queria preguntarles porque en todas partes dicen que Ruby es como el lenguaje de progrmacion del siglo 21 o porque es tan bueno, a futuro entre python y ruby que es mejor saber a profundidad?

**Comment by lopezjurip** [comment]
### Python

**Python** es el lenguaje científico por excelencia, por esto es importante que se use en Ingeniería. Se usa harto para análisis de datos, inteligencia artificial, machine learning, etc.

En mi opinión lo fuerte de Python son los _iteradores/generadores_ y toda la parte de _programación funcional_. También me gusta que sea muy explícito y uno tenga harto control sobre este.

### Ruby

**[Ruby](https://www.ruby-lang.org/)** es muy flexible y _"mágico"_. Se usa principalmente para aplicaciones Web (**Github** está escrito en [Ruby on Rails](http://rubyonrails.org/)) y para administradores de paquetes. 

En mi opinión tiene mejores herramientas para la programación funcional, tiene buen uso de _symbols_, tiene una sintaxis más intuitiva y los _[mixins](https://es.wikipedia.org/wiki/Mixin)_ son muy útiles. Lo malo es que a veces es muy mágico y cuesta ver qué está pasando por debajo, lo bueno es que uno programa super rápido.

### Javascript

Aprovecharé de hablar de **[Javascript](https://www.javascript.com/)** que es el lenguaje más universal. ¿Por qué? **Porque es el único lenguaje que puedes correr en los navegadores (Chrome, Firefox, Safari, etc)**

Puedes programar de todo en JS: aplicaciones web (cliente y/o servidor), juegos, aplicaciones móviles, lineas de comandos, aplicaciones para escritorio, etc.

Además es el lenguaje que tiene más librerías/paquetes: https://www.npmjs.com/ y se administran muy bien. Por ejemplo [Atom](http://atom.io) :heart: está escrito en Javascript y todos sus plugins también

En mi opinión su fuerza es la programación funcional y la gran flexibilidad del lenguaje (puedes programar en cualquier estilo). Lo malo es que puede ser un poco desordenado si uno no tiene cuidado.

Entre los tres **el que tiene mejor rendimiento es Javascript** porque corre sobre [NodeJS](https://nodejs.org/en/), el _runtime_ que usa el [motor V8](https://en.wikipedia.org/wiki/V8_%28JavaScript_engine%29) sacado de Google Chrome. Python y Ruby tienen performance similar, pero ambos son más o menos lentos.

**Comment by lopezjurip** [comment]
Finalmente, los lenguajes son herramientas y uno tiene que saber escoger correctamente para cada problema. 

En mi opinión **Javascript es el lenguaje del momento** y el más útil para cualquier propósito. Casi todas las aplicaciones web en Ruby se están migrando a Javascript.

Python seguirá siendo el lenguaje científico, hasta que sea reemplazado por [Julia](http://julialang.org/) o eventualmente por el mismo Javascript.

**Comment by fgvenegas** [comment]
Dude sabes mucho Ajaja gracias por toda las respuestas !

**Comment by felipehv** [comment]
Javascript es la luz <3

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

**Comment by fgvenegas** [comment]
@mrpatiwi es necesario saber HTML y CSS para aprender JavaScript? y que opinas de  PHP?

**Comment by aaossa** [comment]
No es necesario saber HTML y CSS :grin:, pero si puedes aprenderlos también es mucho mejor (léase _fundamental_) para el desarrollo web. Sobre PHP no tengo una opinión muy fuerte así que Pato les responderá.

Sobre lo que les dijo Pato: Estoy de acuerdo con todo. Lo que más he leído es que **JavaScript** es el lenguaje del futuro (encontrarás mil argumentos por internet), y con mayor razón desde que llegó a las aplicaciones de escritorio.

**Comment by otro-felipe** [comment]
Yo tenía entendido que programar aplicaciones móviles en javascript tenia cierta desventaja contra programarlas en lenguaje nativo, cosas como que tiene un diseño menos característico que el que tendría una aplicación en lenguaje nativo (probablemente esté mal informado respecto a eso y aprovecho de resolver mis dudas). 
¿Javascript ofrece las mismas funcionalidades que ofrece el lenguaje nativo? (esto lo digo pensando en que veo difícil hacer un BroadcastReceiver en JavaScript, pero supongo que es posible o existe alguna forma de hacer lo mismo)
Además está el tema de los SDK. Por ejemplo: Samsung tiene SDKs para sus dispositivos (SmartWatches, Spen, sensores incorporados en los teléfonos Samsung, etc.) que están hechos Java. ¿Se espera que en un futuro estas librerías estén disponibles en javascript también?

**Comment by lopezjurip** [comment]
1. Como dice @aaossa, no es necesario saber HTML ni CSS si quieres hacer lo que ahora haces en Python pasarlo a JS. Esto se hace trabajando con NodeJS. Si quieres hacer interfaces gráficas, estás condenado a saberlo jaja. Pero ahí uno usa frameworks de estilo como Bootstrap o Material Desing y frameworks de aplicación como AngularJS, React, etc.
2. ODIO PHP :anger:, es un lenguaje (prehistórico) para aplicaciones web del lado del servidor. Es mejor usar Ruby on Rails, Express (en Javascript), etc,
3. @MainScientist, claro, hay perdida de performance. Pero cuando tienes que hacer una app rápidamente y lo más universal posible, es mejor inclinarse por JS. Hay buenas alternativas como [React Native](https://facebook.github.io/react-native/) o [Ionic](http://ionic.io/). Sobre las API en específico de la plataforma, desconozco el estado actual de eso.
