### ISSUE TITLE
Respecto a test 

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#277]
Si tengo una funcion F1, que llama a varias otras funciones(F2, F3, F4), con probar  F1 puedo asumir que las otras tambien estan bien ? gracias

**Comment by gebalassa** [comment]
Si la primera te entrega el resultado esperado, ¿Por qué habrían de estar mal las funciones anexas?
Podrías, utilizando la primera, intentar de que se equivoque en las posteriores. Si funcionan todas, entonces no hay problema.

**Comment by fgvenegas** [comment]
yap, y en el tester tengo que crear

`def test_funciona_la_funcion1()` y `def test_no_funciona_la_funcion1()` o basta con crear uno y hacer todos los assert necesarios ahi? se que es lo mismo pero lo pregunto mas como por el lado estetico/eficiente

**Comment by lopezjurip** [comment]
Cómo dice @gebalassa, si hace lo que tiene que hacer y de manera muy directa, eso estaría bien.

Ahora, si la función es muy compleja (ver [Complejidad Ciclomatica](https://es.wikipedia.org/wiki/Complejidad_ciclom%C3%A1tica)), es decir, con muchos `if` y demasiadas variaciones para distintos inputs, lo mejor sería testear la `F2`, `F3` y `F4`.

Sobre lo segundo que preguntas, queda como decisión de diseño tuya.

**Comment by gebalassa** [comment]
La idea del testing es que no tengas que hacer `def test_no_funciona_la_funcion1()`, puesto que todos los test deberían salir correctamente.

**Comment by fgvenegas** [comment]
Yap gracias por lo anterior, lo último, si tengo una función "atacar", que (inventando) baja el hp de un barco, gira un barco, y le sube la vida a otra barco, y retorna las coordenadas donde atacó, todo eso cada vez que la ejecuto, en el test debo asegurarme (con asserts) que todo eso se esté cumpliendo o me debo preocupar solo del retorno ?
