### ISSUE TITLE
Organización e Interacción entre Módulos / Uso de Inputs()

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#278]
¡Saludos!
###### Dos preguntas importantes:

**1)** _¿Qué esquema organizacional conviene usar?_ 

Actualmente estoy intentando hacer un módulo "main.py" con una clase "Interfaz" que se encargue de:
- A] La interacción con el usuario (recibir los "inputs" y levantar Exceptions, básicamente)
- B] Importar todos los módulos dentro de esta clase (los cuales, obviamente, también se importan entre ellos) e instanciarlos/modificarlos cuando corresponda.

Aunque esta forma en particular no me parezca mala, si existe alguna otra forma más eficiente de organizar, esquematizar y comprender el programa sería ideal.

**2)** _Planeo que toda interacción usuario/juego sea con **input()**_

Escuché por ahí que comentaban que era mala idea. Según yo, la ventaja principal de éste método es evitar darle la oportunidad al usuario de escribir comandos directamente al programa, evitándome así tener que impedir que instancie clases abstractas (ej: Vehículo) o que cambie valores que no corresponden (ej: La vida de un barco), etc. 

Los "inputs" se usarían con un **loop de tipo "while"** que **se mantiene hasta que no se cumpla alguna condición, definida por mí.** Si el usuario escribe cualquier cosa que no corresponde, puedo inmediatamente levantar un error y devolverlo al inicio del loop, hasta que ingrese algo que corresponde.

Con esto me refiero a que, si en un determinado momento solo quiero darle las opciones de

1) Mover una pieza
2) Cerrar el juego (disponible siempre)

este método me lo hace muy fácil. Si permito el uso de comandos, le estoy dando al jugador **libertades que no le corresponden**, por lo menos para el contexto de este juego (no así para alguna aplicación científica que requiera mayor libertad en la modificación de valores, por ejemplo).

Por el otro lado, mi compañero me dijo que un ejemplo de la ineficiencia de este sistema sería la dificultad de realizar un buen testing a comandos basados en inputs(), argumento que, la verdad, no me convence, pues los caminos que el jugador puede elegir los puedo limitar con mucha mayor facilidad que permitiéndole usar comandos (acto que finalmente me obligaría a testear mucho más).

Cualquier explicación de por qué este es un camino inadecuado, y que alternativa resultaría mejor, será agradecida.

_Gabriel.-_

**Comment by lopezjurip** [comment]
1. Dentro de la Ingeniería de Software, existe un [patrón arquitectónico](https://es.wikipedia.org/wiki/Arquitectura_de_software) llamado [Model View Controller (MVC)](https://es.wikipedia.org/wiki/Modelo%E2%80%93vista%E2%80%93controlador). Este propone una manera de organizar el código similar a lo que tienes ahí. 
2. No te entendí mucho. Pero sí, lo correcto es hacer un `while` hasta que el usuario escriba `exit`, por ejemplo. No creo que sea bueno permitir al usuario escribir código de Python y ejecutarlo inmediatamente.

**Comment by oatorresuc** [comment]
Yo tengo la misma duda, porque que pasa si el usuario tiene que escoger
entre 1) moverse o 2) atacar y yo pongo un while de que si su input es
distinto de 1 y 2 le vuelva a pedir el input, asi el programa nunca se cae,
hacer eso esta mal?

**Comment by lopezjurip** [comment]
Está bien. Yo haría algo así para una consola interactiva:
1. Defino función que pregunta el nombre del usuario

``` python
def setup_name():
    return input("Name?\n>> ")
```
1. Defino función que pregunta por la edad

``` python
def setup_age():
    user_input = ""
    while user_input.lower() != 'cancel':
        if user_input.isdigit():
            return int(user_input)
        user_input = input("Age?, type 'cancel' to return to main menu\n>> ")

    return None
```
1. Iniciamos el "menú principal"

``` python
name = ""
age = None

user_input = ""
while user_input.lower() != 'exit':
    if user_input.lower() in ["1", "1)", "name"]:
        name = setup_name()
    elif user_input.lower() in ["2", "2)", "age"]:
        age = setup_age()

    user_input = input("Select: 1) Name, 2) Age \nType 'exit' to terminate\n>> ")

print("Name:", name, "|", "Age", age)
```

#### Al usarlo en la terminal

Los `>>` indican que el usuario tiene que escribir.

```
Select: 1) Name, 2) Age
Type 'exit' to terminate
>> Name
Name?
>> Patricio
Select: 1) Name, 2) Age
Type 'exit' to terminate
>> 2
Age?, type 'cancel' to return to main menu
>> lorem ipsum
Age?, type 'cancel' to return to main menu
>>
Age?, type 'cancel' to return to main menu
>> 21
Select: 1) Name, 2) Age
Type 'exit' to terminate
>> 3
Select: 1) Name, 2) Age
Type 'exit' to terminate
>> exit
Name: Patricio | Age 21
```

**Comment by gebalassa** [comment]
Muchísimas gracias. Lo del MVC habrá ya que aplicarlo posteriormente, pero gracias por el ejemplo.

Cualquier "tip" que se pueda aplicar de forma inmediata respecto a la organización que estoy usando sería ideal.
.
Gabriel.-
