### ISSUE TITLE
Duda tarea parte 5 Estadísticas

### ISSUE THREAD

**Issue by silvamatias** [IIC2233-2015-2/syllabus#279]
En el enunciado dice: "Barco con más movimientos" 
Con movimientos se refieren movimientos del barco fisicamente( de un punto a otro) o también consideran como un movimiento el ataque (como una especie de "movimiento" que hizo mi pieza en el tablero) Muchas gracias

**Comment by bamavrakis** [comment]
Movimiento se refiere solamente a desplazamiento.
Saludos!
