### ISSUE TITLE
Materia :D

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#280]
¿Existe alguna posibilidad de poner letras en negritas, subrayadas, cambiar la fuente o lo que sea en python? (La idea es resaltar ciertas cosas de un mensaje que aparezca en la consola)

Busqué en internet y me aparece algo de chr(27), para cambiar el color, lo probé pero nada :( jajaja

Agradezco cualquier ayuda ya que lo quiero implementar en la Tarea 3.

Saludos!

**Comment by fgvenegas** [comment]
Me cuelgo porque tambien busque y llegue a los de chr(27) XD pero en consola no se aprecia :c

**Comment by aaossa** [comment]
Quizás les interese [**colorama**](https://pypi.python.org/pypi/colorama) (permitido según #252) :grin: En las imágenes de ejemplo se ve que pueden usarlo para colores y para _negrita_, pero para Windows parece no poder usar _negrita_.
