### ISSUE TITLE
Testing.. Nuevamente

### ISSUE THREAD

**Issue by spiza** [IIC2233-2015-2/syllabus#281]
Tengo una pregunta!!

Lo que sucede es que mis funciones no se pueden testear "mal".

Me explico, en las opciones donde pido inputs, tengo un manejo de excepciones de tal forma que no se pueden ingresar datos mal, y si se hace asi, entonces la excepción pide nuevamente inputs..

Bajo esa lógica, si ingreso un valor que se que fallara, mi manejo de excepciones para que entre en un loop infinito :warning: 

Cómo se le hace?

**Comment by ghost** [comment]
@jecastro1 @mbucchi @mrpatiwi @mjjunemann @robocop6 @aaossa

**Comment by lopezjurip** [comment]
La podrías testear como _la interaccion con el usuario no arroja exceptiones no capturadas_.

Ahora... no sé si valga la pena testear eso. Se debería testear qué pasa cuando un usuario pone cierto input en una función que lo recibe.

**Comment by trencoret** [comment]
@mrpatiwi Si restrinjo a que solo le entre el input que yo quiero a la funcion, y esta me va a retornar lo esperado, debria testearlas? Esa funcion pasaria a contar dentro de las qeu deberiamos haber testeado? (>50%) 

Tambien me pasa que al hacer from main import funcion, me empieza a correr todo el programa, como lo hago para probar solo la funcion?

**Comment by eavildosola** [comment]
@trencoret esto pasa con python, pero lo que tienes que hacer para evitarlo es que en tu archivo main ocupes:

```
if __name__=="__main__":
   # cosas que quieres que no pasen cuando importes main pero si cuando corres main

```

**Comment by trencoret** [comment]
gracias!

**Comment by trencoret** [comment]
@eavildosola Que pasa si mis funciones dependen del turno, pero la variable turno se controla desde el main por decirlo, no puedo acceder a ellos por la clase o metodo en particular. Puedo ponerle un contadror de turno dentro para el test y despues lo comento?

**Comment by eavildosola** [comment]
Exacto tienes que crear un contador para hacer el test y que te sirva solamente para ese propósito
