### ISSUE TITLE
Testing funciones con input con mock

### ISSUE THREAD

**Issue by sebamenabar** [IIC2233-2015-2/syllabus#282]
Para testear funciones que utilizan input podemos utilizar la libreria mock? Buscando encontre que la solucion seria de esta forma:
![captura de pantalla 2015-10-04 a las 21 05 20](https://cloud.githubusercontent.com/assets/13748963/10271094/17cc78f4-6ae4-11e5-99c8-0d9495b1cf2f.png)
Y en caso de que se pueda, se aplicaria como mock.patch('**builtin**.input',return_value=loquesea)?

**Comment by tamycova** [comment]
comento para saber

**Comment by lopezjurip** [comment]
@IIC2233-2015-2/ayudantes-tareos ?

**Comment by sebamenabar** [comment]
ya cache como se hace, para pytest se usa el monkeypatch, se implementa asi:

def test_funcion(argumentos, monkeypatch):
monkeypatch.setattr(builtins, 'input', lambda : "texto")

el monkeypatch va tabulado, no me salia, y se puede "sobreescribir" cualquier funcion
en builtins va como el modulo donde esta la funcion a sobreescribir y creo que no necesariamente la funcion tiene que ser una funcion lambda
para unittests viene incorporado un mock, pero no se como se usa
