### ISSUE TITLE
Exceptions Genéricas (tarea 03)

### ISSUE THREAD

**Issue by selira** [IIC2233-2015-2/syllabus#283]
Tengo una duda con las exceptions: en el enunciado dice que:
"Se espera que se manejen todas las excepciones correctamente (i.e: indicando el tipo de excepcion a capturar y lo que se haria con ella. Una excepcion generica no se considerarla como 100% correcta, a menos que sea la unica solucion posible - explicar en el README.md por que es la unica solucion posible)."
En mi programa me parece que lo más lógico, que cuando se tiene una función que puede tirar varios errores distintos (y con varios raise (cualquier)Error, dependiendo del caso), escriba un try: con todo el codigo de la función y al final:
except Exception as err:
        print(err)
        return False
Bueno, mi pregunta es: cuando se dice que las excepciones no pueden ser genéricas, ¿se refiere a 
los raise Exception, o se refiere a hacer un except: distinto para cada tipo de error? A esto último no le encuentro sentido, porque con todas las excepciones lo único que quiero es que me imprima en pantalla el porqué del error y retorne False, y eso es lo mismo para todos los tipos de errores.

**Comment by tamycova** [comment]
comento para saber
