### ISSUE TITLE
Recuperar archivos antiguos del Git?

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#284]
Hola! Como es posible bajar archivos antiguos del git?
Saludos

@mrpatiwi

**Comment by lopezjurip** [comment]
Busca qué commit quieres, lo identificamos por su `id` o `SHA`.
Puedes ver los ya pusheados en https://github.com/IIC2233-2015-2/santiagocruzb-repo/commits/master 
O localmente (en tu computador) con `git log --oneline`

Un `SHA` es del estilo `8a7730ec135f5c8c935dea1b518063860232fbef` o acortado `6da5a6a`

Nos aseguramos que tenemos todos los cambios ya commiteados (para no perderlos), y hacemos

``` sh
git checkout <SHA>

# Ejemplo:
git checkout 8a7730ec135f5c8c935dea1b518063860232fbef
```

Ahora tenemos los archivos hasta ese commit.

Para volver a la última versión:

``` sh
git checkout master
```

**Comment by aaossa** [comment]
[Respuesta original](http://stackoverflow.com/a/953573/3281097)
1. Usar `git log --diff-filter=D --summary` para tener todos los commits en los cuales se borraron archivos y cuales se borraron en cada commit.
2. Usar `git checkout $commit~1 filename` para restaurar el archivo borrado. `$commit` es el "nombre" del commit, algo como `1d0c9ef6eb4e39488490543570c31c2ff594426c`.

PS: Asumí que habías borrado el archivo, lo cual puede que no sea así. Si ese es el caso puedes usar git log para navegar por los cambios que hayas hecho.
