### ISSUE TITLE
Tarea 3 - Aviones

### ISSUE THREAD

**Issue by icussen** [IIC2233-2015-2/syllabus#285]
con el cambio de el avion explorador (que es de 3x3 y se mueve donde explora) considere que no tenia ningun sentido que el avion kamikaze y caza usaran un espacio en el mapa del aire, ya que de ser asi el explorador no podria explorar en esa zona, debido a esto los deje fuera. Esta mal lo que hice? me van a bajar puntaje? lo cambio?

**Comment by silvamatias** [comment]
aprovecho de colgarme y preguntar si los aviones kamikaze y caza disponen de movimiento? de ser así es de una casilla?

gracias

**Comment by plorrego** [comment]
Los aviones deben estar en el mapa y si es necesario que se controle el tope de las posiciones. Tambien deberian poder moverse para que el avion explorador tenga la posibilidad de explorar todo el mapa. La magnitud del movimiento de los aviones queda a su criterio.
