### ISSUE TITLE
Duda Contenidos AC15

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#288]
La calendarización dice que mañana toca "Threading básico". Respecto al material de clases que se subió, ¿qué se considera básico? ¿todo el documento de Threading? ¿o no todo? Gracias.

**Comment by aaossa** [comment]
@robocop6 (a.k.a Ariel) podría especificarte un poco mas :grin:

PS: Lo de la etiqueta fue la fuerza de la costumbre

**Comment by robocop6** [comment]
Hola!

La AC de mañana abarca el primer material de threading: 01_Threading. Esto contempla: 
- Creación de threads
- Join
- IsAlive
- Daemons.

No se evaluarán timers.

La AC del jueves se enfocará en lo que queda de la materia: principalmente coordinación de threads (y es clave que dominen **locks**).
