### ISSUE TITLE
radar

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#289]
tengo que darle informacion al otro usuario? por ejemplo, en el turno anterior tu opononente intentó atacar la casilla b5 y resulto exitoso, la nueva resistencia de tu barco es x

**Comment by eiurrutia** [comment]
Así es, debes notificar cuando a un barco tuyo lo han atacado. También puedes implementar que los ataques "al agua" sean notificados si lo estimas conveniente.

**Comment by bamavrakis** [comment]
Hola,
Ese comportamiento tiene sentido y resulta útil para una mejor experiencia de juego, pero queda completamente a tu criterio (debes especificarlo en el README).
Saludos!
