### ISSUE TITLE
Tarea 1 - Uso de librerias

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#29]
¿Podemos usar las librerías numpy y time?

**Comment by lopezjurip** [comment]
No hay ningún problema, úsalas nomás si quieres

**Comment by raiperez** [comment]
@mrpatiwi y la libreria datetime se puede?

**Comment by mathias-katscher** [comment]
@mrpatiwi se puede usar la libreria ast?

**Comment by lopezjurip** [comment]
hmmm... mejor consultarlo con @mbucchi y @bamavrakis. Ellos son los encargados directos de la tarea.

**Comment by mbucchi** [comment]
@raiperez Ningún problema con que utilicen DateTime, no hay por qué reinventar la rueda. Por otra parte @mathias-katscher, la librería ast maneja conceptos que aún no han aprendido. No te puedo dar la respuesta en este momento, por ahora intenta avanzar sin utilizarla.
Saludos!

**Comment by raiperez** [comment]
@mbucchi Gracias, y podemos usar la libreria json?

**Comment by mbucchi** [comment]
@mathias-katscher @raiperez Después de una larga y ardua discusión con el comité de Bummer UC, se llegó a la conclusión de que ustedes deben realizar la parte de lectura de archivos, es decir no pueden usar ni _json_ ni _ast_ ni ninguna librería que les permite hacer un parsing. La principal razón es que ese tipo de materia se va a ver más adelante y queremos que realmente comprendan cómo funciona (y de pasada, cuando lleguemos a esa materia ya van a entender porqué es tan útil y conveniente :) )
Saludos!

**Comment by felipehv** [comment]
y se puede usar funciones como list(), dict(), eval()  que vienen por defecto?

**Comment by aaossa** [comment]
Hola, `list`y `dict` sí pueden usarlos (se ven en Intro a Progra). Pero sobre `eval`... revisa #41
