### ISSUE TITLE
Usar librería termcolor

### ISSUE THREAD

**Issue by diflores** [IIC2233-2015-2/syllabus#291]
¿Se puede usar la librería [termcolor](https://pypi.python.org/pypi/termcolor) en la Tarea 3?
Sé que en otra issue se autorizó el uso de [colorama](https://pypi.python.org/pypi/colorama), pero pregunto por termcolor porque considero que es más fácil de usar.

Saludos.

**Comment by eavildosola** [comment]
Si se puede usar
