### ISSUE TITLE
informacion

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#296]
Si un jugador realiza un ataque exitoso, cuando le toque al oponente le debe salir en pantalla que su barco tanto o coordenada tanto fue atacada? porque en la lógica yo como dueño de mis barcos me debería dar cuenta de si me atacan, para poder realizar mejor mi siguiente jugada dependiendo de lo que hizo mi contrincante.

**Comment by eavildosola** [comment]
Si, es lo más lógico, pero todas las decisiones extras que tomes e implementes debes escribirlas en tu Readme y justificarlas.
