### ISSUE TITLE
Dudas Enunciado Tarea 1

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#30]
Algunas dudas sobre el enunciado de la Tarea 1:
- En el 4.2, al **inscribir un ramo** pide que **se agregue el curso como curso por tomar**. ¿A qué se refiere a que se agregue como curso por tomar? ¿A la carga académica del alumno? Ya que Bummer debería señalar de inmediato si el curso fue otorgado ¿cierto?, no entiendo bien a lo que se refiere. <br> Lo mismo cuando al **botar un ramo** pide que **se elimine el curso como curso por tomar**.
- En el 4.2, la fórmula de **créditos máximos permitidos** permite que, por ejemplo los del grupo 10, tengan 47 créditos máximos permitidos. ¿Está bien eso? Me parece raro, por eso lo comento.
- En el 4.3, en el tercer punto, señala que: _"si Gonzalo Gonzalez es demasiado bacan y es la unica persona que sigue a Fernando Fernandez, entonces este ultimo tambien es muy bacan"_, pero no especifíca que tan bacan lo hace eso a Fernando Fernandez. La duda va en que para calcular la bacanosidad de Fernando Fernandez ¿debemos ponderar:  la cantidad de gente que encuentra bacan a Fernando Fernandez, y qué tan bacan es esa gente?.
- En el 8, en el octavo punto, ¿a qué se refiere con **crear un módulo para cada conjunto de clases**? ¿y **dividirlas por las relaciones y tipos que poseen en común**?

**Comment by bamavrakis** [comment]
Hola!

1- Efectivamente se refiere a la carga académica del alumno.

2- La fórmula está bien. La idea es que los del grupo 1 puedan tomar hasta 55 créditos, y los del grupo 10 hasta 45 créditos. Como todos los cursos dan una cantidad de créditos que es múltiplo de 5, tener un máximo de 47 créditos los limita a 45 créditos.

3- Esto queda a tu criterio, pero siempre tomando en cuenta que la forma de hacerlo debe estar basada en los "follows", y debe ser consistente. 

4- Esto es con el fin de tener tu código más organizado, además de tener la posibilidad de reutilizarlo  en otros programas y por último, para hacer que su lectura sea más amigable para los ayudantes correctores.
TL;DR : Básicamente si no "modularizas" tu tarea hay descuento.

**Comment by fgvenegas** [comment]
Pero a que se refieren con modulos?

**Comment by jgmontoya** [comment]
http://i.imgur.com/MAFk9oH.jpg

**Comment by lopezjurip** [comment]
Es decir, **no hagas toda tu tarea en un solo gran archivo `main.py`**.

Divide parte del programa en archivos/carpetas de manera ordenada y coherente. Luego puedes ir importando partes del programa donde sea necesario usando.

Recuerda modelar bien las clases :+1: 

Puedes revisar: http://www.python-course.eu/python3_modules_and_modular_programming.php

**Comment by javierlopeza** [comment]
Perfecto, gracias. Otra duda, ¿a qué se refiere en el archivo _cursos.txt_ con **apr[SI/NO]: Establece si requiere aprobación especial o no.**? ¿Se refiere a que solo con permiso especial del profesor que dicta el ramo se puede pedir el ramo?

**Comment by btkramm** [comment]
Una duda respecto al punto 4.3. ¿El proceso de asignar "bacanosidad" recursivo debe utilizar directamente los datos de "siguiendo" o puede trabajar con la información de "seguidores" de cada persona (los seguidores deberán ser asignados antes de comenzar a calcular bacanosidad)?

**Comment by mbucchi** [comment]
@javierlopeza Nada especial. Esa es info que da el buscacursos para que sepas si es que necesitas algo más a parte de los créditos y los prerrequisitos para poder tomar el ramo (como por ejemplo requiere aprobación de un profesor específico para poder inscribirlo). Para efectos de la tarea, eso es solo información extra que la "podría" ser útil al alumno. Espero que esto aclare tu duda.

@btkramm Me vas a tener que perdonar, pero podrías explicar un poco más tu pregunta :P?

Saludos!

**Comment by btkramm** [comment]
Es que el documento personas.txt asigna a cada persona la información "ídolos". Se nos indicó que el proceso para calcular la bacanosidad de cada persona debía ser un proceso recursivo si buscábamos la mayor cantidad de puntos. Hasta ahora la única manera recursiva que se me ocurre para calcular la bacanosidad es mediante los "seguidores" de cada persona, no por los "ídolos" (por los que lo siguen, no por quienes él sigue). Mi pregunta es ¿Puedo asignar a cada persona los "seguidores" para posteriormente calcular la bacanosidad como se me ocurrió, o debo limitarme solo a usar los "ídolos" si quiero alcanzar un buen puntaje en esta parte?

Si aún no queda claro, haganmelo saber xd

**Comment by mbucchi** [comment]
@btkramm Ahora entendí tu pregunta. Es bastante compleja la asignación de bacanosidad, esta no solo depende de los "ídolos", sino también de los "seguidores" como tú dices. Efectivamente tienes que encontrar una manera de manejar los datos para tomar en consideración ambas cosas. Por lo mismo, se espera que ustedes encuentren una manera inteligente de manejar esos datos (lo cual puede ocurrir de muchas formas distintas). Eso sí, no debes modificar el _.txt_ original. 
Está permitido el uso de la librería matemática _numpy_ por si sientes que necesitas herramientas matemáticas más completas. Este es un problema muy matemático, por lo cual debes sentarte a pensar un rato antes de programar.
Espero que eso te haya aclarado un poco las dudas,
Saludos!

**Comment by javierlopeza** [comment]
@mbucchi una pregunta acerca de lo que respondiste arriba, ¿qué tan matemático tiene que ser el proceso de asignar bacanosidad? Porque en el ejemplo de: _"José tiene muchos seguidores lo que lo hace muy bacán; por su parte Juan tiene solo un seguidor que es José, y como José es muy bacán, esto hace a Juan ser_ **bastante** _bacán también"_ ese **bastante** queda a nuestra elección, o sea, ver que tan bacan hace a Juan que lo siga José, ¿cierto? Porque no veo algo matematico que decida cuan bacan seria Juan porque lo siga José. (Esta claro de base que alguien con mas seguidores es mas bacan, pero me queda la duda con lo mencionado)

**Comment by mbucchi** [comment]
@javierlopeza Mañana voy a subir un archivo detallando un poco más acerca de cómo se debe comportar la bacanosidad. Espero que esto les aclare más las dudas

**Comment by javierlopeza** [comment]
@mbucchi gracias!

**Comment by javierlopeza** [comment]
@mbucchi se subirá la explicación de la bacanosidad?

**Comment by mbucchi** [comment]
@javierlopeza Sí, hoy se subirá.

**Comment by javierlopeza** [comment]
Pregunta acerca de la aclaración que hicieron para la bacanosidad. Si por ejemplo tengo la siguiente situacion hipotética: 

*en total hay 3 alumnos en la universidad: Andres, Bernardo y Carlos. Si Andres sigue a Bernardo, Bernardo a Carlos y Carlos no considera a nadie como ídolo.* 

En esta situación, sea cual sea la bacanosidad que yo le asigne a los alumnos en el ejemplo, para verificar si mi asignacion de bacanosidad fue correcta hago lo siguiente: Andres le entrega todos sus puntos a Bernardo y Bernardo le entrega todos sus puntos a Carlos, quedando finalmente Andres con 0 puntos recibidos, Bernardo con los mismos puntos iniciales que Andres y Carlos con los mismos puntos iniciales que Bernardo, por lo tanto sea cual sea mi repartición de puntos inicial, no se cumpliría la verificación que ustedes piden. 

Es claro que es un ejemplo hipotético, pero como ustedes dicen que van a usar diferentes archivos de personas.txt podría pasar esto.

**Comment by javierlopeza** [comment]
@mbucchi 

Pregunta acerca de la aclaración que hicieron para la bacanosidad. Si por ejemplo tengo la siguiente situacion hipotética: 

_En total hay 3 alumnos en la universidad: Andres, Bernardo y Carlos. Si Andres sigue a Bernardo, Bernardo a Carlos y Carlos no considera a nadie como ídolo._ 

En esta situación, sea cual sea la bacanosidad que yo le asigne a los alumnos en el ejemplo, para verificar si mi asignacion de bacanosidad fue correcta hago lo siguiente: Andres le entrega todos sus puntos a Bernardo y Bernardo le entrega todos sus puntos a Carlos, quedando finalmente Andres con 0 puntos recibidos, Bernardo con los mismos puntos iniciales que Andres y Carlos con los mismos puntos iniciales que Bernardo, por lo tanto sea cual sea mi repartición de puntos inicial, no se cumpliría la verificación que ustedes piden. 

Es claro que es un ejemplo hipotético, pero como ustedes dicen que van a usar diferentes archivos de personas.txt podría pasar esto.

**Comment by mbucchi** [comment]
@javierlopeza Los archivos de datos están pensados para no causar ese problema, todos encuentran a alguien bacán.

**Comment by javierlopeza** [comment]
En cuanto al Pacmatico, se señala en el enunciado que: _a diferencia de Bummer UC, el Pacmatico no controla topes de horario_. ¿Esto quiere decir que todas las otras restricciones sí las revisa (tope de campus, tope de evaluaciones, requisitos)? ¿O queda a nuestra elección?

**Comment by aaossa** [comment]
@javierlopeza, si sigues con esa pregunta revisa las demas issues por si ya fue respondida. Si no es así abre una nueva :+1:
