### ISSUE TITLE
Readme 

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#300]
Es posible subir el readme más tarde o existe la posibilidad de que el ayudante corrector crea que no lo subí nunca ?

**Comment by lopezjurip** [comment]
Duplicada #124

**Comment by lopezjurip** [comment]
Felicitaciones eres la Issue º300 :tada:

**Comment by fgvenegas** [comment]
Estoy orgulloso de mí mismo :v
