### ISSUE TITLE
Readme tarea03

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#302]
Hola! mi tarea tiene un problema que hace que se caiga si se usa un ataque, y quería saber si puedo modificar el readme solo para agregar el aviso de cuando es que sucede este error y su causa (pues no tiene que ver con que el método no funcione, solo que se me paso corregir una de las llamadas al método). No es para arreglar el error ni nada, solo para que se cache porque es que se genera.

Saludos!

**Comment by lopezjurip** [comment]
Duplicada #124
