### ISSUE TITLE
Método organizacional

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#303]
Requiero urgentemente de un método más inteligente para ordenar las clases/módulos de mis programas. En particular, considerando la última tarea.

Hace algunos días me recomendaron un método pero me pareció muy abstracto; por lo tanto quizás debí ser más específico:

¿Como dividieron la última tarea?

Es imposible, mientras más grande el trabajo, saber desde un principio como se unirán las clases y módulos de cada tarea (o por lo menos así lo siento). ¿Cómo escribieron código en un principio, con tal de que fuese lo más adaptable a lo que escribiesen posteriormente?

Lo digo porque la principal dificultad que se me presenta a la hora de programar es el conectar, posteriormente a haberlos escrito, múltiples módulos distintos. En la última tarea, luego de haber escrito las Armas, los Vehículos, los Jugadores, el Tablero con sus Posiciones, etc., se me hizo un reto espantoso a la hora de crear la parte final, correspondiente al sistema de Turnos, donde debía unir todo lo anterior, de tal forma que un cambio en una instancia afectara al resto. ¿Debería haber dividido en forma distinta? ¿Debería, desde un principio, haber tenido en mente los métodos/atributos/llamados que conectarían las distintas clases?
¿Cómo lo organizaron ustedes?
Personalmente intenté usar un control central (Turnos) que fue un enredo asqueroso; ¿Debería haberle metido clases de "Placeholder" con tal de preparar desde un principio en Turnos la forma en que se uniría al resto?

Si no se entiende muy bien mi duda, por favor decirme y estaré feliz de aclararme.

Muchas gracias.-

**Comment by flobarrios** [comment]
Hola ! no se si te sirva pero yo lo que hice por ejemplo, fue hacer las mismas clases que nombraste tu pero todo quedaba finalmente en el jugador y este tenia un método para atacar.

``` python
class Tablero:
    pass

class Ataques:
    pass

class Misil(Ataques):
    def __init__(self):
        super().__init__(self)

class Vehiculos:
    pass

class Barco(Vehiculos):
    def __init__(self):
        super().__init__(self)
        self.ataques = {"Misil": Misil()}   #a modo de ejemplo

class Jugador:
    def __init__(self):
        self.tablero = Tablero()
        self.vehiculos = {"Barco": Barco(), "Lancha": Lancha()}   #a modo de ejemplo

    def atacar(self, pieza, coordenada):
        pass
```

Algo así! no se si se entiende mucho pero como cada vehículo tenia sus ataques predeterminados, en la clase del vehículo especifico guarde un diccionario con todos los ataques y lo mismo para el jugador, ya que este tiene un determinado numero de piezas, que a su vez cada uno tiene determinados ataques y así es super fácil acceder a todo :) y simplemente al ir por turnos entre el jugador uno y 2/pc accedo rápidamente a toda su info del tablero y los barcos, ataques etc.

**Comment by lopezjurip** [comment]
Uno tiene que encontrar patrones, comportamientos similares así como definir estándares.
Cuando les pedimos que modelen los problemas es con el fin de que uno se de cuenta de que cosas se parecen, y como se parecen puedo reutilizar código. 

**_El mejor código es el que no se escribe_**, por esto hay que apuntar a escribir lo menos posible. Un buen código hace mucho en poco, porque es bien abstracto y general. Así es más fácil de revisar, leer, modificar, etc.

Tienes un método gigante, eso está muy mal:
https://github.com/IIC2233-2015-2/gebalassa-repo/blob/master/Tareas/T03/tablero.py#L64-L731

También noto que no usas herencia:
https://github.com/IIC2233-2015-2/gebalassa-repo/blob/master/Tareas/T03/armas.py

Tanto para ti como para cualquiera que lea esto:

# Si haces un `if` para ver qué tipo/clase es algo, es muy muy probable que tengas un problema de modelación

Muchos en la I1-P1 se equivocaron en esto (pregunta de los trenes). Era claro que había que aplicar herencia.

Si bien en Python hay ducktyping, **no se mal-acostumbren**, porque en lenguajes más serios estructurados la herencia es una de sus armas principales.

**Comment by gebalassa** [comment]
Muchas gracias por las respuestas.

En mi defensa la función gigante y el tema de las armas fue de último minuto xD

@flobarrios:

1)En el pseudo-código, en que parte consideraste los turnos de cada arma? 

2) Qué significa que el jugador tenga un tablero propio (self.tablero)? Y si tiene tablero propio, como afecta al del otro? 

3) Por qué necesitas colocar la pieza en el método "atacar"? para chequear si el barco esta disponible y si por tanto el ataque esta disponible?

4) Como separaste el modo de juego de dos jugadores del
modo de juego contra el PC?

Disculpa te hinche. Muchísimas gracias por sus respuestas.

Si cualquier otro puede aportar con su idea se agradece un montón.

**Comment by otro-felipe** [comment]
No se tu pero yo los turnos no los pense como objeto, si no que habia un metodo turn() que era el loop que preguntaba al usuario que accion realizar durante el turno y al final tenia el metodo self.tick(). Yo la vez quebintente hacer un mod de Minecraft note que los tiempos se dividian en ticks (1/20 de segundo para el caso de minecraft), por lo que decidi que hubiese un metodo que se encargue del tiempo.
Por ejemplo:
Jugador.tick() se encarga de llamar el tick de todos los ataques y todas las piezas.
Pieza.tick() se encarga de verificar si hay daño de napalm y restarlo e imprimir lo correspondiente.
Ataque.tick() se encarga de reducir el cooldown restante del ataque.
De esta forma un tick se convirtio en un turno.
Repito, esta idea la vi en minecraft y me parecio bueno aplicarla aca. No se que piensennlos demás. Correjirma por favor si es un mal enfoque. Saludos.

**Comment by tamycova** [comment]
Yo lo que hice fue ir encapsulando todo dentro de una clase grande, como que vai haciendo un arbol, mi clase principal era juego, entonces desde el main se importa juego y se hace juego.run, el juego esta compuesto de la clase jugador, entonce sjuega con los metodos del jugador (turno y posicionar vehiculo), el jugador compuesto de la clase radar, y de las clases vehicylos, y los vehiculos de la clase ataque, entonces para manipular lo voy haciendo con las instancias de arriba. 

Por ejemplo para lo de los turnos, el jugador tiene un metodo "turno" que al final llama al metodo "pasar turno" que llama a los "pasar turno" del explorador y de los ataques, que la mayoria heredaba de una clase general "ataque" donde con un bool se definia si estaban disponibles siempre o cada ciertos turnos.

Y para el orden fisico, te dejo la estructura del repo:

``` sh
/T03
|-- main.py                     
Debe ejecutarse para iniciar el programa
|-- run_tests.py
Debe ejecutarse para ejecutar los tests de la tarea
|-- /clases                       
Aqui se encuentran los archivos de la modelacion del programa
|   |-- clase_juego.py
|   |-- clases_ataques.py
|   |-- clases_data.py
|   |-- clase_smart.py
|   |-- clases_piezas.py
|   |-- clases_players.py
|   |-- clases_tablero.py
|-- /tests
Aqui se encuentran los tests que se ejecutan con el modulo discover    
|   |-- test_clase_juego.py
|   |-- test_clases_ataques.py
|   |-- test_clases_data.py
|   |-- test_clase_smart.py
|   |-- test_clases_piezas.py
|   |-- test_clases_players.py
|   |-- test_clases_tablero.py
|   |-- test_funciones_aux.py
|-- /tools
Aqui se encuentran funciones auxiliares, especialmente las de manejo de error (que son usadas transversalmente en todas las clases)
|   |-- funciones_aux.py
```

Entonces como empiezo? identificio las clases mas o menos que voy a necesitar y hago los modulos. Hago las clases como de mas arriba para poder ir probando el programa, pero no lo de al medio (atacar,mover,etc), y voy construyendo como de abajo hacia arriba, asi cuando tengo que hacer que todo funcione se perfectamente como interactua todo.

**Comment by tamycova** [comment]
2) Qué significa que el jugador tenga un tablero propio (self.tablero)? Y si tiene tablero propio, como afecta al del otro? Mis jugadores tambien tenian tablero propio, que era la clase Mapa, pero por modelamiento seria raro que el jugador tenga acceso al mapa del otro jugador, esas interacciones se ven desde la clase Juego que si maneja la info de sus dos jugadores. 

4) Como separaste el modo de juego de dos jugadores del modo de juego contra el PC? Hice la clase Jugador, despues la clase Maquina que heredaba de jugador (entonces asi tenia todos los metodos de atacar y solo me preocupaba de que mi inteligencia tome la desicion). Entonces al instanciar el Juego y elegir por consola maquina o no, con un bool hice que los dos jugadores fueran Jugador o uno Maquina y uno Jugador, y la clase juego llama a la funcion turno y ambos la tienen cachai? que @mrpatiwi  me perdone pero esta tarea era para abusar del ducktyping jaja

**Comment by tamycova** [comment]
Eso si yo viaje asique tambien tuve que programar sobre la marcha y hardcodear la parte de atacar/mover asique igual watea un poco el codigo, pero en teoria hice lo que dije arriba

**Comment by otro-felipe** [comment]
No creo que sea ducktyping si heredaste de Jugador. Es mas polimorfismo, que es una de las grandes ventajas de la OOP. 
Yo hice que cada jugador tuviese su tablero y no encontré tan rara la interaccion, ya que un jugador al realizar un ataque como que le "preguntaba" a otro jugador si es que tenia una pieza en la posicion x,y de su tablero naval | aereo. La instancia juego la hice mas como un controlador del timing del juego mas que como una estructura de datos. (Cada jugador guardaba una instancia self.oponente).
Mi humilde opinión ^^

**Comment by tamycova** [comment]
@MainScientist noo pero en los otros casos, como de pasar turno, si use harto ducktyping! Y si lo piensas como analogia al juego en tablero tiene sentido ese modelamiento! yo lo pense distinto

**Comment by lopezjurip** [comment]
No se mal acostumbren abusando del Duck typing nomás. Que no todos los lenguajes tienen eso, y aunque Python lo soporte, puede resultar en problemas de abstracción. Ya sea usando herencia o duck-typing pueden ocurrir.

Ver: https://stackoverflow.com/questions/56860/what-is-the-liskov-substitution-principle
