### ISSUE TITLE
matplotlib

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#305]
Intenté probar los comandos de simulación pero me tira un error por matplotlib:
-ImportError: DLL load failed: %1 no es una aplicación Win32 válida.
probé:
     - pip install matplotlib
     - pip3 install matplotlib
sale que estan actualizadas pero aun no me funciona, busque el error, pero nada de lo que he encontrado ha funcionado

**Comment by lopezjurip** [comment]
¿ Revisaste: https://github.com/IIC2233-2015-2/syllabus/wiki/Windows#python-3x ?
El problema es que parte de esa librería está en `C` y Windows no se lleva bien con eso. Lo mejor es usar el método que puse ahí que baja la librería pre-compilada (_Wheel_).

**Comment by oatorresuc** [comment]
si eso hice y me sale en rojo :+1: 

```
-Failed building wheel for numpy
-Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\OSVALD~1\\AppData\\Local\\Temp\\pip-build-pc7xsovh\\numpy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\OSVALD~1\AppData\Local\Temp\pip-xpj92246-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\OSVALD~1\AppData\Local\Temp\pip-build-pc7xsovh\numpy
```

**Comment by lopezjurip** [comment]
instalaste `numpy` antes?

**Comment by oatorresuc** [comment]
Perdón me explique mal en la última, no puedo, lo intente y eso es lo que me sale cuando pongo:
- pip3 install --upgrade numpy

**Comment by lopezjurip** [comment]
Leíste bien las instrucciones?

```
pip install -i https://pypi.binstar.org/carlkl/simple numpy
pip install --upgrade matplotlib
```

**Comment by oatorresuc** [comment]
Eso lo segui al pie de la letra y me tiro el mismo error

**Comment by iqacevedo** [comment]
Hola mi computador tuvo problemas por lo que tuve que formatearlo y ahora me pasa el mismo error, segui las instrucciones también :(

**Comment by aaossa** [comment]
**SOLO WINDOWS**

Esta página les salvará la vida: [**Unofficial Windows Binaries for Python Extension Packages**](http://www.lfd.uci.edu/~gohlke/pythonlibs/)

Descarguen la libreria que necesitan para su versión de Windows y su versión de Python. Luego, guarden el archivo (`*.whl`) en cualquier directorio, abren la consola, se dirigen a ese directorio y corren:

```
pip install *.whl
```

Donde `*.whl` es el nombre del archivo descargado. Luego no deberían tener ningún problema :grin:

**Comment by aaossa** [comment]
En caso de que alguien tenga el siguiente error al usar `matplotlib` y esté buscando hacer gráficos:

``` python
ImportError: DLL load failed: cannot find the module
```

Pueden haber algunos problemas usando `matplotlib` (que al parecer son mayoritariamente con Windows), por lo que si lo tienen instalado correctamente pueden probar escribiendo el siguiente código antes de importar lo que necesiten de `matplotlib`:

``` python
import matplotlib
matplotlib.use('Agg')
```

Por si acaso, `'Agg'` es el backend que usa `matplotlib` para graficar. Así, después de este código, pueden importar correctamente tanto `pylab` como `pyplot`, segun lo que sea que necesiten:

``` python
import matplotlib.pylab as pylab
import matplotlib.pyploy as plt
```

Lamentablemente, `'Agg'` no tiene UI, por lo que algo como `plt.show()` no funcionará, solamente pueden guardarlo como un archivo usando `plt.savefig('migrafico.png')`.
- [Pregunta original en StackOverflow](http://stackoverflow.com/questions/1052831/matplotlib-dll-load-failed-when-import-pylab)
- ["Ticket" en matplotlib](http://www.mail-archive.com/matplotlib-users@lists.sourceforge.net/msg05372.html)
