### ISSUE TITLE
Tarea 4 - Grilla

### ISSUE THREAD

**Issue by jtagle2** [IIC2233-2015-2/syllabus#308]
Hay una cosa que no entiendo. Para ir mostrando lo que va pasando, cada vez que yo quiero mover un auto, tengo que armar toda la grilla de nuevo? Es decir, si se mueve un auto, tengo que armar la grilla entera de nuevo (poner casas edificios y estaciones de servicio y todos los autos), o hay una formar de remover uno de los elementos, cosa de sacar el auto y poner uno igual pero un poco más adelante, de forma de simular que se movió. 
No se si se entiende la pregunta :S.

**Comment by rodolfopalma** [comment]
Sí, se entiende. Cuando agregas objetos (autos, taxis, cuarteles de bomberos, etc.) a una celda que se encuentra ocupada, el nuevo elemento reemplaza al antigüo, por lo que no es necesario reconstruir toda la grilla de nuevo, sólo debes ir actualizandola de acuerdo a los eventos de tu simulación.

**Comment by jtagle2** [comment]
Esque por ejemplo, para los autos. Eso me sirve en caso de que haya mucho taco y haya un auto atrás de otro y todos se muevan juntos, y el auto de atras hace desaparecer la posicion anterior del auto que está adelante. Pero si hay solo 1 auto en la calle, no habrá otro auto que borre la posicion anterior, y como el agregar_calle no remueve lo que hay en esa posicion, no puedo hacer que avance el auto, dejando el lugar donde estaba él vacío (es decir, una calle).

**Comment by rodolfopalma** [comment]
Tienes razón, se ha actualizado la interfaz gráfica agregando el método `quitar_imagen(x, y)` para solucionar lo que indicas.

**Comment by jtagle2** [comment]
Ok. Gracias!
