### ISSUE TITLE
Duda enunciado Tarea 1

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#31]
En el fondo tengo que crear 2 programas distintos o Bummer tengo que hacer que falle y ahi iniciar Pacmatico?

**Comment by bamavrakis** [comment]
Hola!!
No tienes que hacer que falle!! esa sección del enunciado era parte del contexto. Efectivamente son 2 programas distintos.

Saludos!

**Comment by fgvenegas** [comment]
Vale gracias, otra cosa, el sistema de inscripcion lo invento yo o tambien se hace mediante los NRC de los ramos?

**Comment by mbucchi** [comment]
@fgvenegas Lo puedes inventar tú (cualquier parecido en nombre a banner y pucmático es mera coincidencia :laughing:). La gracia de este extraño parecido es que todos debiesen entender mucho mejor cómo funcionan los sistemas (y a grandes rasgos se _deben_ parecer :speak_no_evil:)

PS: obviamente te favorece que sea muy similar, pues el ayudante que te corrija probablemente se sienta inclinado a utilizarlo como estos sistemas, pero si encuentras una forma más intuitiva/fácil/entretenida, adelante! La idea es que ustedes aprendan a programar para hacer más fácil sus vidas.

Saludos!
