### ISSUE TITLE
problema con descargar simpy

### ISSUE THREAD

**Issue by fjsalinas** [IIC2233-2015-2/syllabus#310]
hola, segun yo tengo simpy descargado perfectamente, me sale esto en la consola:
![image](https://cloud.githubusercontent.com/assets/8507323/10501236/b23c87c0-72b5-11e5-82f2-78caee4c3085.png)

pero a la hora de importarlo en pycharm me tira error:
![image](https://cloud.githubusercontent.com/assets/8507323/10501256/d71dec5a-72b5-11e5-87e0-c7566ecb5949.png)

muchas gracias

**Comment by aaossa** [comment]
Asegurate de estar usando la misma versión de Python en consola y en pycharm, y luego prueba en consola el test que aparece [aqui](https://pypi.python.org/pypi/simpy)

**Comment by fjsalinas** [comment]
Si probe con el test, me sale esto:

![image](https://cloud.githubusercontent.com/assets/8507323/10501436/0441e4a0-72b8-11e5-8dca-1f5f75a0f8ba.png)
![image](https://cloud.githubusercontent.com/assets/8507323/10501440/0bfdac9c-72b8-11e5-80e4-a4e8fd834092.png)

**Comment by aaossa** [comment]
Y las versiones, ¿son las mismas?

**Comment by flobarrios** [comment]
hola yo tengo otro problema y no se por que es :/ al ejecutar la simulación
por primera vez, no hay problema, pero si lo hago una segunda, me tira el
error de la foto. Porque sera? estoy usando el ejemplo del :In [97] e
In [98]

2015-10-14 21:23 GMT-03:00 Antonio Ossa <notifications@github.com>:

**Comment by fjsalinas** [comment]
Como se que version es??

Enviado desde mi iPhone

**Comment by aaossa** [comment]
Estoy buscando sobre lo de los test, pero al menos a mi me aparece lo mismo. Eso sí, una de las veces funcionaron los test, no conozco mucho detalle de ellos, pero la idea era verificar que estuviera instalado.

Para ver la versión corre estas lineas en consola y en PyCharm. O mejor, crea un archivo `*.py` y correlo desde consola y desde PyCharm.

``` python
import platform
platform.python_version()
```

**Comment by fjsalinas** [comment]
si tengo la misma version!! pero me sigue tirando el mismo error

**Comment by fjsalinas** [comment]
ya lo arregleee!! gracias!! :)

**Comment by aaossa** [comment]
¿Cómo lo arreglaste? Por si a alguien mas le ocurre...

**Comment by fjsalinas** [comment]
Fue muy raro, hice lo que me dijiste de verificar que fuera la misma versión, las cuales estaban bien, me había rendido me puse a estudiar la materia para la actividad de mañana y funciono de la nada jajaja 

Enviado desde mi iPhone
