### ISSUE TITLE
problema github

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#312]
Hola. No sé que paso pero acabo de intentar hacer git pull al syllabus y me dice que modifiqué el archivo .html del material de clases (lo cual no hice) y ahora no puedo hacer pull.

![image](https://cloud.githubusercontent.com/assets/13739960/10503740/74b4dfdc-72cf-11e5-9c88-32f39e2196ac.png)

**Comment by flobarrios** [comment]
prueba con 

```
git stash
```

**Comment by aaossa** [comment]
Borra la carpeta del repo y vuelve a clonarlo, es la forma bruta y simple de hacerlo :+1:
