### ISSUE TITLE
Recorrección I1

### ISSUE THREAD

**Issue by flobarrios** [IIC2233-2015-2/syllabus#313]
Hola! subirán la pauta con la asignación de puntajes para poder corregir la I1? Gracias!

**Comment by lopezjurip** [comment]
Se nos pasó a @jecastro1 y a mi. Nuestras disculpas.
La pauta está aquí:
https://github.com/IIC2233-2015-2/syllabus/blob/master/Interrogaciones/I1-2015-2.ipynb

Tienen 3 días adicionales para recorregir, la @bcsaldias publicará oficialmente en el Siding.
