### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'widget'

### ISSUE THREAD

**Issue by icrocco** [IIC2233-2015-2/syllabus#315]
Hola,

Cuando trato de mostrar nuevas calles dando como parámetros x, y no números directamente, si no variables que son números (que generé a partir de la lectura de mapa.txt) no funciona...

Me arroja el siguiente error:

```
  File "C:\Users\Ignacio\Desktop\T04\gui\gui.py", line 59, in agregar_calle
    label = self.simulationGrid.itemAtPosition(y, x).widget()
AttributeError: 'NoneType' object has no attribute 'widget'
```

(lo otro son líneas que hacen referencia a la línea en que arroja el error solamente)

@mrpatiwi ya busqué en google ;)

**Comment by lopezjurip** [comment]
Jajaja :smiling_imp: 
Te pasa que `self.simulationGrid.itemAtPosition(y, x)` retorna `None`. Por eso te dice que `NoneType` no tiene un atributo/método `widget()`.

No sé si la librería que les pasan tiene documentado el caso cuando `itemAtPosition(y, x)` retorna `None`.

**Comment by lopezjurip** [comment]
@rpalmaotero, está documentado eso?

**Comment by robocop6** [comment]
Retorna `None` porque la posición no existe en la grilla. Esta es de tamaño 20x20, al igual que el mapa. Seguramente es por "condiciones de borde": ¿le estás dando el punto x=y=0? Porque, para efectos de la grilla, las coordenadas de los puntos se numeran del 1 al 20 (y no del 0 al 19 como está en el archivo).

**Comment by robocop6** [comment]
P.D:

Para que se note la utilidad de los decoradores, imagínate alguien ya resolvió su tarea 4 con la notación del `mapa.txt`, pero sin probarla nunca en la interfaz. Y entonces, cuando la prueba se da cuenta de que se usó convención distinta para referirse a las coordenadas en la grilla... Tendría que editar las funciones que trabajan con las coordenadas en la grilla (que pueden ser muchas).

Pero entonces recuerda la I1 y escribe un decorador para la clase `GrillaSimulacion` que modifica los métodos de manera que cuando se llamen, el método decorado sume 1 a las coordenadas que recibe, y luego pase estos parámetros al método antiguo. ¡Problema solucionado!
