### ISSUE TITLE
Coordenadas Entidades

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#316]
En el archivo mapa.txt noté que se entregan las coordenadas de las entidades como `i,j entidad` pero estas coordenadas corresponden a `y-1,x-1` (coordenadas en los ejes). Por lo que para agregar las entidades a la grilla hay que hacer algo como `grilla.agregar_entidad(j+1, i+1)`. Quería saber si ese es un error del archivo mapa.txt o del enunciado, o si tenemos que hacer lo que mencione antes nomás.
Gracias.

**Comment by jgmontoya** [comment]
#315

**Comment by alopez7** [comment]
Tendrás que agregar las imágenes con j+1 y i+1 nomás

**Comment by javierlopeza** [comment]
Perfecto, gracias.
