### ISSUE TITLE
Pregunta acerca de los autos cuando adelantan

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#317]
Hola, mi duda es la siguiente: no comprendo que pasa cuando hay un auto que va alcanzando a otro, ya que en una parte se dice que el auto que va atrás iguala en velocidad al que le antecede. Sin embargo, después dice que los autos prefieren la pista derecha, y que solamente en tal situación deberán adelantar al vehículo. ¿Ambas cosas pueden producirse en simultáneo? Ya que también va a ocurrir que el auto va a parar por 0,5 segundos para cambiarse. ¿O lo de igualar la velocidad es para las calles que sólo tienen una pista o en caso de que haya tacos? En el fondo mi duda apunta a qué es lo que tiene que ocurrir cuando se adelanta un vehículo si es que se adelanta, en qué circunstancias ocurre y cuándo debe volver a su pista original. Gracias de antemano :)

**Comment by robocop6** [comment]
Va un auto alcanzando a otro. Ambos por la pista derecha, pues la prefieren.

Si la pista izquierda está desocupada, el auto de atrás se cambia de pista (tarda 0.5s), lo adelanta y luego vuelve a a pista derecha. Pero si la pista izquierda estaba ocupada por otro auto, debe reducir su velocidad para no chocar con el que está adelante.

**Comment by trencoret** [comment]
@robocop6 No entiendo como las calles tienen dos pistas, dentro de un mismo block de calle podemos meter dos autos? Como lo hacemos para ingresar el auto en la mitad del block? O hay que poner dos blocks de calles (dos pistas) por cada "calle", osea que cada vez que queramos hacer una calle hay que poner doble calle?

Ojala se haya entendido jaja. Gracias

**Comment by rodolfopalma** [comment]
La representación gráfica es de una sola pista, pero internamente en la simulación deben considerar que son de a dos, por ende los autos pueden adelantarse, la velocidad de la calle disminuye cuando hay un vehículo de emergencia estacionado, etc. Cómo representen eso en la interfaz queda a su criterio y deben comentarlo en el README.

**Comment by icrocco** [comment]
Al cambiarse de pista aplican las mismas reglas? Es decir, va un auto y justo a su izquierda hay un espacio, así es que se cambia de pista pq iba detrás de otro más lento. pero ¿y si ahora justo adelante, por la pista izquierda, va uno más lento?.

Además, hay casos en que dos pistas aledañas tienen la misma dirección ¿eso sería como tener 4 pistas?

**Comment by vclaro1** [comment]
comento para saber lo de las 4 pistas

**Comment by rodolfopalma** [comment]
Respecto al comportamiento de los autos, es importante que siga alguna lógica que tenga sentido, por ejemplo, siempre que necesite adelantar y pueda, lo haga, pero si no puede hacerlo, baje su velocidad para no chocar al de adelante.
Sobre las dos pistas aledañas, efectivamente equivale a tener 4 pistas en la simulación.

**Comment by trencoret** [comment]
El archivo mapa va a ser siempre asi? O nos van a cambiar el lugar de las calles y casas? Porque si no es mucho mas largo identificar una esquina y ponerle un semaforo...

**Comment by ManuelBeckerT** [comment]
Comento para saber.

**Comment by robocop6** [comment]
No pueden suponer que el mapa será igual. Deben identificar entradas/salidas e intersecciones.

¡Saludos!

**Comment by tamycova** [comment]
pero es como raro que la simulacion muestre una sola pista con autos cuando en realidad internamente hay dos?? como que no serviria de mucho la interfaz.. se puede modificar el gui?
