### ISSUE TITLE
Actualizar Interfaz

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#318]
No logro saber cómo actualizar la interfaz de la ciudad al agregar, por ejemplo, un auto.
Es decir, logro mostrar la ciudad de mapa.txt luego de hacer `grilla.show()` y `app.exec()` (igual que como lo hace el main de prueba que subieron), pero mi duda es cómo actualizo la grilla mostrada si después agrego un auto a esta. He probado todo y no sé que usar para hacerlo. Gracias.

**Comment by rodolfopalma** [comment]
En un rato más vamos a subir un ejemplo comentado sobre el uso de la interfaz para aclarar esta duda y otras que puedan surgir más adelante.

**Comment by rodolfopalma** [comment]
Revisa el [ejemplo que acabamos de subir](https://github.com/IIC2233-2015-2/syllabus/blob/master/Tareas/T04/ejemplo_gui.py). Ojalá te quede claro después de leerlo.

**Comment by javierlopeza** [comment]
Ahí si jaja gracias!
