### ISSUE TITLE
Entrada y salida de autos T04

### ISSUE THREAD

**Issue by icrocco** [IIC2233-2015-2/syllabus#319]
Yo de nuevo, jaja. Gracias por la anterior.

¿Se consideran como entradas y salida de la ciudad todas las calles que comunican con el borde del mapa (que tienen al menos una de sus coordenadas 1 o 20)?

Además, respecto al flujo de entrada y salida, los autos van a ir saliendo a medida que el azar los lleve a las calles de salida y tengo que ver que más o menos ese mismo azar vaya creando autos ¿es así?

**Comment by tamycova** [comment]
comento para saber, lo del flujo de autos

**Comment by crabarca** [comment]
comento para saber..

**Comment by robocop6** [comment]
Invoquemos a @rpalmaotero!

**Comment by robocop6** [comment]
Todas las calles que comunican con el borde son una entrada o salida, dependiendo de su dirección.

Y sí, debes idear una forma de que el flujo de autos se mantenga más o menos constante de modo que la cantidad de autos que salen por unidad de tiempo sea parecida a la que ingresa (crear autos en el borde).

**Comment by vclaro1** [comment]
@robocop6  Ariel que pasa en los casos de que ocurra un incendio o robo justo en una de esas casas que estan a lo mas arriba? hay unas calles que son solo hacia abajo, entonces las casas de ahi quedan inaccesibles, a menos que se metan en contra del transito. Lo mismo con las que son hacia arribas, los autos van a poder llegar pero no devolverse...

**Comment by rodolfopalma** [comment]
Basta con que los vehículos de emergencia se acerquen al punto más cercano factible.

**Comment by tamycova** [comment]
@rpalmaotero en el borde superior las direcciones son abajo/arriba , por lo que son entradas o salidas (tiene sentido que un auto se dirija hacia el borde), pero en el borde inferior la direccion es derecha, por lo que hacer que entre un auto ahi es como hacer que magicamente aparezca de lado, esas igual son consideradas "entradas" o solo si la direccion es perpendicular al borde?

**Comment by rodolfopalma** [comment]
Eso queda a tu criterio y debes detallarlo en el README. Lo importante es siempre respetar la restricción de número máximo de autos por calle.

**Comment by jnrosenbluth** [comment]
Me sumo a la pregunta de tamycova: Yo habia definido calles como entradas y salidas siesque cumplían estar en el borde, pero solo si ademas su dirección era perpendicular a ese borde (entonces si tenia una calle en el borde inferior con direccion a la derecha, ya no la consideraba entrada ni salida por ser paralela al borde).
