### ISSUE TITLE
Variable de entorno Path

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#32]
Me di cuenta que no tengo la variable de entorno Path. ¿Es malo? ¿Cómo lo agrego? ¿Debo llorar?

**Comment by lopezjurip** [comment]
1- Es malo, sí.
2- Depende de tu sistema operativo.
3- Si estás en Windows, sí.

**Comment by btkramm** [comment]
Estoy en un Win7 x64 :/. Me di cuenta de esto cuando pip install no funcionaba y un amigo me dijo que tenía que agregar una ruta al Path. Ayuda!

**Comment by bcsaldias** [comment]
Revisa si estás viendo las variables de entorno del sistema o las del
usuario. Prueba creándolas y avísanos cómo te va !

**Comment by aaossa** [comment]
Si no has podido hacer lo que dijo Belén puedes usar [**este gist que hice**](https://gist.github.com/aaossa/46c7cbf911bc195e6eb7) el cual debería definir _PYTHONPATH_ como variable del sistema. 

Por ahora cerrare esta issue, pero avisanos si pudiste arreglarlo :grin:

**PS:** El archivo es de extensión `.bat` y debes ejecutarlo como administrador :+1:
