### ISSUE TITLE
Uso SimPy Tarea 04

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#320]
¿El uso de SimPy esta restringido para la parte de reconstruccion, o uno puede elegir usarlo para toda la tarea?

**Comment by AlfonsoIgnacioV** [comment]
Hola,  en una parte dice, casi al final: "Se debe simular usando eventos discretos para la primera parte y solo donde se especiﬁca SimPy3". Entonces yo asumiría que sólo se puede usar donde haces la reconstrucción y sí estaría restringido. Saludos!

**Comment by spiza** [comment]
Qué dicen los jefes? Es obligatorio usar DES en la parte uno, y simpy en la parte dos?

**Comment by robocop6** [comment]
No soy jefe :') pero puedo contestar:

Efectivamente, simpy está restringido para la parte 2, y deben hacer simulación DES en forma "manual" para la primera parte.

**Comment by Arios16** [comment]
Ok, gracias.
