### ISSUE TITLE
Dirección calles mapa.txt

### ISSUE THREAD

**Issue by icrocco** [IIC2233-2015-2/syllabus#323]
Si estoy leyendo bien el mapa, creo que tengo un problema: las calles no tendrían una dirección lógica. Me explico: por ejemplo, la calle en la fila 16 de la interfaz gráfica, salvo en la columna 20 todas las calles tienen dirección "abajo", pero lo lógico es que recorrieran de derecha a izquierda o viceversa en este caso.

¿Soy yo o hay algo raro efectivamente?

**Comment by rodolfopalma** [comment]
Mira #316. Ahí aclaramos que a las coordenadas del archivo hay que aplicarles la siguiente transformación cuando se agregan a la interfaz: `(i, j) -> (j + 1, i + 1)`.

**Comment by icrocco** [comment]
Aahh, perfecto. Estaba considerando sólo el desplazamiento en 1, no que cambiaban de eje ;).

¿Entonces quedaría así?
![t4](https://cloud.githubusercontent.com/assets/13770520/10548140/21b67c00-740f-11e5-92a2-18866d4c85ee.png)

**Comment by rodolfopalma** [comment]
Sí, se ve bien!

**Comment by icrocco** [comment]
Gracias!
