### ISSUE TITLE
Destino Taxis

### ISSUE THREAD

**Issue by icrocco** [IIC2233-2015-2/syllabus#324]
¿El destino aleatorio puede ser tanto calles como edificios, o los destinos debieran ser siempre casas o edificios de servicios (no le podría pedir al taxi que me deje en una calle)?

**Comment by rodolfopalma** [comment]
Este aspecto de la simulación queda a tu criterio, preocúpate de detallarlo en el README.

**Comment by icrocco** [comment]
;) Gracias!
