### ISSUE TITLE
[T04] Problema con la gui

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#325]
al tratar de poner la gui en mi simulacion me dice esto:

Traceback (most recent call last):
  File "simulacion.py", line 73, in <module>
    grilla_simulacion = GrillaSimulacion(app)
TypeError: **init**() takes 1 positional argument but 2 were given

en el main solo tengo esto:
# inicio

app = QtGui.QApplication([])
grilla_simulacion = GrillaSimulacion(app)
grilla_simulacion.show()

Simulacion(grilla_simulacion, 50)
DESPUES = time()
print("Se demoro", DESPUES - ANTES)
# para terminar

app.exec_()

**Comment by lopezjurip** [comment]
Usa Markdown para escribir lo que sea código o mensajes:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by rodolfopalma** [comment]
Se actualizó anoche. Hazle pull al syllabus y copia la carpeta `gui` a tu repo.

**Comment by yackpott** [comment]
funciono
