### ISSUE TITLE
Se puede modificar el GUI?

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#326]
Hola! 

¿Podemos modificar / agregar algunas funciones en el script del gui?

**Comment by robocop6** [comment]
La tarea se evaluará con la interfaz gráfica entregada. No puedes modificar `gui.py` en tu repo. Si quieres proponer cambios específicos, envía un mail a @bcsaldias para ver si pueden incluirse y actualizar la interfaz para todos.

Saludos!

**Comment by raiperez** [comment]
Lo que pasa es que actualmente al hacer que el gui muestre un auto en una
ubicacion, elije un estilo de auto al azar (camioneta, convertible o
normal), entonces cuando quiero quitarlo de su posicion actual para
agregarlo al cuadrado del lado (para mostrar su movimiento) el auto
mostrado va cambiando de imagen :/

**Comment by fgvenegas** [comment]
Comentó para saber

**Comment by rodolfopalma** [comment]
Se agregaron métodos nuevos a la interfaz (`agregar_convertible`, `agregar_sedan` y `agregar_pickup`) que no son aleatorios. Igual se conservó `agregar_auto` para que la interfaz sea compatible con código anterior.
