### ISSUE TITLE
[Tarea 04] dudas varias sobre las calles

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#327]
1) si hay dos calles pongo dos semaforos seguidos?
2) que hago si "choco" contra una casa, ya que podria quedarme atascado si voy por alguna direccion y me topo con una casa y no hay mas caminos.

**Comment by robocop6** [comment]
1) Puedes poner dos semáforos, pero tendrías que preocuparte de que estén "sincronizados" de modo que ambas calles adyacentes tengan verde al mismo tiempo y así, cuando esté en rojo, los vehículos de la calle perpendicular puedan atravesar la intersección completa. Es decir, que ambos semáforos se comporten como un solo semáforo. O lo otro que puedes hacer, es tener solo un semáforo, para ambas calles (de modo que al final, el funcionamiento sería el mismo).

2) Si se da el caso, puedes hacer que el auto ingrese a la casa (y que cuente como auto que "se fue de la ciudad").
