### ISSUE TITLE
¿Como puedo disminuir el tamaño de la ventana de pyqt? 

### ISSUE THREAD

**Issue by menavarrete** [IIC2233-2015-2/syllabus#328]
pregunto porque no puedo visualizar las 20 grillas de la ventana...

**Comment by robocop6** [comment]
Solo abre el programa Designer, abre el archivo `grilla_simulacion.ui` y disminuye el tamaño al objeto `simulationGrid` (es una `QGridLayout`), que es ese "cuadro con borde rojo".

Luego, guarda los cambios. Pero ten cuidado de **hacerlo en tu repo: ¡no modifiques el syllabus!**

**Comment by menavarrete** [comment]
gracias

**Comment by santiagocruzb** [comment]
![screen shot 2015-10-18 at 8 42 14 pm](https://cloud.githubusercontent.com/assets/13748925/10567367/c632627e-75d8-11e5-9747-b16f54afce4c.png)
Editar eso
