### ISSUE TITLE
Incendios

### ISSUE THREAD

**Issue by clagos4** [IIC2233-2015-2/syllabus#329]
Podemos suponer que ni la comisaria, ni la bomba de bomberos, ni el hospital se incendian, ni son robados, ni hay enfermos?

**Comment by robocop6** [comment]
En el enunciado, dice que:
- Respecto de los incendios, "los edificios de servicios no pueden incendiarse ya que tienen sistemas anti-incendios".
- Respecto de los robos y enfermos, estos son eventos que ocurren en las **casas**.

Así que no es necesario suponerlo: está explícito en el enunciado :stuck_out_tongue_winking_eye:
¡Saludos!
