### ISSUE TITLE
Duda T01: "El profe $%&# me quitó el permiso".

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#33]
"Podrá quitarle el permiso posteriormente, incluso si el alumno ya inscribió aquel ramo. En este caso se lleva a cabo el mismo proceso que ocurre cuando un alumno bota un ramo."

¿Me están diciendo que si el profe quita el permiso, se quita el ramo al alumno?

**Comment by mbucchi** [comment]
Sip. Algunos profesores son unos desalmados :disappointed:. Ojo que esto es solo para los alumnos que requieran inicialmente su permiso especial. Un profesor no le puede botar un ramo a un alumno cualquiera que haya tomado su ramo de forma lícita.
