### ISSUE TITLE
Relación simulación-GUI

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#330]
Hola
No entiendo cuál es la idea del GUI una vez que haya terminado la simulación, al ejecutarlo se deberían mover los autos, ver los incendios, las ambulancias mover, etc o el GUI se muestra estático en ciertos momentos de la simulación y todo lo demás se printea, por ejemplo "ladrona x entra a casa y". Eso ojalá se entienda 

Edit: aprovechó de preguntar, la tarea se revisará con el mismo mapa.txt que nos dan? Para asumir las posiciones de entrada y salidas de autos, que sería siempre las mismas

**Comment by fgvenegas** [comment]
En base a la pregunta misma, sería mejor hacer la simulación de una y después pasarla al GUI o ir haciendo ambas cosas a la vez?

**Comment by robocop6** [comment]
La idea de la GUI es que, mientras que vaya corriendo la simulación, puedas ver si está pasando algo extraño en la interfaz para identificar errores. Es decir, la simulación y el display en la interfaz son simultáneos.

Sin embargo, si vas actualizando la interfaz cada vez que se cambia algo en la simulación, no vas a poder ver mucho pues los cambios serán muy rápidos. Para esto, existe el atributo `tiempo_intervalo` en la clase `GrillaSimulacion` (revisa el [ejemplo](https://github.com/IIC2233-2015-2/syllabus/blob/master/Tareas/T04/ejemplo_gui.py)) que permite que, aunque la simulación le haga cambios muy rápidos a la grilla, estos solo se actualicen en la ventana cada intervalos iguales a `tiempo_simulacion`.

**Comment by robocop6** [comment]
Respuesta al EDIT:

No puedes asumir que las posiciones de entrada y salida de autos serán siempre las mismas. Debes identificarlas a partir del archivo.

Saludos!

**Comment by fgvenegas** [comment]
Vale gracias por todas las respuestas! Lo último, estamos trabajando todos con mapas distintos ? es que he visto otros mapas y no se ven igual al mío

**Comment by robocop6** [comment]
¿Sí? Eso es extraño, todos deberían tener el mismo mapa.
¿Estás seguro de que hiciste el cambio de (i, j) a (j+1, i+1) como se dijo en una issue pasada?

**Comment by tamycova** [comment]
@fgvenegas  a mi me sale asi 
![screenshot from 2015-10-17 18 18 51](https://cloud.githubusercontent.com/assets/11545206/10561372/24426658-74fc-11e5-809f-6bf46db301f0.png)
@robocop6  hay alguna forma facil de modificar los tamaños en el gui? (no he visto el codigo) , esque no puedo ver lo que pasa en las ultimas dos filas :(

**Comment by robocop6** [comment]
@tamycova
Creo que te está pasando lo que a tu compañero en #323, y que fue resuelto en #316
Para el tamaño, revisa #318.

**PD: Revisen issues pasadas antes de postear!**
Sus ayudantes también tenemos otras cosas que hacer :persevere:

Saludos!

**Comment by fgvenegas** [comment]
A mi me salia como a la Tami D: voy a reivsar que onda

**Comment by tamycova** [comment]
ajaja perdon! esque vi lo del +1 pero no lo de las coordenadas, gracias!
