### ISSUE TITLE
Posicionamiento de un lugar de servicio

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#331]
Hola! 
Para ayudarme hice que las calles tuvieran su sentido. Si posiciono un servicio de emergencia en el punto rojo, no tendrá acceso para llegar a casi todo el mapa. Que ocurre en ese caso?
![pregunta](https://cloud.githubusercontent.com/assets/13748925/10561171/510447f2-74f6-11e5-9ea3-31bf5edaf761.png)

**Comment by rodolfopalma** [comment]
Es un caso parecido a lo que preguntaron en #319. Lo importante es que el vehículo de emergencia quede en el lugar más cercano factible.

**Comment by santiagocruzb** [comment]
Pero como va a ser posible que si tiene una emergencia en cualquier lugar de la ciudad, tiene que dejar el auto en el cruce de abajo a la izquierda. No tiene sentido.

**Comment by gafigueroa** [comment]
Los servicios de emergencia tal vez no se van a encontrar nunca en el lugar ideal, ya que van a haber sectores de la ciudad a la que no van a poder llegar, pero la idea es encontrar la mejor posición de los servicios dado los espacios libres que hay.
Al final, que posicionamiento minimiza los daños, no necesariamente ese posicionamiento va a ser el ideal y solucionar todos los problemas de la ciudad, pero va a ser el mejor dada las condiciones.

**Comment by fwzapata** [comment]
A tu mapa le falta la ultima linea de abajo, la ultima fila tiene una calle que va toda a la derecha, asi si puede llegar a cualquier parte del mapa.
:3

**Comment by ghost** [comment]
pero los mapas pueden tomar cualquier forma. Puede que creen uno en que no exista esa calle.
