### ISSUE TITLE
Semaforos

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#332]
Los semaforos tienen que funcionar bien cierto? osea en una interseccion si uno esta en rojo el otro en verde? o puedo darles valores aleatorios al colocarlos en las esquinas?

**Comment by robocop6** [comment]
Efectivamente, si uno está en rojo, el de la otra calle debe estar en verde. ¡No dejes que choquen! ;)

**Comment by tamycova** [comment]
gracias!
