### ISSUE TITLE
Incendios

### ISSUE THREAD

**Issue by dpassi** [IIC2233-2015-2/syllabus#333]
No se explica bien el tema del peso de los incendios, hay dos posibilidades de abordarlo:
1. Primero encontrar el tiempo del proximo incendio, luego ver de que material sera la casa que se quemara (random 0 a 23) y luego determinar random cual de esas casas se quema.
2. Primero encontrar el tiempo del proximo incendio, luego tirar un random entre 0 y la suma del peso de todas las casas y esa casa en especifico se quema?

Creo que apuntan a que lo hagamos de la forma 2, pero si se ve desde el punto de vista de los grandes numeros, todas las casas tendrian el mismo peso probabilistico....

2/1000 casi igual a 10/1000

Gracias!!

**Comment by spiza** [comment]
Yo creo que estai enfocándolo mal. Me tinca que primero vez cual es la casa que se quema ( usando la distribución de cada casa ), y posterior a eso se calcula el random de tiempo 

Enviado desde mi iPhone

**Comment by dpassi** [comment]
El tiempo que distribuye el siguiente evento (incendio) es independiente de la casa que sea asique da lo mismo si eso se hace antes o despues.

Mi pregunta va enfocada al tema del peso probabilistico, que no está bien explicado,
Algún ayudante que haya creado la tarea?

**Comment by alopez7** [comment]
Digamos que en total hay 3 casas con peso 10, y dos casas con peso 15. la probabilidad de que el incendio sea en una casa específica con peso 10 es 10/peso total = 10/60 = 1/6, y la probabilidad de que el incendio sea en una casa específica con peso 15 es 15/60 = 1/4. Es por esto que mientras más peso probabilístico, más probabilidades de tener un incendio.
El tiempo transcurrido entre incendios no tiene nada que ver con los materiales. Simplemente hay un incendio cada cierto tiempo, y cuando ocurre, se usa el random que determina la casa afectada  usando lo de los pesos.

**Comment by dpassi** [comment]
En tu ejemplo que tiene pocas casas es logico lo que planteas pero en la tarea hay muchas mas casas, suponiendo que la suma de todos los pesos de las casas sea 1000.

La probabilidad que la casa especifica de madera numero X se queme es 10\1000 y la de ladrillo numero Y es 7\1000 al hacerlo de esta forma no se fija tanto la diferencia entre una casa de un material y otra... Pero filo si es de esa forma, solo que encontre que le quitaba todo el realismo al peso de probabilidades de las casas..

**Comment by alopez7** [comment]
Digamos que tenemos 2 casas madera de peso 10 y 2 casas de metal de peso 2. La probabilidad individual de cada casa de quemarse es muy alta, pero la probabilidad de que la casa quemada sea de madera es 20/24 = 5/6. 
Ahora si aumentamos el número de casas a 2000 casas de madera y 2000 casas de metal, cada casa individual tiene menos probabilidades de incendiarse pero la probabilidad de que el incendio sea en una casa de madera sigue siendo 5/6, y lo mismo para las de madera.
