### ISSUE TITLE
Gui Tarea 4

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2015-2/syllabus#335]
A diferencia de lo que se esperaría, la clase "GrillaSimulacion"  en todos sus métodos , excepto por el "agregar_auto", no considera los parámetros "theta" y "reflection" a pesar de recibirlos. En la práctica esto afecta en que no es posible por ejemplo mostrar en pantalla un carro de bomberos rotado en 90° o reflejado, ni ningún otro vehículo de emergencia, (siempre se muestra su imagen por defecto).
En tal caso hacemos nuestro código de modo que ignore la inclinación y reflexión de los vehículos de emergencia, porque al fin y al cabo no tiene sentido implementarlo, o lo implementamos de todos modos aunque esto no sea visible en pantalla ?

**Comment by rodolfopalma** [comment]
Tienes razón, fue un error de tipeo. Se soluciona con la última actualización de la interfaz gráfica.
