### ISSUE TITLE
Nueva Interfaz

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#337]
hola de nuevo, gracias a las respuestas anteriores,  pero con el cambio de archivo de mapa.txt al parecer se aumento el tamaño del mapa pero la grilla grillar_simulacion.ui sigue siendo de 20x20 porque tira error cuando se pone un atuo/casa mas alla del 20. Gracias

**Comment by rodolfopalma** [comment]
Ahora `GrillaSimulacion` recibe dos parámetros adicionales (que por defecto valen 20, para que sea compatible con códigos anteriores) donde puedes definir el número de filas y columnas de la grilla.

**Comment by KatherineGuerrero** [comment]
Y cómo se usaría?
Porque puse esto:
    app = QtGui.QApplication([])
    grilla_simulacion = GrillaSimulacion(app, 20, 25)
Y me tira el mismo error.
¿Dónde se agregan los parámetros?

**Comment by btkramm** [comment]
subieron un .ui que pesa 1 kb :s. Indico 22x25 pero me sigue creando algo que creo es 2x2. No entiendo nada.

**Comment by cdonoso** [comment]
Al parecer lo cambiaron de nuevo y ya no acepta esos 2 parámetros. :sob:

**Comment by fgvenegas** [comment]
si funcionan, pero es 23x25, no 22x25 como sale en el .txt

**Comment by rodolfopalma** [comment]
@btkramm @cdonoso pudieron solucionar el problema?

**Comment by cdonoso** [comment]
Por mi parte si! Gracias!!
