### ISSUE TITLE
nuevo mapa.txt

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#339]
No entiendo algo con el nuevo mapa. Me dice que tiene dimensiones (22x25), y parte del 0,0, pero la ultima posicion es la (24x22). ¿No deberia ser (24x21)? (ya que parte desde 0,0). No se si es un error o si debemos simplemente ignorar coordenadas como esa.

**Comment by ghost** [comment]
Lo otro es que el enunciado dice que las dimensiones están en formato i,j (que supongo se refiere a rows,cols), y que el resto de los elementos (las lineas de texto que describen las casas y las calles) están también en ese formato, pero al mirarlas parecieran estar como (cols, rows).

**Comment by btkramm** [comment]
No entiendo nada. El archivo dice 22x25, pero las cosas están posicionadas como 25x22, y ni siquiera eso, porque llegan hasta (24, 22) cuando debería ser (24, 21) cuando debería ser (21, 24).

Pueden hacer un post explicando los cambios finales ¿?

**Comment by ghost** [comment]
A mi se me armo bien el mapa al final haciendo esto: Cambie la primera linea de (22,25) a (23,25) para que incluyera las coordenadas (x,22). Despues, construi todo asumiendo que la primera linea estaba en formato (i,j) y todas las de despues en formato (j,i).

**Comment by tamycova** [comment]
Si, podrian hacer un post explicando como funcionan finalmente las coordenadas de la grilla? he perdido dm tiempo en esto jaja ademas si se trabaja aparte con una grilla interna que si funciona con fil,col como cualquier grilla hay que hacer cambios a  cada rato para trabajar con la sim

**Comment by aaossa** [comment]
@rpalmaotero , @mjjunemann

**Comment by ghost** [comment]
definitivamente hay algo mal con el mapa de ejemplo. Al correrlo las calles me daban raro, asi que le cambie a imagenes pa ver visualmente las direcciones y me tiro esto:
![image](https://cloud.githubusercontent.com/assets/13824744/10564794/8442d1b4-7597-11e5-8683-678f8c28d8cc.png)

**Comment by aaossa** [comment]
No estarás confundiendo las filas con las columnas? Así el mapa tendría mas sentido

**Comment by ghost** [comment]
Si, obvio, pero el txt no tiene bien definida las dimensiones. Si te fijas, todas las instrucciones abajo de la del tamaño del grid estan definidas como (j,i). La solucion que le habia encontrado era asumir que habia que tomarlas de esa forma (j,i), pero al imprimir me sale lo de arriba. Al final el tema es que no se con que formato nos vamos a quedar.

PD: se me arreglo al final dejando la primera fila como 25x23 en vez de como estaba al principio (22x25)

**Comment by btkramm** [comment]
![image](https://cloud.githubusercontent.com/assets/13784853/10564828/84a2e814-7598-11e5-81d9-886b877a3d8c.png)

Qué es esto.

**Comment by ghost** [comment]
Eso a mi me paso cuando hacia que se generara todo internamente y despues mostrara la ventana. Se me arreglo al poner que primero muestre  (.show()) y despues genere todo (trata a ver si te funciona jaja)

**Comment by aaossa** [comment]
Ah si, yo también hice eso. Hay que poner el show antes de empezar a colocar los elementos.

**Comment by btkramm** [comment]
Solucionado :) Aún no entiendo si las cosas están en i,j o j,i. Al hacer un mapa 23x25 sabiendo que hay casas en el (24, 22) no cobra sentido.

![image](https://cloud.githubusercontent.com/assets/13784853/10564867/5561abc0-7599-11e5-93a9-19a4a062bfd7.png)

**Comment by ghost** [comment]
Pon en la primera fila 25x23 y despues asume que todo todo esta en j,i. Eso ahora me resulto asi:
![image](https://cloud.githubusercontent.com/assets/13824744/10564868/5728bad4-7599-11e5-994a-f627bdcaedf0.png)

**Comment by tamycova** [comment]
@jnrosenbluth puedes subir una pic del nuevo mapa bien con las direcciones de las calles?

**Comment by ghost** [comment]
la subi, esta ahi en el comentario ariba del tuyo. (creo que asi deberia verse, en vola esta mal xD)

**Comment by btkramm** [comment]
en lo que a mi respecta, cuando estamos haciendo GrillaSimulacion(app, rows, cols) en realidad estamos haciendo GrillaSimulacion(app, cols, rows)

**Comment by tamycova** [comment]
y cuando hagas cualquier cosa de la sim, hay que pasarle (j,i)

**Comment by btkramm** [comment]
yo se las doy (i, j). tan solo que al crear la grilla de simulacion los di como (app, cols, rows)

**Comment by fgvenegas** [comment]
igual seria bueno que alguien se pronunciara oficialmente porq sino al final cada uno lo hace como quiere y no sabemos quien esta bien

**Comment by cdonoso** [comment]
No hagan cambios cuando quedan 1 semana para la entrega :cry:

**Comment by tamycova** [comment]
porque no simplemente dan vuelta los parametros en el gui, onda de x,y a y,x.. asi no hay que dar vuelta el map.txt y cuando le pongo 2,10 me pone 2 hacia abajo y 10 a la derecha como deberia ser y no 10 para abajo y dos para el lado (esta indexando al reves)

**Comment by aaossa** [comment]
Vean el aviso publicado en SIDING. Si siguen con dudas o encuentran algo avísennos :+1:

**Comment by tamycova** [comment]
![screenshot from 2015-10-18 15 16 22](https://github-cloud.s3.amazonaws.com/assets/11545206/10565624/8881884c-75ab-11e5-9fde-61517704309f.png)

**Comment by otro-felipe** [comment]
Me molesta que esa casa este ahi en 1, 15 (0, 14 en el archivo). La podemos cambiar para que quede bonito y no pareciese que la calle como que se hace mas angosta?

**Comment by rodolfopalma** [comment]
Puedes cambiarla si te acomoda para desarrollar la simulación, pero recuerda que la corrección será con mapas distintos.
