### ISSUE TITLE
Humilde peticion

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#341]
Hola, hago este issue para pedirles un poco mas de plazo para esta tarea, ya que recien hoy pudimos empezar a usar bien la interfaz grafica que tan complicados nos tenia. Solo si es que no causa mucho problema, ya que varios comenzamos recien hoy la tarea debido a que no pudimos resolver todos los problemas de la gui :(

**Comment by jgmontoya** [comment]
+1

**Comment by fgvenegas** [comment]
+1

**Comment by bcsaldias** [comment]
Estimad@s,

La tarea tiene 2 partes:
1.- crear toda la simulación (que es el objetivo de la tarea).
2.- mostrarlo gráficamente.

Por lo que si su programa está bien en cuanto a modelo de simulación no debería tomarles tiempo cambiar el input de la interfaz. Sobre todo porque ya deben haber aprendido a parsear inputs de forma genérica (ya vamos en la tarea 4 :) )

La tarea se subió hace casi una semana (los problemas se resolvieron hace poco porque hace poco ustedes mismos propusieron cambios, de la forma en que lo habíamos planteado los ayudantes los problemas se resuelven con el material original) así que no hay más plazo.

Saludos !

**Comment by cdonoso** [comment]
¿Pero entonces cual es la versión a ocupar? 
Antes me funcionaban los códigos y con los nuevos archivos no :sob: 

Saludos

**Comment by bcsaldias** [comment]
La que habías descargado y te funciona :)

Usa la que te funcione, de hecho @mabucchi subirá otra versión aparte para
que no tengan problemas.

Saludos !
