### ISSUE TITLE
Semaforos

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#342]
El cambio de los semaforos se modela como evento? Pregunto porque en el enunciado no se mencionan como parte del grupo de eventos, pero dado que el cambio se produce cada cierto tiempo de simulacion, tendria sentido pensarlos asi.

**Comment by sitoro** [comment]
Al menos sabemos lo de #332 (Deben coordinarse de modo que no se produzcan accidentes)

**Comment by alopez7** [comment]
El cambio de los semáforos debe funcionar como un evento, o sino no funciona la simulación

**Comment by ghost** [comment]
gracias!
