### ISSUE TITLE
[T04] nuevo mapa

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#345]
las calles ahora casi todas son dobles a excepcion de una arriba a la derecha.
tenemos q modelarlo considerando q cada calle tiene dos pistas o ya vienen esas dos pistas incluidas en el mapa (de ser asi, q hacemos con la pista q falta en la excepcion? ya que hay una casa en donde deberia haber una pista para q sea doble en todo el mapa)

**Comment by rodolfopalma** [comment]
Con el nuevo mapa considera un bloque, una calle.

**Comment by jgmontoya** [comment]
O sea en cada bloque puede solamente haber 1 auto?

**Comment by rodolfopalma** [comment]
Claro.
