### ISSUE TITLE
Me obligan a chocar casas(?)

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#347]
Que pasa en un caso como en el de la foto que al llegar a la esquina, aleatoreamente puedo escoger seguir adelante, o doblar, pero al doblar estaria chocando contra una casa (es raro tambien que sea la unica parte del mapa donde sucede algo asi, no sera error?)

![image](https://cloud.githubusercontent.com/assets/13748708/10568342/b17a9370-760e-11e5-99c2-980802fdd9a3.png)

**Comment by alopez7** [comment]
Tienes que elegir aleatoriamente la dirección pero sin contar seguir derecho, porque no puedes chocar. de hecho en es esquina solo debería poder seguir hacia abajo.
