### ISSUE TITLE
Gui imagen agregar auto

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#349]
Existe alguna forma de actualizar la imagen de un auto sin que esta cambie? Ya que agrego un auto y al hacerlo avanzar el auto va cambiando de imagen. no podria haber un parametro en el metodo agregar auto donde uno pueda cambiar el color? Haria la interfaz mucho mas clara.

**Comment by mbucchi** [comment]
Hola! Cada auto tiene su propio método en la interfaz:

``` python
grilla.agregar_convertible(x, y) # Agrega un convertible en la posición x,y
grilla.agregar_pickup(x, y)      # Agrega una camioneta en la posición x,y
grilla.agregar_sedan(x, y)       # Agrega un sedán en la posición x,y
```

Para esto tendrías que decidir desde un principio qué auto estás agregando a la ciudad, pero de ahí en adelante sería más fácil mantener la consistencia. Espero que esto aclare tu duda.

Saludos!
