### ISSUE TITLE
Nombres de las personas

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#35]
¿Podemos asumir que los nombres de las personas no se van a repetir?

**Comment by ignaciourzuaf** [comment]
A mi me paso que probé con un nombre de usuario al azar y habían 3 personas como el mismo usuario. ¿Afecta en algo eso? (tienen distintos nombres)

**Comment by felipehv** [comment]
A mi me salen 5 repetidos (['jlopez', 'rbrown', 'agarrido', 'emolina',
'ajimenez'])

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

**Comment by javierlopeza** [comment]
¿Cómo lo hacemos entonces para cuando los usuarios quieran ingresar al sistema? Hay usuarios repetidos, entonces ¿como va a saber el sistema a que persona se refiere? ¿usamos las claves de los usuarios para discriminar?

**Comment by felipehv** [comment]
Yo creo que si, eso si Juan Lopez se repite el usuario y la contraseña, no
se como sera en ese caso.

[('Juan Lopez', 'jlopez', 'm6j0NI'), ('Juan Lopez', 'jlopez', 'm6j0NI'),
('Robert Brown', 'rbrown', 'I5mJ5c2fg'), ('Romina Brown', 'rbrown',
'YG1pn058Fi'), ('Adrian Garrido', 'agarrido', 'd2OZY5nh'), ('Alma Garrido',
'agarrido', 'poT8NHO'), ('Emma Molina', 'emolina', 'x9UC1LR'), ('Elizabeth
Molina', 'emolina', 'WqCBL3Y'), ('Alejandro Jimenez', 'ajimenez',
'Y8Tpm6n'), ('Alondra Jimenez', 'ajimenez', 'zT4YK5')]

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

**Comment by mbucchi** [comment]
Los nombres sí se pueden repetir, los usuarios no debiesen repetirse :scream: . Arreglo los datos en un rato. Gracias por avisar.
Saludos!

**Comment by mbucchi** [comment]
Ok, el archivo nuevo _**debiese**_ no tener ninguna repetición de usuarios. De todas formas pueden asumir que los usuarios serán únicos, no así los nombres.
Éxito!

**Comment by otro-felipe** [comment]
¿Si se pueden repetir los nombres, como sabremos con exactitud quienes son las personas que un usuario encuentra bacán?

**Comment by dpassi** [comment]
Me sumo al comentario de @MainScientist, al haber gente con el mismo nombre tendremos problemas al ver la "bacanosidad"

**Comment by javierlopeza** [comment]
Opino que las listas de idolos de los alumnos deberían contener los usuarios de los idolos, para poder saber con seguridad a quien se refiere.

**Comment by mbucchi** [comment]
@MainScientist @djpassi @javierlopeza Tiene bastante sentido lo que dicen, pero en todo caso, según lo que acabo de revisar, no existe ninguna colisión de nombres por lo cual no debiese haber ningún problema.
Saludos!
