### ISSUE TITLE
Doblar en segunda fila

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#350]
Si un auto quiere doblar en segunda fila solo podra hacerlo si no obstruye a ningun otro auto, o si viene un auto por la primera fila y no va a doblar, este auto se detiene para que el primero (que viene por la pista izquierda) doble?

**Comment by mbucchi** [comment]
Hola! Cada auto tiene su propio método en la interfaz:
```python
grilla.agregar_convertible(x, y) # Agrega un convertible en la posición x,y
grilla.agregar_pickup(x, y)      # Agrega una camioneta en la posición x,y
grilla.agregar_sedan(x, y)       # Agrega un sedán en la posición x,y
```

Para esto tendrías que decidir desde un principio qué auto estás agregando a la ciudad, pero de ahí en adelante sería más fácil mantener la consistencia. Espero que esto aclare tu duda.

Saludos!

**Comment by alopez7** [comment]
El auto que dobla en segunda fila debe ver si no viene nadie en la otra fila. Si viene otro auto, espera para doblar. Queda a tu criterio si quieres hacer que si espera mucho puede decidir seguir derecho, pero tienes que especificarlo en el readme
