### ISSUE TITLE
Gui 2.0

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#352]
Estuve probando el Gui 2.0 y junto a un amigo hicimos los cambios en nuestro codigo y no muestra nada (cuando el gui normal si lo hacia) y tampoco tira error, solo queda esperando. Gracias

**Comment by djnoguera** [comment]
A mi me pasa lo mismo, comento para saber..

**Comment by fgvenegas** [comment]
Me funciono ahora, despues de varios cambios, al final habia que mantener el (i+1, j+1) y ponerle actualizar

**Comment by aaossa** [comment]
Varios cambios o solo el (i+1, j+1)?

**Comment by fgvenegas** [comment]
Bueno quizas "varios cambios" no es la palabra adecuada, pero estuve probando distintas cosas hasta que funciono, tambien inverti las dimensiones con las que inicializo la grilla (en mi caso estaban al reves)
