### ISSUE TITLE
Cambiar tamaño de la grilla

### ISSUE THREAD

**Issue by ManuelBeckerT** [IIC2233-2015-2/syllabus#354]
Cuando usaba el gui antiguo pude cambiar el tamaño de la grilla para ver todo el mapa de la ciudad en la pantalla. Ahora con gui2.0 no puedo editar el grilla_simulacion.ui para lograr lo mismo. Qué debo editar para cambiar el tamaño nuevamente?

**Comment by spiza** [comment]
Debes cambiar el gui. En una parte, creo que en el init del gui dice 800// max(rows, colls).. Ahí cambias el 800 por un número menor y voila

Enviado desde mi iPhone

**Comment by ManuelBeckerT** [comment]
Gracias

**Comment by cdonoso** [comment]
Manuel :heart: jajajaja exacto se cambia un parámetro en el init
