### ISSUE TITLE
Tiempo en que taxis encuentran pasajeros

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#356]
En el enunciado dice que los taxis vacíos encuentran un pasajero en un tiempo aleatorio exponencial con lambda = 1/40. No se especifica la unidad de ese tiempo. ¿Se encuentra un pasajero cada 40 segundos? ¿Cada 40 segundos?

**Comment by alopez7** [comment]
Si, son segundos

**Comment by javierlopeza** [comment]
Gracias.

**Comment by alopez7** [comment]
Pero solo cuando está vacío

**Comment by javierlopeza** [comment]
Sí sí, en dejarlo se demora lo que se demora en dejarlo en su destino nomás.
