### ISSUE TITLE
Calles de una sola pista

### ISSUE THREAD

**Issue by VinceValence** [IIC2233-2015-2/syllabus#357]
En el enunciado dice que las calles de Progralandia son de dos pistas, pero, basándome en la información de #345 (un bloque, una pista) y en el hecho de que hay en el nuevo mapa (mapa fix.txt) un bloque solo, tiendo a asumir que el enunciado ya no es certero al referirse a las calles y que sí es posible tener calles de una pista. ¿Estoy en lo correcto?

**Comment by alopez7** [comment]
Cada bloque de calle del mapa es una sola pista, y dos bloques juntos conforman una calle de dos pistas
