### ISSUE TITLE
app.exec()

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#358]
Tengo el problema de que no se como correr la simulación y que se vaya actualizando la parte gráfica. Al correr app.exec salta a otro thread y no me deja seguir corriendo cosas (el loop) en el mail principal (vi que habían preguntado algo parecido antes pero las respuestas no me sacaron la duda).

**Comment by aaossa** [comment]
Revisaste [el ejemplo que subieron](https://github.com/IIC2233-2015-2/syllabus/blob/master/Tareas/T04/ejemplo_gui.py)? Quizás pueda serte de ayuda

**Comment by ghost** [comment]
ah, tengo que correr eso al final, y esa clase usarla como main. Yo estaba usandola como parte grafica nomas y tenia el main en otra parte.

**Comment by raiperez** [comment]
@aaossa el ejemplo que subieron no me corre; que hago?? D:  

(Se me abre la ventana y no aparece nada)

**Comment by aaossa** [comment]
Se supone que debería funcionarte... D: Si no te sale ningún tipo de error y estas usando exactamente ese archivo .py mañana preguntale a alguno de los ayudantes en clases por esto. Se supone que no deberías tener ningún problema. Asegurate de usar el archivo correcto y con la nueva interfaz. Recuerda: `git pull` :+1:

**Comment by raiperez** [comment]
No importa ahí lo logre! Lo que pasa es que ese ejemplo no ejecuta
actualizar en ninguna parte entonces no muestra nada.

Gracias!!
