### ISSUE TITLE
Problemas del Mapa ~Tarea 4 ~

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#359]
Hola buenas, tengo un pequeño problema:

De un momento a otro las calles de mi planilla ya no tienen separación, si bien funciona el programa, me incomoda por no saber la posición exacta de los autos :cry: Jajajajaja. 
¿Alguien sabe como hacer para que las calles vuelvan a estar con esa separación?

¡¡De ante mano Muchas gracias!!

**Comment by spiza** [comment]
Me paso eso mismo!! Como arreglarlo!

Enviado desde mi iPhone

**Comment by alopez7** [comment]
Sería bueno saber tu sistema operativo y ojalá una imagen del problema para entenderlo mejor.

**Comment by cdonoso** [comment]
![problema](https://cloud.githubusercontent.com/assets/13756718/10595946/a5aa3660-76de-11e5-815f-b7e0d3e85d52.png)

windows 8 de 32.

¿Y también se puede cambiar el nombre de ese archivo que se crea, en ves de Tarea 4 - IIC2233 a progralandia o no se? jajajaja :smile:

**Comment by benjavides** [comment]
Me pasó lo mismo

**Comment by rodolfopalma** [comment]
Tienen que cambiar el parámetro dentro de `self.simulationGrid.setSpacing(...)` a uno distinto de cero. Esa línea es la número 37 de `gui2.0/gui.py`.

**Comment by cdonoso** [comment]
Perfecto! :ok_hand:  por otro lado es posible cambiar el nombre de ese archivo que se genera? Da lo mismo que no influya en la tarea, simplemente quiero crear algo más original jajaja

**Comment by icrocco** [comment]
Pero el mapa sigue siendo de 20x20 a pesar del .txt o no?? :disappointed_relieved:

**Comment by fgvenegas** [comment]
eso se lo entregas como parametro al crear la grilla de simulacion, viene por defecto en 20x20

**Comment by rodolfopalma** [comment]
@cdonoso Puedes hacerle las modificaciones que quieras para el desarrollo de la tarea, pero para efectos de corrección los ayudantes vamos a usar las versiones originales de las interfaces.
@fgvenegas exacto, @icrocco lo solucionaste?
