### ISSUE TITLE
Tope de horario

### ISSUE THREAD

**Issue by sebawarrior** [IIC2233-2015-2/syllabus#36]
Hola! una pregunta con respecto a la tarea 1... cuando hablan de topes de horarios es lo mismo con la realidad?, osea que puede topar cat-ayud, ayud-lab pero no asi cat-cat, cat-lab o lab-lab, o bien no puede topar nada con nada? Muchas gracias!

Sebastián Guerrero Núñez

**Comment by bamavrakis** [comment]
Hola!!
Es exactamente como tu dices, son los topes típicos, para hacer el problema lo más real posible.

Saludos!

**Comment by sebawarrior** [comment]
muchas gracias!!
