### ISSUE TITLE
Problema con la interfaz

### ISSUE THREAD

**Issue by sebawarrior** [IIC2233-2015-2/syllabus#361]
Hola, no se porque pero cuando corro el main me tira esto: 
![image 43](https://cloud.githubusercontent.com/assets/13771365/10618890/d7f4b0c2-7748-11e5-9713-7fd84fb5cb1d.jpg)
Hay que modificar el main para que aparezcan las casas como en las fotos que se han publicado?
y segunda cosa, al hacer la simulación creo mi clase simulación y la corro dentro del if **name** == '**main**':
?? Tengo esas grandes dudas, muchas gracias!

**Comment by aaossa** [comment]
Sí, tienes que modificar el _main.py_. Dice el enunciado, "para ver ejemplos de como utilizar la interfaz gráfica puedes revisar el **código de muestra** en _main.py_". Se supone que eso te muestre :grin:. Incluso te muestra cómo quitar elementos (en `(3, 3)` pone una casa y luego la quita)

Sobre la simulación, tendrás que utilizar los principales elementos que crees para la simulación desde el `if __name__ == '__main__': ...`. Recuerda que lo único que hace ese if es ejecutar el código que escribas ahí cuando llamas directamente al archivo, por lo que, para mantener el orden, crea tus clases antes de ese if y adentro llama lo que necesites para simular.

---

**Un poco mas sobre** `if name == '__main__'`

Tal como dije en la ayudantía, si ejecutas directamente ese archivo (*.py) la variable `__name__` tomará el valor `"__main__"`. Si utilizas ese archivo desde otro, importandolo como módulo, la variable `__name__` toma como valor el nombre del archivo que le está llamando.

**Comment by sebawarrior** [comment]
Dale perfecto muchas gracias!!
