### ISSUE TITLE
Asistir a Emergencias

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#363]
Cuando ocurre un evento (robo, incendio, asalto) quizas hay posiciones a las que no se pueden llegar, y que, como se dijo en otra issue, se debe llegar a la calle más cercana al lugar de la emergencia. Pero, aplicándo la simulación a la vida real, ¿deberíamos considerar un tiempo extra cuando los vehiculos se estacionan y "tienen que correr hacia el lugar de la emergencia y correr de vuelta a sus vehiculos"? ¿O queda a nuestro criterio? Gracias.

**Comment by rodolfopalma** [comment]
Queda a tu criterio el adicionar un tiempo extra (que efectivamente se ajusta mejor a la realidad), recuerda detallarlo en el README.
