### ISSUE TITLE
Duda vehiculos emergencia

### ISSUE THREAD

**Issue by Mapuentes** [IIC2233-2015-2/syllabus#364]
Tengo una duda con respecto, por ejemplo a un carro de bomberos que tiene que llegar a apagar una casa especifica, pero hay casas en las que no se puede acceder si no es yendo en contra del transito, entonces mi pregunta es si se asume que el vehiculo tiene que llegar a la calle mas cercana para apagar el incendio o no ?

PD:Estoy usando el primer mapa

**Comment by rodolfopalma** [comment]
Duplicado de #331. Debe acercarse al lugar más cercano factible.
