### ISSUE TITLE
¿Puedo modificar el límite de vehículos? (Tarea 4)

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#365]
Hola! En el enunciado se especifica que el límite de vehículos debe ser la mitad de las calles. ¿Esto incluye los vehículos de emergencias que podrían estar circulando en las calles? Si la respuesta es sí, podría pasar el caso de que un vehículo de emergencia no pueda salir a circular por haberse alcanzado el límite de vehículos en la ciudad, lo que me parece poco realista. Ante esto, pienso en tres soluciones:
1. Establecer un límite de autos/taxis, que sea la mitad de las calles menos el máximo de vehículos de emergencia que puedan estar circulando en simultáneo (3 vehículos de cada tipo de emergencia por 3 servicios para la primera parte más dos vehículos constructores en la segunda). De esta manera, en el caso de que estén todos los vehículos de emergencia circulando recién se podría alcanzar el máximo propuesto por enunciado
2. Dejar el límite igual y si sale un vehículo de emergencias cuando ya se alcanzó el máximo, "borrar mágicamente" un auto o taxi (no me gusta esta opción)
3. Que los vehículos de emergencia no cuenten para el límite de vehículos en circulación, es decir, que el verdadero caso límite sea la mitad de las calles más el máximo de vehículos de emergencia en simultáneo
¿Que debería hacer para este caso? Si tienen una solución mejor por favor ayúdenme. Gracias =)

**Comment by rodolfopalma** [comment]
Los 3 puntos que indicas tienen pros y contras (personalmente encuentro que la 1 y 3 son mejores). Manéjalo como prefieras, recuerda detallarlo en el README.

**Comment by tamycova** [comment]
puedo fijar arbitrariamente el numero de vehiculos? onda limite // 2, esque incluso con el limite la interfaz se ve como saturada

**Comment by rodolfopalma** [comment]
Si lo consideras necesario, no hay problema.
