### ISSUE TITLE
Intervalos de confianza

### ISSUE THREAD

**Issue by ralvarez94** [IIC2233-2015-2/syllabus#366]
Qué distribución usamos para el intervalo de confianza? Queda a criterio nuestro?

**Comment by rodolfopalma** [comment]
Puedes asumir que será normal, es decir, usa la siguiente fórmula:
<img width="255" alt="screen shot 2015-10-21 at 2 12 35 pm" src="https://cloud.githubusercontent.com/assets/6728087/10644243/f4294aa4-77fd-11e5-9635-0fe8b8be9f55.png">

**Comment by ralvarez94** [comment]
Ok, gracias

**Comment by bcsaldias** [comment]
X barra es la media de los datos. Sigma es la desviación estándar y n es la cantidad de datos :).

Hay librerías que se lo hacen automático, solo preocúpense de entregarle bien los datos :D

La gracia de esto es que al comparar con el resultado real veamos si el resultado real está dentro de su intervalo o no y no comparar con un solo número :D

**Comment by flobarrios** [comment]
@bcsaldias se puede usar scipy?

**Comment by bcsaldias** [comment]
Si

2015-10-26 3:23 GMT-03:00, Florencia Barrios notifications@github.com:
