### ISSUE TITLE
Vehiculos de emergencia

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#367]
Los autos de emergencia tambien deben ir obligatoriamente por la derecha? o seria muy en contra de las reglas hacer que para que lleguen mas rapido, vayan por la izquierda?

**Comment by flobarrios** [comment]
Comento para saber

**Comment by rodolfopalma** [comment]
Es buena idea, queda a tu criterio, recuerda detallarlo en el README.
