### ISSUE TITLE
Velocidad vehiculos

### ISSUE THREAD

**Issue by crxzadytho22** [IIC2233-2015-2/syllabus#368]
No me quedan claro como manejar los vehículos, estos se mueven aprox 60 cuadrados por minuto entonces se tiene que manejar como un evento? o cada vez que ocurre un evento se tienen que mover todos los vehículos al mismo tiempo y sincronizarlos?

**Comment by rodolfopalma** [comment]
El tráfico es una de las partes complejas de la simulación, no puedes asumir que los autos siempre se moverán aproximadamente 60 bloques por minuto, debido a que la velocidad de cada auto es una variable aleatoria y existen eventos que _desordenan_ el tráfico, tales como la alternancia de los semáforos, el bloqueo de los vehículos de emergencia, adelantamiento de vehículos, etc. Lo que nosotros esperamos es que implementes una buena modelación del tráfico de la ciudad mediante simulación por eventos discretos, tomando en cuenta todos los factores que te nombré.

**Comment by jgmontoya** [comment]
Dado que permanentemente hay autos moviéndose, ¿No sería más práctico hacer una simulación síncrona? Ya que de todas formas van a haber autos moviéndose a 1 cuadrado por segundo...

**Comment by crxzadytho22** [comment]
mi pregunta iba mas orientada a si se tiene que manejar como un evento la simulación del trafico en si, o cada vez que ocurra un incendio, robo o enfermo se tenga que actualizar el trafico de nuevo.

**Comment by ghost** [comment]
A mi tambien me entran dudas con eso. A un auto, en la ciudad que tenemos modelada, le toma entre 3 a 5 segundos llegar de una esquina a otra (pues pueden como máximo recorrer los 3 cuadrados que forman una cuadra en 3 segundos). entonces, si modelamos la llegada de un auto a la esquina como un evento (que se me ocurre que es la forma de hacerlo), la simulación la vamos a estar revisando constantemente cada 5 segundos o menos. Me da la impresión de que, al final, la simulación no va a actuar, para efectos prácticos, como una DES, puesto que independiente de cada cuanto hayan incendios o robos, si o si vamos a estar chequeandola cada una cantidad mas o menos fija de segundos (mientras que otros eventos ocurren cada horas).

**Comment by alopez7** [comment]
El tránsito vehicular es la parte principal de la tarea, y probablemente la más difícil. El tránsito también se debe tratar como un conjunto de eventos a pesar de que haya que chequear a cada rato. Se que no es muy proporcional el tiempo entre eventos de vehículos y los tiempos de los eventos grandes, pero era para darle más realismo a la simulación. No sería muy realista un incendio cada 2 minutos.

**Comment by crxzadytho22** [comment]
pero entonces se tiene que chequear cada segundo en la simulacion ? de esta manera un auto puede ser tratado como evento D:

**Comment by rodolfopalma** [comment]
@crxzadytho22 No pienses en revisar cada cierto tiempo los eventos que ocurren (lo que sería una simulación síncrona), sino que en los eventos que van a ocurrir durante la simulación. En particular, debido a la naturaleza de esta simulación, vas a tener una gran cantidad de eventos separados por intervalos cortos de tiempo. Lo importante es que calcules tus eventos y después veas en que tiempo ocurren, no al revés. Te recomiendo releer el [material de clases](http://htmlpreview.github.io/?https://github.com/IIC2233-2015-2/syllabus/blob/master/Material de clases/09_SIMULACIÓN/01-simulation.html) para entender bien las diferencias entre simulación síncrona y por eventos discretos.
