### ISSUE TITLE
Bacanosidad

### ISSUE THREAD

**Issue by orrios** [IIC2233-2015-2/syllabus#37]
Hola!
¿No hay ni un problema si utilizamos las bases de un algoritmo ya creado para medir popularidad? (correctamente referenciado por supuesto y modificado para que funcione en nuestro caso)
¿y se pueden importar paquetes que ayuden solamente con el manejo de matrices?
numpy se que se que se puede usar, pero scipy tambien?

**Comment by bamavrakis** [comment]
Hola!

Lamentablemente no puedes utilizar nada encontrado en internet para realizar los algoritmos pedidos en esta tarea, ya que la idea es que lo piensen y se les ocurra a ustedes. Como objetivo de la tarea (lo puedes ver en el enunciado) esta que aprendan a pensar en algoritmos, y dejarlos utilizar algoritmos de internet impediría este aprendizaje.

Saludos!!

**Comment by otro-felipe** [comment]
¿Y qué tan eficiente debe ser el método? ¿Cuánto tiempo se puede demorar a lo más

**Comment by bamavrakis** [comment]
Hola!

Mañana subiremos una explicación detallada sobre el tema de la bacanosidad, para despejar todas las dudas sobre ella.

Saludos!

**Comment by mjjunemann** [comment]
Si, vallan mañana a la ayudantía para resolver dudas de enunciado tambien.

**Comment by bamavrakis** [comment]
Cállate maldito lacayo
