### ISSUE TITLE
Aporte - Mapa completo con direcciones

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#371]
![gui con grilla](https://cloud.githubusercontent.com/assets/13748708/10652954/95af76ec-7852-11e5-985c-4a07acf0f2a1.png)

Dejo esto, quizas un poco tarde pero demas a alguien le sirve :D 
bueno, no verticalmente no soy muy derecho XD

**Comment by AntoniaMendoza** [comment]
¿Cómo le pones esas flechitas bonitas?

**Comment by fgvenegas** [comment]
Esa se la robe a un tipo de otro issue (#339), yo le puse los numeritos

**Comment by otro-felipe** [comment]
``` python
def agregar_calle(self, x, y, direction):
        if x > self.rows or y > self.cols:
            print("[ERROR] Coordenadas ({}, {})"
                  " fuera de las dimensiones de la grilla!".format(x, y))
            return
        self._agregar_imagen(direction + ".png", x, y)
        self.__curr_act.append(("street", x, y))
```

y en `assets` pones los archivos arriba.png etc etc.

es la forma mas sencilla (ahora puedes tener una pura imagen y en base a la direccion juegas con el theta, lo cual es mas eficiente porque almacenas menos imagenes, pero que tan pesados pueden llegar a ser 4 pngs en vez de uno?

**Comment by bcsaldias** [comment]
@MainScientist  por favor NO publicar código en el foro  sin expresa autorización de los ayduantes, o podrías ser bloqueado.
