### ISSUE TITLE
tiempo taxis

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#372]
el tiempo de dejar/recoger que dice el enunciado se refiere al tiempo en que el taxi esta parado en la calle esperando que el pasajero suba/baje? Porque el tiempo en ir a dejar va a depender de la ruta mas corta y el trafico

**Comment by rpalmaotero** [comment]
Si lo consideras necesario, no hay problema.

**Comment by alopez7** [comment]
Si, es el tiempo que tarda en que el pasajero se suba

**Comment by alopez7** [comment]
Y el tiempo en dejar es el tiempo que demora el pasajero en  bajarse del auto, por lo que se mantiene detenido el taxi
