### ISSUE TITLE
Problema direccion calles

### ISSUE THREAD

**Issue by Mapuentes** [IIC2233-2015-2/syllabus#373]
![photo](https://cloud.githubusercontent.com/assets/13740045/10653713/a5b299da-7838-11e5-9045-b8f27e154608.png)

Tengo una duda, pongamos el ejemplo de la foto (perdon el paint) en teoria el carro de bomberos podrá ir al incendio pero no podrá volver, ¿Que se hace en este caso?, o necesariamente tengo que usar el segundo mapa?

**Comment by Mapuentes** [comment]
Puse todos los autos para notar las direcciones de las calles

**Comment by tamycova** [comment]
tienes que encontrar el punto de referencia mas cercano que si permita volver, lo dijeron en algun issue

**Comment by tamycova** [comment]
(tu mapa esta al revesl, por eso la direccion de las calles estan raras)

**Comment by Mapuentes** [comment]
Entonces las coordenadas del mapa original estaba al reves ? o simplemente estoy confundido ? jajaja

**Comment by fgvenegas** [comment]
Tu mapa está como de lado, en el #339 se ve como debería ser

**Comment by rodolfopalma** [comment]
@Mapuentes lo solucionaste?
