### ISSUE TITLE
Problema QT Designer

### ISSUE THREAD

**Issue by tomvillage** [IIC2233-2015-2/syllabus#374]
¿Como puedo abrir Qt designe?, por lo entendí  se instala por defecto cuando instale Qt4 pero al tratar de abrir los archivos .ui no me los reconoce. Tendrá que ver que instale Qt4 por anaconda? de igual manera instale nuevamente pyqt4 nuevamente( no por anaconda) pero sigo sin poder abrir qt desingner

Si alguien me puede ayudar se los agradeceria mucho

**Comment by aaossa** [comment]
1. ¿Pudiste abrir la ventana de designer? (Prueba escribiendo `designer` en consola)
2. ¿Cómo y dónde estás tratando de abrir los archivos *.ui?

**Comment by tomvillage** [comment]
No no he podido abrir la ventana todavía.
Los archivos los estoy tratando de abrir desde el mismo syllabus pero ahí es cuando me dice buscar programa en el equipo para abrir un archivo .ui pero no encuentro el qt designer.
pd: uso windows

**Comment by tamycova** [comment]
Tampoco he podido abrirlo, como se abre desde ubuntu? (designer en consola no funciona)

**Comment by aaossa** [comment]
@tomvillage 

Donde salgan las carpetas con programas (en la barra de inicio) busca algo que diga "Qt" o "PyQt" y ahí dirá designer. Los *.ui no se abren automáticamente en designer, pero una vez en designer los podrás abrir.

**Comment by aaossa** [comment]
@tamycova

No me manejo con otras plataformas, pero podrías ver si algo de [**aquí**](http://doc.qt.io/qt-4.8/designer-to-know.html#launching-designer) te sirve.

**Comment by crabarca** [comment]
@tamycova En ubuntu:  https://apps.ubuntu.com/cat/applications/qt4-designer

**Comment by tomvillage** [comment]
@aaossa ahi lo encontre, muchas gracias!
