### ISSUE TITLE
QT Designer en mac

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#375]
alguien q ya lo haya bajado, me puede decir como lo hizo?

**Comment by aaossa** [comment]
Se supone que Designer viene con PyQt4. Para instalarlo sigue [la guia](https://github.com/IIC2233-2015-2/syllabus/wiki/Mac-OSX), para abrirlo prueba lo que dice [la documentacion de PyQt](http://doc.qt.io/qt-4.8/designer-to-know.html#launching-designer):

> **Mac OS:** Doble click en Qt Designer en Finder

**Comment by yackpott** [comment]
confiare q lo tengo instalado entonces, aun asi no se en q carpeta esta asi q no puedo abrirlo y san google no me esta apañando

**Comment by spiza** [comment]
@aaossa No aparece en mi finder el qt designer! Yo seguí la guía paso a paso, y no está.. el pyqt4 funciona fino, pero no encuentro lo otro!

**Comment by aaossa** [comment]
@robocop6 y su super memoria recordaron que en la ayudantía alguien encontró designer en su carpeta de Python (`python34/Lib/site-packages`) en `/PyQt4`. Prueba eso :grin:

**Comment by spiza** [comment]
parece que no caché como hacer eso...

**Comment by aaossa** [comment]
Debería haber un `designer.exe` en la carpeta que dije.

**Comment by robocop6** [comment]
¿No hay alguna forma de buscar dónde está instalado?
`where python` or something?
#NoUsoMac

**Comment by spiza** [comment]
No encuentro la weá.. lo único que logré encontrar fue el qtdesigner.so, dentro de la carpeta pyqt4, dentro de la carpeta python 3.4
.. No sé que poronga hacer :(

**Comment by yackpott** [comment]
tampoco lo encontre y ya me rendi :(

**Comment by dpassi** [comment]
Probaron la pagina web?
http://www.qt.io/download/

No venia instalado con Pyqt4 (OS El Capital)
Yo lo descargue ayer googleando el primer link

**Comment by spiza** [comment]
hey djpassi, pero no te webearon con el permiso y todas esas preguntas ??

**Comment by silvamatias** [comment]
@spiza yo respondi las preguntas y licencia free asique no hay problema .. ojo que despues al instalarlo pide el Xcode 5.5 o superior

El programa es pesado por lo que demora un poco en bajarse e instalarse

**Comment by silvamatias** [comment]
@djpassi no has tenido problemas con OS El Capitan? en cuanto a programación me refiero. 

Saludos!

**Comment by dpassi** [comment]
@silvamatias Mmmm lo tengo hace 2 dias asi que no puedo decir mucho jaja

**Comment by spiza** [comment]
Ya! Llegué con la solución... sí, tarde, pero lo logré..

Para pillarlo, ponen en spotlight /usr

En usr, luego:

Cellar/qt/4.8.7/QtDesigner

Así :)

**Comment by rodolfopalma** [comment]
@Yackpott Lo encontraste?

**Comment by yackpott** [comment]
si esta en usr/Cellar/qt/4.8.7/QtDesigner y despues open designer.app
