### ISSUE TITLE
PyQt4 y Python 3.5

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#376]
Saludos.

Al parecer, el link que se da en la guía de instalación de la Wiki para PyQt4 está caído, o no funciona con Python 3.5.

La página oficial de Qt tiene como último instalador el correspondiente a Python **3.4**. Intenté hacerlo funcionar con Python **3.5**, pero solo me dejaba importar PyQt4, pero **no sus módulos** (QtCore,QtGui,etc) diciendo que no existían.

El método que intenté utilizar fue realizar la instalación para 3.4 pero **dentro de la carpeta Python35** (en vez de python34) y pareció funcionar correctamente hasta que ocurrió lo del párrafo superior. 

Cuando digo "correctamente" me refiero a que estaba instalada la librería PyQt4 en la carpeta **Lib** de Python, pero al buscar adentro me di cuenta que los módulos (QtGui, etc.) estaban como **archivos ".sip"**. Intenté bajar SIP y ejecutar el **configure.py** que trae, pero solo se creó un archivo llamado **"makefile"**. No sé si debo meter la carpeta de SIP dentro del Lib (o, más específicamente, dentro de **"site-packages"**).

Gracias.-

**Comment by lopezjurip** [comment]
Solución sana: borrar todo y partir limpiamente.
1. Borrar PyQt y Python3 (si lo instalaste por web, **asegurarse bien** de que esté borrado)
2. `brew uninstall pyqt --force; brew uninstall python3 --force`
3. `brew update; brew upgrade`
4. `brew install python3; pip install --upgrade pip; pip3 install --upgrade pip`
5. `brew install pyqt --with-python3`

**Comment by gebalassa** [comment]
Lo logré arreglar pero gracias :-)

No sé a que OS/programa corresponde el comando "brew", en cualquier caso.

**Comment by aaossa** [comment]
`brew` -> MacOS
