### ISSUE TITLE
La posicion mas cercana

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#378]
![gui con grilla](https://cloud.githubusercontent.com/assets/13748708/10678471/7d005fae-790a-11e5-963c-2ec79817a836.png)

En el mapa si tengo un hospital en 12,1 y se enferma alguien en 11,1, bastaria con que practicamente salga la ambulancia a la calle y se considera que llego, o tendria que darse la vuelta completa para queda justo en frente de la casa en 11,1? gracias

**Comment by fgvenegas** [comment]
si lo hiciera buscando la menor distancia, y se quema la casa 8,13, lo logico seria que avanzara hasta llegar alla, pero si le digo que se mueva a menos que el siguiente movimiento lo aleje, el auto quedaria en 8,11 y no se moveria, eso no se considera que esta cerca de la casa?

**Comment by rodolfopalma** [comment]
Los vehículos de emergencia deben llegar a las posiciones más cercanas factibles dónde ocurren las emergencias. Ojo que la ruta más corta no implica que en todos los pasos se acortará la distancia euclidiana entre los puntos.
