### ISSUE TITLE
Problema con la actualizacion de la interfaz

### ISSUE THREAD

**Issue by sebawarrior** [IIC2233-2015-2/syllabus#380]
Hola, una pregunta es que con la nueva versión del gui, al hacer la simulacion, aplico la funcion actualizar tras agregar widgets a la grilla, pero esta no se actualiza, sino que cuando la cierro como que van apareciendo los enfermos, robos e incendios (cuando aprieto la x para cerrar aparece un evento) hasta que de repente logro cerrar el programa... entonces, hay algún orden especial que debe tener los métodos actualizar, exec, show para que el cambio de imagenes sea en tiempo real?? muchas gracias :)

**Comment by benjavides** [comment]
Tengo un problema parecido, el programa me muestra solo su estado final, estático, no veo movimiento en tiempo real, estoy seguro que es porque no he ubicado bien las funciones mencionadas por @sebawarrior

**Comment by clagos4** [comment]
Tengo el mismo problema, la interfaz se detiene hasta que el programa termina, y después de eso empieza a tirar imagen a imagen

**Comment by robocop6** [comment]
@sebawarrior, encuentro muy extraño eso que te ocurre, que al apretar X se muestra un evento...

@clagos4, @benjavides, el problema es que la interfaz no es responsiva a los cambios de `actualizar` hasta que se ejecuta `app.exec_()`. Discutimos esto en #381, espero que les sea de utilidad.

**Comment by sebawarrior** [comment]
gracias jaja pero no sé como solucionarlo :(

**Comment by robocop6** [comment]
¿Has probado los ejemplos? ¿Te funcionan?
¿Cuál es tu OS?

Ni idea de qué pasa.
