### ISSUE TITLE
Problema con GUI 2.0

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#381]
(Sorry por lo largo de la issue)

Hay alguna manera de llamar a app.exec_ antes del final del codigo? Si no, tengo el siguiente problema (asumiendo que se llama a app.exec al final de todo)...

La nueva version de la gui no muestra nada hasta que se llama a app.exec_. Para procesos cortos esto no es un problema, ya que el codigo se ejecuta casi instantaneamente, se llega al comando app.exec_() al final del codigo, la gui empieza a mostrar los cambios encolados de manera inmediata, y todo funciona bien.

El problema es cuando hay que correr simulaciones que requieren más tiempo. Lo ideal seria que la gui fuera mostrando los cambios en paralelo, pero en lugar de eso lo que pasa es que la simulacion se ejecuta, encolando cambios con grilla.actualizar(). Paralelamente, el worker de la gui va procesando la cola cada cierto tiempo, y emite la señal para que la gui se actualice. El problema es que la gui no es capaz de procesar la señal hasta que se haya llamado a app.exec_, por lo que las señales tambien se empiezan a encolar en la gui, sin que esta las procese. Hasta ahora la gui aun no muestra nada, es una ventana en blanco.

Luego, cuando en el codigo principal se llama a app.exec_, la gui procesa todas las señales que le habian llegado de manera instantanea, llegando al estado en que actualmente esta el worker de la gui. Si el worker de la gui alcanzo a procesar todas las actualizaciones de la simulacion, entonces la gui se salta de una pantalla blanca al estado final de la simulacion. Si el worker no alcanzo a procesar todo, la gui se salta al estado actual del worker y luego funciona correctamente.

Entonces, al simular algo la gui espera a que toda la simulacion termine y se llame a app.exec_ antes de mostrar nada, y todos los cambios que el worker alcanzo a procesar antes de que terminara la simulacion se "pierden".

Nuevamente, si la simulacion es lo suficientemente corta, el worker no alcanza a procesar nada antes de que se llame a app.exec_, por lo que el problema solo surge cuando la simulacion requiere mas tiempo.

Quizás estoy entendiendo mal el tema de las señales, etc. y la causa no es lo que describí mas arriba, pero sí estoy seguro de que cuando la simulación es más larga, la interfaz se demora en partir y luego no muestra la simulación desde el inicio (y si se pone un time.sleep antes de app.exec_, la gui se salta directamente al final).

Hasta donde yo se, al llamar a app.exec_ el codigo se queda "pegado" ahi, por lo que se tiene que llamar al final del main. Pero si se llama al final, surge el problema que describi más arriba. 

¿Estoy haciendo algo mal (hay alguna manera de llamar a app.exec_ antes o algo) o hay efectivamente un error en la gui?

p.d. es fácil darse cuenta que app.exec_ siempre se ejecuta antes que la interfaz se actualice por primera vez; es cosa de poner un breakpoint en app.exec_ y otro dentro del metodo __do de la gui. Siempre se llega al breakpoint de app.exec_ primero.

**Comment by paxcema** [comment]
Tengo el mismo problema : / 

¿A alguien le ha funcionado "en tiempo real" con simulaciones prolongadas?

**Comment by fgvenegas** [comment]
Same :c

**Comment by orrios** [comment]
+1

**Comment by jecastro2** [comment]
Tengo el mismo problema ¿alguien lo pudo solucionar ?

**Comment by robocop6** [comment]
Hola!

@Agrios1636, creo que estás en lo correcto en lo que escribes.
El problema se podría solucionar teniendo un thread que vaya corriendo la simulación, que se inicialice antes de `app.exec_()` de modo que, apenas el thread empieza a correr, inmediatamente la interfaz comienza a actualizarse.

Sin embargo, en el enunciado se dice que no es posible utilizar threading en la tarea. Por lo anterior, se ha decidido que, si bien **no es necesario** que solucionen el problema, pueden usar threading **solo para esto**. Es decir, como máximo pueden tener **un único thread** encargado de correr la simulación.

¡Saludos!

**Comment by Arios16** [comment]
Hola Ariel,

En teoria eso deberia funcionar (correr toda la simulacion en un thread aparte). Sin embargo, por alguna razon eso no funciona, la simulacion de todas maneras parte atrasada y no entiendo por que. ¿Has logrado hacerlo funcionar con simulaciones largas?

**Comment by robocop6** [comment]
Sospecho que ocurre porque al llamar a `app.exec_` la interfaz se queda un poco pegada, y si le empiezan a mandar muchas señales al tiro, no se la puede. ¡Prueba haciendo que el thread que corre la simulación duerma un tiempo antes de ejecutar `actualizar` como loco! Mira esta modificación de `ejemplo_gui.py`:

``` python
#!/usr/local/bin python3
# -*- encoding: utf-8 -*-
from PyQt4 import QtGui
from gui.gui import GrillaSimulacion
import random as rnd
import time
import threading


def main():
    for i in range(1, 21):
            grilla_simulacion.agregar_calle(i, 13)
            grilla_simulacion.agregar_calle(13, i)
    grilla_simulacion.actualizar()
    # se duerme un rato
    time.sleep(2)

    t_init = time.time()
    print("empieza simulacion")
    for vez in range(1000):
        for x in range(1, 21):
            for y in range(1, 31):
                nuevo_auto = rnd.choice([
                    grilla_simulacion.agregar_convertible,
                    grilla_simulacion.agregar_sedan,
                    grilla_simulacion.agregar_pickup
                ])
                nuevo_auto(x, y, 0, y % 2 == 0)
                grilla_simulacion.actualizar()

        for x in range(1, 21):
            for y in range(1, 31):
                grilla_simulacion.quitar_imagen(x, y)

        grilla_simulacion.actualizar()

    print("El thread se demoro {}".format(time.time() - t_init))


if __name__ == '__main__':
    app = QtGui.QApplication([])
    grilla_simulacion = GrillaSimulacion(app, 30, 30)
    grilla_simulacion.show()
    grilla_simulacion.tiempo_intervalo = 0.1
    th = threading.Thread(target=main)
    th.start()
    print("se ejecuta exec")
    app.exec_()
```

EDIT: ¿No se puede usar simpy? Gary Medel **hace** su propio simpy.

**Comment by clagos4** [comment]
Aún así el thread va a correr y va alcanzar a agregar un par de autos y después va a correr la interfaz, pero a menos que esperemos todo el tiempo de la simulación, no se van a dar el 100 % de lo eventos en la interfaz gráfica, por otro lado, en la parte Notas de la tarea, dice que esta prohibido usar threading.

**Comment by robocop6** [comment]
Efectivamente, no podrás ver todos los eventos en la interfaz hasta que esperen mucho tiempo. El objetivo de la gui es que puedan ir viendo los cambios que simularon de modo que puedan debuggear (especialmente útil para el modelamiento del tráfico). Ojo que esto no retrasa el tiempo que dura la simulación. La simulación termina antes (en el ejemplo de arriba, en unos 15 segundos), pero los cambios son encolados en la interfaz de modo que se van mostrando de a uno, cada un tiempo igual a `grilla_simulacion.tiempo_intervalo`.

Como dije arriba, se ha decidido permitir el uso de threading, pero **solo para esta aplicación**: correr la simulación en un thread aparte de modo que puedan visualizar problemas en su código.

**Comment by fgvenegas** [comment]
Pero cuando entreguemos la tarea, el ayudante que revise debe poder ver también las cosas que pasan en el GUI o el solo debe ver los resultados ?

**Comment by robocop6** [comment]
Se revisarán los resultados! La interfaz es para ayudarlos a debuggear. Eso sí, ojo, porque sin mostrar lo que va pasando en la interfaz, es difícil que detecten problemas en el modelamiento del tráfico (y su código para modelar tráfico sí será corregido por los ayudantes :smiling_imp: )

**Comment by Arios16** [comment]
Poniendo el thread a dormir un rato parece funcionar mejor. Gracias Ariel.

**Comment by fgvenegas** [comment]
Yap, si  la he usado la interfaz, pero entonces puedo entregar la tarea sin que al correr se vea nada? (obviamente con todo lo demas funcionando)

**Comment by robocop6** [comment]
Sí, puedes hacerlo!

**Comment by fgvenegas** [comment]
Gracias :D

**Comment by robocop6** [comment]
De nada ;)
(a ambos jaja)
