### ISSUE TITLE
Posibles ubicaciones de incendios, enfermos o robos.

### ISSUE THREAD

**Issue by icrocco** [IIC2233-2015-2/syllabus#384]
Si una casa está ocupada por un accidente, y la probabilidad la selecciona a ella ¿no se produce un nuevo accidente o se cambia la casa donde ocurre?

Ej: Considerando los distintos pesos probabilísticos y todo, sale seleccionada la casa en (3, 14) para que se queme, pero la (3,14) ya está siendo robada ¿busco que se queme otra u omito el incendio?

Gracias!

**Comment by bcsaldias** [comment]
Busca que se queme otra. Es máximo un evento simultáneo por casa.

Saludos !
