### ISSUE TITLE
Distribución de los cambios de semáforo.

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#386]
Cuando comencé a ajustar los tiempos para que mi programa todo lo trabajase en horas, me di cuenta de que colapsaba, puesto que mis cambios de semáforo pasaron de ser cada 20 horas a cada 20/3600 segundos y mis autos ya no recorren 1 baldosa/segundo \* DeltaT [hora] sino que 1 baldosa/segundo \* DeltaT [segundo] \* 3600. Estos dos cambios (principalmente el de los semáforos) genera que haya tantos eventos en la cola, que el programa tarda demasiado en simular 14 días, ni hablar de repetir esto 50 veces.

¿Alguna solución?

**Comment by fgvenegas** [comment]
Aprovecho de preguntar si es mejor trabajar la simulación en horas o segundos

**Comment by bamavrakis** [comment]
Como mencionó @robocop6 en un issue anterior, la interfaz es solo una ayuda que te permite debuggear mejor tu simulación. Finalmente, lo que se tomará en cuenta son las estadísticas que se calculen en el programa, por lo que no te compliques mucho con eso (supongo que te referías a la demora en que la interfaz muestre los cambios, si no es así por favor corrígeme).

Saludos!

**Comment by btkramm** [comment]
No, no es la interfaz lo que demora. Es el programa. No me da el summary :/
1 hora puedo simularla casi al instante, 24 horas ya tardo, 14 días es mucho, 14 \* 50 es...

**Comment by Arios16** [comment]
No te olvides de probar todos los escenarios (24 en total). Tengo el mismo problema con la eficiencia, mi programa se demoraría demasiado en simular las dos semanas 50 veces para cada escenario.

**Comment by btkramm** [comment]
Encuentro que deberían poner un tiempo entre semáforos algo más largo, a pesar de que sea irreal.

**Comment by btkramm** [comment]
Yapo respondan :c

**Comment by lopezjurip** [comment]
@IIC2233-2015-2/ayudantes-tareos

**Comment by fgvenegas** [comment]
heeelp :c

**Comment by robocop6** [comment]
En realidad, aún no estoy seguro de qué se va a hacer con que la simulación dure mucho tiempo.

Mientras tanto, te puedo _sugerir_ que uses la menor unidad de tiempo en que pasa una cantidad razonable de cosas (**segundos**) para los tiempos.

**Comment by fgvenegas** [comment]
Ninguna respuesta aún ? la última tarea nos respondieron después de la fecha de entrega :(

**Comment by orrios** [comment]
El enunciado, en la parte de "notas" dice:

'Al ejecutar el programa se debe preguntar al usuario el tiempo de simulacion y el periodo de tiempo
entre cada imagen de la simulacion que quiere ver en la interfaz.'

yo hice todo como sale en el enunciado y depende del ayudante corrector cuanto se va a demorar. no es nuestra culpa que la simulacion sea compleja o que en un tiempo rapido de simulacion no se alcancen a ver los suficientes eventos.

**Comment by bamavrakis** [comment]
Como hay problemas con los tiempos de simulación, para la corrección se utilizará un tiempo menor, así que no se preocupen por eso.

Saludos!
