### ISSUE TITLE
Prerreq y Equiv duplicados

### ISSUE THREAD

**Issue by dpassi** [IIC2233-2015-2/syllabus#39]
Que hacemos en el caso de cuando tenemos, por ejemplo el ramo ICE1003:

```
{
    "equiv": "(ICE1003 o ICE1513 o ICM1022)",
    "sigla": "FIS1513",
    "prerreq": "(FIS1503 y MAT1203 y MAT1620(c)) o (MAT1203(c) y MAT1610)"
 }
```

y luego en otro lado tambien aparece como equivalente:

```
 {
    "equiv": "(ICE1003)",
    "sigla": "ICM2803",
    "prerreq": "(FIS1513 y ICM2313) o (ICE1513 y ICM2313) o (FIS1513 y ICM2022) o (ICE1513 y ICM2022) o (IPP1000 y MAT1102 y MAT1503) o (ING1011 y MAT1102 y MAT1503) o (FIZ0121 y ICM2313) o (FIZ0121 y ICM2022) o (FIS1513 y ICM2313) o (ICE1513 y ICM2313) o (FIS1513 y ICM2022)"
  }
```

Claramente los prerrequisitos que tendra el ramo ICE1003 no son los mismos en uno y otro caso. Que hacemos? 

P.d: Perdon por no seguir la sintaxis del Issues

**Comment by mbucchi** [comment]
Los prerrequisitos que observas ahí son los que corresponden a FIS1513 y ICM2803 respectivamente. Las equivalencias solo sirven para completar los requisitos a otros cursos. Un ejemplo sería un curso que tenga como requisito a FIS1513, en ese caso, si es que el alumno ha cursado el ramo ICE1003 (o ICE1513 o ICM1022), entonces él cumple con los requisitos necesarios para inscribirse en aquel curso.

Los prerrequisitos del curso ICE1003 tendrían que aparecer directamente para aquel curso, no en sus equivalencias. La razón por la cual no aparecen es porque ese es un curso obsoleto que ya no se dicta.
Espero que te haya clarificado las dudas.
Saludos!
