### ISSUE TITLE
Calles e intersecciones (tarea 04)

### ISSUE THREAD

**Issue by selira** [IIC2233-2015-2/syllabus#390]
En alguna parte del foro leí que van a probar el programa con archivos de mapas distintos.
El asunto es que para modelar el programa me parece que es fundamental saber distinguir entre las intersecciones de calles y las calles propiamente tales. Mi pregunta es: Puedo asignar manualmente las intersecciones basado en el mapa de la gui 2.0, o debo crear una especie de algoritmo que permita identficiar las intersecciones, dado cualquier mapa? Si es así, van a tener reglas para crear los mapas distintos? Ojalá que se puedan asignar manualmente, porque igual es complicado encontrar reglas para identificar las intersecciones :o

**Comment by cdonoso** [comment]
Yo asumí que había que crear un algoritmo para encontrar todas las intersecciones independiente del mapa, no es tan dificil hacerlo. Lo que yo hice fue recorrer el mapa e ir comparado con la posición siguiente o anterior (en x o en y dependiendo de la dirección de la calle) y si habia un cambio significa que es una intersección, y luego esas coordenadas las adjuntaba a una lista y listo, tienes todas tus esquinas independiente del mapa.
O también puedes ir comparando si el bloque de al lado es una casa o no y listo, hay varias formas de encontrar las intersecciones jajaja 
Espero haberte ayudado :smile:

**Comment by selira** [comment]
Había pensado en hacer eso de las casas adyacentes, pero se complicaba en las intersecciones que chocan con casas. No se me había ocurrido lo de las direcciones, gracias por eso! :). Ojalá que los ayudantes no crean que esto es copia, jajaja.

**Comment by alopez7** [comment]
Tienen que hacer un algoritmo que detecte las intersecciones

**Comment by selira** [comment]
ok
