### ISSUE TITLE
output escenario X.txt

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#393]
Al grano. ¿Ese archivo no sería gigante?

**Comment by alopez7** [comment]
Si

**Comment by btkramm** [comment]
Tengo que incluso poner los eventos de cambio de semáforo ¿?
Además, sinceramente no comprendo nada la tabla. Tengo que hacerla igual a como sale ahí ¿? Si debo seguir el formato, podrían explicarlo un poquito ¿? Qué es Otro 0, Otro 1. Por qué Otro 1 tiene un 4 en la tercera fila ¿?

**Comment by bcsaldias** [comment]
La idea es q si asignaron u  ID lo pongan.

Creen una tabla donde las columnas tengan siempre el mismo tipo de dato. Dejémoslo en que si es en otro orden perfect igual, pero si en una columna hay "tipo de objeto" entonces no irá un "evento" ahí.

Sip, la gracia es q estén los eventos por auto: cambia de celda,cruza calle, etc.

Saludos !

**Comment by btkramm** [comment]
En lo que a mi respecta ya tengo demasiado con los grandes eventos como para ahora colocar los cambios de de calle y avance de cada auto :/ ¿Es realmente necesario?

**Comment by bcsaldias** [comment]
Puedes siempre representar todo básicamente como un grupo reducido como
entra a calle, adelanta, cruza calle.

**Comment by andresespinosapc** [comment]
Aprovecho de preguntar si es mejor ir abriendo el archivo cada vez q qiiero
escribir, o tenerlo abierto duramte todo el programa o guardar todo en una
estructura de datos y al final pasarlo al archivo.

**Comment by btkramm** [comment]
Quiero además confirmar: ¿Es necesario que haga la tabla tal cual está en el PDF?

**Comment by rodolfopalma** [comment]
@andresespinosapc Lo óptimo sería calcular todos los eventos y al final pasar los datos al archivo.

@btkramm Qué variaciones quieres hacer?

**Comment by bcsaldias** [comment]
Para que estés tranquilo de que está escrito:
Mientras cumplan con que en cada columna irá un mismo tipo de
información (entidad1 involucrada en el
evento)/evento/tiempo/ubicación/(entidad2 involucrada en el
evento)/(id de entidad 2 si es que tiene)/ etc...

Está correcto.

Pero si mezclas 2 cosas distintas en una columna no está correcto.

Saludos

2015-10-26 11:18 GMT-03:00, btkramm notifications@github.com:
