### ISSUE TITLE
Calles Continuas?

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#396]
Hola. Si un auto se esta yendo del tablero (hacia arriba por ejemplo) , y hay una calle en esa misma columna pero en el extremo de abajo del tablero. Puedo hacer que reaparezca ahi? o debo eliminarlo?

**Comment by bamavrakis** [comment]
Hola! esto queda a tu criterio, pero recuerda especificarlo en el README!!
Saludos.
