### ISSUE TITLE
Licencia Pycharm

### ISSUE THREAD

**Issue by benjavides** [IIC2233-2015-2/syllabus#4]
En la clase de ayer un ayudante mencionó que con el correo uc podíamos descargar la versión completa de Pycharm gratis. Me registré en la página con el correo uc, pero no tengo la opción de bajarla gratis. ¿Qué hay que hacer para obtener la licencia completa gratis?

**Comment by lopezjurip** [comment]
También puede bajarla siguiendo las instrucciones de las guías. 
https://github.com/IIC2233-2015-2/syllabus/wiki

Sino, busca en su sitio oficial la versión **Pro**.

**Comment by benjavides** [comment]
Funcionó haciéndolo como dice en la guía. Gracias!
