### ISSUE TITLE
Error de lectura en "cursos.txt"

### ISSUE THREAD

**Issue by paxcema** [IIC2233-2015-2/syllabus#40]
Hola,

Al intentar leer el archivo "cursos.txt" me encuentro con el siguiente error:

```
File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 76: character maps to <undefined>
```

Probé leer las primeras 2000 líneas de código, y no hubo problemas. Me ayudaría mucho saber que podría estar haciendo mal que explique el mapeo a "<undefined>", o por último, averiguar si le está pasando a alguien más.

**Comment by fgvenegas** [comment]
Hola humano

Cuando abras el archivo  abrelo asi "open("cursos.txt","r", encoding="utf8")" asi no te molestan los acentos ni las ñ

**Comment by felipehv** [comment]
Mismo error!

_Felipe Haase Vargas_
_Delegado Generación 2014_
Estudiante de Ingenieria
Pontificia Universidad Católica de Chile

**Comment by paxcema** [comment]
Freddie, eres un sabio, era eso!

Particularmente, la primera "ñ" está cerca de la línea 2500, por eso no tuve problemas con la porción más chica del archivo, muchas gracias!!

**Comment by bcsaldias** [comment]
Hola !

Eso también depende de dónde estés escribiendo tu código, es muy probable
que estés en un editor como Sublime ?..

Recuerden que recomendamos PyCharm :) , más que todo por el debuggeo que te
hubiera permitido encontrar ese error debugueando. Si ya usas PyCharm y no
supiste cómo debuggear para llegar al error intenta averiguar cómo hacerlo.

Saludos !
Belén

**Comment by bcsaldias** [comment]
Ah ! y siempre hemos tenido inconvenientes con el encoding de sublime,
tanto en Ac's como tareas. En PyCharm no tuvimos problemas.

Saludos !

**Comment by gebalassa** [comment]
¡Hola!

Estoy leyendo una versión corta del archivo **cursos.txt**, abriéndolo con

```
texto = open("PRUEBA2.txt","r",encoding="utf8")
```

y no quiere funcionar, pues me tira:

```
Traceback (most recent call last):
  File "D:\alumno\Escritorio\PARSING\parsing.py", line 52, in <module>
    dic_texto = parsing(texto)
  File "D:\alumno\Escritorio\PARSING\parsing.py", line 10, in parsing
    read_lines = archivo.readlines()
  File "D:\Python\lib\codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 75: invalid start byte
```

Revisé el posible caracter que ocasionaba el problema en la posición 75, y era la **"Á"** de "Álgebra Lineal". No entiendo por qué utf-8 no está aceptando el tilde.

Gracias.

**Comment by paxcema** [comment]
Hola, 

La verdad no estoy seguro, pero te recomiendo mirar el Issue #80, en él comentan un problema bastante similar!

Saludos.

**EDIT (@aaossa)**: A lo que se refiere es esto:

![Encoding sugerido](https://cloud.githubusercontent.com/assets/13739643/9571270/5c9d636e-4f71-11e5-8e5f-7423c187001d.png)

**Comment by gebalassa** [comment]
Acabo de **sacar** `encoding=utf8` y se arregló :-/
