### ISSUE TITLE
Movimiento T5

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#400]
Cuando el jugador y los zombies se mueven, lo hacen arriba, abajo, derecha e izquierda según donde estén mirando (posición mouse y mirando al jugador, respectivamente) mi pregunta es se pueden mover y mirar en otro angulo o  solo es en 90 grados osea hacia arriba, abajo, derecha e izquierda de la pantalla?
Si es que es en otro angulo este es la diagonal (45) o tenemos que definir los 360 grados de moviemento?

**Comment by bamavrakis** [comment]
Hola! 
Con respecto al jugador, efectivamente se puede mover y posicionar en ángulos distintos a 90 grados. Es literalmente como dice esa parte del enunciado: el jugador apunta hacia donde está apuntando el mouse, y se puede mover hacia arriba, abajo, derecha e izquierda tomando como referencia hacia dónde está mirando el personaje.

Con respecto a los zombies, estos apuntan hacia el jugador (con su ángulo correspondiente) y se mueven en línea recta hacia el.

Espero haber aclarado tu duda.
Saludos!

**Comment by oatorresuc** [comment]
Si, gracias. Tengo otra duda, yo se que si creo una interfaz en qt designer
y despues la cargo, en el init puedo agragarle mas widgets, pero cuando
intento agregarlo mas widgets despues del init(es decir, en cualquoer otro
metodo de la clase MainWindow) estos no se cargan a la interfaz, como lo
soluciono o no puedo agregarle widgets fuera del init?

**Comment by btkramm** [comment]
No me quedó muy claro el movimiento.

Si mi personaje está mirando hacia la derecha de mi pantalla y yo pulso 'A', él va ir hacia la izquierda de mi pantalla o hacia su izquierda ¿?

**Comment by fgvenegas** [comment]
En ese caso como que el retrocederia no?

**Comment by robocop6** [comment]
Si presionas A, el personaje debe moverse hacia **su** izquierda.

Es decir,
- W lo mueve hacia el cursor.
- S hace que retroceda, mirando hacia la posición del cursor.
- A lo hace girar hacia su izquierda, manteniendo siempre la vista hacia el cursor.
- D lo hace girar hacia su derecha (sin dejar de mirar el cursor).

Esto permite que el personaje no se mueva solo en ángulos discretos (0, 45°, 90°, 135°, etc.), sino que su dirección depende de la posición actual y de la posición del mouse.

**Comment by btkramm** [comment]
Muchas gracias robocop6, eres un ayudante muy atento :) tkm

**Comment by robocop6** [comment]
De nada! ;)
@oatorresuc, a mí me está resultando agregar widgets en métodos que no son el init.

¿Estás seguro de que estás creando el widget dándole como argumento la ventana, y llamando a `show`? Algo como:

``` python
def mi_metodo(self):
    self.label = QtGui.QLabel(self)
    self.label.setText("Algo va aca")
    self.label.show()
```

**Comment by oatorresuc** [comment]
gracias ariel, me faltaba el self.label.show()

2015-10-27 22:25 GMT-03:00 Ariel notifications@github.com:

**Comment by crabarca** [comment]
Entonces.. el movimiento es algo parecido a como se mueven los juegos FPS?
Obviamente considerando una vista superior

**Comment by robocop6** [comment]
¡Exactamente!

**Comment by chrisams** [comment]
Aún no me queda muy claro el movimiento del personaje. En el enunciado dice que el personaje siempre mirará hacia donde está el puntero del mouse, entonces si dejo el puntero del mouse fijo en algún lugar y comienzo a moverme hacia la derecha o izquierda, el personaje constantemente estará cambiando "su derecha" o "su izquierda" debido a que debe estar mirando hacia el mouse. Por lo tanto el personaje al moverse hacia la izquierda o derecha, ¿estaría "rodeando" al mouse describiendo una trayectoria curva?

**Comment by fgvenegas** [comment]
Exacto, no soy ayudante pero eso es lo que me habian dicho, que el formara
un circulo alrededor del mouse
