### ISSUE TITLE
Tarea 5 - pygame

### ISSUE THREAD

**Issue by ManuelBeckerT** [IIC2233-2015-2/syllabus#401]
Se puede utilizar pygame?

**Comment by robocop6** [comment]
**NO** :smiling_imp:

**Comment by santiagocruzb** [comment]
![untitle](https://cloud.githubusercontent.com/assets/13748925/10762287/3415005e-7ca4-11e5-9b30-2756cb896572.JPG)

**Comment by lopezjurip** [comment]
De otro modo nos perderíamos toda la diversión :v:

**Comment by crabarca** [comment]
:'(

**Comment by crabarca** [comment]
:cry:
