### ISSUE TITLE
[Tarea 05] interfaz

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#402]
tengo pensado hacer dos qwidget, el inicial y el del juego pero no se como unirlos para que sea amena la transicion (que al apretar el boton me aparezca el nuevo widget pero que el anterior no se haya tenido que cerrar ni nada) o mejor me conviene tener un solo widget y "borro" todas las variables y limpio la interfaz para cargar la nueva?

**Comment by robocop6** [comment]
No estoy seguro de si te estoy entendiendo bien, pero algo que puedes hacer es que cuando empiece el juego, el widget inicial nunca se cierre verdaderamente, pero sí deje de ser visible. Y luego, volver a hacerlo visible, ya sea cuando perdió el juego, o fue pausado, por ejemplo.

Busca sobre el método `setVisible` de `QtGui.QWidget`.

**Comment by AntoniaMendoza** [comment]
Yo tengo un problema con eso, resulta que le puse música al inicio y cuando le aplico "hide()" desaparece la ventana pero sigue la música sonando jaja no hay una forma de eliminar ese widget (de la memoria), para abrir otro completamente de 0?

**Comment by AntoniaMendoza** [comment]
Yo tengo una duda similar. Resulta que a mi ventana de inicio le puse música, y cuando usaba hide() igual seguía sonando. ¿No hay una forma de que se "cierre verdaderamente" para abrir otro como si le cambiase todas las propiedades al widget inicial? (Igual lo arreglé haciendo que se apagase la música, pero pregunto por si las moscas)

**Comment by AntoniaMendoza** [comment]
Además, me ocurre que si hago hide() y de ahí hago show() en el otro widget que quiero abrir, se abre y se cierra instantáneo.

**Comment by AntoniaMendoza** [comment]
Ya jaja lo pude arreglar. Tuve que guardar el segundo widget como atributo del primero y luego llamarlo desde el primero. No sé cuál sera la gran diferencia de eso con lo que hacía anteriormente, pero funcionó.
![code](https://cloud.githubusercontent.com/assets/13214114/10867029/7b731802-802b-11e5-8fd5-e08f17b91eee.jpg)

**Comment by cdonoso** [comment]
@AntoniaMendoza Como le pusiste música??? Que quiero hacer lo mismo, en el meú de inicio ponerle una música de zombies o no se jajaja

Y para los ayudantes, también se le puede poner que cada vez que el soldado dispare suene un pequeño ruido de un disparo? o es muy dificil hacerlo?

**Comment by AntoniaMendoza** [comment]
usé phonon :) Hay varias formas. Dentro de lo que encontré en google, usé la que me pareció más adaptable a lo que necesitaba jaja  
Lo raro es que pycharm no me reconoce algunas clases de phonon, pero igual me funciona al ejecutarlo, no sé si fallará cuando lo vean los ayudantes.
