### ISSUE TITLE
Ayuda MouseMoveEvent

### ISSUE THREAD

**Issue by sebamenabar** [IIC2233-2015-2/syllabus#403]
Hola, no me funciona el mouseTrackEvent, no se porque, intente creando gui con Designer y desde python. hago setMouseTrackEvent(True), pero la funcion mouseMoveEvent solo se ejecuta si muevo el mouse y apreto al mismo tiempo. El intente con el setMouseTrack en el setupUi y en el init. Estoy trabajando en mac con python 3.5

**Comment by robocop6** [comment]
Hola!
No conozco `setMouseTrackEvent`.

¿Probaste con la sintaxis de la ayudantía 8?

**Comment by sebamenabar** [comment]
si perdona use el setMouseTracking(True), lo hice sobre la MainWindow y sobre un label, y para las 2 me funcionaba solamente si hacia click y movie el mouse

**Comment by robocop6** [comment]
Si corres esto, funciona?

``` python
from PyQt4 import QtGui, QtCore


class Ventana(QtGui.QWidget):
    def __init__(self):
        super().__init__()
        self.setMouseTracking(True)

    def keyPressEvent(self, QKeyEvent):
        if QKeyEvent.key() == QtCore.Qt.Key_Return:
            print("Presionarion ENTER!")

    def mousePressEvent(self, QMouseEvent):
        if QMouseEvent.buttons() == QtCore.Qt.LeftButton:
            print("Hizo click izquierdo!")

    def mouseMoveEvent(self, QMouseEvent):
        boton = QMouseEvent.buttons()
        x = QMouseEvent.x()
        y = QMouseEvent.y()
        print(x, y)

    def closeEvent(self, QCloseEvent):
        ans = QtGui.QMessageBox.question(
            self, 
            "Titulo", 
            "Salir?", 
            QtGui.QMessageBox.Yes | QtGui.QMessageBox.No
        )
        if ans == QtGui.QMessageBox.Yes:
            QCloseEvent.accept()
        else:
            QCloseEvent.ignore()


if __name__ == "__main__":
    app = QtGui.QApplication([])
    ventana = Ventana()
    ventana.show()
    app.exec_()
```

**Comment by sebamenabar** [comment]
eso si, mira esto es lo que tengo, me abre la ventana, pone el fondo y el monito, pero imprime el angulo solo cuando estoy haciendo click

``` python
# No es posible mostrar codigo
```

**Comment by robocop6** [comment]
Vi el código y no encontré problemas. Es más, hice un `.ui`, lo cargué, y me funcionó perfecto.
¡Ni idea de qué pasa! Quizá tiene que ver con el OS D:

Tuve que editar tu comentario para evitar que se muestre código.

**Comment by sebamenabar** [comment]
Podrá ser por python 3.5? Cuando instale el PyQt tuve que borrar todo para que me quede funcionando y ahi me quedo instalado el python 3.5 y no puedo poner el 3.4 por que solo me funciona el PyQt si lo instalo con el brew, y con el brew solo puedo instalar python 2.7 o 3.5

**Comment by robocop6** [comment]
Invoquemos a @mrpatiwi 
(no uso mac :astonished:)

**Comment by btkramm** [comment]
Tengo el mismo problema. Funciona muy bien en el código que entregaste, pero cuando lo utilizo en el .ui solo funciona si estoy manteniendo el click :c

**Comment by fgvenegas** [comment]
A mi me pasa que tu codigo lo lee cuando muevo el mouse, lo puse en mi codigo, si tengo lo widgets visibles solo lo lee al hacer click, pero si le hago setVisible(False) ahi lo reconoce el mouse con solo pasarlo por encima

**Comment by sebamenabar** [comment]
Jaja plagio, broma. @btkramm para avanzar por mientras hazlo creando manualmente la gui, ahi me funciona bien, y probablemente el diseño no llegue a ser tan complejo para necesitar hacerlo con designer

**Comment by lopezjurip** [comment]
PyQt4 funciona bien con Python 3.5

Los problemas ocurren cuando mezclan las instalaciones, de internet y las de `brew`.
En tales caso, borrar (bien borrado y asegurarse de aquello) todo lo relacionado con Python y seguir la guía paso a paso.

**Comment by vjmoreno** [comment]
Me pasa lo mismo que a @fgvenegas , alguien lo ha podido solucionar?

**Comment by fgvenegas** [comment]
@vjmoreno Ahora me di cuenta que cuando lo paso por un widget no pasa nada (a menos que haga click) pero si es por la ventana "limpia" printea las coordenadas altiro

**Comment by vjmoreno** [comment]
Lo acabo de solucionar, le puse a mis Qlabels y al Widget setMouseTraking(True).

**Comment by Rodancoci** [comment]
Tengo un problema:
Tengo un Widget dentro de un MainWindow (el Widget es el CentralWidget del MainWindow).
Definí el método mousePressEvent en el Widget y funciona perfecto, aún cuando lo abro desde el MainWindow. Sin embargo, no se ejecuta el keyPressEvent del Widget cuando lo abro en el MainWindow.

**Comment by Rodancoci** [comment]
Por si a alguien le sirve, resolví mi problema. Sólo tenía que definir keyPressEvent en el MainWindow para que ejecutara el keyPressEvent del Widget actual.

**Comment by jfcampos1** [comment]
Por si a alguien le sigue sin funcionar lo mejor es en el mismo ui setear el mousePressEvent. Esto se hace en la barra de la derecha de Qtdesigner donde dice Property Editor, uno baja un poco hasta la opción de mouseTracking y listo.

**Comment by silvamatias** [comment]
@btkramm como lo solucionaste? me pasa lo mismo, tengo que tener mantenido el mouse y mover para que imprima las coordenadas del codigo de la ayudantia.

gracias!
