### ISSUE TITLE
¿Un Thread por entidad?

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#405]
Un dato freak es que yo comencé a programar editando código en el editor de Warcraft 3 :). En él, para saber si un misil había colisionado con alguna entidad se realizaban 'ticks' de intervalos muy cortos para verificar quienes se encontraban cerca de cada proyectil. Para hacer eso yo iteraba sobre cada misil en mi arreglo y realizaba la comprobación. Ahora que ya sé lo que es un thread, me pregunto: ¿Debo crear un thread por cada entidad para realizar este tipo de procedimientos o mejor un thread que realice una comprobación general (iterando)? Pregunto porque me parece más eficiente un solo thread pero no sé si será lo correcto... no sé. Alguna recomendación ¿?

**Comment by robocop6** [comment]
En lo personal, ¡a mí me gusta aprovecharme de los threads!
Así no tengo que preocuparme de andar iterando sobre misiles y removiendo un misil del arreglo cuando explota o cosas por el estilo. Simplemente creo un thread para el misil y me "olvido de él" sabiendo que va a hacer su pega bien y terminar cuando corresponde.

Creo que desde un punto de vista de modelación, es más natural. Me parece más lógico que cuando se dispara un misil, tenga una vida independiente de la del resto en vez de que haya un thread tipo "Dios omnipotente" controlando los movimientos de todos los misiles.

Sin embargo, creo que la alternativa que planteas también es válida y que pasa más que nada por una decisión de modelación.

**Comment by btkramm** [comment]
No se generaría una sobrecarga de threads ¿? Bueno, igual la vida de los proyectiles es corta, pero subestimo mi computadora.

**Comment by lopezjurip** [comment]
Has visto cuántos threads están ejecutándose en tu computador diariamente? 
![image](https://cloud.githubusercontent.com/assets/7570744/10785648/b04ccd52-7d4c-11e5-8b89-82365d2c531b.png)
