### ISSUE TITLE
movimiento continuo

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#406]
hay algun metodo magico q me permita moverme como en los fps dejando apretado w en vez de apretarlo varias veces y lo mismo para el mouse para un efecto metralleta en vez de pistola.

**Comment by robocop6** [comment]
Revisa la [documentación de Qt](http://doc.qt.io/qt-4.8/qkeyevent.html) en relación a los `QKeyEvent` que existen (eso está en otro lenguaje, pero de todas formas los tipos de eventos que existen y te pueden servir son los mismos: básicamente presionar y soltar una tecla).
¡Saludos!

**Comment by Rodancoci** [comment]
Los KeyPressEvent tienen un atributo .isAutoRepeat() que retorna un booleano que corresponde a si es la primera vez que se presiona la tecla o si se está repitiendo al mantenerla presionada.
