### ISSUE TITLE
Rotacion imagenes

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#407]
Cuando muevo el mouse y el personaje tiene que rotarse, debo rotar la imagen en esa direccion o cambiar el sprite del personaje que parezca que esta mirando en esa direccion?

**Comment by robocop6** [comment]
Me parece que la idea es rotar la imagen para que apunte en esa dirección.
Dejemos que confirme @bamavrakis

**Comment by raiperez** [comment]
No podríamos dejar ambas opciones?

2015-10-29 12:57 GMT-03:00 Ariel notifications@github.com:

**Comment by mbucchi** [comment]
Ambas opciones son válidas! Lo que pasa es que hay sprites que son en diagonal (y no vista superior). Este tipo de imágenes se verían mal si se rotan. En el caso de top down, ustedes pueden decidir usar otra imagen del sprite sheet o bien rotar la que ya tienen.

Saludos!

**Comment by bamavrakis** [comment]
He sido invocado!
Pero llegué tarde ya que Marco respondió la issue.
Saludos!
