### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#408]
Hola!

Tengo un par de dudas: 
- Estoy haciendo:  map(lambda x: funcion(x) , lista_de_objetos) .

Mi funcion(x) modifica los objetos, sin embargo, al llamar map, estos no se modifican, hasta recorrer por completo el iterable, o por ejemplo llamando la funcion list() sobre el resultado de map. 

No sé si se entiende, pero hay alguna forma de hacer que el map también ejecute la función para cada elemento?
- Hay alguna manera de agrupar varios objetos en el qtdesigner, para luego poder llamar rápidamente una función que los afecte a todos al mismo tiempo? (Actualmente para salir del menu principal y comenzar el juego tengo como 6 lineas haciendo setVisible(False) a los distintos objetos lo que no me parece muy eficiente)

De antemano gracias!

**Comment by aaossa** [comment]
#### Sobre `map`

Tienes razón sobre lo de `map`, es interesante, no había pensado en eso pero tiene sentido ya que según la documentación "retorna un iterador que aplica la función a cada item del iterable", por lo que "tecnicamente" no se ha aplicado la función, solo se ha declarado que se aplicará. Lo que podrías hacer es usar una equivalencia de `map` como lista: 

``` python
def func(x):
    print(x)
    return 0

iterable = (range(1, 10))

A = map(func, iterable)
print(A)

B = [func(x) for x in iterable]
print(B)
```

Así, en cuanto se crea la lista se ejecuta la función.

#### Sobre PyQt

Lo que podrías hacer es tener todos esos widgets en un mismo layout, y luego iteras sobre ellos con algo como esto:

``` python
items = (layout.itemAt(i) for i in range(layout.count())) 
for w in items:
   funcion(w)
```

De hecho, lo de layout es más cuando los quieres agrupar gráficamente. En tu caso basta con que metas todos los widgets en una lista, iteres sobre ellos y apliques la función, depende de como hayas hecho la interfaz. Yo lo haría iterando sobre cada layout y dentro de cada uno iteraría sobre los widgets y a cada uno le aplicaría la función (algo como un "doble `for`")

**Comment by Mdelaf** [comment]
Buenas @raiperez , siempre me ha gustado harto el tema de generadores, iteradores e iterables, así que me sumo a la conversación.

La característica de la función **map** y de las funciones de programación funcional, en general, es que no guardan los datos en memoria y por lo tanto son más rápidas. 

En el caso particular de un _map object_, puede decirse que es similar a un generador. Es decir, cuando usamos `map(func, iterable)` es análogo a usar `(func(element) for element in iterable)`, con la diferencia que el primero es un poco más rápido porque esos _built-ins_ están pre compilados en C (los lenguajes compilados son más rápidos que los interpretados). A menos que la velocidad sea algo realmente importante yo preferiría usar la segunda forma que es más clara y no implica conocer la función. Una implementación de **map** en Python para este caso sería algo como:

``` python
def map(func, iterable):
    for elemento in iterable:
        yield func(elemento)
```

La función **map** se vuelve más útil cuando la usas para iterar sobre varios iterables `map(func, iterable1, iterable2)` y en ese caso ya no es análoga a usar un generador con paréntesis. Una implementación en Python de este caso (es decir, del **map** general) sería, si no me equivoco:

``` python
def map(func, *iterables):
    for tupla_de_elementos in zip(*iterables):
        yield func(*tupla_de_elementos)
```

A lo que voy con esto es que, cualquiera sea el caso, **map** no guarda los valores en memoria y cuando lo usas, la función no es llamada hasta que iteras sobre el _map object_. Por eso tus objetos sí cambian cuando usas **list** o iteras sobre el  _map object_, pero antes no. Ahora, respondiendo a la pregunta, **no es posible que la función sea ejecutada al crear el map** por lo recién dicho.

Una solución es hacer una lista por comprensión (que sí guarda los valores en memoria) como dice @aaossa, y efectivamente tus objetos van a cambiar al crearla. Pero si tu función no tiene un retorno (suponiendo que sólo hace cambios en los objetos sin retornar nada) creo que esta no es una forma muy elegante de hacerlo, porque al final estarías creando una lista de `None`'s tipo `[None, None, None, ..]` y guardándola en memoria, lo que a mi juicio es innecesario. 

De PyQt y la tarea no te puedo responder mucho porque todavía no la empiezo pero arriba te dieron una buena solución.

Me motivé mucho escribiendo parece jajaj. 

Saludos.

**Comment by raiperez** [comment]
@aaossa  @Mdelaf  Muchas gracias a ambos! Buena información. :D

**Comment by robocop6** [comment]
Sobre PyQt, podrías tener dos ventanas: una para menú principal/pausa y otra para el juego mismo, por ejemplo. Y entonces, bastaría con que hicieras `setVisible(False)` a un solo `QWidget` (pero que a su vez, contiene a varios otros `QWidget` dentro).

Como me mostraron unos compañeros tuyos hoy en la programatón, otra forma de hacerlo es que se vaya intercalando entre esas dos ventanas con el método `setCentralWidget` de una tercera ventana que "controla" a las otras dos. Aunque, personalmente, no he usado ese método.

Por otra parte, si no quieres tener dos ventanas, sino usar una misma ventana para mostrar ambas cosas, el método `children` de una `QWidget` te permite iterar de forma un poco más elegante sobre los elementos gráficos de una ventana.

**Comment by fgvenegas** [comment]
Como acotacion, cuando haces `setCentralWidget` y cambias la ventana actual por otra nueva, la anterior es destruida, literalmente, asique por ejemplo si terminas el juego y quieres volver al menu tendrias que instanciar de nuevo ese Widget

**Comment by robocop6** [comment]
¡Toda la razón!
Entonces, creo que resultaría mejor usando [QStackedWidget](http://pyqt.sourceforge.net/Docs/PyQt4/qstackedwidget.html).
