### ISSUE TITLE
mapa T05

### ISSUE THREAD

**Issue by selira** [IIC2233-2015-2/syllabus#409]
en el issue #400 dijeron que los movimientos tienen que ser "continuos", entonces el tablero también debe serlo, o se pueden usar bloques discretos para moverse? (o sea que el jugador tiene 4 u 8 "bloques" a los que puede moverse, dependiendo de su dirección continua...). En el caso de que el mapa también sea "continuo", esto quiere decir que se tienen que rotar y mover las imágenes pixel por pixel?

**Comment by robocop6** [comment]
Según entiendo, la idea es que la imagen se rote dependiendo de las posiciones del jugador y el mouse, ambas en pixeles.
Puedes usar `atan2` para conseguir el ángulo.
Invoquemos a @bamavrakis para que confirme!

**Comment by robocop6** [comment]
Revisa #407, no estoy seguro de si es la misma duda que planteaste!

En particular, no sé si con "tablero discreto" te refieres a que vaya cambiando la imagen del sprite sheet dependiendo de 4 (u 8) direcciones de movimiento, pero se desplace en un ángulo "continuo", o a que el desplazamiento sea solo en direcciones cuyos ángulos son múltiplos enteros de 45°.

**Comment by benjavides** [comment]
Creo que con "bloques discretos" se refiere a que el movimiento sea como el de los autos en la interfaz grafica de la tarea anterior en que el movimiento visual no era pixel por pixel (continuo), sino que el auto pasaba entero de una casilla de la grilla a otra. Tengo la misma duda

**Comment by robocop6** [comment]
¡Ah, creo que ya entendí la pregunta!
Si es como dice @benjavides, entonces por supuesto que **no pueden hacer que el movimiento sea por bloques** como en la `grillaSimulacion`. La idea es que la interfaz sea amigable para el juego, con movimiento lo más continuo posible: pixel por pixel y que se vea en forma "fluida" cómo el personaje se va desplazando.

**Comment by selira** [comment]
me entendieron perfecto! jajaja, gracias por contestar.

**Comment by oatorresuc** [comment]
A mi me funciono moverlos pixel por pixel y que el jugador rote segun el
mouse pero no puedo hacer que los zombies roten respecto a el porque tal
como ustedes nos explicaron los threads no deben cambiar a la interfaz,
sino que deben mandar una señal al trhead principal de la interfaz pero el
problema es que no entiendo bien el ejemplo que nos dieron en la ayudantia
8 :(

**Comment by robocop6** [comment]
En ese ejemplo, tú tienes un `Character` (`QThread`) que, tal como dices, en vez de modificar directamente el widget, envía una señal a la ventana para que esta lo modifique. 
Los dos puntos claves sobre las señales en PyQt4 son:
1. Una señal se conecta a un método en la ventana mediante el método `connect` (igual que `boton.clicked`... de hecho... ¿cuál será el `type` de `boton.clicked`?
2. Cuando creas una señal, `senhal = pyqtSignal(*args)`, los `*args` son cuáles son los tipos de los argumentos que enviará a la ventana. Por ejemplo, si quisieras hacer que la señal se vincule a un método en la ventana que es como sigue:

``` python
def mi_metodo(self, x, y):
    self.label.move(x,y)
```

Entonces, la señal podría ser definida como `senhal = pyqtSignal(int, int)`. En el ejemplo de la ayudantía, para que esté más ordenado el código y se asemeje más a cómo se manejan típicamente los eventos, hice que la señal se creara con el argumento `MoveMyImageEvent`, lo cual quiere decir que en vez de enviarse a la ventana directamente una posición x, y, en argumentos separados, lo que se envía es toda la información necesaria para realizar los cambios en la interfaz, empaquetada en un solo objeto clase `MoveMyImageEvent`. De esta forma, el método en la ventana queda algo como:

``` python
def mi_metodo(self, imageEvent):
    self.label.move(imageEvent.x, imageEvent.y)
```

¡Y la sintaxis es la misma que para los otros métodos que se ejecutan cuando ocurre algún evento! Por ejemplo:

``` python
def keyPressEvent(self, QKeyEvent):
    print(QKeyEvent.keys())
```
