### ISSUE TITLE
Duda archivos

### ISSUE THREAD

**Issue by jecastro2** [IIC2233-2015-2/syllabus#41]
Hola,
En algunas partes del archivo evaluaciones esta escrito  "fecha": "24/10 - 9:00"` con ese signo final que no permite usar la función eval(), ¿Es un error o están bien puestos ahí?

**Comment by flobarrios** [comment]
+1, tengo el mismo problema con ese archivo

**Comment by mbucchi** [comment]
Efectivamente es un typo, debiese decir _"fecha": "24/10 - 9:00"_ nada más. No obstante usar la función `eval()` es una pésima práctica, pues te puedo inyectar código. Por ejemplo, si te paso un archivo que dice

 `__import__('shutil').rmtree('../../')`

y tu corres  `eval()` sobre ese string, borrarás tu repo del computador :cry:

Así que **NO** usen `eval()`!
