### ISSUE TITLE
Problema con python

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#410]
Hola! Tenia un problema con python, asi que trate de arreglarlo, pero no me funcionaba, asi que lo desinstale para instalarlo de nuevo, y ahi quedo la embarrada: No me dejaba instalarlo de nuevo (me decia que habia un paquete que no estaba funcionando bien). Despues trate con python 3.5, y ahi si me dejo instalar, pero no me lo reconocio pycharm como interprete (parece que hay un tema con los paths, pero tampoco encontre mucha info que me ayudara). Al final trate de usar la guia del curso para desinstalar y despues volver a instalarlo con el powershell, pero cuando trato de hacer choco install me tira el siguiente error:

![image](https://cloud.githubusercontent.com/assets/13824744/10806895/9c927e12-7db8-11e5-8f9e-f09b585a8cc6.png)

**Comment by lopezjurip** [comment]
Anda a `C:` y revisa las carpetas `tools` y `Python`. Bórralas si están.

Luego busca acceder a la variable de entorno `PATH` y remueve la ruta hacía algún Python.

El comando `choco` para instalar python añádele `--force`.
Quedaría como: `choco install python -y --force`

**Comment by ghost** [comment]
Ya, hice todo eso y no me resulto =(. Esto es exactamente lo que hice:

1- Borre la carpeta tools (que dentro tenia la carpeta python 3) en C:
2- Borre las rutas a python de path (habian 2, una a 3.4 y otra a 2.7).
3- Use el comando con --force en el powershell como administrador. 

Pero me volvio a salir el mensaje de error de antes.

**Comment by ghost** [comment]
Ahora logre que me resultara, me borre otras variables de entorno aparte de path que apuntaban a python y resulto =)
