### ISSUE TITLE
¿Hay alguna razón en particular por la cual usamos PyQt4 y no PyQt5?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#411]

**Comment by lopezjurip** [comment]
`¯\_(ツ)_/¯`

**Comment by fgvenegas** [comment]
![](http://i.imgur.com/C8P3Nps.jpg)

**Comment by robocop6** [comment]
![Image](http://www.miseat127.es/portal/files/posted_images/user_2388_14480d1370632709_nor_cal_darts_club_meet_june_23rd_why_meme.png)

Fuera de broma, tampoco sé, pero si les interesa, [acá hay algunas diferencias.](http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html)

**Comment by bamavrakis** [comment]
![Ni idea](http://sd.keepcalm-o-matic.co.uk/i/keep-calm-because-i-don-t-know.png)
