### ISSUE TITLE
Shot through the heart

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#412]
Estaba probando llevar lo que aparece en la ayudantia 8 sobre threads para recrear el disparo de las balas, pero el problema es que cuando disparo el programa se detiene unos segundo y solo se muestra la posicion de la bala y no su desplazamiento, como aun no defino que se mueva en linea recta al punto donde disparo le dije que se moviera en x y en y hasta llegar al punto (de manera similar a los for en la ayudantia) y eso creo que es lo que puedo explicar sin spoilear codigo, espero sea suficiente(?)

**Comment by robocop6** [comment]
Imagino que estás creando una label (u otro widget) que contiene la imagen de la bala. Si es así, ¿dónde lo haces?:
- En la propia ventana, antes de crear el thread,
- En el `__init__` del thread, 
- En el `run` o 
- Mediante una señal que avise a la ventana que debe crear el widget?

Quisá por ahí puede estar el problema (yo no lo haría en el `run`, a menos que fuese enviando una señal a la ventana), pero no estoy seguro.

P.S: ¿Estás echando a correr el thread con `.start()`, verdad? También podría ser que el programa se queda pegado porque lo haces con `.run()`...

**Comment by fgvenegas** [comment]
Ya cache! mi problema era como estaba llamando al thread (aun no lo domino bien)  gracias !
