### ISSUE TITLE
error pychrm

### ISSUE THREAD

**Issue by fjsalinas** [IIC2233-2015-2/syllabus#413]
![image](https://cloud.githubusercontent.com/assets/8507323/10839084/048a012a-7eae-11e5-8d8f-fd42fb1401ba.png)
me aparece este error cuando trato de correr cualquier archivo, alguien sabe que puede ser??

**Comment by andresespinosapc** [comment]
Yo creo que tienes mal seteado el interpreter de python, puede ser? Se
puede cambiar en settings.
