### ISSUE TITLE
QtThread o QtTimer?

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#415]
Leyendo la documentacion de Qt, me encontre con esto: https://wiki.qt.io/Threads_Events_QObjects#When_shouldn.27t_I_use_threads.3F

Aca dan un ejemplo en el que ponen un thread con un time.sleep() adentro, y dicen que eso es precisamente lo que NO hay que hacer, sino que hay que poner un QtTimer que repita una accion cada cierto tiempo. Como yo tenia estructurado el programa (y como se hizo en la ayudantia) era precisamente con threads con sleeps adentro. ¿Hay alguna ventaja en hacer esto (threads con time.sleep) vs poner un QtTimer?

Osea, que sería mejor, poner un QtThread que este chequeando constantemente el angulo al que apuntan los zombies (por ejemplo) con un time.sleep(0.01) o poner un QtTimer que ejecute un metodo que chequee ese angulo cada 0.01 segundos?

**Comment by robocop6** [comment]
Imagino que resultará mejor con un `QTimer`, ya que fueron diseñados para eso (y, de hecho, ¡no heredan de `QThread` así que deben funcionar de forma diferente!).

Pero no tengo claras las ventajas que tendría por sobre un thread normal (yo nunca los he usado :$). Hay algunos compañeros tuyos que están teniendo problemas cuando tienen varios threads corriendo, como en #417. Quizá con timers no pasarían estas cosas (?).

**Comment by Arios16** [comment]
No, con timers no he tenido esos problemas. 

Pregunto solo por si acaso: si logro hacer funcionar mi juego solo con timers, sin usar explicitamente ningun thread (osea, solo usando los que trabajan internamente en pyqt), ¿hay algun tipo de descuento o algo (dado que uno de los temas de la tarea es threading)?. Pregunto porque el codigo me queda mucho mas ordenado usando timers (cada zombie tiene sus timers adentro que lo van moviendo/rotando, por ejemplo, en lugar de crear zombies que luego echan a correr threads que se definen en clases distintas).

**Comment by robocop6** [comment]
Por supuesto que no se descontará puntaje por usar `QTimer` en vez de `QThread`. Uno de los temas de la tarea es threading, pero el objetivo es que aprendan a separar el problema en procesos independientes, y eso también se logra con timers.

**Comment by Arios16** [comment]
Ok, gracias Ariel.
