### ISSUE TITLE
Trayectoria Bala

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#417]
Que tanto se quiere que se vea la trayectoria de la bala? porque si se quiere ver mas en detalle como se mueve habria que disminuir la velocidad de la bala y siento que eso podria afectar un poco al juego (se ve raro que se muevan como en camara lenta )

**Comment by eiurrutia** [comment]
Te comparto un video que te puede servir como ejemplo. A partir del segundo 50 se puede ver la jugabilidad de este. 
https://www.youtube.com/watch?v=4zsYNKPV6jE
Saludos!

**Comment by fgvenegas** [comment]
Vale! me sirvio, aprovecho de preguntar para no abrir otro issue, porque cuando me pongo a disparar balas mucho a veces el juego crashea y se cierra? tendra que ver con esto ? `QThread: Destroyed while thread is still running`, a las balas les hago label_bala.setParent(None) para borrar el label una ves llegado a donde le dije

**Comment by robocop6** [comment]
Hmm... No estoy seguro, pero podría haber problemas si estás modificando el `parent` del label  desde el thread. Prueba con el método `deleteLater` en vez de setear el `parent` en `None`.

Sobre lo otro que dices, [acá hay un ejemplo en que ocurre este problema](http://stackoverflow.com/questions/24968400/qthread-destroyed-while-thread-is-still-running).  No estoy seguro de si tenga mucho que ver: ahí le responden que eso pasa porque está creando un thread y haciéndole `start()` en un método que termina inmediatamente. Entonces, como dicho thread era una variable local en el scope del método, deja de existir en cuanto el método retorna, y el programa arroja ese mensaje.

**Comment by fgvenegas** [comment]
Vale gracias!

**Comment by raiperez** [comment]
@fgvenegas ¿Cómo lo solucionaste? En el constructor del thread le agregué self.deleteLater() y me sigue crasheando

**Comment by fgvenegas** [comment]
El deleteLater lo tiene la bala (que es un Qthread) y se activa cuando llega a su destino, yo la hago `deleteLater()` al label de la bala y `terminate()` al objeto mismo, ahí no he tenido problemas (creo)

**Comment by fgvenegas** [comment]
@robocop6 , he tenido algunos problemas con deleteLater, no existe algo como setDaemon, para un Qthread? Busqué en internet y no encontré ninguna referencia, gracias

**Comment by robocop6** [comment]
Yo tampoco conozco un `setDaemon` para `QThread`. En todo caso, el programa principal se queda pegado en `app.exec_()` hasta que se termina la aplicación. Puedes controlar lo que ocurrirá cuando se cierre la ventana con un evento que se vio en la ayudantía 8, y bastaría con que en ese momento cerraras manualmente los threads para evitar que se queden corriendo una vez que terminó el programa principal.

**Comment by fgvenegas** [comment]
yap, lo tendre en cuenta, ahora mi problema es cuando disparo muchas balas, ellas llegan al return, pero siento que no estan muriendoo completamente porque el programa se lagea o termina en crash :c hay alguna forma de asegurarme de que murieron ? como isAlive() o  darle un corte definitivo ? (con terminate me quedaba la ~~caga~~)

**Comment by ouhenio** [comment]
Querido Freddie: yo creo que hay que darle con QTimer y te ahorras tanto
problema. <3

**Comment by fgvenegas** [comment]
ya me pase a timers :(, te odio xd mas encima me costo cachar quien eras ajaja, ya close definitivo, gracias tio robocop por todo
