### ISSUE TITLE
Libreria math 

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#419]
Hola, ¿podemos usar la librería math de python? 
Gracias de antemano
Saludos!

**Comment by robocop6** [comment]
¡Claro que sí!
Saludos.

**Comment by paxcema** [comment]
Aprovecho de preguntar aqui, ¿se pueden usar time y defaultdict() de collections?

Saludos.

**Comment by lopezjurip** [comment]
Tanta paranoia sobre los permisos para usar librerías.
**Claro que hay librerías obvias que pueden usar.**

Pregúntense: 

> _¿Qué se está evaluando en esta Tarea?_

Luego: 

> _¿Esta librería hará que yo me abstraiga de un problema o implementación que evite que yo aprenda lo que debería aprender?_

Las librerías típicas matemáticas, de collections, de fechas, claro que pueden usarlas.
Si encuentran una poco conocida y/o cuestionable, quizás esas si valgan la pena preguntar. **Y ADJUNTEN EL LINK**.

**Comment by jgmontoya** [comment]
Podría haber una issue sticky por tarea donde se mantenga una lista de las librearías o módulos que podemos usar (o que no podemos usar) para la tarea en partícular, para no abrir tantos issues preguntando por esto..

Yo creo que el origen de la paranoia es esta linea en los enunciados: 

> Si no se encuentra especificado en el enunciado, asuma que el uso de cualquier librería Python está
> prohibido. Pregunte por foro si se pueden usar librerías específicas.

**Comment by cdonoso** [comment]
Preguntaré por aquí aunque creo que esta si está prohibida jajajaja tkinter?

**Comment by aaossa** [comment]
¿Por qué tkinter? Tienes PyQt D:

**Comment by cdonoso** [comment]
Es que me sale más fácil manejar tkinter que PyQt jajajajaja (al menos por ahora, no se si más adelante será mejor ocupar PyQt que tkinter)

**Comment by robocop6** [comment]
No es posible usar tkinter.
Saludos!
