### ISSUE TITLE
Tarea 1 - Bacanosidad

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#42]
¿Es obligatorio determinar la bacanosidad de manera recursiva o es solamente una sugerencia?

**Comment by bcsaldias** [comment]
Hola !

Que una función esté definida recursivamente no significa que debas calcularla recursivamente. Como la función de fibonacci:

``` python
def fibR(n):
     if n==1 or n==0:
         return 1
     return fibR(n-1)+fibR(n-2)

def fib(n):
     a,b = 1,2
     for i in range(n-1):
         a,b = b,a+b
     return a

for i in range(10):
    print(fibR(i)==fib(i), i, fib(i))
```

La misma función, el mismo resultado, calculado recursivamente e iterativamente.
