### ISSUE TITLE
Rotacion problema coordenadas

### ISSUE THREAD

**Issue by flobarrios** [IIC2233-2015-2/syllabus#420]
Hola!! Tengo un problema con el mousetrak porque creo que esta tomando como origen el mainwindow en la esquina superior izquierda y no el widget del player por ejemplo (defini un label para el player no se si estara bien). Al hacer mousetrak true solo para el label, no pasa nada, pero si lo seteo para el mainwindow, gira la imagen pero solo en un rango de 90grados. Que puede ser??

**Comment by fgvenegas** [comment]
asumiendo que estas sacando arcotangete, estas usando atan o atan2?

**Comment by flobarrios** [comment]
Atan2 pero creo haberlo resuelto usando las coordenadas del player y
restarle las absolutas

**Comment by robocop6** [comment]
Justamente, la posición que te entrega un `QMouseEvent` son relativas a la posición del widget en que se define el método `moveMouseEvent`, que en tu caso es la ventana (como se dijo en la ayudantía 8 :wink: ). Si te entendí bien, lo resolviste restando a la posición del cursor (relativa a la ventana), la posición del jugador (relativa a la ventana).

Sí puedes trabajar con labels, o también podrías hacerlo con `QGraphicsItem`.
