### ISSUE TITLE
Problema con la interfaz

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2233-2015-2/syllabus#421]
Hola! Mi pregunta es cómo hacer para que, al momento de aparecer varios zombies en la pantalla, no me aparezca la ventana "Python.exe dejó de funcionar" a los 3 segundos de andar y deje de correr mi programa (cuando creo un solo zombie y el jugador funciona sin problemas). 
Muchas gracias!
Saludos

**Comment by robocop6** [comment]
¿Estás usando `QThread` o `QTimer` en vez de `threading.Thread`?

**Comment by AlfonsoIgnacioV** [comment]
Estoy usando threading.Thread...  Pero eso para la parte del programa que esta "por detrás". El programa se encarga de setear la posición de la label de la imagen con setPixmap cada vez que el jugador o algún zombie se mueve, pero no se en que parte podría usar lo que dices tú, qué me recomiendas en este caso? Considerando que todo cambia desde atrás primero y hay unos veinte threads de threading funcionando.

**Comment by robocop6** [comment]
Sus ayudantes dedicamos tiempo y esfuerzo a preparar material para que ustedes no sufran tanto como nosotros el semestre pasado (cuando nadie había tenido nuestros mismos errores). **¡Aprovéchenlo!**

Creo que te está pasando porque la ventana tiene un thread principal encargado de realizar las modificaciones gráficas y no funciona bien si haces una gran cantidad de modificaciones desde otros threads. Esto se abordó en las ayudantías, las cuales están subidas al syllabus. Algunos compañeros tuyos también han decidido usar `QTimer` en vez de `QThread` (mira #415 )

Saludos!
