### ISSUE TITLE
Acceso a clases de otro modulo?

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#422]
Hola!

A partir de un string, quiero poder compararlo con los nombres de las subclases de una clase en particular, para encontrar cual es la subclase que coincide con ese string para crear una instancia de ella.  (Espero se entienda). En internet encontré  que podía utilizar la funcion vars() de la siguiente manera:

[subclass for subclass in vars()['nombre_clase']._ _ subclasses _ _() ]

Ahora, eso funciona pero parece que vars solo tiene acceso a las variables dentro del scope de la función dentro de la que se utiliza. Aparte parece que solo reconoce las clases que se definen dentro del mismo módulo, y necesito acceder a las de otros scripts que estoy importando.

¿Cómo puedo hacerlo?

**Comment by robocop6** [comment]
Hola!
Según lo que dices, `vars()`, cuando no recibe un argumento, entrega simplemente las variables del scope en el cual estás. Es un diccionario indexado por strings, cuyos values son los valores de la variable. Creo que podrías solucionarlo como sigue:
- Si conoces cual es la clase a la cual debes buscar subclases (y no es un string, por ejemplo) simplemente puedes hacer `MiClase.__subclasses__()`.
- Si el nombre de la clase de la cual heredan las subclases viene descrito a partir de un string, para **no usar eval**, podrías usar `globals()`. Básicamente te retornará un diccionario al estilo `vars()`, pero con las variables globales.

¡Recuerda usar ` al inicio y al final de un trozo de código para mostrarlo en formato markdown!
