### ISSUE TITLE
lock a Qthread

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#423]
Tengo una duda, cuando un zombie me mata, hago un cambio de ventana y muestro la de Game Over, el tema es que la otra ventana sigue funcionando y el QThread encargado de crear zombies sigue funcionando, pero la ventana con la que trabaja ya no esta, mi duda es como eliminar bien ese thread, porque probe con exit, quit, terminate, deleteLater y no funcionaro, o si existe alguna forma de hacer lock a los Qthread, gracias

Edit: revisando mejor mi problema creo que tiene que ver con que al revisar la lista de zombies no se finalizan todos y la ventana cambia, siendo que tengo que se remuevan, dentro de un for, y despues que cambie de ventana

**Comment by robocop6** [comment]
¿Quizá probando que retorne el `run`?

**Comment by fgvenegas** [comment]
No te cache :(

![](http://i.imgur.com/xOgLRd6.jpg)

**Comment by robocop6** [comment]
jajaja sry, no fui muy claro que digamos.
Es que si pones un `return` en el método `run` cuando quieres que termine, entonces el método acabará en esa línea y después no seguirá creando zombies. Quizá es una forma fea de hacerlo, pero podría funcionar (?).

En cualquier caso, puedes usar los `Lock` de `threading` para sincronizar `QThread` también. O, si prefieres trabajar con PyQt, puedes crear locks instanciando a la clase `QtCore.QMutex`.

**Comment by fgvenegas** [comment]
Es que el tema es que el run es loop que no debe acabar hasta que el juego termine y cambie de ventana, y decirle al thred "la ventana cambio y ya no existe, deja de trabajar" es lo que no me resulta

**Comment by robocop6** [comment]
Podrías tener un atributo `trabajando` en el thread, setearlo en `False` cuando quieras que termine, y que el `run` tenga un `while` verificando si está trabajando (insisto, forma fea de hacerlo jaja).

**Comment by robocop6** [comment]
P.D: Recuerda que debes pausar el juego. Con esto, la alternativa de arriba sería **aun más fea** que pensar en locks.

**Comment by fgvenegas** [comment]
yap si habia pensado algo asi, pero tu dices que mas correcto seria hacerlo con locks?

**Comment by robocop6** [comment]
¡Claro, para eso están!
Ahora, por un tema práctico, si no estás familiarizado con locks, quizá te conviene primero probar con un while chequeando un atributo, ver que funcione, y luego decidir si modificar el código para trabajar con locks.

**Comment by fgvenegas** [comment]
ya perfect gracias por todo :D!

**Comment by spiza** [comment]
Ahí va!
