### ISSUE TITLE
Seleccionar pedazo de foto para el setPixmap

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#425]
Hola! Como puedo seleccionar un espacio determinado de una foto e ir alternando este pedazo?
Por ejemplo, en un tiempo, el zombie se estará moviendo en tal direccion y en otro tiempo, en el sentido contrario (que serían representados por los cuadrados azul y rojo). Necesito ser capaz de decirle al programa que en un momento setee uno de los cuadrados como imagen a mostrar y luego ir cambiandola a necesidad mia. No creo que la idea sea estar cargando constantemente distintas fotos (o si se puede y da lo mismo la memoria?????)

Por ultimo, este comando por el que pregunto, se le aplicaría a un QLabel o a otro contenedor?
Saludos!
![pregunta](https://cloud.githubusercontent.com/assets/13748925/10888319/51848356-816a-11e5-83c4-a4841b1bec71.jpg)

**Comment by jlires** [comment]
Se que no soy ayudante pero si te sirve, para modificar sprites o imagenes en general, lo que yo hice fue transformar previamente estas imagenes en objetos QImage y a partir de ahi medisnte funciones propias de estos objetos recortarlas y guardar los recortes.

**Comment by dpassi** [comment]
Mm... yo tampoco soy ayudante, pero una solucion valida igual es cortar las imagenes con un editor de texto y manejarlas por separado. Obvio hay una solucion mas eficiente.

**Comment by aaossa** [comment]
Yo si soy ayudante (?) y aunque no lo he aplicado ni probado quizás puedan **mostrar** el cuadro de la imagen que quieren (_imaginen un cuadro mas pequeño que una pintura_) y cuando quieran cambiarla **mueven la imágen** (_pintura_) por detrás con _alguna operación matemática_, para ajustar los pixeles, que muestre el pedazo que les interesa. Aunque no sé que tan eficiente ni simple sea.

**Comment by fgvenegas** [comment]
igual no es tan tragico usar imagenes por separado, son solo 30 para que mi zombie se vea fluido (? xdd

**Comment by Pochoclo** [comment]
lo puedes hacer con QRect

``` python
q = QtCore.QRect(10,20,30,40)
pixmap = pixmap.copy(q)
label.setPixmap(pixmap)
label.show()
```

prueba cambiando los valores de QRect y vas a ver que ahí como que corta la imagen me parece que es como QRect(x,y,ancho,alto)

**Comment by trencoret** [comment]
@Pochoclo me dice que pixmap is not defined, cuando le haces pixmap.algo

**Comment by Pochoclo** [comment]
@trencoret Es que me falto poner ahí que hay que antes definir el pixmap

``` python
label = QtGui.QLabel(self)
label.setGeometry(x1, y1, ancho, alto)
q = QtCore.QRect(x, y,ancho,alto)
pixmap = QtGui.QPixmap(ruta_imagen)
pixmap = pixmap.copy(q)
label.setPixmap(pixmap)
label.show()
```

QRect(x, y, ancho, alto) -> x, y corresponden al x, y de la imagen que estas recortando, mientras que ancho y alto es el ancho y el alto del frame que quieres recortar.
Cada vez que quieras volver a cortar la imagen para cambiar el frame, te recomiendo volver a cargar la imagen (pixmap = QtGui.QPixmap(ruta_imagen) ) para que no tengas problemas como cuando rotas la imagen y no la vuelves a cargar.
