### ISSUE TITLE
Puntaje Máximo

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#426]
Existe alguna forma de guardar el puntaje máximo cada vez que se usa el juego y colocarlo en el menú de inicio?
¿Algo así como los juegos arcades? y también alguna página para diseñar una buena imagen para colocarla de fondo del menú de inicio? (Nisiquiera se si se puede, pero agradezco cualquier ayuda :smile: )

Saludos!

**Comment by robocop6** [comment]
- Sobre puntaje máximo: ¡Claro que se puede! Déjalo guardado en archivos (?). Ahora que están viendo serialización, incluso podrías guardar directamente objetos de clase `Puntaje`, o un diccionario u otra cosa que te permita acceder de forma sencilla a la información en vez de andar parseando un string.
- Sobre imágenes... cualquier editor de imágenes en algún formato que puedas cargar a los pixmaps. Si le pones a Paint, hasta podrías hacerlo ahí jaja
