### ISSUE TITLE
Música

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#428]
Agradezco cualquier ayuda, página web o ánimos jajajaja para poder ponerle música al juego o al menos al menú de inicio y un "Game Over" con voz tenebrosa cuando uno pierde.

HEEEEEEEELP! :tired_face: 

Gracias de antemano :)

**Comment by aaossa** [comment]
[**PyQt4.Phonon**](http://pyqt.sourceforge.net/Docs/PyQt4/phonon.html)

``` python
from PyQt4.phonon import Phonon
```

Trataré de dar una mano, pero como es algo simple no quiero poner el código :stuck_out_tongue: Podrías partir por esto.

_PS: Asegúrate de que funcione en tu OS. Como otros alumnos llegarán a esto sería bueno que lo prueben en distintos OS y digan si les funciona para evitar sorpresas cuando algún ayudante vea sus tareas_

**Comment by cdonoso** [comment]
@aaossa graaaciaaaas!!!!! :smile:

**Comment by cdonoso** [comment]
Tengo un problema con esto :( la canción se escucha al final y quiero que mientras se ejecute el menu principal este la canción pero solo pasa si cierro el menu :( como lo arreglo?

**Comment by fgvenegas** [comment]
A mí me funcionó la librería para los sonidos de las balas al menos, como lo pruebo para ver que no vaya a tener problemas después ?

**Comment by aaossa** [comment]
Si te funcionó **escribe tu sistema operativo** para asegurarse de que salgan todos. Si pareciera que funciona en todos los de ustedes, es muy posible que funcione en todos los de los ayudantes. Aunque _debería_ funcionarles a todos ya que vienen con PyQt4 . 

No es lo más seguro del mundo pero debería ser una buena forma de probar en todas las plataformas confiar en sus compañeros

**Comment by fgvenegas** [comment]
![image](https://cloud.githubusercontent.com/assets/13748708/10925713/75e47d40-8288-11e5-8700-ee631faafb4d.png)

**Comment by flobarrios** [comment]
a alguien con mac le funciono ? no me reconoce phonom

**Comment by aaossa** [comment]
¿Cuál es el output cuando usas

``` python
from PyQt4 import phonon
```

@flobarrios ?

PS: A los que les funciona, ¿usan `phonon` o `Phonon`?

**Comment by flobarrios** [comment]
``` python
Traceback (most recent call last):
  File "/Users/Florencia/flobarrios-repo/Tareas/T05/main.py", line 5, in <module>
    from PyQt4 import Phonon
ImportError: cannot import name 'Phonon'
```

**Comment by flobarrios** [comment]
creo que es con minúscula:

``` python
Traceback (most recent call last):
  File "/Users/Florencia/flobarrios-repo/Tareas/T05/main.py", line 5, in <module>
    from PyQt4 import phonon
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyQt4/phonon.so, 2): Symbol not found: __ZN6Phonon22ObjectDescriptionModelILNS_21ObjectDescriptionTypeE0EE11qt_metacastEPKc
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyQt4/phonon.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyQt4/phonon.so
```
