### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#43]
Revisando mi código con PyCharm en una línea me indica lo siguiente:
`PEP8: line too long (151>120 characters)`
donde para la convención PEP8 el máximo de caracteres por línea es 120.
El problema es que en varias partes del código _necesito_ usar más de 120 caracteres. 
¿Tomarán en cuenta ese error al revisar? De no tomar en cuenta ese error PEP8, ¿cuáles no se tomarán en cuenta?

**Comment by aaossa** [comment]
PEP8 no es un conjunto de reglas, sino recomendaciones, por lo que el criterio y la "entendibilidad" de tu código van primero que la guia PEP8. Por lo tanto, no creo que se deba descontar por eso. Pero una recomendación que podrías seguir es definir ese string (si es que es uno) como una variable antes de usarla.

-----Mensaje original-----
De: "javierlopeza" notifications@github.com
Enviado el: ‎23-‎08-‎2015 13:48
Para: "IIC2233-2015-2/syllabus" syllabus@noreply.github.com
Asunto: [syllabus] PEP8 (#43)

Revisando mi código con PyCharm en una línea me indica lo siguiente:
PEP8: line too long (151>120 characters)
donde para la convención PEP8 el máximo de caracteres por línea es 120.
El problema es que en varias partes del código necesito usar más de 120 caracteres. 
¿Tomarán en cuenta ese error al revisar? De no tomar en cuenta ese error PEP8, ¿cuáles no se tomarán en cuenta?

**Comment by mbucchi** [comment]
@javierlopeza , lo que dice @aaossa es cierto, una línea con más de 120 caracteres efectivamente le quita legibilidad a tu código. A mi parecer no existe ninguna situación en la que _necesites_ usar más de 120 caracteres. Tendrás que reestructurar tu código un poco para poder evitar esa situación, pero siempre es posible escribir buen código. A diferencia de lo que dice @aaossa, en una situación como esta **sí** se te descontará por no seguir las normas de PEP8.
Saludos!

**Comment by javierlopeza** [comment]
@aaossa @mbucchi gracias a los dos por la aclaración, voy a tener que reestructurarlo entonces.

**Comment by mbucchi** [comment]
@javierlopeza, acá te doy unos ejemplos que te pueden servir:

``` python
string_no_pep8 = "Este es un string demasiado largo. Por lo mismo esta linea va a tener más de 120 caracteres y no cumplirá con el estandar pep8"

string_pep8 = "Este string también es muy largo. Sin embargo el autor del código conoce" \
              "los estándares de PEP8 y por lo mismo escribe el string en varias lineas."

if "Tambien puede ocurrir en un bloque if porque tienes muchas condiciones." or \
   "Aquí también existen los quiebres" or \
   "Aunque por lo general, bloques if así de largos se pueden evitar":
    pass
```

**Comment by lopezjurip** [comment]
De hecho **lo más correcto son 80 caracteres máximos por linea**. PyCharm les relaja eso a 120, pero en general es así. No sé qué regla aplican los @IIC2233-2015-2/ayudantes-tareos .

Bueno, ¿cómo se hace? @mbucchi les dio un buen ejemplo de _strings_.
Al usar parámetros o clases puedes separar la asignación en múltiples lineas.

``` python
# Mal, mide 83
self.personal.append(Guardia(nombre='Guardia Nº: 1', equipamento=['Equipamento']))

# Bien
self.personal.append(Guardia(
    nombre='Guardia Nº: 1',
    equipamento=['Equipamento']
))

# Bien
self.personal.append(
    Guardia(nombre='Guardia Nº: 1', equipamento=['Equipamento'])
)

# etc, siempre hay una manera bonita de hacerlo
```

**Comment by javierlopeza** [comment]
Perfecto, ¿entonces lo dejamos en 80 caracteres máximos por línea?

**Comment by javierlopeza** [comment]
¿Entonces lo dejamos en 80 caracteres máximos por línea? ¿120?

**Comment by bcsaldias** [comment]
Hola Javier !

Como PyCharm trae por defecto 120 caracteres quedaremos en eso por el curso! . Así tienen un poco de flexibilidad también, pero recuerden que el objetivo general es de 80 :)

Saludos !
Belén

**Comment by javierlopeza** [comment]
Gracias @bcsaldias !
