### ISSUE TITLE
QThreads con eventos de mouse y teclado

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#430]
Hola! Tengo implementado el keyPressedEvent y el mouseMoveEvent, pero el programa solo escucha a uno a la vez. Pensé que podía ser un tema de threads, pero he buscado por horas y no logro encontrar un ejemplo en que los usen para reconocer distintos inputs (solo ejemplos de Qthreads haciendo tareas puntuales, como calcular datos), y tampoco he logrado implementar algo que me funcione. 

Mi duda es si se puede hacer lo que estoy tratando o si en verdad mi problema no se trata de threads. Específicamente pasa que o reconoce al teclado o reconoce al mouse, no a los dos a la vez.

**Comment by ghost** [comment]
Otra cosa que me pasa es que la imagen rota, pero se deforma entera y los pixeles se desordenan.

**Comment by ghost** [comment]
Al final estoy llegando a que definitivamente no tiene que ver con los threads. Algo pasa cuando roto la imagen que hace que el programa se ponga lento y la imagen se distorsiona (a menos que use angulos de 90 grados o multiplos). Ademas, me ha salido este error "qimage out of memory returning null image" que estoy buscando porque pasa.

**Comment by Pochoclo** [comment]
Cuando rotes la imagen vuelve a cargar la imagen y aplicale a la imagen recién cargada la nueva rotación, a mi me pasaba lo mismo y así lo pude arreglar.

**Comment by dpassi** [comment]
Hola, como rotan las imagenes? Gracias!

**Comment by fgvenegas** [comment]
Yo revise el gui de la T04, donde rotaban los autitos, y ctrl + c hizo su trabajo(?

**Comment by Pochoclo** [comment]
Usando un objeto QtGui.QTransform()

``` python
t = QtGui.QTransform()
t.rotate(angulo)
pixmap = QtGui.QPixmap(ruta_imagen)
pixmap = pixmap.transformed(t)
label.setPixmap(pixmap)
label.show()
```

Cada vez que quieras girar la imagen en un ángulo distinto, vuelve a hacer este proceso para que no se te acumulen las rotaciones y no te crashee el programa

**Comment by dpassi** [comment]
Gracias @Pochoclo & @fgvenegas

**Comment by ghost** [comment]
Gracias, funciono perfecto :)

**Comment by benjavides** [comment]
@jnrosenbluth pudiste hacer que la detección del mouse y el teclado sea simultanea? Estoy con el mismo problema, intenté hacer un thread distinto para el trackeo del mouse, pero no puedo usar **self.setMouseTracking(True)** en una clase **QtCore.QThread**.

**Comment by otro-felipe** [comment]
Ambos eventos si son simultaneos por defecto  Si tu programa no lo hace asi es porque debes tener un problema de memoria en alguna parte que retrasa la deteccion de los eventos.

**Comment by ghost** [comment]
@benjavides Si al final era otro el problema, no de threads. Lo que pasaba es como dijeron mas arriba, estaba acumulando la transformaciones en una sola imagen y eso al final chupaba toda la memoria y hacia al programa correr lentísimo y terminar cayéndose.

Si tu problema es el mismo que el mio, entonces la solucion es que, cuando apliques la rotacion, sea sobre un nuevo pixmap que le apliques al label (el codigo lo puso Pochoclo mas arriba).

**Comment by AntoniaMendoza** [comment]
Hola, no sé si vaya al punto pero yo tenía un problema con el keyboard event porque tengo dos widgets (uno dentro de otro) y quería que los keyboard events fuesen reconocidos solo por el widget hijo. Con lo que tenía inicialmente, los recibía solo el widget padre, pero apliqué setFocus()  y  grabKeyboard() y todo funcionó de forma hermosa. 
Eso, lo dejo aquí por si a alguien más le sirve.
