### ISSUE TITLE
QThreads y QGraphics

### ISSUE THREAD

**Issue by jlires** [IIC2233-2015-2/syllabus#431]
Estuve intentando cambiar mi código, el cual se basaba en QTimers a pasar a la utilización de clases QThreads, sin embargo cuando ejecuto he inicio estos threads la consola me devuelve un error/mensaje diciendome que no debiera usar pixmaps desde un thread distinto al de la escena. He intentado y no encuentro la forma de arreglarlo, ojala alguien sepa...

![error](https://cloud.githubusercontent.com/assets/11801248/10928156/dda1f880-8284-11e5-99d7-b5ad92e0d94b.png)

PD: el thread envia notificaciones al objeto QGraphicsScene y este se encarga de mover a la imagen (QGraphicsPixmapItem) que esta en thread

**Comment by robocop6** [comment]
Hmm... imagino que te alega eso para que te veas "obligado" a separar las cosas gráficas (como los pixmaps) de la lógica del juego (`QThread`s). Algo que podrías hacer es que el `QThread` no tenga guardada la `QGraphicsPixmapItem` en su propio ser, sino que esta esté en la ventana, y que el thread solo le notifique que debe actualizar la imagen.

Esta idea de "separar lo gráfico" se conoce con el paradigma de Model-View-Controller, que fue visto en las ayudantías y se evaluó en una actividad (esa del buscaminas).

¡Espero que funcione!

**Comment by robocop6** [comment]
Igual encuentro extraño que tire ese error... ¿el thread no hace nada con pixmaps? Quiero decir... ¿crea el `QGraphicsPixmapItem` en el `run` o algo así?

Quizá es más simple aun, y basta con que en el `QThread`, no uses ningún método relacionado con algo gráfico (aunque sí tengas guardado el `QGraphicsItem` ahí adentro). En tal caso, podrías hacer que reciba el `GraphicsItem` como parámetro al inicializarse, y solo lo guarde como atributo.

**Comment by santiagocruzb** [comment]
Al intentar cambiar la imagen a medida que rotan los zombies me muestra el mismo error (se apreta una tecla, se cambia la imagen, se mueve). Estoy usando QLabels para los zombies. Si los cambio a QGraphicsPixmapItem esto deberia cambiar?

**Comment by jlires** [comment]
Logre solucionarlo separando el programa de la parte gráfica, gracias robocop6

**Comment by flobarrios** [comment]
gracias!! :)
