### ISSUE TITLE
Simplicidad de las colisiones

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#432]
Que tan simple debe ser el sistema de colision? deben esquivarse unos a otros, o si hay un zombie en que los interrumpe en su camino hacia al jugador simplemente no caminan hasta que haya espacio?

**Comment by robocop6** [comment]
Hola!

Puede ser tan simple como que no camine si otro zombie está ocupando la posición de destino. La tarea está más bien enfocada en la parte gráfica que en la inteligencia de loz zombies ;)

Ahora, si quieres hacer algo un poco más sofisticado, ¡no hay problema! Pero será trabajo extra :+1:

**Comment by tamycova** [comment]
pregunta! esque en el juego de referencia los zombies igual se "sobrelapan", como son png no se ve mal de hecho le da mas realismo a la cosa, mientras no calcen al 100% esta bien cierto?

**Comment by robocop6** [comment]
Dejemos que responda @bamavrakis o @mbucchi!
