### ISSUE TITLE
QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by tomvillage** [IIC2233-2015-2/syllabus#433]
¿A alguien más le pasa este error? al llamar el método .start() de un thread  python me deja de funcionar. 
También me pasa con el ejemplo de thread de  la ayudantía 8, por lo que quería saber si es un problema de mi computador o a más gente le pasa y si alguien tiene alguna solucion!

saludos!

**Comment by fgvenegas** [comment]
Yo por eso me cambie a timers :(

**Comment by benjavides** [comment]
Me pasaba lo mismo era **porque no estaba guardando el thread en una variable del thread principal**, en mi caso en la `MainWindow`.
Lo que yo hacia era crear un thread en el `__init__` de mi `MainWindow`, el problema es que se creaba, pero al terminar de ejecutarse el `__init__` se perdía la referencia al thread y era eliminado.
Para solucionarlo guarda el `Thread` como:

``` python
class MainWindow(QtGui.QWidget):
    def __init__(self):
        self.nuevo_thread = Thread()

class Thread(QtCore.QThread):
    pass
```

**Comment by tomvillage** [comment]
@benjavides buena ahí los solucione, gracias!
