### ISSUE TITLE
Problema con QTimer

### ISSUE THREAD

**Issue by flobarrios** [IIC2233-2015-2/syllabus#434]
Hola!! Estoy teniendo un problema con QTimer. Hasta ahora, tengo 2 timers, uno que crea cada cierto tiempo un objeto del tipo zombie (funciona bien) y el segundo esta dentro del objeto zombie, que cada cierto tiempo debería mover al zombie. El segundo timer esta definido en el init del objeto Zombie y llama a: 

``` python
self.timer.timeout.connect(self.walk)
```

mi problema es que este timer no es ejecutado y no logro descifrar porque :(. Lo otro, una vez iniciado el timer, se puede cambiar el intervalo (dado que la frecuencia de aparición de zombies va aumentando). Gracias!!

**Comment by otro-felipe** [comment]
Has que tu zombie extienda a `QObject` y como parent le pones el `QWidget` que tienes para tu juego. Asi lo solucione yo.

**Comment by flobarrios** [comment]
gracias!! :smile:

**Comment by crabarca** [comment]
Hola! @MainScientist a que te refieres con ponerle como parent el Qwidget? Dentro de los atributos del zombie?

**Comment by otro-felipe** [comment]
Para que tus clases sean compatibles con los threads de PyQt puedes hacer que hereden de la clase QObject que esta en el package QtCore. El init de QObject tiene un solo parametro que es el parent (lo puedes pensar como el objeto que va a contener a tu clase). Esto hara que dentro de tu clase puedas llamar los QTimers y ejecutarlos desde la misma. (Asi me resulto a mi).

Te dejo la [documentacion](http://pyqt.sourceforge.net/Docs/PyQt4/qobject.html) de la clase para que le puedas echar un ojo si asi lo deseas :) la parte importante es:

> **_Thread Affinity_**
> 
> A QObject instance is said to have a thread affinity, or that it lives in a certain thread. When a QObject receives a queued signal or a posted event, the slot or event handler will run in the thread that the object lives in.
> 
> Note: If a QObject has no thread affinity (that is, if thread() returns zero), or if it lives in a thread that has no running event loop, then it cannot receive queued signals or posted events.
> 
> By default, a QObject lives in the thread in which it is created. An object's thread affinity can be queried using thread() and changed using moveToThread().
> 
> All QObjects must live in the same thread as their parent.

y

> **QObject.__init__ (self, QObject parent = None)**
> 
> The parent argument, if not None, causes self to be owned by Qt instead of PyQt.
> 
> Constructs an object with parent object parent.
> 
> The parent of an object may be viewed as the object's owner. For instance, a dialog box is the parent of the OK and Cancel buttons it contains.
> 
> The destructor of a parent object destroys all child objects.
> 
> Setting parent to 0 constructs an object with no parent. If the object is a widget, it will become a top-level window.

Espero que eso te aclare un poco mas las dudas a ti y a quienes lean esto :)

**Comment by crabarca** [comment]
@MainScientist Lo pude solucionar. Muchas gracias por la explicación, muy clara!

**Comment by jgmontoya** [comment]
@MainScientist para ayudante 2016  :exclamation: :exclamation:  :smile:
