### ISSUE TITLE
Pixeles y rotar label

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#435]
Tengo dos dudas semi triviales, 

1) Cuando roto el pixmap tengo que rotar la label para que no se corte la imagen, o usar una label mas grande (creo), existe alguna forma de rotar la label o chao?
2) Para las colisiones y cuando el zombie ataca, tengo que revisar que los pixeles del zombie lleguen a un pixel usado por el jugador?

**Comment by robocop6** [comment]
No sé si puedes rotar una label. ¡Pero puedes probar cambiándole el tamaño!
Te puede servir el método `sizeHint`. ¡Dime cómo te va!

**Comment by robocop6** [comment]
Y para las colisiones, podrías hacerlo como dices, revisando pixeles. También podrías hacer que ataque/se detenga si llegan a un pixel que esté a menos de cierta distancia de una colisión.

O podrías tener una "grilla" de posiciones de modo que el movimiento sea "continuo" (pixel por pixel) y a cada posición en pixeles le asocies una posición en una grilla de mayor tamaño, y trabajar revisando la grilla.

**Comment by tamycova** [comment]
gracias!!!
