### ISSUE TITLE
Error importando .py

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#436]
Hola!
En tareas anteriores había importado infinitos .py pero ahora sin razón no lo quiere hacer.
En la foto queda claro que el archivo A.py está en la misma carpeta que Front.py (donde estoy trabajando), pero aún así no lo importa.
Como información extra, me deja importar .py's de otras carpetas nada que ver (?)
Ayuda!
![screen shot 2015-11-05 at 6 37 21 pm](https://cloud.githubusercontent.com/assets/13748925/10982590/dccfd9e0-83ec-11e5-8238-7ed94d3a7cee.png)

@mrpatiwi @robocop6

**Comment by aaossa** [comment]
No sé como funciona pyCharm exactamente (yo no lo uso), pero quizás tienes mal configurado el path del archivo. Si lo importas ejecutando Python de otra manera, ¿te sale el mismo error?. Si creas un nuevo `.py`, ¿te sigue saliendo el error?

**Comment by robocop6** [comment]
Estás seguro de que no lo importa? 
A mí me ha pasado que el editor no me lo reconoce (como muestras en la imagen), pero el programa corre bien. No he buscado por qué pasa... Mientras funcione, yo feliz :joy:

**Comment by jgmontoya** [comment]
Si solo te marca que no lo reconoce pero igual corre (como mencionó Ariel) lo puedes solucionar haciendo click derecho en la carpeta en la barra project (a la izquierda) y seleccionando 
Mark Directory As --> Sources root

**Comment by fgvenegas** [comment]
Cuando creas la carpeta la creas normal o como una carpeta para "almacenar modulos"?

**Comment by santiagocruzb** [comment]
Algo pasó que si los está importando, pero me muestra como si hubiera un error pero igual corre (lineas rojas de pycharm estilo falta de ortografía). Será por ahora, gracias de todas maneras!
