### ISSUE TITLE
QThread con lag random

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#437]
Para hacer el movimiento del personaje hice un QThread, y corro el programa y funciona perfecto, trato de hacer lo que sea, apretar muchas teclas a la vez etc., y ningún problema. Después cierro el programa, lo corro de nuevo y al tratar de moverme funciona asquerosamente mal, en el momento de apretar una tecla el player se teletransporta, funciona pegado, hasta que en muy poco rato ya deja de funcionar el programa completamente. Lo corro varias veces y sigue pasando lo mismo. 
 Lo raro es que me ha pasado que al volver a una version de git anterior me funciona bien, o creo que al apagar el computador y prenderlo de nuevo. No estoy tan seguro de estas cosas, pero sé que me ha pasado muchas veces que a la primer me funciona y después deja de funcionar.
 Alguna idea ? :/

**Comment by aaossa** [comment]
Quizás no eliminas todos los threads que creas y tienes muchos procesos abiertos suspendidos. Cuando corras el programa revisa cuántos procesos `python` están ejecutándose y después de cerrar la interfaz vuelve a revisar.

Esto de los threads es como los archivos: "Es de buena educación cerrar la puerta después de entrar", asi como es una buena práctica cerrar un archivo después de usarlo o eliminar un thread cuando ya no lo necesitas.

**Comment by andresespinosapc** [comment]
Lo arreglé simplemente usando threads del módulo threading, no cambié nada más (tuve que heredar de Thread y de QObject para poder enviar señales). 
 Cuando lo estaba haciendo con QThreads según yo cerraba todos los threads, traté muchas veces y rigurosamente. La última vez que lo hice fue haciendo una variable is_running fuera del thread que se volvía True justo antes de empezarlo y no se podía empezar otro hasta que fuera False de nuevo. Se volvía False justo al final del run() (según yo al terminar el run debería eliminarse el proceso automáticamente, no sé si estoy en lo correcto).
 En fin, mis intentos por usar QThread fallaron, creo que realmente me falta conocer mejor su diferencia con los built-in.

**Comment by aaossa** [comment]
Solo por si acaso, ¿qué editor usas?¿Sublime, PyCharm, la IDLE de Python?

**Comment by andresespinosapc** [comment]
Usé Sublime, después probé una vez desde la terminal, pero supongo que no importa porque desde Sublime creo que corro directo a la consola, no con Anaconda.

**Comment by aaossa** [comment]
Sublime tiene como un problema con esto, lo que sucede es que, puedes ejecutar el código de una interfaz muchas veces y nunca va a cerrar las interfaces anteriores, como que el proceso queda corriendo por detrás. Entonces seguramente lo que haces es usar la interfaz y cerrarla "mal", en el sentido de que sigue corriendo a escondidas). Lo que te recomiendo es que, en vez de cerrar la interfaz _mates_ el programa desde Sublime. Esto lo puedes hacer creando un _shortcut_ para terminar el programa.

## ¿Cómo agregar un atajo de teclado en Sublime?

Ve a `Preferences > Key Bindings - User`, se abrira un archivo que en verdad es un JSON. Lo único que debes hacer es agregar esto (asumo que está vacío):

``` json
[
    { "keys": ["ctrl+k"], "command": "exec", "args": {"kill": true} }
]
```

Luego guardas el archivo, lo cierras, cierras sublime y vuelves.

## ¿Para qué hacer esto?

¿Alguna vez te ha quedado un loop infinito corriendo? Lo que debes hacer es ir a la sección de consola de Sublime, mientras tu programa está corriendo y presionar `ctrl + k` para _matar_ el programa. Esto debería matar todos los threads de **la ejecución actual** (ojo, no garantiza funcionar si ya tienes corriendo mil veces un programa).

Ve a probar esto. Cuando estés probando la interfaz y no tengas claro que pasa con los threads, anda cerrando tu programa así, de forma que te asegures de matar la ejecución del programa.

**Comment by andresespinosapc** [comment]
Graicas ! Voy a dejarlo como thread normal por ahora para seguir avanzando, pero lo voy a tener en cuenta para más adelante ! 
 Solo una pregunta: Si en la consola de Sublime sale [Finished] todavía podría estar pasando que queden threads abiertos?

**Comment by aaossa** [comment]
Se supone que no, al menos acabo de hacer una prueba rápida con threads de `threading` y no tuve problema. Pero no revisé con `PyQt4`.
