### ISSUE TITLE
Error Importando

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#438]
Hola!!

Alguien me podría aclarar cómo debería ser la jerarquía de importadas de otros módulos? 

Hasta ahora lo he estructurado como que el script "más principal" importe uno menos principal, el que a su vez va a estar importando otro todavía menos principal.

El problema es que ahora necesito hacer un método de una clase que está muy por abajo en esta cadena, interactuando con una clase de un script que está muy arriba, y no me deja importarlo porque (creo yo) al importar el de más arriba intentaría importar también los ese mismo está importando (entre  los cuales está el script del principio).

Espero se entienda. En el fondo necesito saber cómo debo organizar los distintos scripts para que puedan siempre interactuar libremente con la información de los otros scripts sin tener que juntarlos todos en un solo archivo de 100000 lineas.

Gracias de antemano

**Comment by jgmontoya** [comment]
No sé como _debiera_ ser pero las veces que me he encontrado en una situación como esa en la que tengo un módulo A que necesita importar de otro B que a la vez necesita importar de A, siempre he podido crear un tercer modulo C tal que tanto A como B importen de C.
