### ISSUE TITLE
Ocupando Imagenes

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#439]
Estimados tengo una duda, por todo el tema del código de honor y derechos de autor y esas cosas, si estoy ocupando una imagen para mi mapa de otro juego o para el menu de inicio, ¿es necesario decir en el README que los archivos no son míos y casi que poner el link de donde los saque? 

Perdón si es tonta la pregunta pero prefiero asegurarme :sweat_smile: 

Saludos!

**Comment by bamavrakis** [comment]
Da lo mismo eso, siempre y cuando no lo vayas a comercializar.
Saludos!
