### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#440]
Hola, estaba revisando la actividad del semestre pasado donde creaban un "chat" con sockets, en teoria ese chat deberia funcionar mas alla que en solo 2 consolas de mi pc a la vez?, por ejemplo con 2 pcs que corran el programa y que esten conectados a la misma red? o deberia hacer alguna modificacion porque lo intente y el cliente nunca encontraba al pc que hacia de servidor. Gracias!

**Comment by otro-felipe** [comment]
Ese problema podria tener muchas causas. Tipear mal la ip, algun firewall que este bloqueando la conexion tanto del programa como del puerto, o que la red donde esta el servidor no tenga los puertos redireccionados (en caso de que no sea una conexion local este es el mas probable).

**Comment by lopezjurip** [comment]
No lo intentes en la U porque la WiFi tiene hartas restricciones.

Pero sí, en tu casa bajo una red local (LAN) debería funcionar.
Para trabajar en la red _global_, no es trivial.

**Comment by fgvenegas** [comment]
Lo estaba probando con el wifi de mi casa, respecto a lo de la ip, estaba usando lo de gethostname() pero creo que no  es lo correcto en este caso, como podria ver tambien lo de los puertos redireccionados?

**Comment by otro-felipe** [comment]
Si es el wifi de tu casa entonces no tiene que ver con la redireccion de puertos, de todas cotmas si te interesa saber puedes googlear port forwarding. Probablemente el gethostname no esta dandote tu ip local o el firewall de un equipo este bloqueando la conexion del programa.
