### ISSUE TITLE
Tarea5

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#441]
hola, cree un metodo del main windows que creara zombies, al apretar la tecla z se llamaba aeste metodo y se crean los zombies y funciona super bien pero al crear un worker que vaya llamando al metodo para crear zombies cada cierto tiempo, este en vez de crearlos en la interfaz, como que abre una nueva ventanita y se queda pegado todo hasta que el worker termine de trabajar, como hago para que el worker pueda llamar al otro metodo y cree los mismos zombies que deberian estar buenos porque funciona si los creo apretando el boton pero que los cree en la misma ventana pincipal??

**Comment by fgvenegas** [comment]
Yo tengo un sistema parecido, lo de la ventanita extra podria ser porque el worker no este recibiendo al widget con el que trabajas como parent, lo otro, que es tu worker? si es un Qthread o un Qobject deberia funcionarte mandandole una señal al Widget para darle la orden que cree los zombies, al menos algo asi hago yo
