### ISSUE TITLE
Clase con QPixmap

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#443]
Tengo un problema muy raro, supongo que por no entender bien cómo funcionan los QPixmap. Lo que pasa es que el jugador no se muestra cuando recién empieza el juego, si lo muevo sí aparece, y cuando lo dejo de mover desaparece.
 Esto pasó cuando creé una clase que tiene como atributo el pixmap del jugador quieto, un iterador con los pixmaps que irán cambiando durante la animación y un atributo con el pixmap que debería tener actualmente.
 Pensé que era un problema de no estar guardando el pixmap en el QWidget principal (aprovecho de decir que la clase no hereda de nada, y ya traté heredando de QObject con parent el QWidget principal), pero en ese caso no debería funcionar ni siquiera la animación (esta sí funciona, como dije antes al moverme funciona).
 Ojalá alguien sepa qué puede ser... No quiero hacer variables para cada objeto, lo encuentro muy hardcodeado :(

**Comment by fgvenegas** [comment]
Pero cuando instancias al jugador no le haces `self.label.setPixmap(pixmap)` en el constructor ? Al menos así me funciona a mi

**Comment by andresespinosapc** [comment]
Tú dices hacer eso en el **init** de la clase? Heredando la clase de algo o no? Es que cuando uno usa QPixmap en una clase aparte sale "QPixmap: It is not safe to use pixmaps outside the GUI thread"

**Comment by fgvenegas** [comment]
Claro, lo que yo hago es que mi GUI instancie al jugador y entre los parametros, se entrega el widget asi mismo y un pixmap ya creado, asi el jugador es el que crea el label, y le hace setPixmap, con el pixmap que recibio como atributo

**Comment by andresespinosapc** [comment]
Gracias, ahí me funcionó, aunque no exactamente como dijiste, porque yo necesitaba ir guardando un pixmap distinto para cada objeto, así que al final guardé los pixmap como atributos pero mandé una señal para hacer setPixmap().
