### ISSUE TITLE
cambiar estilo

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#445]
¿Como le cambio el estilo a un QPushButton o a un QLCDNumber? En el primero me sale la linea del borde del botón detrás del icono de pausa que le puse y en el segundo quiero cambiar el color y sacarle la linea de borde también. Busqué y encontré los métodos style y setStyle() pero no caché muy bien como implementarlos.

Gracias !

**Comment by fgvenegas** [comment]
Puedes averiguar un poco sobre [StyleSheet](http://doc.qt.io/qt-4.8/stylesheet-examples.html), que es un poco como funciona CSS, que no es mas que un JSON, salen ejemplos en el link de como modificar muchos parametros de los QPushButtons
