### ISSUE TITLE
¿input() detiene los Threads que ya partieron?

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#446]
¡Saludos!

Resulta que si uno usa **input()** después de haber iniciado un **Thread** con **start()** éste se detiene a la espera de la entrada del usuario. Suponiendo que los Thread se ejecutan paralelos al programa principal no me hace sentido este hecho. Más específicamente, los print() que debería lanzar el Thread en pantalla se detienen cuando llega el momento de un input(). El código de ejemplo es el siguiente:

```
import threading
import time

def funcion_1(frase):
    number = 0
    while number < 100:
        print(frase,end="")
        time.sleep(0.5)
        number += 1

def funcion_2():
    number = 0
    while number < 100:
        user_input = input()
        print(user_input,end="")
        number += 1

a = threading.Thread(name="1",args=("Esto debería aparecer cada medio segundo.",),target=funcion_1)
a.start()
b = threading.Thread(name="2",target=funcion_2)
b.start()
```

El resultado esperado sería que la frase del Thread se imprimiese de forma continua cada medio segundo, independientemente de si ingreso un input o no. Sin embargo, se imprime una sola vez y después me exige el input() antes de continuar. 
El comportamiento a continuación, por alguna razón, varía entre el Python Shell de IDLE, y el CMD (pueden probarlo fácilmente). En cualquier caso, ninguno de los dos tiene el mensaje imprimiéndose de forma continua.

Esto sucede independientemente de si el input() forma parte del Thread "b" (como en el ejemplo) o si lo pongo como variable global (o sea, como parte del programa principal).

¿Qué sucede? ¿Se puede hacer lo que pido con correcciones o comandos simples? ¿Es un problema de input()? 

Muchas gracias.-

**Comment by otro-felipe** [comment]
Mas que un problema de input yo creo que va en la funcion print e input juntas. Puedes tener varios threads, pero la consola es una sola, por lo que aunque ambas funciones esten en threads separados, ambas buscan usar la consola y si la consola ya esta ocupada con un input, la funcion print podria ser que "espere" a que la consola se desocupe con el primer print. (No se nada en especifico, pero creo que es por algo de este estilo). Puedes asumir que la consola de python y el cmd procesan el stream de manera ligeramente diferente en base a las diferencias que notas al ejecutar tu programa en ambas y obtener resultados diferentes.

Por eso es mejor usar GUIs, donde no hay un organizmo manipulador de la inforamcion, si no que varios threads se encargan de mostrar la infromacion. Piensa la consola como un widget donde al enviarle una señal, esta la mete en una cola y las va mostrando una a una :) (me da la impresion de que es algo asi).

Insisto, no se bien si esto es asi y si estoy mal o alguien sabe algo mas especifico por favor corrijanme.

**Comment by lopezjurip** [comment]
Prueba esto:

``` python
import threading
import time

def funcion_1(frase):
    for number in range(100):
        print(frase, number)
        time.sleep(0.5)

def funcion_2():
     for number in range(100):
        user_input = input("Ingrese Input")
        print(user_input, number)

a = threading.Thread(name="1",args=("Esto debería aparecer cada medio segundo.",),target=funcion_1)
a.start()

b = threading.Thread(name="2",target=funcion_2)
b.start()
```

En la terminal:

```
$ python thread.py

Esto debería aparecer cada medio segundo. 0
Ingrese InputEsto debería aparecer cada medio segundo. 1
Esto debería aparecer cada medio segundo. 2
Esto debería aparecer cada medio segundo. 3
Esto debería aparecer cada medio segundo. 4
Esto debería aparecer cada medio segundo. 5
Esto debería aparecer cada medio segundo. 6
Esto debería aparecer cada medio segundo. 7
jeje
jeje 0
Ingrese InputEsto debería aparecer cada medio segundo. 8
Esto debería aparecer cada medio segundo. 9
Esto debería aparecer cada medio segundo. 10
jeje
jeje 1
Ingrese InputEsto debería aparecer cada medio segundo. 11
jEsto debería aparecer cada medio segundo. 12
ejeEsto debería aparecer cada medio segundo. 13
```

**Comment by otro-felipe** [comment]
Entonces lo que decia yo no tenia nada nada **nada** que ver, pero no entiendo por que no funciona al usar el end="" :(

**Comment by gebalassa** [comment]
@mrpatiwi

Agradezco el código pero no entiendo cómo el imprimir un número al lado de cada **print()** arregló el problema. :-(

**Comment by gebalassa** [comment]
Sí,
eso del **end=""** no debería tener efecto :-/
