### ISSUE TITLE
Pueden los zombies botar vida y ammo?

### ISSUE THREAD

**Issue by ouhenio** [IIC2233-2015-2/syllabus#447]
Hace mas sentido que se le caiga a un zombie a que pase un helicoptero y no te sheve.

**Comment by vabesa** [comment]
El terreno quizás no es apropiado para aterrizar y por eso no te pueden llevar y solo lanzar ayuda para que sobrevivas. Te recomiendo que lo que esta especificado en el enunciado lo cumplas y lo que no lo dejes a tu criterio!.
