### ISSUE TITLE
Exportar

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#449]
Hola!

Existe alguna manera de transformar todo nuestro juego en un archivo que no requiera tener instalado python ni las librerias? (Así como para poder enviarlo a algun amigo )

**Comment by lopezjurip** [comment]
Se suele usar [py2exe](https://pypi.python.org/pypi/py2exe/). Puedes revisar la documentación y contarnos cómo te va :)

**Comment by jgmontoya** [comment]
Si lo logras coméntalo acá porfa!

**Comment by aaossa** [comment]
Yo tuve algunos problemas con py2exe (hace unos dias estuve haciendo un ejecutable). Para windows me fue más fácil utilizar [cx_Freeze](http://cx-freeze.readthedocs.org/en/latest/index.html). Aunque me costó encontrar algún ejemplo parecido a lo que necesitaba (PyQt4) al final lo encontré en su repo.

**Comment by Rodancoci** [comment]
A mí me funcionó pyinstaller
