### ISSUE TITLE
Consulta módulo re

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#45]
¿Se puede utilizar el módulo _re_ para trabajar con expresiones regulares?

**Comment by bcsaldias** [comment]
Hola ! 

Deben hacer la lectura de archivos y el parseo con la materia que aprendieron en el curso requisito. 

" La principal razón es que ese tipo de materia se va a ver más adelante y queremos que realmente comprendan cómo funciona (y de pasada, cuando lleguemos a esa materia ya van a entender porqué es tan útil y conveniente :) ) (Marco Bucchi, Jefe Tareos)"

Saludos!
Belén
