### ISSUE TITLE
Background image QWidget

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#450]
Hola, como le puedo agregar una imagen de fondo a la ventana(Widget) ? Probé definiendo un QLabel y dandole un Pixmap para el fondo, pero si hago eso no me deja rotar al shooter...

Heelp

**Comment by flobarrios** [comment]
hola!! prueba con esto:

``` python
self.setStyleSheet("QMainWindow {border-image: url('imagen.png');}")
```

**Comment by ghost** [comment]
@flobarrios no me funciona, también probé con background-image y nada

**Comment by crabarca** [comment]
Hola! tambien puedes hacer QLabel.setMouseTracking(True)

2015-11-08 19:25 GMT-03:00 Florencia Barrios <notifications@github.com>:

**Comment by eduguerra-uc** [comment]
@fekunze Para que me funcionara hice que la clase de mi ventana/widget a la que quería cambiarle el fondo herede de QFrame en vez de QWidget.

**Comment by andresespinosapc** [comment]
Si todavía te sirve yo lo hice con QPalette de la siguiente forma, dentro
del QWidget:

``` python
palette = QPalette()
palette.setBrush(QPalette.Background,(QPixmap('assets/{}'.format(map_filename)))
self.setPalette(palette)
```
