### ISSUE TITLE
Dudas enunciado T05

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#451]
En el enunciado dice "el arma tiene un rango limitado, por lo que un disparo no viajará
indefinidamente".  ¿Hay que darle un rango fijo al arma, de manera que uno no sea capaz de disparar de una esquina a otra, o esto simplemente hace referencia a que hay que eliminar la bala cuando salga del mapa?

También dice (en relación al personaje principal) '... se debe diferenciar su aspecto al caminar en distintas direcciones'. ¿Hay que poner sprites distintos cuando se mueve para los lados que cuando se mueve para adelante (o en diagonal)? ¿O da lo mismo, simplemente hay que animarlo al caminar?

Y por ultimo, al final dice que la tarea debe ubicarse en la carpeta 'Tareas\Tarea_05'. Supongo que esto es un error de enunciado y que el formato es el mismo de siempre, osea, 'Tareas\T05', no?

**Comment by lopezjurip** [comment]
Sobre la bala, lo primero que dices es lo correcto.

Sobre lo del movimiento, que mejor lo conteste un tareo.

Sobre lo de la carpeta, voy a tener que asesinar a un tareo. Sí, hay un error, debería ser la carpeta `Tareas/T05`, a modo de seguir el estándar del curso :+1:

**Comment by aaossa** [comment]
Corregido lo de la carpeta en #452 :grin:
