### ISSUE TITLE
Tarea 5 delete Qlabels

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#453]
Hola, en cada run() defini un while que funcione si se cumple cierta cosa, por ejemplo que la vida sea mayor que 0, el tema es que cuando la vida es cero sale del while y muere el thread (por lo menos eso creo yo) pero si es un zombie el que muere este no desaparece despues de que el run() finalice, tuve que eliminarlo por asi decirlo de la lista de los zombies y aparte ponerle que no sea visible, pero como hago realmente para eliminar los Qlabels?

**Comment by iqacevedo** [comment]
Hola me parece que es con Label.close()
