### ISSUE TITLE
Prioridad

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#454]
Mi juego funcionaba bien hasta cuando el agregue las colisiones entre zombies, por cosas que desconosco ahora cuando colisionan los zombies y hay muchos se ve con lag, sera mejor dejar las colisiones o sacarlas y que este fluido?

**Comment by vabesa** [comment]
Prioriza lo de las colisiones de los zombies, trata de nunca dejar de lado aspectos que estén explicitos en el enunciado.
