### ISSUE TITLE
Prioridad de visibilidad

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#456]
Hola, alguien sabe cómo hacer que algunos labels se vean siempre encima de los otros widgets?
Aclaro que no estoy usando QGraphicsView ni QGraphicsScene y no tengo mucho tiempo para cambiarlo todo a eso. En última instancia, si alguien sabe cómo cambiarme rápidamente a esto que me lo diga por favor.

**Comment by fgvenegas** [comment]
label.raise_() y lable.lower(), cuando crees un label nuevo por ejemplo sangre, debes hacer raise a lo que quieres que quede encima

**Comment by benjavides** [comment]
Si los labels los creas con QtDesigner puedes hacer click derecho en este y luego **Bring to front** o **Send to Back**. Si los creaste en el juego me imagino que puedes usar `label.raise()` y `label.lower()`. ([Fuente](http://www.qtcentre.org/threads/803-Z-order-for-standard-widgets)) siempre y cuando las cosas estén en el mismo `QWidget`.

**Comment by andresespinosapc** [comment]
Gracias !!! Funcionó perfect :+1:
