### ISSUE TITLE
Error libpng 

### ISSUE THREAD

**Issue by flobarrios** [IIC2233-2015-2/syllabus#457]
Hola ! al crear la heath bar (imágenes en formato .png), me tiro esta advertencia muy rara:

``` python
libpng warning: iCCP: known incorrect sRGB profile
```

No me había pasado con ninguna otra imagen, solo esta. Me preocupo o lo dejo así nomas  (no interfiere en el juego, solo que cuando cambia la imagen de la barra aparece eso en consola).

Gracias :smile:

**Comment by aaossa** [comment]
Encontré que ese error al parecer se da en Linux. Si estás usando Linux, en Google salen varias posibles soluciones :grin:

**Comment by flobarrios** [comment]
Estoy usando mac :/ y no encontre nada al respecto en google 😔

**Comment by paxcema** [comment]
A mi me pasó con un par de imágenes. Opté por la solución bruta y las guardé con extensión .tiff, asegurándome de que tuvieran un perfil de color normal (usé Seashore en OS X, por si te sirve).

**Comment by benjavides** [comment]
A mi me aparece desde el principio en Windows, no he tenido ningún problema. Según leí te advierte que el color que se muestra en la pantalla de tu imagen podría no ser tan fiel al real del archivo, pero da lo mismo.
