### ISSUE TITLE
Python 2.7.10 v/s Python 3.4.0

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#459]
Estimados como puedo hacer que un archivo se quede guardado en una versión y no se cambie a la otra? Resulta que quiero utilizar la librería pygame para un juego y no está disponible para la versión 3.4. Entonces abrí IDLE con python 2.7, después guardé el archivo y al momento de abrirlo me lo abre con python 3.4. Esto me genera enormes problemas por la librería pygame

¿Como lo arreglo? 

Saludos y gracias! :smile:

**Comment by lopezjurip** [comment]
Me imagino que no es para esta tarea.

No importa con que lo abras y/o guardes. Lo importante es con qué lo interpretas. La mejor manera es ejecutarlo usando la terminal. 

Sin embargo, en PyCharm puedes elegir qué versión de Python usar. 

Pero si estás en Linux u OSX y prefieres el modo _hacker_, puedes bajar algún administrador de versiones. Yo uso [pyenv](https://github.com/yyuu/pyenv).
