### ISSUE TITLE
I2

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#460]
Hola!
Para poder estudiar, van a subir las resoluciones de las actividades de la materia que entra?
Saludos!

**Comment by bcsaldias** [comment]
Hola ! :)

No, pero puedes mirar el material del semestre pasado.

Saludos !!

**Comment by bcsaldias** [comment]
*Y obviamente todo lo de este semestre contando las ayudantías.

**Comment by javierlopeza** [comment]
En cuanto a Interfaces Gráficas, ¿qué se pide saber para la prueba mañana? Para no memorizar cosas por nada. Gracias. 
EDIT: Pregunto porque en una ayudantía pasada se señaló que no se esperaba que nos aprendieramos ciertas cosas de PyQt en específico.
`AYUDANTIA 8: Ninguno de nosotros pretende que sean unos maestros en PyQt. Solo se espera que sepan buscar por las clases que necesitan en Google.` Y claramente en la prueba no tenemos Google.

**Comment by tamycova** [comment]
+1!!

**Comment by aaossa** [comment]
Para la prueba les recomendaria conocer los principales widgets disponibles y sus principales métodos (por ejemplo, conocer los QButton y como hacer connect). Les recomiendo ver el material del semestre pasado para que vean el nivel de la pregunta de ese semestre

**EDIT:** No hace falta ser un maestro de PyQt para conocer algunos de los widgets mas importantes. Si  los han usado regularmente conocerán los principales métodos y esperamos que, como hayan hecho las actividades y tareas, ya conozcan muchos widgets y su uso básico

**Comment by trencoret** [comment]
@aaossa con que profundidad nos van a preguntar Networking? Porque no entro el semestre pasado... Al estilo de las actividades? O mucho mas simple?

Saludos y gracias

**Comment by ivaniadg** [comment]
Networking se va a preguntar con la misma profundidad vista en clases, ayudantías y tareas.
