### ISSUE TITLE
Alcance del servidor

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#462]
Cuando dice que un cliente pueda conectarse desde cualquier computador, es de manera local? o yo de desde mi casa puedo subir archivos al servidor de un amigo?

**Comment by mbucchi** [comment]
Hola!

Tu pregunta tiene respuesta en dos niveles distintos. En primer lugar, la tarea de cada alumno es individual y única, es decir, no tienen que interactuar. En ese sentido, la única forma de que te conectes al servidor de un amigo es que utilices su cliente.

Por otra parte, la tarea debe funcionar por sockets, sin importar el computador en el que estés. Se plantea que debe funcionar en una red local, pues para poder conectarte por sockets a través de la internet, debes modificar los settings de tu router y eso complicaba de forma innecesaria la tarea.

Dicho esto, si tu me pasas tu cliente y echas a andar el servidor en tu computador, yo debiese ser capaz de conectarme a tu servidor desde mi computador. Esto siempre y cuando estemos en la misma red local (o que hayas hecho los cambios correspondientes a tu router, y de esa forma tu tarea incluso debiese funcionar a través de la internet).

Espero que esto aclare tu duda. Saludos!

**Comment by fgvenegas** [comment]
Ya perfect! entonces lo basico seria poder trabajar local con 2 computadores conectados a la misma red, gracias!

**Comment by jfcampos1** [comment]
Hola!
El servidor tiene que guardar la información de alguna manera? Esto pensando en que eventualmente puedo apagar el servidor y desconectarlo, por lo tanto tendría que guardar los usuarios también. O simplemente cuando uno apaga el servidor se pierde toda la información?

**Comment by mbucchi** [comment]
Hola @jfcampos1 ,
La información se debe mantener, sin importar lo que pase con el servidor. Deberás crear una forma de serializar todos los datos de la plataforma y guardarlos en el servidor.
Saludos!
