### ISSUE TITLE
¿Qué puedo hacer para no tener que cambiar el port despues de cada prueba?

### ISSUE THREAD

**Issue by ouhenio** [IIC2233-2015-2/syllabus#463]
^

**Comment by robocop6** [comment]
Estás cerrando la conexión con `socket.close()` ?

**Comment by ouhenio** [comment]
No :baby_chick: 
Gracias!

**Comment by dpassi** [comment]
Si a alguno le sirve, lo mismo que me dijo @robocop6 hoy en la ayudantía.
Hacer un try todo lo que va debajo de tu **main**:
y luego un finally: socket_cliente.close() y socket_server.close()

``` python
try:
    if __name__ == "__main__":
        # Todo tu codigo
finally:
    socket_client.close()
    socket_server.close()
```

**EDIT (@aaossa):** Supongo que a algo así te refieres

**Comment by andresespinosapc** [comment]
Lo que dijeron antes está bien como manera preventiva, pero una vez que ya dejaste abierto el socket puedes poner esta línea justo después de la instanciación del socket del servidor:
`self.s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)`
No sé qué es lo que hace, pero nunca más me dio el error de Address in use :)
