### ISSUE TITLE
¿Se puede iniciar un chat con un usuario que no esté *online* en ese momento?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#464]
De ser así, cómo funcionaría el envío de archivos en estos casos?

**Comment by crabarca** [comment]
Quizas dejar guardada esa informacion en el servidor, y hacer que un thread "detecte" cuando se conecte la persona con la cual se pretendia comunicar y entregarle el mensaje. Algo asi se me ocurre.. 
Saludos !

**Comment by mbucchi** [comment]
Hola! Esto queda a tu criterio. Ambas formas de manejarlo, ya sea prohibirlo o permitirlo, tienen sentido.
Saludos!
