### ISSUE TITLE
Issue centralizado para preguntar por módulos en la tarea.

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#465]
Quizás podría ser una buena idea tener una issue sticky donde se mantenga la lista actualizada de módulos/librerías que podemos utilizar para la tarea de forma tal de cumplir con la siguiente restricción:

> Si no se encuentra especificado en el enunciado, asuma que el uso de cualquier librería Python está
> prohibido. Pregunte por foro si se pueden usar librerías especificas.

Me imagino que podemos usar _socket_ y _pickle_

**Comment by mbucchi** [comment]
Buena idea!
A continuación dejo una lista de las que están permitidas y que se me ocurren en este momento. (Iré actualizando esta lista a medida que pregunten por más módulos que estén permitidos)

# Librerías permitidas
- _abc_
- _base64_
- _collections_
- _copy_
- _csv_
- _datetime_
- _functools_
- _hashlib_
- _io_
- _itertools_
- _os_
- _pickle_
- _PyQt4_
- _socket_
- _sys_
- _re_
- _threading_
- _time_
- _uuid_
- _zlib_

Por lo general, si su uso estaba permitido en otras tareas, en esta también. De todas formas no está de más que pregunten por módulos que se nos pueden estar escapando.

**Comment by robocop6** [comment]
- _collections_
  ?

**Comment by eduguerra-uc** [comment]
¿Se puede usar htmlpy? http://amol-mandhane.github.io/htmlPy/ 
(esto requiere además instalar PySide, que es de Qt).

**Comment by jgmontoya** [comment]
¿Podemos usar flask -y la materia de web services- para hacer la tarea?

**Comment by lopezjurip** [comment]
@jgmontoya nop, esta tarea está enfocada en networking. Al fin y al cabo webservices es un subset networking. Puedes crear tu propio protocolo y competir contra HTTP, pero debes implementarlo a mano usando sockets y streams.

**Comment by lopezjurip** [comment]
@eduguerra me imagino que trata sobre #469. Yo diría que sí (**esperemos la confirmación de los tareos**), pero considera que si te escapas mucho de lo que vemos en el curso los ayudantes no te podemos _ayudar_ y vas a tener que dejar todo bien documentado de cómo se usa, dejar declaradas las dependencias (librerías), cómo se instalan y asegurarte que funcionan en los tres sistemas operativos.

**Comment by jgmontoya** [comment]
[abc](https://docs.python.org/3/library/abc.html) ?

**Comment by lopezjurip** [comment]
@jgmontoya claro que pueden usar `abc`.

**Comment by jgmontoya** [comment]
¿ [uuid](https://docs.python.org/3.5/library/uuid.html) ? (Lo quiero para usar uuid4() para el salt de las contraseñas)

**Comment by mbucchi** [comment]
@jgmontoya sip

**Comment by eduguerra-uc** [comment]
Se puede usar la librería [csv](https://docs.python.org/3/library/csv.html)?

**Comment by lopezjurip** [comment]
@eduguerra  https://github.com/IIC2233-2015-2/syllabus/issues/465#issuecomment-157158738 claro que sí

**Comment by jnrosenbluth** [comment]
Hay un modulo de networking dentro de PyQt. Eso tambien se puede usar? (se que esta incluido en PyQt pero es por si hay obligacion de usar los sockets de socket.

**Comment by icrocco** [comment]
tkinter está permitida??

**Comment by Arios16** [comment]
binascii, pandas?

**Comment by PaulaSanzana** [comment]
se puede ocupar re (regular expresions)?

**Comment by lopezjurip** [comment]
@PaulaSanzana do re mi fa sol la si do :musical_score:  y todo eso, sí

**Comment by jfcampos1** [comment]
se pueden ocupar estos win32con, win32api? principalmente para poder ocultar archivos

**Comment by lopezjurip** [comment]
@jfcampos1 desconozco esa librería, pero por su nombre me imagino que son exclusivas para Windows. ¿Y qué pasa con los demás sistemas operativos?

**Comment by ManuelBeckerT** [comment]
se puede usar base64?

**Comment by lopezjurip** [comment]
@ManuelBeckerT sip

**Comment by lopezjurip** [comment]
@icrocco que hace?
@Agrios1636  binascii que hace? para qué pandas?

**Comment by lopezjurip** [comment]
# Por Favor poner el link a la librería y con una breve descripción de lo que hace, así podemos contestar más rápido.

**Comment by Arios16** [comment]
@mrpatiwi 
[binascii](https://docs.python.org/2/library/binascii.html) Son una serie de funciones para transformar data en bytes/binario (lo uso para el tema de hash+salt para las contraseñas)

Pandas pensaba usarlo para guardar la informacion de los usuarios, pero ya cambie de opinion asique da lo mismo.

**Comment by icrocco** [comment]
@mrpatiwi para lo que yo estaría usando tkinter (que es para GUI) sería para seleccionar directorios (ej: http://stackoverflow.com/questions/13018427/selecting-directorys-path-with-tkinter).

Aunque no he averiguado si se podrá hacer algo similar con QtGui.

**Comment by aaossa** [comment]
@icrocco Entonces no es necesario usar tkinter: [QFileDialog](http://pyqt.sourceforge.net/Docs/PyQt4/qfiledialog.html)

**Comment by crxzadytho22** [comment]
shutil? sirve para mover y copiar directorios.

**Comment by lopezjurip** [comment]
@crxzadytho22 yo diría que sí shutil.

**Comment by ouhenio** [comment]
pysmb? lo usaría para solucionar el problema que tengo aqui: https://github.com/IIC2233-2015-2/syllabus/issues/487 montando un filesystem en la red local
https://pythonhosted.org/pysmb/

**Comment by lopezjurip** [comment]
@eiherrera yo diría que nop

**Comment by sebawarrior** [comment]
se puede usar la librería select? es para poder trabajar con los socket conectados y que el servidor pueda esperar acciones de ellos

**Comment by sitoro** [comment]
Se puede utilizar la librería pyinotify para monitorear los directorios?

**Comment by jfcampos1** [comment]
Se puede ocupar la librería inspect? es básicamente para saber si es una variable es un objeto o no, por que no encontré que type sirva para lo mismo. Ocuparía inspect.isclass(Myobjeto)
https://docs.python.org/2/library/inspect.html

**Comment by lopezjurip** [comment]
@sebawarrior No creo que se pueda usar `select` porque los abstrae un poco de los problemas principales de la tarea. Esperemos que @bamavrakis o @mbucchi confirmen.

@sitoro yo diría que no por la misma razón que `select`.  Usa threads :wink: 

@jfcampos1 Yo diría que sí, pero ojo, si estás haciendo ese tipos de `if`'s puede que tengas un problema de modelación :warning:

**Comment by jgmontoya** [comment]
¿[zipfile](https://docs.python.org/3.5/library/zipfile.html)?

**Comment by sebamenabar** [comment]
[hurry](https://pypi.python.org/pypi/hurry.filesize/) ?? para que el tamaño de los archivos se vea bonito

**Comment by jgmontoya** [comment]
Asumí que [zipfile](https://docs.python.org/3.5/library/zipfile.html) estaba permitido al estar permitido [zlib](https://docs.python.org/3/library/zlib.html#module-zlib)

**Comment by santiagocruzb** [comment]
se puede usar webbrowser para generar una pagina web en vez de hacer un pyqt qwebview? @aaossa 
https://docs.python.org/3/library/webbrowser.html
