### ISSUE TITLE
Programa en inglés

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#466]
Importa si hago todo el programa de la Tarea 6 en inglés?

**Comment by mjjunemann** [comment]
No influye en nada , siempre y cuando se mantenga la coherencia ningún
problema por mi que lo hagas en inglés .

**Comment by lopezjurip** [comment]
Lo correcto siempre es programar en inglés, ahora si quieres poner en inglés los strings que se mostrarán al usuario, bueno :)
