### ISSUE TITLE
Compatibilidad de SO

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#467]
Es necesario que el programa sea compatible con cualquier sistema operativo o puedo especificar el que uso en el README?

**Comment by aaossa** [comment]
Hablas de la tarea? Se supone que **todo lo que hacemos aquí es multiplataforma**. Quizás si utilizas algo muy específico pueda haber problemas con el SO. Pero, si por ejemplo utilizas alguna librería o módulo que no sabes si funcionará en todos lados pregúntalo en #465 :grin:
