### ISSUE TITLE
Interfaz gráfica

### ISSUE THREAD

**Issue by eduguerra-uc** [IIC2233-2015-2/syllabus#469]
¿Puedo usar QtWebKit y hacer la interfaz gráfica del programa en HTML, CSS y JavaScript, desde pyqt? En principio estaría usando una librería permitida.

**Comment by mbucchi** [comment]
Totalmente permitido que uses HTML y CSS para desarrollar la interfaz con QtWebKit :smiley:. Sin embargo necesitamos que la lógica de tu tarea esté en Python. Saludos!

**Comment by eduguerra-uc** [comment]
Y usar JavaScript solo para refrescar la UI, animaciones etc, pero no para reemplazar Python en la lógica de la tarea? Que HTML y CSS sin JavaScript no es nada... 😁

**Comment by lopezjurip** [comment]
Claro que sí

**Comment by eduguerra-uc** [comment]
Gracias!
