### ISSUE TITLE
Orden lógico.

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#47]
Duda, ¿La acción de Añadir ramo, es una función del módulo que trabaja como menú (el que se dedica a ofrecer opciones y aceptar las respuestas) o debe ser un método de la clase Alumno?

DUDA EXTRA: ¿La estructura de los cursos, alumnos, etc que son indicados en el pdf de instrucciones deben poseer exactamente los atributos indicados?

**Comment by mbucchi** [comment]
La modelación del problema queda a tu criterio y es parte de la evaluación, por lo tanto esa es una decisión que deberás tomar tú.
En cuanto a tu segunda duda, esa estructura se te entrega para que conozcas cómo funciona cada uno de esos objetos. Muchos de esos son atributos importantes y debiesen estar para crear un buen modelo. Eso no implica que no se puedan omitir algunos (si es que te parece razonable en el contexto del problema y lo puedes justificar bien) o incluso agregar otros.
Saludos!
