### ISSUE TITLE
Recorrección controles

### ISSUE THREAD

**Issue by icrocco** [IIC2233-2015-2/syllabus#470]
En el syllabus sólo se encuentran las pautas hasta el control 5.

¿Cómo hacemos para revisar los otros?

**Comment by lopezjurip** [comment]
Toda la razón, intentaremos solucionarlo lo antes posible

**Comment by lopezjurip** [comment]
Se subió otra pauta más de los controles: 1a59465fa40d3fb40f8dd05b09247de2e3e1436e
Disculpen los atrasos

**Comment by aaossa** [comment]
Hola, al parecer ya están todos los controles disponibles. Cualquier duda sobre algún control o de materia no duden en preguntarla en una nueva issue!!

Saludos,
