### ISSUE TITLE
listen Servidor DrobPox

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#475]
¿En la tarea se supone que el Servidor puede recibir ilimitadas conexiones? ¿O debemos definir un máximo? Es decir, ¿tomamos un `N` fijo para `socket_servidor.listen(N)`?

**Comment by rodolfopalma** [comment]
El parámetro que recibe el método `listen` de un objeto `socket` no es el número máximo de conexiones simultáneas que aguanta el socket, sino que el número máximo de conexiones que puede tener esperando ser aceptadas. La documentación de Python recomienda dejarlo seteado en 5. Si tu servidor está modelado correctamente (acepta las conexiones sin hacerlas esperar un tiempo exagerado) no deberías tener problemas.

**Comment by javierlopeza** [comment]
Perfecto gracias!
