### ISSUE TITLE
Unmerged files / Not currently on a branch

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#476]
Hola!
Para la AC25 tuve que subir el archivo manualmente a mi repositorio porque tenía un problema.
Ahora que estoy tratando de subir archivos, me salieron una serie de problemas derivando en este:

`A  Actividades/AC25/main.pdf`
`U  Actividades/AC25/main.py`
`Pull is not possible because you have unmerged files.`
`Please, fix them up in the work tree, and then use 'git add/rm <file>'`
`as appropriate to mark resolution and make a commit.`

luego borré los que intenté subir al principio para solo subir el de la actividad y nada....

por ultimó intenté push lo archivos que tenia y me mostró este error

`git push origin HEAD:<name-of-remote-branch>`

@robocop6 @mrpatiwi 
![original_41554986](https://cloud.githubusercontent.com/assets/13748925/11190059/723f4d0c-8c72-11e5-8bb8-ffa72b27a04f.png)

**Comment by lopezjurip** [comment]
Hace `git status` y muéstranos que te aparece.

**Comment by santiagocruzb** [comment]
`rebase in progress; onto afaab37`
`You are currently rebasing branch 'master' on 'afaab37'.`
`(all conflicts fixed: run "git rebase --continue")`
`nothing to commit, working directory clean`

**Comment by lopezjurip** [comment]
Clona de nuevo el repo en otra carpeta :cry:
