### ISSUE TITLE
flask

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#477]
No pude instalarlo, no vamos a usarlo en la actividad cierto?

**Comment by lopezjurip** [comment]
Nop. En el curso nos enfocamos más en el lado del cliente. Eso sí, lleven [`request`](https://github.com/kennethreitz/requests) instalado.

Aprovecho de promocionar IIC2513 - Tecnologías y Aplicaciones Web (https://github.com/IIC2513-2015-2) donde también soy ayudante y ahí si vemos todo lo que es servidor :heart:

**Comment by tamycova** [comment]
Gracias!
