### ISSUE TITLE
Importando Modulos

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#48]
Hola. A propósito de la indicacion de "modularizar" el programa:

¿Está bien si desde un archivo main importo un modulo, el cual a su vez importa un segundo modulo?
O debo importar ambos modulos directamente desde el archivo main?

**Comment by lopezjurip** [comment]
Claro que está bien, considera que cuando importas una librería como `numpy` esta internamente importa muchas cosas, pero tu solo usas la cara más externa de esta.

De todas formas en la ayudantía de mañana vamos a ver un ejemplo de un código modularizado.

**Comment by raiperez** [comment]
Perfecto. Gracias!
