### ISSUE TITLE
Emojis - UnicodeEncodeError PyCharm

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#480]
Tengo un problema al tratar de mostrar los emojis en el chat. Por ejemplo, para este emoji ☺️, al intentar imprimirlo en PyCharm me tira el siguiente error:

```
print('☺️')
```

```
...
print('\u263a\ufe0f')
File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
```

Pero al imprimirlo directamente en la IDE de Python funciona sin problemas y lo imprime bien.
En cuanto a la interfaz del programa, pasa que ☺️ en mi interfaz se reemplaza por un `?`.
Busqué y no encontré respuesta al problema... No sé si es por PyCharm o qué ¿alguna recomendación? Gracias.

EDIT: aparte no quería hacer nada raro en PyCharm por que a los ayudantes correctores no les podría funcionar.

**Comment by lopezjurip** [comment]
Es un problema de encoding, los emojis están en Unicode, no te puedo garantizar que funcionen.
También es poco probable que funcionen en otros sistemas operativos (me imagino que estás en OSX).

**Comment by javierlopeza** [comment]
:worried: 
Estoy en Windows pero, ¿que otra opción hay? ¿o busco otra forma de hacerlo nomas?

**Comment by javierlopeza** [comment]
Ahí me funcionó :sweat_smile:, parece que faltaba `# -*- coding: utf-8 -*-`.
