### ISSUE TITLE
Enviar datos a traves del .connect()

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#481]
Hola!
Es estandar que al conectar el cliente al servidor se haga de la manera `socketdelcliente.connect((host,port))`,  en donde el servidor por su parte procesa luego los datos en el **`self.escuchar(self)`** de manera `cliente_nuevo, address = socketdelserver.accept()`. He intentado de distintas maneras y no he logrado enviar algun tipo de dato extra durante el connect() (quiero manda un string). Como se puede hacer esto?
Saludos, gracias

**Comment by lopezjurip** [comment]
Revisastes los ejemplos? Ayudantias, materia?
