### ISSUE TITLE
ultima actividad

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#482]
La primera vez que salió matplotlib, tuve muchos errores hasta que el antonio me ayudó a que python lo cargara, pero ahora al probar todos los ejemplos para la actividad, python no tira ningun error y dice que correrlo fue exitoso pero no muestra nada, osea no se abre ninguna ventanita de nada. Que hago?

**Comment by lopezjurip** [comment]
@aaossa, tu sabes de esto.

**Comment by aaossa** [comment]
Hablas de la función `plot`, `show`, ambas o otra?

**Comment by oatorresuc** [comment]
De esas ambas dos jaja

**Comment by aaossa** [comment]
Prueba con esto

``` python
import matplotlib
matplotlib.use('Qt4Agg')

import matplotlib.pyplot as plt
import numpy as np


x = np.arange(0, 5, 0.1);
y = np.sin(x)
plt.plot(x, y)
plt.show()
```

Si no te funciona (es decir, si no se despliega ninguna ventana) usa `Agg` o `TkAgg` en lugar de `Qt4Agg`. Mañana si quieres te explico un poco de esto, pero creo que ya lo hice en una issue anterior. Estaré atento a si te funciona :grin:

**EDIT:** Ver #305

**Comment by oatorresuc** [comment]
Gracias antonio al cambiarle de Agg a Qt4Agg funciono.
Saludos!
