### ISSUE TITLE
5.5. Descargar Carpeta

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#483]
Si yo subo una carpeta a mi DrobPox, la cual se encontraba en el Escritorio, entonces mi DrobPox ahora observará esa carpeta que está en el Escritorio para estar atento a cualquier cambio que se le haga, ¿cierto?. Pero ahora, si yo desde el mismo computador descargo esa carpeta completa a Mis Documentos, por ejemplo, ¿ahora DrobPox observará solo en Mis Documentos, o debe estar observando en ambos lugares por si en cualquiera de las partes se realizan cambios? ¿En general las carpetas pueden tener varias lugares de observación o  es unico y se va modificando, por ejemplo al descargarla?

**Comment by jfcampos1** [comment]
En dropbox(el de verdad) uno tiene una carpeta dropbox en el computador en la cual yo agrego, modifico o elimino los archivos y esa es la que la aplicación revisa cada vez que me conecto, ¿la idea es hacer lo mismo o 'observar' donde sea que este en el computador el archivo?

**Comment by crabarca** [comment]
Comento para saber ...

**Comment by chrisams** [comment]
Otra pregunta relacionada, ¿El usuario debe poder descargar también la carpeta "raíz" de sus archivos online? O sea, ¿ puede descargar una carpeta que contenga todos los archivos y carpetas que ha subido? o solo puede descargar subcarpetas y archivos de su carpeta raíz?

De ser así, supongamos que un usuario A comparte una carpeta con un usuario B, si el usuario A llegase a descargar esta carpeta "raíz", podría eliminar tal carpeta compartida. Si esto sucede, el usuario B debería poder seguir viendo y editando esa carpeta "compartida"? o ya no tendría acceso a esta?

**Comment by mbucchi** [comment]
@javierlopeza, DrobPox debiese observar ambas carpetas.

@jfcampos1, la idea es tener _carpetas_ observables. Podría ser una, o podrían ser muchas. Cada una de estas se comportará como la carpeta de Dropbox que tu nombras.

@ChrisAMS No es necesario que hagas eso, ya que vas a tener problemas de consistencia. Si deseas hacerlo genial, pero no es requisito de la tarea.

Espero que esto aclare las dudas, saludos!
