### ISSUE TITLE
QPixmap: It is not safe to use pixmaps outside the GUI thread

### ISSUE THREAD

**Issue by dpassi** [IIC2233-2015-2/syllabus#484]
Busqué harto y no encontré alguna solución..

Me pasa este problema al pasar del widget "crear usuario" al volver al widget "iniciar sesion"...

Intenté todas las combinanciones de codigo obviamente entendiendo lo que el problema me trata de decir, y nada jaja...

Cualquier ayuda sirve!

**Comment by yackpott** [comment]
no soy ayudante ni nada pero en la tarea anterior lo solucione con trigger (ayudantia 8), ya que con eso podi mandarle señales a thread de la ventana y este se va a encargar de hacer lo que tenga q hacer.

**Comment by dpassi** [comment]
Gracias. Lo tengo con triggers y señales pero tampoco funciona :(

**Comment by lopezjurip** [comment]
Suele pasar que los elementos visuales están en otro thread. 
Revisa esta issue del semestre pasado: https://github.com/IIC2233-2015-1/syllabus/issues/233

**Comment by crxzadytho22** [comment]
hola encontraste la solución? tengo casi el mismo problema D:
