### ISSUE TITLE
Conexiones a través de multiples sockets

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#485]
¿Sería correcto establecer la comunicación cliente-servidor a través de sockets independientes, uno para el chat y otro para el manejo de archivos (usando, obviamente, puertos distintos)? ¿Hay alguna razón por la cuál hacer esto sería no-deseable (aparte de el hecho de estar usando 2 puertos por cliente)?

**Comment by crabarca** [comment]
Estaba considerando hacer lo mismo... me sumo a la pregunta de @jgmontoya

**Comment by lopezjurip** [comment]
Dale nomás, considera que muchas apps se toman unos rangos de puertos para funcionar.

**Comment by jgmontoya** [comment]
Oka, gracias!

**Comment by santiagocruzb** [comment]
Hola!
Para hacer otro socket desde el servidor, al momento de hacer por **segunda** vez 
`cliente_nuevo, address = self.Socket2.accept()` me muestra el error

```
fd, addr = self._accept()
OSError: [Errno 22] Invalid argument
```

creo que address no es como muy variable al momento de crear la conexión. Como lo hicieron entonces?

**Comment by lopezjurip** [comment]
Llamaste a `listen()` antes?

También revisa esto: http://stackoverflow.com/a/14862764

EDIT: `self._accept()`? está bien eso? `self` tiene ese método?

**Comment by santiagocruzb** [comment]
```
class Servidor:
    def __init__(self):
        self.host = '127.0.0.1'
        self.port = 2457
        self.SocketServidor = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.SocketServidor.bind((self.host,self.port))
        self.SocketServidor.listen(100)
        self.ComenzarThread = threading.Thread(target=self.Aceptar)
        self.ComenzarThread.start()

        self.SocketServidorMensajes = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.SocketServidorMensajes.bind((self.host,self.port+1000))
        self.SocketServidorMensajes.listen(100)
        self.ComenzarThreadMensaje = threading.Thread(target=self.AceptarMensajes)
        self.ComenzarThreadMensaje.start()
        #mas para abajo

    def AceptarMensajes(self):
        while True:
            cliente_nuevo, address = self.SocketServidorMensajes.accept()
            #mas para abajo
    def Aceptar(self):
        while True:
            cliente_nuevo, address = self.SocketServidor.accept()
            #mas para abajo
```

Era para no mandar el código entero antes.
Si saco el método AceptarMensajes, me logra conectar 1 único socket. Pero cuando meto otro es cuando se cae. Con respecto al error, eso es lo me muestra la consola como error

**Comment by otro-felipe** [comment]
Encontre [esto](http://stackoverflow.com/questions/14862742/invalid-argument-exception-in-socket-accept-if-i-restart-immediately-after-a-p). Tal vez eso te ayude. Lo otro podria ser que tienes el listen en 100. Lo recomendado es 5, tal vez eso pueda estar causando un problema o algo asi.

No soy nadie para decirte esto, pero me duele en el corazon que tengas los atributos de la clase con mayusculas. Te recomiendo echarle un ojo a [pep8](https://www.python.org/dev/peps/pep-0008).
