### ISSUE TITLE
Uso de protocolos de ftp

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2015-2/syllabus#486]
Para el manejo de los archivos de gran tamaño es posible usar algun otro ftp que controlemos desde python, o debemos apegarnos al socket de python?

**Comment by lopezjurip** [comment]
La idea es que usen sockets planos, tanto `ftp` como `http` son implementaciones de más alto nivel sobre sockets. Puedes inventar tu propio protocolo :ok_hand:
