### ISSUE TITLE
open archivos con espacios

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#488]
me tira el siguiente error: 

```
File "servidor.py", line 213, in subir
    with open(archivo, "wb") as nueva:
IsADirectoryError: [Errno 21] Is a directory: 'rfblanco/Antropologia/resumen laudato si.txt'
```

esto sucede al tratar de crear un nuevo archivo que recien habia subido para guardarlo, como lo puedo arreglar?

**Comment by lopezjurip** [comment]
Puede ser por los espacios ` ` en el nombre del archivo.

**Comment by otro-felipe** [comment]
si es un archivo nuevo puede ser que tengas que abrirlo en modo "wb+" (?

**Comment by yackpott** [comment]
si se q falla por los espacios pero no se como arreglarlo, no funciona con wb+

**Comment by yackpott** [comment]
al final si funciono con wb+, nose porque

**Comment by otro-felipe** [comment]
"w" es para abrir archivos ya existentes, si quieres que python cree un archivo nuevo que no existe debes agregarale el + (cuando tiene el + si no esta el archivo que quieres escribir, python creara uno vacio en el path que le das). Que bueno que haya funcionado.

**Comment by lopezjurip** [comment]
Culpemos a Python por arrojar un error tan ambiguo
