### ISSUE TITLE
Problema al enviar archivos mas grandes

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#490]
Al mandar archivos de menos de 1MB, mi programa no tiene problemas. Pero al tratar de enviar otros mas grandes, se cae al hacer pickle.loads() a lo que recibio.

Lo que tengo actualmente es que mi programa hace pickle al objeto mas un header con info sobre el tamaño, y eso lo manda. Por el otro lado, se recibe el header, y con la informacion del tamaño se va recibiendo de a trozos y juntando el archivo. Luego, a todo eso se le hace pickle.loads.

Lo de mandar y recibir lo hace bien. Al poner un try except en la seccion de decodificar con pickle me tiro que al momento de hacer loads se disparaba un error : run out of input.

**Comment by ghost** [comment]
Ahora puse en el except que escriba en un txt lo que no esta logrando sacar con pickle, y efectivamente el tamaño del archivo queda perfecto (y el contenido, al menos la parte legible, tambien). O sea, el problema esta en cuando pickle tiene que deserializar.

**Comment by crabarca** [comment]
como lo solucionaste ? estas mandando el archivo serializado completo o por partes?

**Comment by ghost** [comment]
La verdad no lo he arreglado aun, que me puse a avanzar en otras cosas. Pero esa era la unica solucion que se me ocurria, enviarlo en partes (lo que si, igual me parece arbitrario. Me gustaria saber en primer lugar porque al serializar archivos mas grandes pickle se falla- Ademas tendria que definir un tamaño para particionar los archivos, que tambien seria muy al ojo).

**Comment by crxzadytho22** [comment]
lo que tienes que hacer es recibirlo por partes, tienes que mandar un mensaje de por ejemplo 4 bytes donde te diga el largo del mensaje siguiente y recibirlo por partes Dx

**Comment by ghost** [comment]
Se arreglo al final. Era un tema de que estaba mandando el tamaño del objeto y el objeto pickleado de una por el socket, y despues los desempaquetaba en orden (pero a veces eso hacia que se corrompiera el serializado). Ahora los estoy mandando por separado nomas.

**Comment by crabarca** [comment]
Tenia el mismo problema y lo solucione al enviar todo por separado
