### ISSUE TITLE
T6 borra 1? o se incluye a las otras 5

### ISSUE THREAD

**Issue by trencoret** [IIC2233-2015-2/syllabus#491]
No queda muy claro en el programa sobre la tarea extra, esta tarea borra una tarea? O se agrega a las otras 5 y pasan a ser 6 en total?

Muchas gracias

**Comment by bamavrakis** [comment]
Hola!
La T7 es la recuperativa, y esa es la que borra la peor nota.
Saludos!

**Comment by trencoret** [comment]
@bamavrakis gracias!
