### ISSUE TITLE
Feedbacks T04

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#495]
Estoy subiendo los feedbacks de la T04, para que después de 30 minutos o una hora de publicar este mensaje hagan `git pull` a sus repos.

**Comment by paxcema** [comment]
Mi feedback está vacío :(

**Comment by lopezjurip** [comment]
Haremos caer las penas del infierno sobre el encargado :innocent: 
Me lo conseguiré y te lo dejo como una Issue en tu repositorio :ok_hand:

**Comment by btkramm** [comment]
Mi feedback se ve como la mierda, ni siquiera entiendo qué es lo que me están diciendo :)

**Comment by lopezjurip** [comment]
@btkramm ya veo, hubo un problema de _merge_ y de _encoding_.
Te subiré una versión distinta a tus Issues

**Comment by dpassi** [comment]
Aprovecho el post, Cuando suben las notas de las 6 AC's restantes? Gracias!

**Comment by lopezjurip** [comment]
@djpassi apenas las tengamos de los correctores :)

**Comment by santiagocruzb** [comment]
Cuestionario para la recorreccion de la tarea 4?

**Comment by lopezjurip** [comment]
@santiagocruzb -> @bcsaldias

**Comment by santiagocruzb** [comment]
Esperando respuesta a mis mails
![3fe06ce4_skeleton-at-keyboard](https://cloud.githubusercontent.com/assets/13748925/11412113/463ff3ea-93b7-11e5-9158-526479398bad.jpeg)
