### ISSUE TITLE
Agregar restricciones a la clave sin guardarla en ningún momento (Tarea 6)

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#498]
Tengo una duda sobre el cómo crear la clave para la tarea 6. El enunciado dice claramente que no debo almacenar la clave en una variable. sin embargo, deseo imponer restricciones sobre ella, como por ejemplo, que solo tenga letras y números, o que tenga un largo mínimo y uno máximo. Además, me gustaría que al crear la clave el usuario la escriba dos veces (como normalmente se hace para crear una nueva clave). ¿Cómo puedo hacer esto sin guardarla? Estaba pensando en crear una función que ocupe una variable con la contraseña, que le ponga restricciones y que luego, al finalizar la función, nunca se guarde esa variable (por lo que se limpiará de la memoria), pero no se qué tan seguro es esto. 
De antemano gracias y éxito en el fin de semestre.

**Comment by robocop6** [comment]
Puedes tener una ventana en que se pidan tres inputs de texto: uno para usuario y dos para contraseña. Luego, compruebas si ambas son iguales (y mayores a cierta cantidad de caracteres, que tengan números o algo así como requerimiento de seguridad), y si es así, la hasheas!

Algo así (puedes omitir la parte de "indicio de contraseña"):
![Image](http://www.nisfe.com/wp-content/uploads/2012/09/Crear-una-nueva-cuenta-de-usuario-Windows-8-6.png)

**Comment by fagomez2** [comment]
Gracias por la respuesta, pero al momento de comparar, voy a tener que haber guardado las dos contraseñas para hacerlo (algo así como: if clave_1 == clave_2: hace algo) y luego para comprobar los requisitos de seguridad. No hay problema con eso? Sorry si es reiterativo pero es para asegurarme de que no contradigo el enunciado ("bajo ningún motivo guardará la contraseña del usuario")

**Comment by mbucchi** [comment]
Hola @fagomez2!

Cuando hablamos de "no guardar la contraseña" estamos hablando de nunca guardarla en disco. Que la tengas por un rato en la memoria del programa da igual. Es más, es imposible que no la guardes en memoria por un par de segundos. 

Saludos!

**Comment by fagomez2** [comment]
Gracias @mbucchi y @robocop6 Por responder. Todo claro ahora =)
