### ISSUE TITLE
problema al seguir la guía

### ISSUE THREAD

**Issue by jpdattas** [IIC2233-2015-2/syllabus#5]
En la parte de instalar pip me sale otro error:

![image](https://cloud.githubusercontent.com/assets/13739046/9233028/308d8326-4107-11e5-97e1-25526fb7372c.png)

**Comment by lopezjurip** [comment]
Ese error es típico, prueba que al menos tengas el comando `pip` (puede que tengas que reiniciar la consola). El `easy_install` no es necesario para el resto de la guía.

**Comment by jpdattas** [comment]
la reinicie y sale que se instalo 1/2 y que fallo easy_install. esta bien asi?

**Comment by lopezjurip** [comment]
Sí, a mi me pasaba lo mismo y pude seguir instalando todo sin problemas :+1:

**Comment by jpdattas** [comment]
ok, gracias!

**Comment by clagos4** [comment]
A mi me resulto siguiendo las instrucciones en
https://pip.pypa.io/en/latest/installing.html

**Comment by bcsaldias** [comment]
Estimados, 

De cualquier manera todas las dudas se resolverán el lunes en la ayduantía.

Mañana la AC será entregada por el Siding así que solo deben tener instalado Python3.4 para entonces.

Saludos !
