### ISSUE TITLE
Problema al abrir "cursos.txt"

### ISSUE THREAD

**Issue by djnoguera** [IIC2233-2015-2/syllabus#50]
No se que hice pero ahora no puedo abrir "cursos.txt".
Al abrirlo con GitHub Desktop me aparece lo siguiente:

![captura de pantalla 2015-08-24 a las 12 17 24](https://cloud.githubusercontent.com/assets/13739955/9444294/2312fae2-4a5c-11e5-9dd9-2cd8361c962e.png)

¿Como lo arreglo?

**Comment by lopezjurip** [comment]
Están advertidos que si usan la app de Github no les podemos ayudar
http://lmgtfy.com/?q=cannot+rebase+you+have+unstaged+changes

UPDATE:
Tienes que restaurar los cambios del `syllabus` en tu computador. O borrarlo y clonarlo de nuevo.

**Comment by jtagle2** [comment]
![error cursos](https://cloud.githubusercontent.com/assets/6934080/9474729/b98d1db8-4b38-11e5-96ac-0c66f6ea5208.png)
A mi tampoco me funciona abrirlo. Tengo una misma función para ir leyendo los archivos y pasarlos a diccionarios, y me funciona con los archivos requisitos.txt, evaluaciones.txt y personas.txt, pero cuando lo hago con el de cursos.txt se me cae y me tira ese error

**Comment by eavildosola** [comment]
@jtagle2 asegurate de que estes leyendo en UTF-8.
