### ISSUE TITLE
Historial 

### ISSUE THREAD

**Issue by jatrincado** [IIC2233-2015-2/syllabus#500]
El historial es solo de modificaciones que hace el cliente cuando está corriendo el programa? Porque como yo lo entiendo, cuando abro el servidor debo actualizar las carpetas. Aquellas modificaciones que se hicieron en el computador del cliente sin estar corriendo el programa no deberían ser consideradas en el historial, o sí?

**Comment by mbucchi** [comment]
Existen algunas modificaciones que si puedes controlar aunque no estés corriendo el programa. Lo _ideal_ es que esas se manejen aunque el programa no esté corriendo. No obstante, se va a evaluar que tu programa sea capaz de manejar los cambios vitales cuando esté corriendo. Saludos!

**Comment by jatrincado** [comment]
Ok. Gracias!
