### ISSUE TITLE
Almacenamiento de archivos 

### ISSUE THREAD

**Issue by silvamatias** [IIC2233-2015-2/syllabus#501]
Para almacenar los datos de los clientes (archivos subidos, usuario, etc) se pueden utilizar bases de datos? (MySQL o SQLite) o simplemente usamos CSV? 

Gracias!

**Comment by lopezjurip** [comment]
Si sabes bases de datos, yo diría que sí. En tal caso usa SQLite, demás que hay alguna librería que te facilite un poco la cuestión. CSV también está bien.

**Comment by mbucchi** [comment]
@silvamatias Si bien puedes hacerlo, tendrías que asegurarte que el ayudante será capaz de corregir tu tarea sin tener que implementar nada externo. En mi opinión, solo te complicará la vida para efectos de esta tarea. En todo caso estos contenidos se escapan del foco del curso.

Saludos!
