### ISSUE TITLE
Feedback y notas T3

### ISSUE THREAD

**Issue by jlires** [IIC2233-2015-2/syllabus#503]
¿Ya están las notas de la re corrección puestas, junto al feedback? Yo me junte hace más de una semana con el corrector porque no le corría en su computador la tarea, la corrigió desde el mio y quedó todo en que pondría la nota. Ahora no se si es que las nota ya se las enviaron y no están actualizadas o aún no reciben nada. Ese 1 me destruye :(
@mrpatiwi

**Comment by lopezjurip** [comment]
Consultaré con el ayudante con quien te juntaste.
ASAP

**Comment by jlires** [comment]
Gracias :)

**Comment by eiurrutia** [comment]
@jlires tu recorrección ya está hecha. Sin embargo se actualizará tu nota y feedback en conjunto con el resto de las recorrecciones de la tarea 3. Esto debería ser dentro de los próximos días. Saludos

**Comment by jlires** [comment]
Vale, gracias.
