### ISSUE TITLE
pyqt emoji

### ISSUE THREAD

**Issue by yackpott** [IIC2233-2015-2/syllabus#504]
python no me quiere motrar los emoji en pyqt pero si me los muestra en el terminal (mac), he buscado en google pero no hay mayor info, a alguien le ha pasado? como lo arreglaron?

**Comment by ouhenio** [comment]
Hola! En Display Widgets esta Text Browser. Este permite que le ingreses texto en formato html y por lo tanto emojis. Yo no sé usar html pero con una googliada rapida se aprende :smile:

**Comment by yackpott** [comment]
gracias

**Comment by yackpott** [comment]
tampoco me funciono ni siquiera poniendo en el head lo de la codificacion, si abro el mismo html desde chrome me funciona pero desde pyqt no.
en que SO estay, en mac por lo menos a mi no me funciona

**Comment by ouhenio** [comment]
Tienes que especificar el tipo de formato quieres que tenga el texto ingresado. Si lo ingresas con setText(string) sera un string normal, si poni setHtml(string) se interpretará como html.

**Comment by yackpott** [comment]
no me funciona, lo tengo asi

```
    ht ="""
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<body><p>hola &#128512;</p></body>
</head>
    """
    browser.setHtml(ht)
```

esto solo me muestra el hola y no el emoji, si abro lo mismo en chrome si lo muestra

**Comment by lopezjurip** [comment]
Ese `html`debería ser así:

``` html
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
  <p>hola &#128512;</p>
</body>
```

Tenías puesto el `<body/>` en el `<head/>`. En el head va solo la metadata.

**Comment by lopezjurip** [comment]
Lo más correcto sería algo así, pero desconozco cómo funcionan esos widgets:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <p>hola &#128512;</p>
  </body>
</html>

```

**Comment by yackpott** [comment]
aun no me funciona, estoy pensando seriamente que es problema de pyqt de mac, alguien que me pueda confirmar que no es asi porfa? (igual como que ya me rendi y ya subi la tarea sin emoji nomas jajajaja)

**Comment by otro-felipe** [comment]
yo le puse el formato html directo al qtlabel y funciona perfect jaja
