### ISSUE TITLE
QWidget::setLayout: Attempting to set QLayout "" on Window "", which already has a layout

### ISSUE THREAD

**Issue by jfcampos1** [IIC2233-2015-2/syllabus#506]
Hola trate de ocupar triggers y no logro arreglar el problema, este pasa cuando quiero mostrar algún cambio en mi CentralWidget en Mainwindow y llamo a esta función, alguna idea de como solucionarlo?:

```
    def actualizar_layout(self):
        self.treeView.setContextMenuPolicy(Qt.CustomContextMenu)
        self.treeView.customContextMenuRequested.connect(self.openMenu)
        self.model = QStandardItemModel()
        self.additems(self.model, self.cliente.hijos)
        self.treeView.setModel(self.model)
        self.model.setHorizontalHeaderLabels([self.tr("Dropbox")])
        layout = QVBoxLayout()
        layout.addWidget(self.treeView)
        self.setLayout(layout)
```

**Comment by otro-felipe** [comment]
Por el poco conocimiento que tengo del ingles creo que estas intentando ponerle una layout a una ventana que ya tiene una layout definida. 
Podrias guardar la layout en una variable, vaciarla y volverla a llenar a la hora de actualizar la interfaz.

**Comment by jfcampos1** [comment]
gracias! ya lo arregle.
