### ISSUE TITLE
Feedbacks AC24..27

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#507]
Les subí los feedbacks, para que recuerden hacerle `pull`. @jecastro1 abrió un cuestionario en el Siding para que vean el tema de las recorrecciones.

Veo que les fue muy bien en la [AC27](https://github.com/IIC2233-2015-2/syllabus/tree/master/Actividades/AC27/Release), lo que me hace muy feliz :smile: 
En mi opinión es la materia más bacán y útil, porque ahora todo desarrollo de software es web :globe_with_meridians:.

Ojalá que se motiven por esa área :heart: 

Cualquier problema con los feedbacks me lo avisan por aquí.

**Comment by crxzadytho22** [comment]
hola me falta el feeedback de la act25, no subieron ese o solo me falta ami? saludos !

**Comment by oatorresuc** [comment]
me falta el feedback de la activad 27, y me aparece un 1,0 :(

2015-11-27 16:28 GMT-03:00 crxzadytho22 notifications@github.com:

**Comment by oatorresuc** [comment]
acabo de revisar y parece que el commit nunca se realizo, damn!

**Comment by jfcampos1** [comment]
El Feedback de la actividad 24 me aparece en blanco

**Comment by jecastro1** [comment]
Mi consejo para los que no tienen feedback y recibieron 1.0 sin saber por qué es que recorrijan en el plazo establecido.

**Comment by oatorresuc** [comment]
Si creo qur no funciono cuando hice el.push me gane el.1,0 por gil vd?

**Comment by crxzadytho22** [comment]
perdon la tarea la habia subido mi compañero asi que por eso no tengo feedback,  perdon :P

**Comment by tomvillage** [comment]
existe alguna posibilidad de ver el feedeback si tu pareja subio la actividad??

**Comment by lopezjurip** [comment]
@tomvillage pucha no está implementado :(
Quizás el próximo semestre.

Si quieres me mandas un correo con:
- Username del compañero
- Número AC

Y te puedo responder con el feedback.
