### ISSUE TITLE
[T07] Subida y descarga de archivos

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#508]
Solo para confirmar, al subir archivos solo deberia ser capaz de subirlos en una carpeta que yo escoja y no sueltos? y cuando descargo un archivo .rar siguiendo las instrucciones de la API me descarga un archivo de 0kb y que ademas esta corrupto :c tengo que idear un metodo de descarga  o asumo que no descargara cosas asi el que lo pruebe?

**Comment by lopezjurip** [comment]
Sobre lo último, dudo que sea Dropbox el que tiene errores jaja

Sobre lo que se espera de la tarea en sí, esperemos que @bamavrakis o @mbucchi contesten.

**Comment by fgvenegas** [comment]
Es que yo estaba usando esto (sale en la pagina de Dropbox asique supongo que no es ilegal ponerlo)

`f, metadata = client.get_file_and_metadata('/magnum-opus.txt')`
`out = open('magnum-opus.txt', 'wb')`
`out.write(f.read())`
`out.close()`
`print metadata`

Lo probe con un  .pdf y un .txt y funciono perfecto, pero cuando seleccione un .rar no lo descargo bien, en volá estoy pasando por alto algo, pero segui el mismo procedimiento para los 3

**Comment by fgvenegas** [comment]
Existe la posibilidad de hacer tantas request que no me deje seguir probando mi tarea? :v 
![image](https://cloud.githubusercontent.com/assets/13748708/11454630/49052034-962b-11e5-919c-4184487b369f.png)

![image](https://cloud.githubusercontent.com/assets/13748708/11454629/41b9ca96-962b-11e5-8ad0-e888ab7b2afc.png)

**Comment by fgvenegas** [comment]
Hare todas mis preguntas por si algun tareo ve esta issue algun dia:

-Es necesario mostral todo el historial o solo cuando se modifico por ultima vez?(la API solo entrega lo ultimo)
-Como es posible ver el historial de una carpeta? (La v2 de la Api solo permite tener la metadata completa de los archivos)
-Para modificar el nombre, no existe un metodo directo con la API, es necesario un proceso como: descargar el archivo, cambiarle el nombre, borrar el anterior, subir el nuevo? (Lo cual seria horriblemente tedioso para carpetas con muchos archivos)

Gracias

**Comment by mbucchi** [comment]
Hola! 
1. La API sí permite obtener el historial de modificaciones.
2. Puedes ver el historial de cada uno de los archivos pertenecientes a esa carpeta
3. Puedes hacer un "move" que lo único que hace es cambiar el nombre del archivo :wink: (es como hacer trampa al sistema!)

Espero que esto aclare tus dudas, saludos!

**Comment by fgvenegas** [comment]
Vale ! Y respecto a subir archivos, es en la carpeta que hago click (dentro de ella) o en el directorio de la carpeta (ósea el archivo queda junto con la carpeta y no dentro) eso último, gracias

**Comment by silvamatias** [comment]
@mbucchi se puede utilizar el SDK de dropbox para python?

**Comment by fgvenegas** [comment]
segun yo es como obvio que si, sino como trabajarias con la API? @silvamatias

**Comment by andresespinosapc** [comment]
Se puede hacer con puros request, pero si existe el SDK lo lógico sería
usarlo, además que el link que sale en el enunciado te lleva casi
directamente al uso del SDK, por eso yo creo que sí se puede.

El 30 de noviembre de 2015, 0:47, Freddie Venegas Apablaza <
notifications@github.com> escribió:

> segun yo es como obvio que si, sino como trabajarias con la API?
> @silvamatias https://github.com/silvamatias
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IIC2233-2015-2/syllabus/issues/508#issuecomment-160508992
> .

## 

Andrés Espinosa
Estudiante Ingeniería UC

**Comment by aaossa** [comment]
Sí, pueden usarlo :grin:
