### ISSUE TITLE
Con respecto a QTreeWidget

### ISSUE THREAD

**Issue by ManuelBeckerT** [IIC2233-2015-2/syllabus#509]
Para poder añadir items al Tree se usa self.treeWidget.addTopLevelItem(item)
Existe un equivalente para eliminar el item? Lo ideal sería poder eliminarlo todo inmediatamente y según lo que encontré, QTreeWidget tiene clear(), pero no lo he podido implementar correctamente... alguna ayuda/sugerencia? Gracias

**Comment by aaossa** [comment]
¿Qué significa _no lo he podido implementar correctamente_? Recuerda que la forma correcta de trabajar con widgets en PyQt es haciendo que el thread de la interfaz haga esos cambios (ustedes saben como). Y sí existen formas de eliminar un item de un `QTreeWidget`, revisa bien la documentación :book: (quizás te sirva [este método](http://pyqt.sourceforge.net/Docs/PyQt4/qtreewidget.html#takeTopLevelItem))
