### ISSUE TITLE
Cambio de los archivos txt

### ISSUE THREAD

**Issue by amartini93** [IIC2233-2015-2/syllabus#51]
Noté que cambiaron el orden de las cosas del archivo personas.txt, yo ya había terminado de trabajar con ese, pero cuando hago pull denuevo, me encuentro con la sorpresa de que no me compila el código (para variar), y era porque cambiaron el orden. Debo suponer que van a repetir esto y que tengo que hacer mi código a prueba de trolleos? o puedo especificar en el README el tipo de formato del archivo que use??

**Comment by mbucchi** [comment]
Jajajaj no es un trolleo. Simplemente tienes que hacer que tu lector funcione para ese tipo de archivos de una forma un poco más genérica. Estos siempre vienen de la forma

```
{
"property_1" : valor_1,
"property_2" : valor_2,
...
"property_n" : valor_n
} 
```

Aunque las propiedades de los objetos no tienen por qué estar en orden, incluso dentro del mismo archivo. La idea es que crees un lector genérico y no hard codeado.

_**PD**_: En ciertas situaciones _(de la vida)_ te podrías topar con archivos que posean más espacios en blanco entre declaraciones o más saltos de línea. **NO** es el caso para los archivos que te daremos en esta tarea, pero esta sería una razón de peso para no hardcodear un parser de archivos.

Saludos!

**Comment by amartini93** [comment]
Si, si lo supuse, pero la primera vez lo hice a base del orden que estaba, ya lo arregle (Y)
Gracias!!
