### ISSUE TITLE
No me aparece QWebView

### ISSUE THREAD

**Issue by juancarlostorres** [IIC2233-2015-2/syllabus#512]
Para hacer que el usuario entre su cuenta a autorizar la app, necesito crear un QWebView pero en mi lista de widgets no aparece, intenté crearlo a mano como web= QtGui.QWebView y tampoco lo reconoce. En internet pude ver que a otras personas también les ha pasado pero no hay solución para Windows. Ayuda por favor!

**Comment by otro-felipe** [comment]
no es de QtGui creo que es de QtWebKit

**Comment by juancarlostorres** [comment]
Muchas gracias, problema solucionado.
