### ISSUE TITLE
Error al descargar archivos

### ISSUE THREAD

**Issue by Mapuentes** [IIC2233-2015-2/syllabus#513]
Al tratar de descargar un archivo con el comando files_download_to_file(download_path, path, rev=None) me sale:
PermissionError: [Errno 13] Permission denied

saludos

**Comment by aaossa** [comment]
Asegurate de no estar dando la ruta a una carpeta cuando se espera la ruta a un archivo

**Comment by mathias-katscher** [comment]
@Mapuentes te funciona? yo no logro solucionarlo

**Comment by oatorresuc** [comment]
yo tampoco he podido solucionarlo

**Comment by javierlopeza** [comment]
Según yo es lo que dice @aaossa, a mi me pasó al principio. Si quieren descargar una foto `imagen.jpg` en el escritorio, deben entregarle el `download_path = "C:\Users\Javier\Desktop\imagen.jpg"` (en mi caso), y  no cometer el error de entregarle `"C:\Users\Javier\Desktop"`.

**Comment by oatorresuc** [comment]
sisi, yo lo arreglé al procesar lo que dijo el antonio jaja

**Comment by oatorresuc** [comment]
Al descargarlo hay que descargarlo en "C:\Users\usuario\Desktop o puede ser
en una carpeta "descargas" dentro de la carpeta donde se encuentra mi app?

**Comment by oatorresuc** [comment]
perdon, corrigo:

Al descargarlo hay que descargarlo en "C:\Users\usuario\Downloads o puede
ser en una carpeta "descargas" dentro de la carpeta donde se encuentra mi
app?

**Comment by aaossa** [comment]
Eso es pregunta para los tareos? @oatorresuc Si es así, supongo que puedes especificar en el README o dejar que el usuario seleccione algún lugar para descargarlo

**Comment by fgvenegas** [comment]
En el enunciado no especifican, solo dicen que se de la opcion de descargar un archivo, asique no deberia tener problema si simplemente se baja al lado del main.py?

**Comment by aaossa** [comment]
### README

Pero no, no deberían tener problemas a no ser que un tareo diga lo contrario

**Comment by mathias-katscher** [comment]
yo voto por que haya un bonus por elegir el directorio de descarga
