### ISSUE TITLE
Dropbox API version

### ISSUE THREAD

**Issue by jlires** [IIC2233-2015-2/syllabus#514]
Empece a hacer la Tarea 7 y ya voy muy avanzado, y recién me doy cuenta que todo este tiempo estuve usando la v1 de la API. ¿Debo cambiar todo por la v2?

**Comment by juancarlostorres** [comment]
+1

**Comment by aaossa** [comment]
Dado que ambas siguen vigentes pueden ocupar ambas por igual :package:
