### ISSUE TITLE
duda con observar el arbol de archivos

### ISSUE THREAD

**Issue by tomvillage** [IIC2233-2015-2/syllabus#515]
Cuando en el enunciado dice se debe poder observar el arbol de archivos y carpetas asociado a su cuenta de Dropbox obligatoriamente se tiene que mostrar una especie de treeWidget donde al entrar a una carpeta se tienen que seguir viendo las otras carpetas  o puedo hacer una especie de listWidget y cuando ingreso a una carpeta veo solo lo que hay en esa carpeta y luego puedo volver atrás.

**Comment by twallacech** [comment]
+1

**Comment by tomvillage** [comment]
?

**Comment by flobarrios** [comment]
+1

**Comment by aaossa** [comment]
Marco: "Las dos son válidas, mientras sea funcional y simple".

Es una decisión de ustedes ver cómo resuelven el requerimiento

**Comment by flobarrios** [comment]
en ese caso, no seria necesario hacer una llamada recursiva a files_list_folder o si?? ya que al apretar una carpeta, puedo obtener los archivos de esa definiendo el path
