### ISSUE TITLE
Historial de modificaciones de carpetas

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#516]
Para el historial de modificaciones de archivos/carpetas, dice que se muestre la metadata, esto quiere decir para el archivo mostremos su: id, vclient_modified, server_modified, rev, size y media_info dado que eso nos entrega el get_metadata y para el caso de las carpetas el name, path_lower y el id?
o tenemos que mostrar para los archivos por ejemplo la ultima vez que se modifo y para las carpetas no se me ocurre que mostrar, dado que no tienen fecha de modificacion?

**Comment by javierlopeza** [comment]
Aprovecho de preguntar: ¿cuánto debo mostrar si solicito ver el historial de modificaciones de una carpeta? Me pongo en el caso de seleccionar un carpeta con muchas carpetas y archivos dentro, ¿cuál sería el historial de modificaciones que debo mostrar? ¿recursivamente de todos los archivos dentro? ¿o basta con que se pueda ver el historial de modificaciones de los archivos solamente? Gracias.

**Comment by aaossa** [comment]
Podrían preguntarse, ¿qué es lo que hace Google Drive con esto? Es un caso de referencia que hace algo similar a lo que les piden y ustedes deben tomar una decisión con respecto a esto.

Sobre el detalle (que lo que pregunta @oatorresuc ) justifiquen lo que decidan poner en el README  (a no ser que alguien de @IIC2233-2015-2/ayudantes-tareos diga otra cosa)
