### ISSUE TITLE
Cantidad de archivos

### ISSUE THREAD

**Issue by santiagocruzb** [IIC2233-2015-2/syllabus#518]
Hola! 
Viendo mi dropbox tengo como 25 archivos/carpetas en la carpeta raiz, y me los muestra todos con el comando `files_list_folder`. Pero cuando intento ver recursivamente `(recursive=True)` todos los archivos de mi dropbox, ya no me aparecen los 25 orgininal si no que un numero bastante menor,  cosa que se repite para el resto de las carpetas indexadas. 
Alguien no tuvo este problema?
Saludos

**Comment by aaossa** [comment]
Hay alguna carpeta que se repita? Leí la documentación y es posible que lo que retorne con `recursive=True` sea la lista para las subcarpetas, sin incluir la raíz (cosa que no me parece que esté bien). ¿Hay archivos en común?¿Aparecen los archivos de una forma y de la otra no?

**Comment by oatorresuc** [comment]
A mi me paso lo que dice el Antonio que no entrega la raíz, por lo que
primero encontré las carpeta raíz y después esas las recorrí recursivamente.

**Comment by santiagocruzb** [comment]
Pero como lo haces en poco tiempo? Cada vez que intento solicitar los archivos/carpetas de una dirección, el tiempo que respuestas es "considerable" (3 segundos) y si intentas recursivamente probarlo (para cada elemento intentar `files_list_folder`) para todos los elementos, se demora muchísimo

**Comment by aaossa** [comment]
De hecho son solo 2 requests no? Una para la raiz (sin recursive) y la otra en el mismo path pero recursivo

**Comment by santiagocruzb** [comment]
Efectivamente asi parece que funciona, muchas gracias @aaossa @oatorresuc !!
![large](https://cloud.githubusercontent.com/assets/13748925/11505882/54639ecc-982b-11e5-916d-0da0c7d8ccdc.gif)
