### ISSUE TITLE
Error conexión sin internet

### ISSUE THREAD

**Issue by jlires** [IIC2233-2015-2/syllabus#519]
Estoy tratando de debuggear mi programa y entre otras cosas evitar que se caiga cuando no hay internet. El problema es que la respuesta (el error que recibo) no logro atraparlo como excepción y no entiendo por qué. 
Notese el tipo de error que me devuelve es el de un exceso de intentos de request al servidor que al no haber internet todas fallan. 
¿Qué tipo de excepción es la que devuelve el server en ese caso?

**Comment by jlires** [comment]
La excepción final que me salta, junto con otras dos que son manejadas por la sdk es la siguiente:

![sin titulo](https://cloud.githubusercontent.com/assets/11801248/11507197/b046777c-9831-11e5-8f62-dbb2fac4defb.png)

**Comment by otro-felipe** [comment]
``` python
try:
    blabla
except urllib3.exceptions.MaxRetryError:
    blablabla
```

funcionara eso?

**Comment by jlires** [comment]
Como mencioné probé poniendo todas las excepciones que ahí me muestra y nada

**Comment by otro-felipe** [comment]
aah perdon no habia leido bien jajaja eso es todo el mensaje que arroja?

**Comment by otro-felipe** [comment]
provaste con `request.exceptions.ConnectionError`?

**Comment by andresespinosapc** [comment]
Puedes hacer esto:

``` python
try:
    # Acá lo que quieras
    int('fdsa')
except Exception as e:
    print(type(e))
```

2015-12-01 17:09 GMT-03:00 MainScientist notifications@github.com:

> provaste con request.exceptions.ConnectionError?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IIC2233-2015-2/syllabus/issues/519#issuecomment-161081444
> .

## 

Andrés Espinosa
Estudiante Ingeniería UC

**Comment by andresespinosapc** [comment]
Perdón, ahora con Markdown jaja respondiendo desde el mail no al parecer no funciona :(

``` python
try:
    # Acá lo que quieras
    int('fdsa')
except Exception as e:
    print(type(e))
```

Me faltó especificar que esto es para saber el tipo de error que se está produciendo.

**Comment by jlires** [comment]
He probado con eso también y nada (sigue saliendo el mismo assert completo), puede ser que algo afecte que la solicitud de conexión la hago dentro de un thread. Seguiré probando y si lo arreglo lo cuento

**Comment by andresespinosapc** [comment]
A qué te refieres con el "mismo assert completo"?

**Comment by jlires** [comment]
El mismo error de la imagen jajaj, no me expresé bien. A lo que voy es que no se atrapa la excepción incluso generalizando con Exception

**Comment by andresespinosapc** [comment]
Ojo que te está tirando una excepción mientras otra está siendo manejada, por lo que deberías hacer algo de este estilo según lo que entiendo:

``` python
try:
    print('Tu código')
except urllib3.exceptions.NewConnectionError:
    try:
        print('Más código')
    except urllib3.exceptions.MaxRetryError:
        pass
```

No sé cómo es tu código, no sé si aplique lo que puse. Haces algo dentro del except?

[EDIT]
Creo que me equivoqué, probablemente ya estabas manejando la primera excepción en el código en que tienes la segunda... Pero no está demás decirlo por si acaso jaja

**Comment by aaossa** [comment]
No sé como estás tratando de hacer el "`try/catch`". ¿Probaste usando solo `except:` en lugar de `except algunErrorBlaBlaBla:`?

**Comment by jlires** [comment]
Lo que tengo es muy simple:

``` python
try:
       self.client = dropbox.client.DropboxClient(self.access_token)
except:
       ...
```

**Comment by andresespinosapc** [comment]
Y ahi es cuando se genera que excepcion? Porque te aparecen 2 en lo que
mandaste. No puede ser que se este generando en lo que esta en el except?

**Comment by aaossa** [comment]
Es cierto lo que dice @andresespinosapc. El que salgan dos excepciones de esa forma indica que se produce otro error en el `except`. Recuerda que (siguendo tu ejemplo) no habrá nada en la variable `self.cliente` (no estará definida)

**Comment by jlires** [comment]
Toda la razón no me percate de eso tan simple. Muchas gracias @andresespinosapc  y @aaossa
