### ISSUE TITLE
historial

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#520]
Hola! Qué info tiene que aparecer en el historial de modificaciones? la enumeracion de las fechas y horas?

**Comment by tamycova** [comment]
Otra cosa, Dropbox no te da el historial de revisiones de una carpeta, solo de los archivos (la pagina), por lo tanto la funcion de la API tampoco... puedo asumir que la opcion va solo para los archivos y no las carpetas?

**Comment by javierlopeza** [comment]
@tamycova +1 a lo último, Dropbox no te da el historial de revisiones de una carpeta, solo de los archivos. La misma duda.

**Comment by tamycova** [comment]
@mbucchi  te invocoo

**Comment by oatorresuc** [comment]
tareos necesitamos saber esto pronto, la tarea es para el viernes :(

**Comment by fgvenegas** [comment]
Yo opte por poner la fecha de modificacion de los archivos que es como la forma de tener un historial de el

**Comment by oatorresuc** [comment]
yo hice lo mismo, pero que hacemos para las carpetas :/

2015-12-02 2:20 GMT-03:00 Freddie Venegas Apablaza <notifications@github.com

**Comment by fgvenegas** [comment]
poner los de cada archivo de la carpeta como al parecer intento decir @mbucchi en #508

**Comment by oatorresuc** [comment]
gracias!

2015-12-02 2:53 GMT-03:00 Freddie Venegas Apablaza <notifications@github.com

**Comment by andresespinosapc** [comment]
Yo como informacion puse todo lo de metadata nomas, tiene sentido porque en
el emunciado sale en parentesis metadata.

**Comment by aaossa** [comment]
Recuerden que cualquier decisión / cambio / cosa de la que no estén seguros o no salga tan explicita en el enunciado pueden (y deben) justificarla en su README :grin:

**Comment by fgvenegas** [comment]
Yo encontré que era innecesario poner todo, para mí (metadata) significaba que de ahí había que sacar la info, pero bueno tal vez algún tareo responda

**Comment by tamycova** [comment]
Al final hice lo mismo que @fgvenegas  , puse las modificaciones de todos los archivos que contiene (evitando las carpetas obvio), y la hora de modificación del server y el user + nombre del archivo.
