### ISSUE TITLE
FEEDBACK T05 vacio

### ISSUE THREAD

**Issue by twallacech** [IIC2233-2015-2/syllabus#521]
Hola, me encuentro todavia con un feedback vacido para la tarea 05  :/

**Comment by nateare** [comment]
+1

**Comment by oatorresuc** [comment]
+1 y nota 1,0 :(

**Comment by santiagocruzb** [comment]
Me pasó lo mismo para la tarea 4 :rage:

**Comment by juancarlostorres** [comment]
Yo también estoy con 1.0 y sin feedback de t05. Cuando te dieron la nota de tu tarea 4? tuviste que mandar a recorregir?

**Comment by santiagocruzb** [comment]
@juancarlostorres para cuando entregaron la tarea 4. Llené el cuestionario y hasta ahora espero..

**Comment by lopezjurip** [comment]
plz @IIC2233-2015-2/ayudantes-tareos ver qué pasó

**Comment by juancarlostorres** [comment]
@santiagocruzb @mrpatiwi  Gracias!

**Comment by plorrego** [comment]
Hubo problemas con la planilla de notas. Todos manden a recorregir. No se preocupen van a tener la nota que merezcan. Perdon por los inconvenientes!

**Comment by juancarlostorres** [comment]
@plorrego Podremos conocer nuestra nota de tarea 5 antes del examen como para estimar que nota necesitaremos? o estarán despúes? Gracias!

**Comment by lopezjurip** [comment]
Subí los feedbacks pendientes de:

```
AlfonsoIgnacioV
Treisenegger
ignaciourzuaf
jatrincado
jnrosenbluth
nateare
panchopp
rrfoster
thomasfmunozs
twallacech95
```

**Comment by santiagocruzb** [comment]
@mrpatiwi  tuve el mismo problema en la tarea 4, algo que se pueda hacer???? De todas maneras alcancé a mandar el cuestionario por el siding :pray: 
![giphy](https://cloud.githubusercontent.com/assets/13748925/11536849/06f99348-98f9-11e5-9647-5f3c6a6f227f.gif)
