### ISSUE TITLE
files_move

### ISSUE THREAD

**Issue by clagos4** [IIC2233-2015-2/syllabus#522]
hola! Estuve viendo otros issues y al parecer la api de Dropbox tiene un error en la función files_move, que es muy útil para la tarea, según pude ver, solo ocurre en algunos casos, hay gente que le pasa siempre y otros que les pasa muy poco. Qué hacemos con esto? Aplicamos el método de descarga y upload del archivo o usamos el comando files_move que tiene fallas?
Les adjunto la issue:

https://github.com/dropbox/dropbox-sdk-python/issues/30

**Comment by fgvenegas** [comment]
En mi caso personalmente era porque ~~soy weon~~ no estaba poniendo el path bien, pense que con indicarle la carpeta bastaba y en realidad tenia que poner /folder/archivo_que_muevo

**Comment by clagos4** [comment]
No me pasa lo mismo, ya trate de esa forma. me devuelve ServerInternalError, no malformed path

**Comment by javierlopeza** [comment]
Aprovecho de preguntar, `files_move` me funciona perfecto para archivos, pero carpetas no me deja. Me tira: `dropbox.exceptions.ApiError: RelocationError('to', WriteError('conflict', WriteConflictError('folder', None)))`. Y puedo suponer que es algo así como que Dropbox internamente escribe el archivo en el directorio nuevo, por lo que no puede "escribir" la carpeta que quiero mover. ¿alguna ayuda/recomendación? Gracias!

**Comment by aaossa** [comment]
@javierlopeza ¿Hay alguna repetición de nombres? ¿Qué status HTTP te retorna (no sé si puedes verlo, pero según la documentación el error incluye uno)?

**Comment by javierlopeza** [comment]
@aaossa Ahí lo arreglé! Se me había olvidado poner también el nombre de la carpeta en el path de destino. Gracias!

**Comment by clagos4** [comment]
Al parecer el problema de mover solo pasa cuando uno usa la api en una sub-carpeta del dropbox, lo cambié para que tenga acceso a todo el dropbox y empezó a funcionar, por si a alguien le estaba pasando lo mismo.
