### ISSUE TITLE
Duda materia examen

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#523]
Sobre lo que entra: ¿habra enfasis en la materia no evaluada? (data mining y web service) ¿o sera completamente aleatorio que cosas pregunten? 

En el caso de data mining, ¿habría que estudiar de los links que mandaron para hacer la actividad? (pregunto porque no hay un apunte formal).

Gracias!

**Comment by bcsaldias** [comment]
Hola !
Piensa que en un examen se debe evaluar cuánto sabes de curso en general y en total, no es una i4. Es completamente aleatorio lo que se pregunte, independiente de en lo que se pueda enfocar.

Los links publicados son solamente sintaxis. ¿Es fundamental saberse esa sintaxis (en particular la de esta materia) para aprobar el curso?

Saludos !

**Comment by ghost** [comment]
dale, gracias!

**Comment by AntoniaMendoza** [comment]
Hola, entrará la materia de la última actividad?

**Comment by bcsaldias** [comment]
No, es solo sintaxis.

Saludos !

2015-12-02 14:58 GMT-03:00 Antonia Mendoza notifications@github.com:
