### ISSUE TITLE
Examen 2015-1

### ISSUE THREAD

**Issue by lopezjurip** [IIC2233-2015-2/syllabus#525]
Subimos el examen del semestre pasado al [syllabus](https://github.com/IIC2233-2015-1/syllabus) de ese semestre.
Lo pueden ver acá:
https://github.com/IIC2233-2015-1/syllabus/tree/master/Pautas%20Interrogaciones/Examen

> Ojo que es un borrador, no entra tanto en detalle y puede tener errores. También pueden existir otras soluciones (como siempre).

**Comment by bcsaldias** [comment]
Gracias @mrpatiwi
