### ISSUE TITLE
Username Dropbox

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#527]
¿Alguien sabe o ha encontrado cómo obtener el username de quien está conectado? Es como aparte de las restricciones del enunciado, quiero usarlo para mostrar el nombre de quien está conectado.

**Comment by jfcampos1** [comment]
dpx=dropbox.Dropbox('token')
dpx.users_get_current_account()

**Comment by javierlopeza** [comment]
@jfcampos1 quiero obtener el nombre del usuario conectado, después de conectarme revisé el `dbx.__dict__` y no hay nada que me pueda entregar el nombre del usuario por lo que veo hasta el momento.

**Comment by nateare** [comment]
Esto es lo que buscas creo... si no trata con user_info.name. (given_name, surname o familiar_name...)

```
import dropbox
token = '<token>'
dbx = dropbox.Dropbox(token)
user_info = dbx.users_get_current_account()
print(user_info.name.display_name)
```

**Comment by javierlopeza** [comment]
@nateare Bueeena buena perfecto, justo lo que buscaba. Gracias!
