### ISSUE TITLE
Error 400: bad request

### ISSUE THREAD

**Issue by Vanana** [IIC2233-2015-2/syllabus#528]
Autorizo mi app de dropbox pero cuando copio el codigo a mi programa me tira el error de bad request, probe mi codigo en otro computador y funciona, entonces la verdad nose porque me falla en el mio, estoy en mac.

**Comment by aaossa** [comment]
Probaste con **exactamente el mismo código** y la misma request?

**Comment by Vanana** [comment]
el mismo codigo con el mismo request :/

**Comment by Vanana** [comment]
![image](https://cloud.githubusercontent.com/assets/13741917/11540376/37322612-990b-11e5-9c88-09ee87cf48b2.png)

**Comment by Vanana** [comment]
ayudaaaaaaaa! porfavor que mañana es el unico dia que puedo trabajar en la tarea, porque estoy haciendo la practica. Tal vez tu sabes que pueda ser @mrpatiwi :' (

**Comment by fagomez2** [comment]
Estás obteniendo el token? Si es así, a mí me está resultando con esta linea:
dropbox.client.DropboxClient(access_token)
La saqué directamente de un ejemplo de la página, así que supongo que no debería haber problemas en ponerla aquí.
Para comprobar que te estás conectando bien, te sugiero guardar lo de arriba en una variable y usar el método account_info, si te sale información personal de la cuenta (como el nombre y apellido) es porque se conectó bien. Suerte!

**Comment by lopezjurip** [comment]
hmmm, hay alguna librería que instalaste por `pip` en un computador y no en el otro?

**Comment by lopezjurip** [comment]
Si puedes pushear a tu repo lo que llevas podría echarle una mirada a ese archivo `dropbox_client.py` en particular

**Comment by Vanana** [comment]
ya @mrpatiwi lo subi :) en los dos computadores esta instalado con pip

**Comment by lopezjurip** [comment]
Prueba actualizando la librería `requests`:

``` sh
pip install -U requests
```

También prueba:

``` sh
pip3 install -U requests
```

**Comment by Vanana** [comment]
dice que ya esta actualizado :/

**Comment by sebamenabar** [comment]
hola, lo pudiste pudiste arreglar?

**Comment by Vanana** [comment]
@sebamenabar no pero me consegui otro computador :)
