### ISSUE TITLE
Puedo usar Tkinter?

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#529]
Hola. Quiero usar Tkinter para abrir un explorador donde pueda seleccionar el path a un archivo. Hay algun problema?

**Comment by aaossa** [comment]
Yo diría que no puedes usar tkinter, [esto se puede hacer usando PyQt4](https://github.com/IIC2233-2015-2/syllabus/issues/465#issuecomment-158678658)
