### ISSUE TITLE
Horario Examen

### ISSUE THREAD

**Issue by AntoniaMendoza** [IIC2233-2015-2/syllabus#530]
¡Hola!
¿A qué hora es el examen?
Varios tenemos la duda jaja
Gracias

**Comment by javierlopeza** [comment]
+1

**Comment by twallacech** [comment]
+1

**Comment by fgvenegas** [comment]
+1

**Comment by oatorresuc** [comment]
+1

**Comment by benjavides** [comment]
+1

**Comment by crxzadytho22** [comment]
El próximo jueves 3 de diciembre tenemos nuestro examen en la mañana.
yo asumo que es a las 8:30 como todos los examenes de la mañana, pero igual seria bueno que confirmen :)

**Comment by aaossa** [comment]
Se les va a enviar un correo con la hora y las salas, no se desesperen :)

**EDIT:** Empezaría a las 9:15

**Comment by lopezjurip** [comment]
Efectivamente a las 9:15
