### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#531]
Es normal que cuando haga `with open("/blabla"``) en windows me reconozoca el "/" para moverme entre paths? pense que me tiraria error como las carpetas estan escritas "\folder"

**Comment by lopezjurip** [comment]
Parece que lo hace de manera automática, no logro encontrar documentación oficial, pero en la práctica funciona. Igual trata de usar la forma _canónica_ de manipular paths:
https://docs.python.org/3/library/os.path.html

**Comment by fgvenegas** [comment]
ok, pero podria generarse algun problema si subo mi tarea asi?

**Comment by lopezjurip** [comment]
El que nada arriesga, nada gana :see_no_evil: 

Si te ha funcionado hasta el momento, bien :+1:

**Comment by fgvenegas** [comment]
jaja ya me la jugare nomas gracias!
