### ISSUE TITLE
Historial con dropbox.client.DropboxClient(token)

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#533]
¿Se puede obtener la lista de revisiones de un archivo con API mediante la clase `dropbox.client.DropboxClient(token)`o solo se puede usando `dropbox.Dropbox(token)`?

He buscado por todos lados y no he encontrado nada. 

Gracias

**Comment by ghost** [comment]
@mbucchi

**Comment by jlires** [comment]
https://www.dropbox.com/developers-v1/core/docs/python

Ahí están todas las funciones para el SDK en su version v1

**Comment by ghost** [comment]
@jlires el tema es que cuando hago `self.client.revisions(path)`me retorna un diccionario solo con la última revisión al parecer (en un archivo X me retorna `revision: 19858`). Obtengo lo mismo con al solicitar la metadata del archivo, pero no encuentro un método con TODAS las revisiones y modificaciones.

**Comment by ghost** [comment]
@mrpatiwi help plz !

**Comment by lopezjurip** [comment]
Revisaste la documentación oficial?
https://www.dropbox.com/developers-v1/core/docs/python#DropboxClient.revisions

**Comment by lopezjurip** [comment]
Será por esto?
![image](https://cloud.githubusercontent.com/assets/7570744/11576600/9abfb352-99f6-11e5-9927-e4eb48f134fc.png)

**Comment by fgvenegas** [comment]
Estas seguro que has modificado los archivos? Porque a mi me pasaba que me retornaba solo uno pero era porque no los habia modificado
