### ISSUE TITLE
Duda con respecto a escala en I2

### ISSUE THREAD

**Issue by ghost** [IIC2233-2015-2/syllabus#534]
Hola! Les quería consultar con respecto a la escala que se uso para calcular la nota de la I2. Estaba sacando cálculos con respecto a mi puntaje y el total de puntos (90 en la I2), y no me calzaban las notas.

Lo que hice fue tomar mi puntaje y dividirlo en el total (90). El resultado lo multiplique por 6 y le sume 1 (punto base), y me dio una nota mas alta que la que tengo en el siding. Pensé que quizás era un tema de que habían sacado las notas usando un procedimiento distinto, pero al tratar de hacerlo con la I1 (tomando mi puntaje sobre los 100 puntos de la interrogación) me dio la nota publicada exacta.

Posteriormente saque mi nota de I2 pero dividiendo sobre 100 en vez de 90, y me dio la nota que tengo publicada para la interrogación 2 en el siding.

¿Habrá un problema con como se calcularon las notas? ¿O hay alguna variable que yo no estoy considerando en el análisis anterior? Perdonen las molestias!

**Comment by lopezjurip** [comment]
Así es, @jecastro1 lo está viendo y él avisará cuando se hayan actualizado las notas :+1:

**Comment by rjherrera** [comment]
Me pasó lo mismo, si calculo con 100 puntos como máximo (en vez de los 90 de la prueba) me da la nota que sale en siding, gracias por revisarlo!

**Comment by ghost** [comment]
gracias!

**Comment by crxzadytho22** [comment]
osea subiran la nota? jajaj que bakan !

**Comment by jecastro1** [comment]
Hola,

Estamos revisando este tema. Mañana les deberíamos tener las noticias correspondientes, aunque quizás no las anuncie yo mismo jaja.

**Comment by juancarlostorres** [comment]
Buena @jnrosenbluth , ojala suban las notas! todo punto suma =)

**Comment by javierlopeza** [comment]
¿Qué pasó con esto al final?

**Comment by bcsaldias** [comment]
Hola, cuando se suban más notas actualizaremos eso.

Saludos
