### ISSUE TITLE
Descarga de archivos "pega" la interfaz

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#535]
Hola, cuando bajo carpetas como tienen muchos archivos se demora, por lo que mi app se queda pegada y dice "No responde" pero esto dura hasta que se complete la descarga, y ahi todo vuelve a la normalidad, hay que evitar que pase esto o da lo mismo si total es solo por el tiempo de descarga?

**Comment by javierlopeza** [comment]
A mi me pasaba eso, pero le di un thread al proceso y aunque se demorara lo hacia en "segundo plano" entonces dejo de "no responder".

**Comment by aaossa** [comment]
Manden un thread a hacer el trabajo y hacen una sub ventana con una barra de progreso o algún indicador de que al menos esta cargando. Hay una solución muy buena haciendo una clase trabajadora que herede de QThread y envíe señales a la interfaz para los cambios en la barra de progreso/indicador

**Comment by lopezjurip** [comment]
### Eso pasa en todas las aplicaciones. Siempre están los dos casos:
1. Las apps que lo controlan bien pasando la operación a un thread y suscribiéndose a el progreso para mostrarlo como una barra de progreso. 
   ![image](https://cloud.githubusercontent.com/assets/7570744/11576694/612ecc44-99f7-11e5-9840-a059b276b7b2.png)
2. Las apps que tiran todo el thread principal y se quedan esperando/pegadas.
   ![image](https://cloud.githubusercontent.com/assets/7570744/11576709/7254cac8-99f7-11e5-8e2f-ba91f4d35ff8.png)
   ![image](https://cloud.githubusercontent.com/assets/7570744/11576717/8a48834a-99f7-11e5-8e12-32cdff64aa00.png)
