### ISSUE TITLE
no me reconoce el modulo dropbox

### ISSUE THREAD

**Issue by ManuelBeckerT** [IIC2233-2015-2/syllabus#536]
Seguí las instrucciones para instalar dropbox y no he podido hacer que me reconozca el módulo para trabajar. Ayuda por favor!!

**Comment by aaossa** [comment]
Que hiciste para instalarlo? Te sale algún error en particular? Prpbaste por consola, pycharm y todas las formas que pudiste?

**Comment by santiagocruzb** [comment]
Al menos yo hice desde la terminal `pip3 install dropbox` y ningún problema

**Comment by ManuelBeckerT** [comment]
Hice eso y no me reconoció nada después PyCharm. Luego traté de la manera
que indica el enlace en la tarea que. Cloné la carpeta y luego hice desde
el path a esa carpeta en la terminal python setup.py install y aún así no
me funcionó.

**Comment by otro-felipe** [comment]
y si lo descargas directo desde pycharm? [installing-uninstalling-and-upgrading-packages](https://www.jetbrains.com/pycharm/help/installing-uninstalling-and-upgrading-packages.html)

**Comment by ManuelBeckerT** [comment]
Hice un cambio desde pycharm para que reconozca el módulo y ahora funciona.
Muchas gracias

2015-12-03 19:13 GMT-03:00 MainScientist notifications@github.com:
