### ISSUE TITLE
Problema con historial de modificaciones

### ISSUE THREAD

**Issue by trencoret** [IIC2233-2015-2/syllabus#537]
Hola, cuando le hago folder_metadata['modified'] solamente me retorna un str con la ultima modificacion, no cacho como poder guardar todo el historial. Hay algun metodo que retorne todo el historial del archivo? O tengo que ir almacenandolo externamente?

Saludos y gracias!

@mbucchi @mrpatiwi

**Comment by otro-felipe** [comment]
`Dropbox.files_list_revisions` ?
