### ISSUE TITLE
Historial de carpetas

### ISSUE THREAD

**Issue by icrocco** [IIC2233-2015-2/syllabus#539]
¿Existe algo así como un historial de la carpeta o la idea es que mostremos el de todos los archivos que contiene?

Porque he buscado harto y lo más que logro con metadata de la carpeta es obtener su id, pero nada de revs. Y es que de hecho parece que no se puede ( ver https://www.dropboxforum.com/hc/en-us/community/posts/203809315-Unable-to-retrieve-folder-revisions-through-metadata-using-rev-parameter- ) :cold_sweat:

**Comment by aaossa** [comment]
#516

**Comment by icrocco** [comment]
:wink:  gracias! no había encontrado ese otro issue.
