### ISSUE TITLE
AC04

### ISSUE THREAD

**Issue by cdonoso** [IIC2233-2015-2/syllabus#54]
Tengo una duda, en el calendario sale que entra hasta antes de árboles, entonces ¿entra EDD-1,EDD-2,EDD-3,EDD-4 y EDD-5?

Saludos!

**Comment by vjmoreno** [comment]
Y entra properties?

**Comment by cdonoso** [comment]
En todo caso con esas siglas me refiero a:

EDD-1 = Introducción
EDD-2 = Pilas
EDD-3 = Colas
EDD-4 = Dictionaries
EDD-5 = Sets

Yo asumo que entra properties como no ha sido evaluado, pero igual creo que es mucho para una sola AC

**Comment by bcsaldias** [comment]
Entra solo EDD, tal como aclaré en un mensaje por el Siding.

Saludos !
Belén

**Comment by cdonoso** [comment]
¿Entonces entra efectivamente Introducción, Pilas, Colas, Dictionaries y Sets?

Saludos!

Clemente

**Comment by bcsaldias** [comment]
Exacto !!

Pueden ir viendo los contenidos en el calendario también,

Saludos !
