### ISSUE TITLE
Subida de archivos y creación de directorios

### ISSUE THREAD

**Issue by andresespinosapc** [IIC2233-2015-2/syllabus#540]
En el enunciado sale que la subida de archivos y creación de directorios tiene que ser seleccionando una carpeta y creando el nuevo archivo o carpeta en el mismo directorio que la seleccionada. Esto no me hace mucho sentido, sería más intuitivo que se cree dentro de la carpeta seleccionada, pero que se puedan seleccionar archivos y en ese caso sea en el directorio del archivo.

 Ya que sale explícito en el enunciado, quería preguntar si puedo hacerlo de la forma que digo.

**Comment by aaossa** [comment]
A mi parecer personal es menos intuitivo lo que tu dices (si es que lo entiendo bien). Si ningún tareo dice que puedes hacerlo, lo mejor seria que hicieras lo que sale explicito en el enunciado, para eso es el enunciado.

Por cierto, hay una manera de que al mostrar una ventana para que un usuario seleccione una carpeta no aparezcan archivos, eso creo yo es lo mas correcto y lo que debes hacer.

**Comment by andresespinosapc** [comment]
Lo que estoy haciendo es que en el mismo árbol donde se muestran los archivos del servidor puedo hacer click derecho y poner Upload File. Ahí se abre una ventana para seleccionar el archivo, pero nunca se abre una ventana para seleccionar hacia donde subirlo, se entiende? Ojalá ahí quede más claro.

**Comment by aaossa** [comment]
Entonces podrías hacer que lo del click derecho funcione solamente sobre los directorios y no sobre los archivos

**Comment by andresespinosapc** [comment]
Sí hice eso. Ahora, sabiendo mejor cómo lo estoy haciendo, crees que es mejor que se suba el archivo dentro de la carpeta en que hice click derecho o fuera? (Igual esperaré a un tareo para asegurarme)

**Comment by otro-felipe** [comment]
+1 Al hacer click derecho mi tarea abre un menu contextual que dice Upload files. Segun yo es mas inuitivos que esos archivos queden dentro dr la carpeta que se hizo click derecho, de lo contrario no se podrian crear archivos ni carpetas dentro de una carpeta vacia.

**Comment by aaossa** [comment]
@alopez7 les dirá algo que conversamos, él es tareo así que creanle :laughing: ( :cry: )

**Comment by alopez7** [comment]
Puedes hacerlo de la manera que dices pero debes especificarlo en el readme explicando porqué consideras que es mejor de esa manera.

**Comment by andresespinosapc** [comment]
Perfecto, gracias !
