### ISSUE TITLE
Solicitar un repo privado

### ISSUE THREAD

**Issue by Pochoclo** [IIC2233-2015-2/syllabus#541]
Había escuchado por ahí que podemos solicitar otro repo privado como para hacer algún proyecto. Con quien hay que hablar para pedir uno? Quiero pedir uno!

**Comment by lopezjurip** [comment]
Tienes 3 proveedores de `git`. 

En Github todos parten con 0, pero puedes pedir 5 repos privados (y otras cosas más) mientras seas estudiante en: https://education.github.com/pack. Puedes tener ∞ colaboradores en un repo privado.

Nosotros usamos [Github Classroom](https://education.github.com/guide) para pedir los repos que ahora usan (**sus repos de este semestre son para siempre**).

En [Bitbucket](https://bitbucket.org/) por defecto tienes ∞ repos privados, pero con un máximo de 5 colaboradores. También puedes pedir los beneficios de estudiante para tener ∞ colaboradores.

En [Gitlab](https://gitlab.com) por defecto tienes ∞ repositorios privados con ∞ colaboradores. Además es un servicio open source. (puedes montar tu propio servicio de git en cualquier servidor).

> Personalmente uso Github para proyectos código abierto y Gitlab para proyectos privados.

**Comment by yackpott** [comment]
a mi me dieron el de estudiante, eso si se demoran harto en verificar tu cuenta (como unos 10 dias) y dura solo 2 años, no es para siempre

**Comment by Pochoclo** [comment]
Que bueno saberlo, muchas gracias!

**Comment by fgvenegas** [comment]
Cómo funcionan los repos? Eso de pedirlo en uno pero usarlo en otro?

**Comment by fgvenegas** [comment]
Ignoren mi comentario
