### ISSUE TITLE
Uso de listas o diccionario en clase árbol

### ISSUE THREAD

**Issue by tmorales1** [IIC2233-2015-2/syllabus#544]
Supongo que se pueden usar listas o diccionarios para la clase árbol por ejemplo. O no?

**Comment by gafigueroa** [comment]
Siempre y cuando las listas y diccionarios los hayas creado tu.

**Comment by aaossa** [comment]
Hola, ya nadie (excepto @gafigueroa al parecer jajaja) ve este repo. Trata de usar el de este semestre :grin: [Ir al semestre correcto](http://github.com/IIC2233-2016-1/syllabus)
