### ISSUE TITLE
Error al instalar Packages ATOM

### ISSUE THREAD

**Issue by ThOmZam** [IIC2233-2015-2/syllabus#545]
Hola cada vez que intento descargar un package desde la aplicacion me sale un error, por ejemplo cuando intento descargar "color-picker" me sale este error:

"Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module."

Despues voy a simbolo de sistema y corro el comando "apm -v" y me dice: 

'"apm" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.'

gracias.

**Comment by aaossa** [comment]
Hola, para solucionar el segundo problema [podrías intentar agregando el directorio bin de Atom al path](https://discuss.atom.io/t/atom-is-not-getting-opened-in-cmd/19572/4). Con eso podrás encontrar el primer problema.

PS: Este repo es de un curso que actualmente se encuentra cerrado. Para preguntas de este tipo se recomienda buscar por tu cuenta y/o utilizar StackOverflow. Además, este repositorio no contiene código fuente que se relacione con lo que estás usando, así que no corresponde abrir la issue en este repositorio.

Éxito solucionando tu problema :)
