### ISSUE TITLE
Tarea1 - MAT1600 Bummer UC

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#55]
Este curso es prerrequisito de todos los ramos del primer semestre de ingeniería, pero es un curso antiguo, por lo que no aparece en la lista de ramos para tomarlo (Y nadie lo tiene como ramos_pre). No puedo tomar lineal, ni calculo I etc etc etc.

**Comment by lopezjurip** [comment]
Pucha que me hace sentir viejo haber tomado Introducción al Cálculo (MAT1600) :cry:

**Comment by aaossa** [comment]
No que es la nivelación de entrada para los novatos ahora? D: #OffTopic

**Comment by mbucchi** [comment]
Argh, maldito buscacursos y sus pre requisitos anticuados... Ahora se encuentra el archivo de personas en el que todos los alumnos ya han cursado _MAT1600_, espero que eso solucione los problemas, saludos! 
PD: @MainScientist de todas maneras igual era posible programar el sistema, solo que aquellos que se hayan echado Álgebra Lineal o Cálculo I no podrán volver a tomarlos nunca jamás (muajaja :smiling_imp:)

**Comment by otro-felipe** [comment]
esa clase de pensamiento hizo que bannerUC resultara como resultó jajajajajaja
