### ISSUE TITLE
Abrir archivos de texto que esten en una carpeta

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#57]
Ordenando el proyecto de la Tarea 1 en sub-carpetas, me di cuenta que me tira errores si tengo los archvios _.txt_ en sub-carpetas, _por ejemplo_, si tengo

```
>T09
   >main.py
   >lectura
      >animales.txt
      >lector_animales.py
      >__init__.py
```

y el archivo main.py hace `from lectura.lector_animales import lector_animales` donde `lector_animales()` es un metodo del archivo `lector_animales.py` que abre archivo _animales.txt_.
El problema es que si es que tengo los archivos organizados de dicha forma me tira el siguiente error,

```
FileNotFoundError: [Errno 2] No such file or directory: 'animales.txt'
```

¿Alguna recomendación para poder abrir bien los archivos de texto modularizando en carpetas? Para no tener que poner todos los archivos _.py_ y _.txt_ en la carpeta `T01`.

**Comment by otro-felipe** [comment]
eso pasa porque al llamar un archivo desde el main.py tu estas en la carpeta T09 y, sin importar de donde venga la funcion lector_animales(). El path relativo desde main.py hasta animales.txt es: "/lectura/animales.txt", por lo que para llegar a tu archivo debes llamarlo con ese path y no como "animales.txt" ya que asi lo deberias llamar solo si te encuentras en la misma carpeta de ese archivo.

**Comment by javierlopeza** [comment]
Hago lo que señalas arriba: `file_animales = open("/lectura/animales.txt")` pero al ejecutar el _main.py_ me tira el error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/lectura/animales.txt'
```

**Comment by otro-felipe** [comment]
al parecer hay que usar un punto antes del path. Intenta con "./lectura/animales.txt"

**Comment by javierlopeza** [comment]
Ahí sí funciono. Gracias!
