### ISSUE TITLE
Librería permitida: json

### ISSUE THREAD

**Issue by ivanwolf** [IIC2233-2015-2/syllabus#58]
Hola, estoy tratando de transformar un objeto `str` a uno `dict`, sin utilizar `eval()`.
Buscando en google encontré que existe la librería `json`, que en foros se menciona como "más segura" que  usar directamente eval() ya que el metodo de `json` solo se limita a listas, tuplas, etc.

En fin, quisiera saber si es que se puede usar la librería, o es uno de los objetivos de la tarea  que transformemos (si es necesario) un objeto `str` a un diccionario, lista, tupla, etc. ?

Saludos.

**Comment by lopezjurip** [comment]
Ya preguntaron si se podía, y no se puede.
https://github.com/IIC2233-2015-2/syllabus/issues/29#issuecomment-133474468

**Comment by aaossa** [comment]
Y en #41 recomendaron no usar `eval()`

**Comment by ouhenio** [comment]
Y bajo ningún motivo se puede usar re? No nos compliquen la existencia :(

**Comment by aaossa** [comment]
En #45 dijeron que no se puede usar **re** :(

**Comment by oatorresuc** [comment]
Hola, se puede usar la libreria copy y la libreria operator?

**Comment by aaossa** [comment]
La librería **copy** no se puede utilizar como dijeron en #76. Sobre **operator** espera a que te responda un tareo.
