### ISSUE TITLE
Problema al leer evaluaciones.txt

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#59]
Hola. Puede ser que haya algun error en el formato de este archivo? (que falte alguna coma o algo asi). Lo que hice para leer y guardar la informacion de un archivo de texto funciona en cursos, personas y requisitos, pero falla en este archivo y no he podido localizar el error.

**Comment by ralvarez94** [comment]
A mi me paso eso, pero lo resolví especificando que la lectura del archivo sea en utf-8

**Comment by raiperez** [comment]
También los he estado leyendo con encoding utf-8 >.<

**Comment by aaossa** [comment]
Podrías poner el error que recibes

**Comment by mbucchi** [comment]
@raiperez efectivamente la versión antigua tiene un caracter loco dando vuelta por ahí. Con la versión nueva ya no deberías tener problema.
Saludos!

**Comment by raiperez** [comment]
@mbucchi Perfecto!! gracias!!
