### ISSUE TITLE
Problema siguiendo guía

### ISSUE THREAD

**Issue by raiperez** [IIC2233-2015-2/syllabus#6]
Hola. Estoy en la parte de instalar pip, pero me arroja el siguiente error. ¿Qué puedo hacer?

![image](https://cloud.githubusercontent.com/assets/13739960/9235174/1b129ab4-410b-11e5-8702-9c86060c4d18.png)

**Comment by lopezjurip** [comment]
Probaste con: 

``` sh
choco install pip -version 7.1.0
```

Ese es el error más típico, a veces hay que simplemente reintentarlo

**Comment by AlainLotissier** [comment]
Me pasa lo mismo. Ya intente varias veces con todos los codigos

**Comment by raiperez** [comment]
Ahí logré instalar pip! Muchas gracias!

2015-08-12 16:46 GMT-04:00 AlainLotissier notifications@github.com:

**Comment by lopezjurip** [comment]
@AlainLotissier asegúrate de haber instalado bien Python3 (en Window siempre conviene ir reiniciando la consola para evitar problemas), prueba escribiendo `python` en consola.

De todas formas es una **guía sugerida de instalación**, puedes instalar todo del método típico (bajando las cosas de las páginas oficiales) pero ahí dependería de ti el cómo instalar lo demás y evitar conflictos entre programas :)

**Comment by raiperez** [comment]
@mrpatiwi  Ahora cuando intenté seguir y actualizar pip me arrojó el siguiente error

![image](https://cloud.githubusercontent.com/assets/13739960/9236858/76d5312c-4115-11e5-87a0-e8909d694e5c.png)

**Comment by AlainLotissier** [comment]
Ahí me funciono. Gracias

2015-08-12 17:13 GMT-04:00 raiperez notifications@github.com:

**Comment by clagos4** [comment]
A mi me resulto siguiendo las instrucciones en
https://pip.pypa.io/en/latest/installing.html

**Comment by bcsaldias** [comment]
Estimados,

De cualquier manera todas las dudas se resolverán el lunes en la ayduantía.

Mañana la AC será entregada por el Siding así que solo deben tener instalado Python3.4 para entonces.

Saludos !

**Comment by cpieringer** [comment]
En Windows les recomiendo instalar la distribución de Python Anaconda3 desde http://continuum.io/downloads#py34.

Las librerías que necesiten las pueden instalar fácilmente como:

```
   conda install <nombre-librería>
```

O bien actualizarlos como:

```
  conda upgrade <nombre-librería>
```

**Comment by raiperez** [comment]
@cpieringer  Ya instalé Anaconda3, pero cuando intento hacer por ejemplo "conda install pyqt" recibo el error siguiente:

PS C:\Windows\system32> conda install pyqt
Traceback (most recent call last):
  File "C:\Users\Raimundo\Anaconda3\Scripts\conda-script.py", line 2, in <module>
    from conda.cli import main
ImportError: No module named 'conda'

**Comment by cpieringer** [comment]
@raiperez Anaconda 3 ya tiene instalado por defecto PyQt4. Puedes revisar la lista de paquetes instalados con la distribución en http://docs.continuum.io/anaconda/pkg-docs.

Después de la instalación deberías poder, por ejemplo, hacer:

```
 from PyQt4 import QtCore
```

**Comment by aaossa** [comment]
@raiperez si sigues con problemas te recomiendo abrir otra issue :grin:
