### ISSUE TITLE
El encapsulamiento en Python y las buenas costumbres

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#60]
¡Tengo una duda que necesito solucionar!

Supongamos tengo un objeto con atributos A y B. Digamos que en un principio los cree sabiendo que serían nada más de uso interno de la clase, así que decidí llamarlos _A y _B buscando un encapsulamiento por convención.

Supongamos ahora que más tarde se me ocurrió agregar una función, ejemplo **eq**(self, other), que trabajase con la instancia de otro objeto de la misma clase. Si yo deseo trabajar con los atributos del objeto "other", necesitaré hacer other._A y other._B, lo cual sería contradictorio con mi búsqueda de "encapsular".

Me pregunto entonces ¿Quito los "_" o utilizo @property? ¿Es una buena costrumbre usar el decorador @property, a pesar de que sabes que no necesitarás de funciones setter y deleter (solo buscar un getter para privatizar)?

**Comment by mbucchi** [comment]
Si estás planteando algo como 

``` python
class A:
    def __init__(self, a, b):
        self._a = a
        self._b = b
    def __eq__(self, other):
        return self._a == other._a
```

entonces no hay ningún problema.
La idea de la encapsulación es para evitar que accedan a esos atributos desde _afuera_ de la clase, pero los métodos internos a ella no debiesen causar problema.
Si deseas utilizar esos atributos desde otro lugar que no sea `class A`, entonces sí deberías crear un property o bien no dejarlo como atributo privado.
Saludos!

**Comment by lopezjurip** [comment]
Fuera de Python y de su 'pseudo-privado' (lo que declaras con `_`). Dentro de una clase puedes usar atributos privados de instancias de la misma clase. 

Por ejemplo en Java, declaro la clase `Persona`:

``` java
public class Persona {
    private String nombre; // es privado, en python lo hacemos con '_'

    public Persona(String nombre) {
        this.nombre = nombre;
    }

    public boolean seLlamanIgual(Persona otro) {
        // Ojo que aquí estoy usando el atributo 'nombre' de 'otro'.
        // aunque sea privado.
        return this.nombre.equals(otro.nombre);
    }
}
```

Pero por fuera de la clase, yo no puedo usar el atributo `nombre` porque es privado.

``` java
public class untitled {
    public static void main(String[] args) {
        Persona persona = new Persona("Patricio");
        Persona otro = new Persona("Patricio");
        System.out.println(persona.seLlamanIgual(otro)); // true

        // El programa no compila si uso esta linea.
        // System.out.print(persona.nombre); 
    }
}

```

**Comment by otro-felipe** [comment]
ojo que en Python los atributos """privados""" se declaran con dos guines bajos:

``` python
class A:
    def __init___(self):
        self._no_es_privado = "no_'privado'"
        self.__si_es_privado = "'privado'"
```

es solo que un guion bajo sugiere la idea de que el atributo **debería** ser privado, pero no hace engorroso su acceso en caso de necesitarlo (no como el ejemplo que dio @mrpatiwi ya que en Java lo privado es privado y nadie mas que la clase tiene acceso a ese atributo).

Con respecto a tu pregunta la annotation property en python podría ser usada en conjunto con una variable privada para otorgar acceso de solo lectura a un atributo. Por ejemplo una clase así:

``` python
class Mes:
    def __init___(self, nombre):
        self.__nombre = nombre
        if nombre in meses_de_31_dias:
            self.__dias = 31
        elif nombre in meses_de_30_dias:
            self.__dias = 30
        elif nombre == "Febrero":
            self.__dias = 28

        @property
        def nombre(self):
            return self.__nombre

        @nombre.setter
        def nombre(self, nombre):
            self.__nombre = nombre
            if nombre in meses_de_31_dias:
                self.__dias = 31
            elif nombre in meses_de_30_dias:
                self.__dias = 30
            elif nombre == "Febrero":
                # En un mundo sin años bisiestos...
                self.__dias = 28

        @property
        def dias(self):
            return self.__dias

```

Nota: Como recomendación siempre que trabajes con properties en python la idea es que uses atributos privados por debajo de ellos al igual como se haría en Java con getters y setters.

En tu caso es perfectamente razonable (y yo me arriesgaría a decir que es una buena práctica) que quieras usar property para hacer que el atributo solo pueda leerse y no modificarse.

Como en el ejemplo de arriba, tu puedes pedir `mes.dias`, pero no puedes hacer `mes.dias = 30`.
