### ISSUE TITLE
Atributos no especificados en cursos.txt

### ISSUE THREAD

**Issue by Mdelaf** [IIC2233-2015-2/syllabus#62]
Buenas. Hoy me di cuenta que en el archivo _cursos.txt_ existe un ramo (Ingeniería de Construcción - ICC2304) que tiene dos atributos que no se mencionan en las instrucciones, estos son _hora_terr_ y _sala_terr_. Me parece que es el único ramo que los tiene, ¿debemos considerarlos también? y de ser así, ¿con qué otro tipo de horario pueden topar? 

Edit: Lo mismo con otros dos atributos _hora_tall_ y _sala_tall_ que se encuentran en varios cursos más.

Saludos,
Martín.

**Comment by oatorresuc** [comment]
Hola, gracias a lo comentado por Martín me di cuenta que hay otros
atributos relacionados con las salas de talleres al parecer, ¿que debemos
hacer?, porque si ustedes prueban nuestro programa que venga con otros
atributos en el texto cursos no van a funcionar o debemos prepararlo
incluyendo estos y todos los que encontremos en archivo cursos.txt que
tenemos ahora?

Saludos,
Osvaldo

**Comment by javierlopeza** [comment]
Yo _creo_ que no deberíamos tener que tomar en cuenta esos horarios de taller o atributos que no salen mencionado en el enunciado, porque en el enunciado se menciona que: **el archivo "cursos.txt" puede contener o no, dependiendo del curso**:
- hora_cat
- hora_ayud
- hora_lab
- sala_cat
- sala_ayud
- sala_lab

Pero no sé, eso es lo que dice el enunciado, no menciona que los cursos tengan hora_taller ni sala_taller ni otros atributos.

**Comment by bamavrakis** [comment]
Hola!  
Toda la información de los cursos que no esté considerada en el enunciado debe ser ignorada.
Saludos!

PD: maldito IIE
