### ISSUE TITLE
Guardar instancias de una clase en la misma clase

### ISSUE THREAD

**Issue by benjavides** [IIC2233-2015-2/syllabus#63]
Quiero guardar un diccionario o lista de todos los alumnos, es una mala práctica o no es conveniente hacerlo en la misma clase Alumno() ?

**Comment by lopezjurip** [comment]
¿Algo así?:

``` python
class Alumno:
    lista_alumnos = ...

    def __init__(self, ...):
        # ...
    # ...
```

Sí, sería malo.

**Comment by lopezjurip** [comment]
Conversándolo con @mbucchi, en contextos web se usa algo parecido donde uno consigue los alumnos desde la **base de datos** por medio de un _método de clase_. Pero es para cargarlos, no es que uno los tenga siempre en memoria.

**Comment by andresespinosapc** [comment]
Qué tan malo es? Tan malo como para bajar la nota? jaja Es que ya lo tengo hecho todo así. Y me gustaría saber por qué es malo.

**Comment by lopezjurip** [comment]
Porque es una tarea plenamente orientada a objetos. 

Pregúntate : ¿cómo haría un diagrama de esto? ¿Cómo se relaciona la clase 'alumno' para tener a todos los alumnos? ¿Qué pasa con la memoria de mi computador, si todos los alumnos (incluso los que todavía no se crean) tienen acceso a todos los alumnos? ¿Tengo control sobre esa lista? ¿**Qué pasaría si después tengo alumnos de otra universidad**, se mezclarían, eso es bueno? ... etc, hay muchas razones

**Comment by gebalassa** [comment]
Pero, ¿Cómo se supone que trabajemos con los alumnos si no los podemos guardar dentro del programa en un diccionario? Acaso la idea es parsear el personas.txt y buscar a Juanito Alvarado **cada vez** que necesitemos la información de Juanito Alvarado?

EDIT: Ahora veo que la duda es si debe ser dentro o no de una clase. Sin embargo, no entiendo la diferencia. ¿Qué es mala práctica; usar un diccionario interno con todos los alumnos y su información, o hacerlo dentro de una clase (y por qué?)?

**Comment by aaossa** [comment]
El problema esta en el modelamiento y en la velocidad que tendrá tu programa. Piensa esto, tu quieres conocer tus ramos y los días de sus pruebas, pero te interesa saber los nombres de todos los alumnos debla uc? Es necesario que todos sepamos los nombres de todos? Esto se puede modelar de otra forma.

Piensa que tengo una clase Auto y un diccionario de patentes. Conviene tener los datos centralizados en alguna parte (digamos que la clase Registro Civil o una lista por ejemplo), pero no tienes que guardar los datos en cada instancia de Auto.

La mala practica (y eficiencia) esta en darle a cada instancia datos que no le interesan ni le corresponden por modelamiento.

**Comment by lopezjurip** [comment]
Está bien que los guardes (hay mejores soluciones pero para esta tarea está bien). El tema es: **¿Dónde los guardas?**. 

Creo que debes buscar más información sobre las diferencias entre **variables de instancia** y **variables de clase**.

**Comment by gebalassa** [comment]
En el pseudo-código que pusiste definiste la lista (o diccionario) como una variable perteneciente a la clase **en su totalidad**. O sea que las instancias de esa clase la comparten, pero eso no significa que cada instancia tenga una copia entera de la lista/diccionario. No entiendo por qué dices que cada instancia tendrá una lista propia.

Entonces, según yo, da lo mismo si los colocas dentro o fuera de la clase. No me queda claro por qué es mala práctica, si al final te quedas con una sola copia.

**Comment by vjmoreno** [comment]
Lo que le entendí a Patricio es que es una mala práctica debido a que cada alumno no necesita saber los datos del resto. Esto obviamente tiene repercusiones en la eficiencia de tu programa debido a que estas guardando una mayor cantidad de datos dentro de cada objeto alumno.

**Comment by gebalassa** [comment]
@vjmoreno Se supone que eso no es cierto ya que está definiendo la lista dentro de la clase, y por tanto se comparte entre los alumnos, no es que se copie cada vez que se instancie un alumno. A eso me refería yo. No entiendo por qué sería una mala práctica. Es una lista, **no** una self.lista.

**Comment by otro-felipe** [comment]
Es una mala práctica. Imaginalo de esta forma, quieres modelar una fábrica de autos y tienes tu clase auto con todas las cosas que esta pueda tener. Ahora, ¿Dónde guardas los autos de la fábrica? Uno podría pensar que guardarlos en la clase Auto es lo mejor, pero eso limita bastante tu código. ¿Qué pasa si se abre otra fábrica? ¿Usarás dos variables `Auto.autos_fabrica_uno` y `Auto.autos_fabrica_dos`? ¿Qué pasa si hay n fábricas?. Para no tener que lidiar con eso y hacer el código más flexible y entendible lo mejor es que guardes los autos a la entidad que le interesa saber cuantos autos tiene. Esta entidad sería una clase `Fabrica`. Aun si lo único que hace es guardar una lista con los autos que tiene, es mejor guardar los autos ahí, pues podría llegar otro programador y hacer un "mod" de tu programa y darle alguna utilidad a esas fábricas, y para él será mucho más fácil (ese programador podrías ser tu en el futuro). Por eso no es buena idea que guardes instancias de tu clase dentro de ella, porque siempre estos objetos básicos están contenidos dentro de una estructura más amplia.

**Comment by gebalassa** [comment]
Ah, muy cierto. Sin embargo, en términos de memoria, guardar el diccionario de alumnos globalmente, dentro de la clase "Alumno", o dentro de una clase "Universidad", debiese ser lo mismo, ¿No? Por definir la lista dentro de la clase no se está copiando para cada alumno.

Eso pues. Quería saber si estaba permitido. No creo que en este caso haga mucha diferencia crear una clase "Universidad" que incluya la lista de alumnos, o por lo menos no se me ocurre.

**Comment by otro-felipe** [comment]
en términos de memoria yo supongo que `Alumno.alumnos` o `Universidad.alumnos` debiese ser lo mismo, solo que una forma es mejor práctica que otra, solo al leerlas te das cuenta de que `Alumno.alumnos` hace muy poco sentido. Una pequeña aclaración: No son variables globales, son variables estáticas (las variables globales aveces también son una mala práctica).

Si está permitido guardar los alumnos dentro de la clase Alumno no sé (probablemente descuenten, yo no soy la persona adecuada para responder eso). Ahí tendrás que ver tú dónde almacenas los alumnos dependiendo de cómo hayas modelado el tarea.

Saludos! :)

**Comment by gebalassa** [comment]
Por variables globales me refería a definirla fuera de cualquier clase (o la clase que representa todo el programa).

Muchas gracias por tu análisis y respuesta :smiley:

**Comment by vjmoreno** [comment]
@gebalassa Tienes razon, no me fije en ese pequeño gran detalle.

**Comment by otro-felipe** [comment]
De nada, gabriel.

Espero haberte sido de ayuda y mucha suerte con la tarea :)

**Comment by fgvenegas** [comment]
Que pasa si yo creo una lista al comienzo del programa con todos los alumnos (como objetos) y trabajo despues con esta ? esta creacion la hace una clase especial que tengo y no la Clase Alumnos

**Comment by lopezjurip** [comment]
Hay muchas maneras de modelar un problema y aún más en Python donde puedes declarar cualquier cosa en cualquier parte. En lenguajes más formales no tienes tanta libertad. 

Busquen la manera que haga más sentido, que ordene de manera más natural su proyecto, que les facilite el desarrollo de los requerimientos y de la manera más elegante posible.
