### ISSUE TITLE
Bummer & Pacmatico

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#64]
Para la entrega de los dos sistemas de toma de ramos que se piden, ¿debemos entregarlos algo así como en carpetas separadas dentro de T01?
¿Como esto?:

```
>T01
   >bummer
      >archivos.py
      >...
   >pacmatico
      >archivos.py
      >...
```

**Comment by bamavrakis** [comment]
Hola!!

Esto no es necesario, pero si deseas hacerlo (para tener mas ordenada tu tarea) no hay problema, siempre y cuando lo especifiques en el README.

Saludos!

**Comment by javierlopeza** [comment]
Gracias!
