### ISSUE TITLE
Créditos mínimos y máximos permitidos

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#65]
En el enunciado, 4.2, al conectarse como alumno e intentar inscribir un ramo dice que se debe considerar los créditos mínimos y máximos permitidos. El caso de los créditos máximos se entiende perfectamente que no se deben sobrepasar, pero se señala también que _la cantidad mínima que puede tomar un alumno es de 30_. ¿Se supone que debemos hacer algo con la cantidad mínima de créditos? ¿Algo así como que cuando el usuario intente salir del sistema le advierta que esta tomando menos de 30 créditos? ¿O no hacemos nada con eso?
(Pienso en Banner real que no le importaba que tomaramos menos de 30)

**Comment by mbucchi** [comment]
Varios de los aspectos del sistema quedan a tu criterio, lo que importa es que tengan sentido y que los expliques brevemente en tu `README.md`. No dejarlo salir es un opción, o bien darle una advertencia antes de que salga, dentro de varias otras posibilidades.
Saludos!
