### ISSUE TITLE
Sobre pacmá̶n̶tico

### ISSUE THREAD

**Issue by sitoro** [IIC2233-2015-2/syllabus#66]
Pacmatico y bummer deben ser dos archivos ejecutables distintos
o el mismo main.py debe dejarnos decidir que sistema iniciaremos
o si es de otro modo, como se supone que es? O.o

**Comment by felipehv** [comment]
Segun yo deberia ser como quieras, por eso hau que hacer el Readme.md para
explicar el funcionamiento.

Felipe Haase Vargas
Estudiante de  Ingenieria
Pontificia Universidad Católica de Chile

**Comment by aaossa** [comment]
Quizás #64  te dé un punto de partida. Puedes mantener esta issue abierta si quieres que te responda algún tareo.

**Comment by vabesa** [comment]
Todo lo que no este especificado en el enunciado puedes dejarlo a tu criterio, pero debe ser especificado en el Readme.
