### ISSUE TITLE
Sobre instanciar

### ISSUE THREAD

**Issue by AlainLotissier** [IIC2233-2015-2/syllabus#67]
Hola. Quería saber si es posible usar "setattr" para setear atributos a un objeto mas rapidamente. Gracias

**Comment by otro-felipe** [comment]
setattr es un método reflexivo, es bastante más ineficiente que setear los atributos de un objeto de manera común y corriente. IMHO setattr solo debe ser usado en caso de extrema necesidad.

**Comment by mbucchi** [comment]
@AlainLotissier, existen varios contextos en los que es útil usar  `setattr`, no obstante, dudo que esta tarea sea uno de aquellos. Si lo estás utilizando para modificar los objetos una vez que ya están instanciados, probablemente tienes un problema con tu modelo inicial (repito, en el contexto de esta tarea). Vuelve a la raíz de esos objetos y redefine la instanciación y el comportamiento de aquella clase para que no sea necesario el uso de `setattr`. 

Saludos!
