### ISSUE TITLE
Tiempo en cargar datos

### ISSUE THREAD

**Issue by javierlopeza** [IIC2233-2015-2/syllabus#68]
¿Es malo que al iniciar el programa se demore como tres minutos en dejar todos los datos preparados para poder usar la interfaz del programa? Es en lo único en lo que presento demoras porque uso varias iteraciones para preparar datos de la bacanosidad de los alumnos.

**Comment by mbucchi** [comment]
Parte de la evaluación considera la eficiencia del código, por lo que las demoras de esta magnitud sí son malas :disappointed: . Intenta depurar tu código y tus algoritmos, de seguro posees unos cuantos ciclos que son innecesarios.
Saludos!

**Comment by javierlopeza** [comment]
¡Perfecto! Es que ahora con la publicación del _.pdf_ de _bacanosidad_ que dice que podamos crear un _.txt_ con las _bacanosidades_ y usar ese archivo, evito ese tiempo al principio. Gracias!

**Comment by flobarrios** [comment]
Ademas de el txt que se puede guardar de la bacanosidad relativa, puedo
ademas guardar un archivo con el numero que se le asigna a cada alumno,
para simplemente cargar eso y ahorrar tiempo (obviamente con un archivo .py
que demuestre que si se realizo)? :)

**Comment by flobarrios** [comment]
*el numero de grupo de bummer
