### ISSUE TITLE
Consulta fecha evaluaciones Tarea 1

### ISSUE THREAD

**Issue by fagomez2** [IIC2233-2015-2/syllabus#69]
Hola. Hay algunas fechas de evaluaciones del tipo:
"fecha": "26/11 - NA"
Supongo que para todos los efectos esta evaluación no está incluida en ningún cálculo de topes de horario, pero me gustaría saber si hay alguna consideración oficial para este tema o si simplemente queda a criterio de cada uno.

**Comment by mbucchi** [comment]
Tal como se ha nombrado en varios issues anteriormente, varias de las funcionalidades de sus sistemas quedarán a su criterio. Lo importante es que las decisiones tengan sentido y las especifiquen en el `README.md`. 

Saludos!
