### ISSUE TITLE
Problema en instalacion PyQt4 en Mac OSX

### ISSUE THREAD

**Issue by silvamatias** [IIC2233-2015-2/syllabus#7]
Hola, tengo un problema con la instalacion del PyQt4. Lo instalo en el Iterm2 como se muestra en la figura 
<img width="308" alt="screen shot 2015-08-13 at 2 10 55 am" src="https://cloud.githubusercontent.com/assets/13739643/9243000/c34122dc-4160-11e5-8694-a9026845ba28.png">

Pero luego abro python para ver que este bien instalado y me tira el siguiente error:

<img width="788" alt="screen shot 2015-08-13 at 2 10 30 am" src="https://cloud.githubusercontent.com/assets/13739643/9243005/d40f91d4-4160-11e5-9092-7394d41f2e21.png">

Alguien sabe que es, le paso lo mismo o sabe arreglarlo? Gracias

**Comment by lopezjurip** [comment]
Me sale el mis error, lo estoy solucionando y actualizo la guía. Avisaré por aquí

**Comment by lopezjurip** [comment]
Actualizada la guía: https://github.com/IIC2233-2015-2/syllabus/wiki/Mac-OSX#pyqt-4

**Comment by silvamatias** [comment]
Segui la nueva guia y utilice los nuevos comandos pero me tira el mismo error al ejecutar el import en python y en el iterm me sale esto:

<img width="683" alt="screen shot 2015-08-13 at 12 32 05 pm" src="https://cloud.githubusercontent.com/assets/13739643/9254010/791b75e8-41b7-11e5-8a69-b3ea1e34a1fb.png">

Que hago? Muchas gracias

**Comment by lopezjurip** [comment]
Cómo instalaste `python3`? 
Ejecuta `which python3`, si lo instalaste con Homebrew debería salir: `/usr/local/bin/python3`

O estás usando OSX _El Capitan_? Porque parece que hay problemas con Python ahí

**Comment by silvamatias** [comment]
Lo desintale y seguí la guía paso a paso

**Comment by silvamatias** [comment]
Al ejecutar which python3 sale esto:

<img width="455" alt="screen shot 2015-08-13 at 6 32 34 pm" src="https://cloud.githubusercontent.com/assets/13739643/9262231/b1f6eaaa-41e9-11e5-8aad-0d34bbf50837.png">

No estoy usando OSX El Capitan aun, que podra ser?

**Comment by lopezjurip** [comment]
Es porque instalaste Python3 de la manera _web_, por decirlo. O sea de la manera manual bajando el instalador de internet. 

Usas esa y te la arreglas para instalar lo restante de la guía o la borras bien borrada y partes la guía de nuevo

**Comment by silvamatias** [comment]
De que manera puedo borrarlo bien borrado? dado que ya lo habia hecho!

**Comment by lopezjurip** [comment]
Entonces tienes un problema con el `PATH`. 

Si haces:

``` sh
echo $PATH
```

En alguna parte te saldrá la ruta que apunte a `Library/Framworks/.../python3`. Vas a tener que buscar una manera de solucionar eso.

**Comment by aaossa** [comment]
@silvamatias, si aún tienes este problema puedes reabrir esta issue :+1:

**Comment by dpassi** [comment]
Hola, yo estoy con problemas tambien!

Segui los pasos de la guia y no avanza despues que arroja un comando 
'make'

Pd: Estoy con OS El Capitan

**Comment by dpassi** [comment]
@mrpatiwi creo poder saber que puede ser,
con brew install python3 ahora se está instalando python 3.5, quizas al intentar instalar pyqt hay conflictos...

Hay alguna forma de bajar python3.4 espeficicamente con comando brew? busque y no encontré mucho,

Gracias!

**Comment by lopezjurip** [comment]
### Se me ocurre esto, pero es muy _hacky_ y no lo he probado:

> Solo para Mac OSX

Borra la instalación actual de `python3` y pyqt (si es que está presente):

``` sh
$ brew uninstall pyqt4
$ brew uninstall python3
```

Bajamos la _formula_ antigua de `brew` que instala `python3.4` y la guardamos con las demás formulas. Llamémosla `python34`:

``` sh
$ curl -o /usr/local/Library/Formula/python34.rb https://raw.githubusercontent.com/Homebrew/homebrew/7d8b04c417d16f320680c58d0eb335cafd881849/Library/Formula/python3.rb
```

Instalamos `python34`:

``` sh
$ brew install --debug python34.rb
```

Revisamos si está todo ok:

``` sh
$ python3 --version
```

Ahora deberías poder instalar pyqt.

**Comment by dpassi** [comment]
Me funcionó,
Gracias!
