### ISSUE TITLE
Bacanosidad (Nuevamente)

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#71]
¿Mis archivo de bacanosidad tiene que seguir fielmente el archivo subido por ustedes? Debido a que para calcular la bacanosidad cada uno puede haberle asignado distinto "peso" a los seguidores y a los seguidores de los seguidores y así, por lo lo que podrían dar diferentes resultados dependiendo de los  criterios de transmisión de bacanosidad que uno pueda tener o haber pensado, por esto mismo ¿Está bien si mi archivo difiere del de ustedes siempre y cuando explicite en el readme cómo se calculó la bacanosidad?

**Comment by mbucchi** [comment]
Si tu método cumple correctamente con el ejercicio planteado en el pdf _(puntos entregados = puntos recibidos)_, entonces no debiese haber ningún problema :smiley:.
Saludos!
