### ISSUE TITLE
Bacanosidad de punto flotante

### ISSUE THREAD

**Issue by amartini93** [IIC2233-2015-2/syllabus#72]
El punto flotante en computadores siempre es complicado de usar... cuando termino de calcular la bacanosidad, algunos de los resultados difieren en unos cuantos decimales, tengo que intentar hacerlo más preciso? o puedo despreocuparme de que los resultados sean exactos?

**Comment by mbucchi** [comment]
Despreocupate de la exactitud pasado unos cuantos decimales. Lo importante es que sea suficientemente preciso para poder diferenciar claramente a todos los alumnos entre ellos. Para eso (en la bacanosidad relativa) te debiesen bastar unos 8 puntos decimales. Saludos!

**Comment by amartini93** [comment]
Gracias!
