### ISSUE TITLE
duda archivo bacanosidad

### ISSUE THREAD

**Issue by fgvenegas** [IIC2233-2015-2/syllabus#73]
El archivo .txt que nos entregaron es un ejemplo de como deberia quedarnos o son los bacanosi-puntos que aporta cada alumno? 
Y lo otro, en el pdf dice que podemos calcular la bacanosidad y guardarla para no calcularla cada vez, pero en el Readme dice que siempre debe pedir calcular la bacanosidad y ahi me confundi

**Comment by mbucchi** [comment]
El archivo es un ejemplo de cómo se debiesen ver las bacanosidades relativas. Además les sirve para seguir avanzando con la tarea en caso de que no pudiesen calcularla ustedes mismos.
En cuanto a lo segundo, la idea es que no tengas que calcularla cada vez que inicias tu sistema (y así ahorrar tiempo). Por lo mismo puedes calcularla y dejarla en un .txt que podrás cargar cada vez que inicies tu sistema. Sin embargo, debido a que la corrección se hace con otros archivos, es **necesario** que tu sistema de la opción de generar ese archivo en cualquier momento, así el corrector podrá generar la bacanosidad correspondiente a los nuevos archivos. Se entiende mejor?
Saludos!

**Comment by fgvenegas** [comment]
si gracias!

**Comment by flobarrios** [comment]
El txt que generemos debe tener los mismos valores de bacanosidad relativa
o pueden variar un poco (siempre y cuando la correccion funcione)?
