### ISSUE TITLE
datos de cursos.txt

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#74]
Hola, ¿los datos de "apr" y "retiro" deben ser considerados?

Pregunto porque nunca entendi su función en el buscacursos, ¿si un curso sí necesita "apr" tengo que modelar esa solicitud de aprobacion al profesor? ¿Si el curso no permite retiro el sistema debe tirar un error si el alumno intenta borrarlo o si el profesor elimina a un alumno?

**Comment by bamavrakis** [comment]
Hola!
Queda a tu criterio si los consideras o no. Cualquier cosa que asumas y que no esté explícito en el enunciado debes indicarlo en el README.

Saludos.

**Comment by tamycova** [comment]
Gracias!
