### ISSUE TITLE
¿Se puede usar el módulo getpass de la librería estándar?

### ISSUE THREAD

**Issue by jgmontoya** [IIC2233-2015-2/syllabus#75]

**Comment by bamavrakis** [comment]
Hola!
No, ese módulo no puede ser utilizado para la realización de la tarea!

Saludos.

**Comment by jgmontoya** [comment]
¿Pedimos la clave al usuario mediante un simple _input()_  entonces?

**Comment by bamavrakis** [comment]
Queda a tu criterio, siempre y cuando lo especifiques en el README, pero sin utilizar el módulo getpass.

Saludos.
