### ISSUE TITLE
#comentarios

### ISSUE THREAD

**Issue by tamycova** [IIC2233-2015-2/syllabus#78]
¿Es buena practica comentar el código en la tarea? Para así facilitarle la tarea al ayudante, ¿existe algun formato? (como pdoc por ejemplo)

**Comment by lopezjurip** [comment]
Claro qué si :)

Dado que PyCharm prefiere la convención `reST`, creo que lo mejor sería respetar esa. https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format

A modo de ejemplo:

``` python
def send_message(user, message, private=False):
    """
    Send a text message (private or not) to an user through websocket.
    :param user: User instance target.
    :param message: Text content of the message.
    :param private: Message should be private or not (default: False)
    :return: boolean indicating success or failure. 
    """
    id = user.id
    m = process(message, 'utf-8')
    # ...
    return True
```

**Comment by tamycova** [comment]
Gracias!
