### ISSUE TITLE
Guardar cambios

### ISSUE THREAD

**Issue by ouhenio** [IIC2233-2015-2/syllabus#79]
¿Nuestro programa debe ser capaz de recordar las acciones realizadas por los usuarios? ¿Si se toma un curso, la proxima vez que ejecute el programa tiene que haber un cupo menos en él?

**Comment by robocop6** [comment]
Hola,
revisa esta issue #38
SPOILER ALERT: no deben modificar los archivos.

**Comment by gebalassa** [comment]
@robocop6 

1) La pregunta se refiere, probablemente, a si se deben almacenar los cambios, de alguna forma, una vez cerrado el programa. O sea, si como alumno tomo ciertos ramos y después cierro el Shell, **¿Debe guardarse, de alguna forma, lo que hizo el alumno?** ¿O se asume que todo el programa y la gente existen sólo dentro del Shell?

2) ¿Se puede asumir que los comandos que intentarán ingresar **son correctos**? No me refiero a que el sistema te alerte si no quedan cupos, me refiero a que si intentan ingresar "fdshgxcfghxhg" como comando durante la corrección (la diferencia siendo que lo primero es lógico considerando el enunciado, mientras que el segundo es un intento explícito de hacer caer el sistema).

**Comment by robocop6** [comment]
Hola!

1) No es necesario guardar ningún tipo de información, puedes suponer que todos los cambios solo existen en durante ejecución del programa.

2) **No** puedes suponer que el usuario ingresará un input correcto. El programa no debe caerse bajo ninguna circunstancia.

Saludos!
