### ISSUE TITLE
Problema al leer 'cursos.txt'

### ISSUE THREAD

**Issue by ivanwolf** [IIC2233-2015-2/syllabus#80]
Tengo un problema al leer las letras que tienen tilde como 'Á' y esto me pasa solo con el texto 'cursos.txt',
Mi porción de código es:

``` python
with open('cursos.txt', 'r', encoding='utf-8') as file:
    lista = file.readlines()
    for i in lista:
        print(i) 
```

Y el error que me arroja es:

```
Traceback (most recent call last):
  File "/home/ivanwolf/ivanwolf15-repo/Tareas/T01/asd.py", line 4, in <module>
    print(i)
UnicodeEncodeError: 'ascii' codec can't encode character '\xc1' in position 14: ordinal not in range(128)
```

Tengo la idea de quitarle los acentos a las palabras, pero quisiera encontrar otra solución.
Cualquier idea es bienvenida.
Saludos

EDIT: mi SO es ubuntu 14.04

**Comment by otro-felipe** [comment]
El problema está en el print, es decir que la consola está teniendo problemas al interpretar el caracter (yo supongo) Si estás usando pycharm, tienes que especificar en la taskbar (la barrita de abajo) el tipo de encoding que vas a usar. (Por defecto creo que está en windows-1252 en mi caso). Espero que ese sea el problema y lo puedas solucionar.
Saludos.

**Comment by cfvilla** [comment]
estoy teniendo el mismo problema, y no me cambia nada alcambiar a windows-1252

EDIT: lo pude arreglar cargando el archivo asi:
 archi = open(archivo,'r',encoding="utf8")  (antes lo estaba cargando sin indicar encoding)

**Comment by lopezjurip** [comment]
Prueba con `with open('cursos.txt', 'r', encoding='utf8') as file:`
(sin guión en el _utf8_ del `encoding`).

**Comment by ivanwolf** [comment]
Ya probé eso y no funcionó.
Sin embargo, pude solucionar el problema cambiando el project encoding a utf-8 en pycharm.

**Comment by lopezjurip** [comment]
Creo que también funciona agregando:

``` python
# coding=utf-8
```

Al inicio de los archivos.

**Comment by icrocco** [comment]
Al tratar de leer ese mismo archivo me arroja el sgte. error:

```
Traceback (most recent call last):
  File "C:/Users/Ignacio/Desktop/syllabus/Tareas/T01/leyendo_general.py", line 15, in <module>
    for line in f.readlines():
  File "C:\tools\python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 76: character maps to <undefined>

```

Pasa lo mismo si pruebo con otras formas de read como splitlines ¿qué puedo hacer? :(

**Comment by lopezjurip** [comment]
Pero busquen en internet, no son la primera persona con ese problema en el mundo
http://lmgtfy.com/?q=UnicodeDecodeError%3A+charmap+codec+can%27t+decode+byte

**Comment by silvamatias** [comment]
por si alguien sigue con ese error, yo lo solucione con el siguiente encoding:

<img width="152" alt="screen shot 2015-08-30 at 11 45 16 pm" src="https://cloud.githubusercontent.com/assets/13739643/9571270/5c9d636e-4f71-11e5-8e5f-7423c187001d.png">

**Comment by gebalassa** [comment]
Usaré el encoding de ISO, ¡Gracias! Prefiero eso a dejarlo sin encoding.

**Comment by antarescor** [comment]
> 
> 
> estoy teniendo el mismo problema, y no me cambia nada alcambiar a windows-1252
> 
> EDIT: lo pude arreglar cargando el archivo asi:
> archi = open(archivo,'r',encoding="utf8") (antes lo estaba cargando sin indicar encoding)

Por dios eso si me funciono llevaba horas buscando
