### ISSUE TITLE
Problema Git

### ISSUE THREAD

**Issue by Zepk** [IIC2233-2015-2/syllabus#81]
Tengo un problema intentando subir nuevas actualizaciones a mi repositorio privado, resulta que en algun momento, guarde dentro de mi repositorio un archivo en mi repositorio, luego, mas adelante, hice el clásico procedimiento para subir los cambios a mi repositorio, pero no fue posible, ya que git no deja subir archivos mayores a 100 megas, y ese archivo lo era.

Luego simplemente borre el archivo, e intente actualizarlo nuevamente, pero aun me sigue diciendo que no me aceptara el push, porque contiene archvos mayores a 100 megas, tambien intente usando el comando git reset, pero tampoco funciono.

Como hago para poder hacer push nuevamente?

**Comment by lopezjurip** [comment]
hace `git status` y ve si está _staged_ (o sea, aparece en la lista de archivos listos para ser commiteados).

O revisa los commits locales si es que en alguno agregaste ese archivo con `git log` o busca en internet comandos más especializados.

**Comment by lopezjurip** [comment]
No suban archivos muy grandes, si llego a detectar uno simplemente lo borraré de sus repositorios porque dificultan el proceso de recolección (y los podemos penalizar).
 ( ͠° ͟ʖ ͡°)

**Comment by Zepk** [comment]
Problema solucionado, utilizando los siguientes comandos:
git checkout -- \* 
git reset --soft HEAD~1

Eh, el archivo ese era una tabla excel de otro ramo, que se me traspapelo y termino en la carpeta del repositorio por error.
