### ISSUE TITLE
Requisitos complicadosos

### ISSUE THREAD

**Issue by orrios** [IIC2233-2015-2/syllabus#82]
Hola!
Viendo el tema de la restriccion de requisitos me topé con el curso ICM2323 que tiene como prerrequisitos:
"prerreq": "(ICM2303 o ICE2313 o ICM2028) y (ICM2313 o (ICE1302 y ICM1122 y ING1011) o (ICE1302 y ICM1122 y IPP1000))"

lo encuentro un poco raro.

Se puede decir que:
todos los otros prerrequisitos son del tipo
(a y b y c) o (d y e y f) o (g y h y i)...
o del tipo 
(a o b o c) y (d o e o f) y (g o h o i)...

excepto este que es

(a o b o c) y (a o (a y b y c)) o (a y b y c)

estan estos prerrequisitos bien asignados?

EDIT: correcion errores de tipeo

**Comment by dpassi** [comment]
Yo no me preocuparia si son complicados o no, te recomiendo hacer un replace de los 'o' por 'or' y os 'y' por 'and' y luego el computador se preocupara del resto de la valuacion.

**Comment by mbucchi** [comment]
@orrios, todos los prerrequisitos son los verdaderos obtenidos del catálogo de cursos. @djpassi te da una muy buena idea de cómo enfrentarlo.
Saludos!

**Comment by trencoret** [comment]
@djpassi  te la hubierai soltado antes esa.. jaja la hice a mano. Llevo dos dias haciendome amigo de las diferentes posibilidades

**Comment by tamycova** [comment]
Pero si hacemos ese replace tendriamos que usar eval? y no esta permitido

**Comment by mbucchi** [comment]
@tamycova efectivamente, si usas replace nada más tendrías que usar eval, lo cual está **prohibido**. Pero no deja de ser cierto lo que dice @djpassi, partiendo de ese supuesto se te hace mucho más fácil el análisis (y la creación del código necesario para evaluar los requisitos). Saludos!
