### ISSUE TITLE
Duda librerias

### ISSUE THREAD

**Issue by oatorresuc** [IIC2233-2015-2/syllabus#83]
Hola, se puede usar la libreria copy y la libreria operator?

**Comment by aaossa** [comment]
La librería **copy** no se puede utilizar como dijeron en #76. Sobre **operator** espera a que te responda un tareo.

**Comment by oatorresuc** [comment]
gracias, perdón por preguntar algo que ya estaba respondido

**Comment by oatorresuc** [comment]
si diccio = dict(), puedo utilizar diccio.clear() ?
