### ISSUE TITLE
Pacmático

### ISSUE THREAD

**Issue by ralvarez94** [IIC2233-2015-2/syllabus#84]
Hola, respecto a la parte del pacmático, me quedan las siguientes dudas:
1) ¿El programa debiese prohibir tomar un ramo si es que el alumno no cumple con los requisitos? ¿O eso queda a criterio nuestro?
2) ¿Podrían especificar un poco cómo funciona la asignación de vacantes cuando uno pide un ramo cuyo correquisito también se está solicitando? Ejemplo: El ramo A tiene correquisito el ramo B, y el alumno está pidiendo A y B.  Por lo menos yo no me acuerdo bien qué pasaba en esos casos en la época de Pucmático.

**Comment by bamavrakis** [comment]
Hola!
El control de requisitos y co-requisitos se aplica antes de asignar las vacantes y después de la redistribución de puntos por parte de los alumnos. Por lo tanto, los alumnos pueden seleccionar ramos y redistribuir puntos entre ellos aún si no cumplen con los requisitos y co-requisitos de éstos. Luego, tu programa al otorgar los cursos entre los alumnos, debe ser capaz de controlar los pre-requisitos:

1- Un alumno que no cumple con el requisito del curso A, puede seleccionarlo y apostarle puntos, pero no se le dará ese curso.
2- Si el ramo A tiene como co-requisito el ramo B, y el alumno pide los dos. Solo se le dará el curso A al alumno si es que el sistema le da el curso B al alumno (y obviamente si la cantidad de puntos apostados a A se lo permiten).

Espero que te haya aclarado tu duda,
Saludos!

**Comment by ralvarez94** [comment]
Gracias @bamavrakis !
