### ISSUE TITLE
Archivo Evaluaciones

### ISSUE THREAD

**Issue by estebanmino** [IIC2233-2015-2/syllabus#85]
Hola! Una duda super puntual, en este archivo no existen las evaluaciones de algunos ramos como por ejemplo MAT1610 o QUI100A (de hecho son casi solo ramos de Ingeniería). Con esto no podría generar el calendario de pruebas para los otros cursos. Que hacemos en estos casos?

**Comment by mbucchi** [comment]
Si no existen los datos, no te preocupes. Lo importante es que tu sistema sea capaz de manejar los datos que _sí_ existen en los archivos. En cuanto a qué hacer con el calendario y cómo informar esto al usuario, eso queda a tú criterio, pero recuerda explicarlo brevemente en el _readme_. Saludos!
