### ISSUE TITLE
Paquetes Matemàticos (Matrices)

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#86]
Al probar con grupos pequeños de gente (en papel) llego generalmente a un punto donde, al pedir el cálculo de "bacanosidad" de una persona "C", el programa necesita la "bacanosidad" de "A" (pues sigue a C) cuando esta también depende de C (pues C sigue a A). Esto mismo se puede enredar muchas veces más en grupos grandes.

En ese caso lo único que se me ocurre es que al llegar a estas situaciones se deje el cálculo de la bacanosidad de "A" (o "C", o cualquiera dependiendo de quien sea llamado antes por **segunda vez**) en **STANDBY**, se termine con todos aquellos que falta llamar por **primera vez** y ya terminado este proceso resolverlo como matriz, ya que me queda un sistema de ecuaciones.

No sé si usar paquetes de matrices está permitido, o si no tiene sentido lo que digo, pero es lo único que se me ocurre.

Help!

**Comment by mbucchi** [comment]
Hola! Tienes permitido usar el paquete Numpy, el cual permite el manejo de matrices. Saludos!
