### ISSUE TITLE
"(unicodeerror) "unicodeescape" codec can't decode... " [código]

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2015-2/syllabus#87]
![error 1](https://cloud.githubusercontent.com/assets/11603889/9564222/6678a3da-4e6d-11e5-8339-46c1d46062ea.png)

La única línea de código que tenía era:

```
a = open("C:\Users\Gabriel\Desktop\prueba python modulos\banana.txt","r")
```

Donde "banana" es un texto de prueba con dos líneas:
- banana
- manzana

Ya probé agregando al principio 

```
 -*- coding: utf-8 -*-
```

No sirvió de nada. 

Ayuda porfa, antes podía abrir archivos sin ningún problema :(

**Comment by lopezjurip** [comment]
``` python
a = open("C:\Users\Gabriel\Desktop\prueba python modulos\banana.txt","r", encoding="utf8")
```

En #80 lo estabamos discutiendo

**Comment by jgmontoya** [comment]
¿En verdad era necesario abrir una issue para [esto](http://goo.gl/CO0O4R) ?

La primera página de la búsqueda indica el problema...

**Comment by gebalassa** [comment]
La primera página de búsqueda dice que coloque doble slash para evitar que \U actúe como escape. Nunca antes había tenido que corregir una dirección al usar Open.
Además, # coding=utf-8 no sirve.

~~Busco una solución que asuma que todo el código esta en utf-8.~~

Edit: Voy a probar el backslash doble, o sino el "r" de Raw. Nunca había tenido que hacerlo por lo que me parece raro.

Edit2: En cualquier caso,

```
a = open("C:\Users\Gabriel\Desktop\prueba python modulos\banana.txt","r", encoding="utf8") 
```

no funciona. Tira el mismo error.

**Comment by aaossa** [comment]
Las _issues_ son para preguntar y para responder están los ayudantes, si no fuese así nos quedamos todos en nuestras casas y listo. Está bien, hay que **buscar por cuenta propia** también, pero uno de los requisitos informales del curso es aprender a usar Google para buscar recursos y recién estamos empezando. Así que un poquito más de paciencia @jgmontoya. La idea es que a medida que vayamos avanzando en el curso nos encontremos con menos preguntas del tipo `tengo un error`, `en qué me equivoqué`, pues sabrán buscar soluciones por su cuenta (cuando programen fuera del curso no tendrán a los ayudantes), pero siempre pueden preguntar y con mayor razón si ya han intentado lo que encuentran "googleando" o no encuentran alguna respuesta.

**RESUMEN**: Lo que queremos es que pregunten, pero solo después de que hayan analizado su problema, pensado soluciones y buscado suficiente como para determinar que necesitan ayuda. Así se preparan mejor para cuando programen más allá del curso :grin:

**Volviendo a la issue.** Otra cosa que podría ser es el uso de `\` (_backslash_) en lugar de `/` (_slash_), pues como acaba de decir @gebalassa `\` indica caracter de escape. Por cierto, creo que en Python para las paths puedes usar simplemente `/`.  

Sugiero:

``` python
a = open(r"C:\Users\Gabriel\Desktop\prueba python modulos\banana.txt","r")
```

La flag `r` indica que el string es un raw string. O sea, le dice a Python "ignora los caracteres de escape" por lo que los backslash son simplemente backslash. Para que lo vean en acción escriban esto:

``` python
print("Hola mundo")
print("Hola mu\ndo")
print(r"Hola mu\ndo") 
```

PS: Para el encoding: lo que dijo @mrpatiwi

**Comment by gebalassa** [comment]
Agregar la "r" para conseguir un raw string fue lo que funcionó. Muchas gracias. :)

Edit: Lo prefiero por sobre el doble backslash y reemplazar los \ por /, aunque probaré igual. Muchas gracias.
