### ISSUE TITLE
Try / Except?

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#88]
Cuando uno le pide inputs al usuario, si el usuario ingresa algo incorrecto (por ej. le pido seccion del curso y él ingresa 'foo') generalmente mi programa tira error a menos que empieze a chequear uno por uno los requisitos que debe cumplir la respuesta, esto es, que la seccion sea un entero, que exista la seccion para este curso, etc. Podría evitar hacer este chequeo cada vez que pida un input si simplemente uso try / except.

¿Es considerado mala practica usar try/except? ¿Hay descuento por usarlo?

**Comment by bamavrakis** [comment]
Hola!
No hay problema en que uses try/except. Habrá descuento si tu programa se cae incluso si usas try/except.
Saludos.

**Comment by Arios16** [comment]
Ok, gracias!
