### ISSUE TITLE
Distribución de puntos - Pacmático

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#89]
¿Puedo quitarle puntos a un ramo y que los demás ganen los puntos repartidos?

**Comment by bamavrakis** [comment]
Hola!
No se si entendí muy bien tu duda, pero la idea es que si decides quitarle puntos a un curso, éstos se repartan entre el resto de los cursos seleccionados: "Ley de conservación de los puntos" (?).
PD: cualquier comportamiento que quieras agregar a la tarea en cualquier ámbito lo puedes hacer, siempre y cuando lo especifiques en el README, y no esté en contra de lo que diga el enunciado.
Saludos!
