### ISSUE TITLE
Pacmatico - Ramos aprobados y sus créditos.

### ISSUE THREAD

**Issue by btkramm** [IIC2233-2015-2/syllabus#90]
Pacmático plantea una fórmula para calcular los puntos que se le asignará a cada persona. Esta fórmula utiliza los créditos aprobados de la persona. Hay personas que en su lista de ramos aprobados tienen ramos que ya no existen. Qué hago.

Otra duda: ¿Qué es exactamente le bacanosidad relativa?

**Comment by robocop6** [comment]
Hola!
La bacanosidad relativa es el cuociente entre la bacanosidad del alumno que está inscribiendo ramos (en bacanosi-puntos o como sea que lo hayas calculado) y la bacanosidad del alumno más bacán de la Univerdidad.

Así, por ejemplo, el alumno más bacán tiene bacanosidad relativa 1 (es su propia bacanosidad, dividida por si misma), y los otros alumnos, tienen bacanosidad menor o igual a 1. Un alumno que tiene bacanosidad relativa 0.5 es la mitad de bacán que el alumno más bacán.

En la carpeta "bacanosidad" está el archivo "bacanosidad.txt" que tiene las bacanosidades relativas de todos los alumnos, para que las revises. Puedes cargar este archivo a tu programa para seguir avanzando con la tarea mientras tanto, pero recuerda se evaluará tu tarea con otros archivos, por lo que tu programa **debe** ofrecer calcular bacanosidad.

Sobre los créditos aprobados de ramos obsoletos, invoco a @mbucchi , @bamavrakis

**Comment by bamavrakis** [comment]
Hola!
Sobre los alumnos con ramos aprobados obsoletos, simplemente ignóralos. 
Saludos!
