### ISSUE TITLE
bacanosidad.txt - ¿Nombres o usuarios?

### ISSUE THREAD

**Issue by otro-felipe** [IIC2233-2015-2/syllabus#91]
Nuevamente en el archivo bacanosidad.txt están almacenadas las bacanosidades por nombre, sin embargo, los nombres podrían estar repetidos, ¿No será mejor guardarlas usando el usuario?. Ya que en bacanosidad.pdf dice que se debe seguir el formato de este archivo, está bien si yo los guardo por el nombre de usuario?

**Comment by mathias-katscher** [comment]
En todo caso, como el usuario es la primera letra del nombre + el apellido es más probable que se repita un usuario que un nombre.

**Comment by otro-felipe** [comment]
Tienes toda la razón, si no existieran los números estaríamos en graves problemas.

**Comment by mbucchi** [comment]
@MainScientist, @mathias-katscher ambos tienen razón. Pueden guardarlo por uno o por otro, da igual. En todo caso no existen nombres repetidos en estos archivos. Saludos!

**Comment by fgvenegas** [comment]
Los tipos que estan en el bacanosidad.txt son los mimos de personas.txt?
