### ISSUE TITLE
Problema importando archivos

### ISSUE THREAD

**Issue by caackermann** [IIC2233-2015-2/syllabus#92]
Dentro de mi tarea tengo un archivo en python llamado bacanosidad que tiene un metodo llamado get_grupo que calcula el grupo a partir del nombre de la persona, pero cuando trato de importar ese archivo a otro usando "import bacanosidad as bac" me tira el error "AttributeError: 'module' object has no attribute 'get_grupo'". Todos los archivos estan en la misma carpeta. Cual podra ser el problema?

**Comment by caackermann** [comment]
Tambien cuando escribo "import bacanosidad as bac" python muestra el error "No module named bacanosidad"

**Comment by aaossa** [comment]
¿Tienes el modulo en la misma carpeta que "bacanosidad.txt"? Podrías probar cambiandole el nombre al módulo.

**Comment by caackermann** [comment]
Esta en la misma carpeta, intente cambiandole el nombre pero sigue mostrando el mismo error

**Comment by caackermann** [comment]
Buscando en internet salia que creara un archivo vacio en la misma carpeta que se llamara **init**.py pero no sirvio de nada

**Comment by aaossa** [comment]
Podrías mostrar la estructura de tus archivos en la carpeta?

**Comment by caackermann** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13741717/9570489/cb4d93e6-4f63-11e5-80cb-ebf99e382657.jpg)

**Comment by aaossa** [comment]
``` python
import bacanosidad

help(bacanosidad)
```

¿Qué te entrega? Ejecutando esto desde consola.

**Comment by caackermann** [comment]
Help on module bacanosidad:

NAME
    bacanosidad

FUNCTIONS
    get_grupo(nombre)

```
write_bacanosidad()
```

AUTHOR
    Christian

FILE
    c:\users\christian\desktop\caackermann-repo\tareas\tarea1\bacanosidad.py

Process finished with exit code 0

**Comment by aaossa** [comment]
Que raro, entonces reconoce el módulo y reconoce que existe la función...

``` python
import bacanosidad

bacanosidad.get_grupo("Christian")
```

¿Este código falla? :scream:

**Comment by caackermann** [comment]
Extrañamente no falla.... de esa manera si devuelve el grupo

**Comment by caackermann** [comment]
Pero solo en el archivo "vacio", en otro con mas codigo me sigue tirando error. En el archivo "datos_personas.py" me tira error aun. Cuando puse help(bacanosidad) me devolvio esto:
Help on module bacanosidad:

NAME
    bacanosidad

AUTHOR
    Christian

FILE
    c:\users\christian\desktop\caackermann-repo\tareas\tarea1\bacanosidad.py

Lo mismo que antes, pero sin  reconocer las "FUNCTIONS"

**Comment by aaossa** [comment]
Un par de ideas rápidas. Revisa que `bacanosidad` no tenga errores. Revisa que tu función no sea privada ni contenga `_` (leí algo de esto el otro día, podría ser el error y se lo quitas y funciona me avisas). En otro caso, pregunta en ayudantía mañana, creo que hay que verlo porque algo no estoy viendo.

**EDIT:** Dice ideas rápidas -><- Responde 34 minutos después.

**Comment by caackermann** [comment]
No es privada, sera algo en como defini la funcion?:
def get_grupo(nombre):
    with open("bacanosidades_finales.txt", "r", encoding="utf-8") as a_bacan:
        l_bacan = a_bacan.readlines()
        a = int(len(l_bacan)/10)
        for x in range(10):
            for b in l_bacan[a*x:a*(x+1)]:
                if nombre in b:
                    return x+1

**Comment by caackermann** [comment]
No es privada. Será algo en como defini la funcion?:
![sin titulo](https://cloud.githubusercontent.com/assets/13741717/9571190/1e23db64-4f70-11e5-9a10-f3648125277f.png)
