### ISSUE TITLE
Horario de curso

### ISSUE THREAD

**Issue by dpassi** [IIC2233-2015-2/syllabus#94]
Busque dentro de cursos.txt pero es demasiada la info,

En el caso de Tenis II (sacado de busca cursos): tenemos que la catedra va 
M-J:1 y L:2

el archivo cursos.txt vendria como:
M-J:1,L:2 ? Una lista?

Gracias

**Comment by SHGoldfarb** [comment]
Con python encontré que todos los atributos hora_\* tienen a lo mas un solo
":", asi que no hay que preocuparse de eso.

El 31 de agosto de 2015, 12:19 a. m., Diego Passi R.<
notifications@github.com> escribió:

> Busque dentro de cursos.txt pero es demasiada la info,
> 
> En el caso de Tenis II (sacado de busca cursos): tenemos que la catedra va
> M-J:1 y L:2
> 
> el archivo cursos.txt vendria como:
> M-J:1,L:2 ? Una lista?
> 
> Gracias
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IIC2233-2015-2/syllabus/issues/94.

## 

Samuel Goldfarb Hau
Estudiante de Ingeniería
Universidad Católica de Chile
