### ISSUE TITLE
Restriccion Bummer 

### ISSUE THREAD

**Issue by trencoret** [IIC2233-2015-2/syllabus#96]
De campus: No puede ocurrir que dos cursos de un alumno se dicten de forma consecutiva
(horario) y en campus diferentes.

Eso hace referencia a dos catedras solamente? o incluye ayudantia y lab?

Muchas gracias

**Comment by bamavrakis** [comment]
Hola!
De igual manera que con los topes de horario, solo se deben tomar en cuenta para la restricción de campus: cat-cat, cat-lab y lab-lab.
Saludos!
