### ISSUE TITLE
Maximizar puntos efectivos / co-requisitos Pacmatico

### ISSUE THREAD

**Issue by Arios16** [IIC2233-2015-2/syllabus#99]
¿Como funciona maximizar los puntos efectivos cuando hay co-requisitos involucrados?

Por ejemplo, el ramo A tiene como co-requisito a B. Yo le apuesto muy poco a B, pero le apuesto mucho a A. Si veo solo el curso A (sin considerar co-requisitos) me lo deberian dar. Sin embargo, mucha gente le aposto mas puntos a B que yo.

Si se da el caso en que los puntos efectivos totales que asigna el sistema son mayores cuando a mi me dan A y B, ¿me deberian dar ambos cursos, a pesar de que estoy dejando fuera a alguien en B que le aposto mas puntos que yo?

**Comment by ralvarez94** [comment]
Yo creo que en esos casos la apuesta que hizo el alumno para el ramo A y B quedan "guardadas" y se congela una vacante en cada curso.  Al final del proceso, se retorna a estos ramos y se evalúa si es que dando ambos cursos al alumno se maximizan los puntos totales asignados.  Si esto sucede, se le asignan los ramos al alumno en cuestión.  De lo contrario, se le da preferencia a los otros alumno.

**Comment by Arios16** [comment]
¿Pero ha habido alguna respuesta oficial acerca de esto? Porque en #84 se menciona

_"Si el ramo A tiene como co-requisito el ramo B, y el alumno pide los dos. Solo se le dará el curso A al alumno si es que el sistema le da el curso B al alumno (y obviamente si la cantidad de puntos apostados a A se lo permiten)."_

Esta es la única aclaración que he encontrado acerca de los co-requisitos, pero no deja claro si el que me den el ramo B se ve influenciado por los puntos que le apuesto a A, por lo que da para pensar que cada ramo se calcula por separado. Al final, ¿Maximizamos los puntos totales del sistema o a cada curso le asignamos los alumnos que apostaron más puntos? (considerando requisitos y restricciones obviamente)

_cough_ @mbucchi _cough_
